"use client";

import { useMemo, useState } from "react";
import {
  AUDIT_LOG, CUSTOMERS, ESTIMATES, INQUIRIES, PROJECT_TYPES, USERS,
  type Inquiry, type Priority,
} from "../data";
import { estimateTotals, formatDate, money, moneyShort, TODAY, userName, userOf } from "../calc";
import {
  Badge, Drawer, EmptyState, Field, GridControls, Icon, Pagination, Panel, PageHeader,
  Person, Pill, ProgressCell, SearchInput, Select, StatusLegend, Tabs, Toolbar, toneOf, usePaged,
} from "../ui";
import { useT } from "../i18n";
import type { ScreenProps } from "../routes";

const FILE_CATEGORIES = [
  "Customer RFQ", "Meeting Record", "Specification", "Drawing", "Layout",
  "Equipment List", "Customer Standard", "Supplier Document", "Reference Document", "Other",
];

const PRIORITY_TONE: Record<Priority, "red" | "amber" | "blue" | "slate"> = {
  Urgent: "red", High: "amber", Normal: "blue", Low: "slate",
};

/* ==========================================================================
   Inquiry list
   ========================================================================== */

export function InquiryList({ go }: ScreenProps) {
  const [search, setSearch] = useState("");
  const [customer, setCustomer] = useState("All customers");
  const [type, setType] = useState("All project types");
  const [owner, setOwner] = useState("All owners");
  const [status, setStatus] = useState("All status");
  const [priority, setPriority] = useState("All priorities");
  const [pageSize, setPageSize] = useState(50);
  const [page, setPage] = useState(1);
  const t = useT();

  const rows = useMemo(() => INQUIRIES.filter((inquiry) => {
    const customerRecord = CUSTOMERS.find((c) => c.id === inquiry.customerId);
    const haystack = `${inquiry.no} ${inquiry.projectName} ${customerRecord?.name} ${inquiry.rfqNo}`.toLowerCase();
    if (search && !haystack.includes(search.toLowerCase())) return false;
    if (customer !== "All customers" && customerRecord?.code !== customer) return false;
    if (type !== "All project types" && inquiry.projectType !== type) return false;
    if (owner !== "All owners" && userName(inquiry.estimateOwnerId) !== owner) return false;
    if (status !== "All status" && inquiry.status !== status) return false;
    if (priority !== "All priorities" && inquiry.priority !== priority) return false;
    return true;
  }), [search, customer, type, owner, status, priority]);

  const paged = usePaged(rows, pageSize, page);

  return (
    <>
      <PageHeader
        eyebrow={t("SALES TO ENGINEERING")}
        title={t("Inquiry Management")}
        subtitle={t("Every customer inquiry is registered here and receives a unique inquiry number automatically.")}
        actions={<button className="btn primary" type="button" onClick={() => go({ name: "inquiry-new" })}><Icon name="plus" />{t("New Inquiry")}</button>}
      />

      <Toolbar>
        <SearchInput value={search} onChange={setSearch} placeholder="Search inquiry no., project, customer or RFQ no.…" />
        <Select label="Customer" value={customer} onChange={setCustomer} options={["All customers", ...CUSTOMERS.map((c) => c.code)]} />
        <Select label="Project type" value={type} onChange={setType} options={["All project types", ...PROJECT_TYPES]} />
        <Select label="Estimate owner" value={owner} onChange={setOwner} options={["All owners", ...USERS.filter((u) => u.role === "Engineer").map((u) => u.name)]} />
        <Select label="Status" value={status} onChange={setStatus} options={["All status", "New", "Estimating", "Waiting Supplier Price", "Estimate Completed", "Engineering Review", "Approved"]} />
        <Select label="Priority" value={priority} onChange={setPriority} options={["All priorities", "Urgent", "High", "Normal", "Low"]} />
        <button className="btn ghost" type="button"><Icon name="calendar" />Inquiry date</button>
        <button className="btn ghost" type="button"><Icon name="calendar" />Due date</button>
      </Toolbar>

      <StatusLegend items={[
        { label: "New", kind: "new" },
        { label: "Estimating", kind: "revised" },
        { label: "Waiting supplier price", kind: "wait" },
        { label: "Engineering review", kind: "approved" },
        { label: "Approved", kind: "confirmed" },
        { label: "Overdue", kind: "canceled" },
      ]} />

      <Panel title={`${rows.length} inquiries`} subtitle="Inquiry numbers are generated by the system and can never duplicate" flush>
        <GridControls pageSize={pageSize} onPageSize={(size) => { setPageSize(size); setPage(1); }} search={search} onSearch={(value) => { setSearch(value); setPage(1); }} />
        {rows.length ? (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>{t("Inquiry No.")}</th>
                  <th>{t("Inquiry Date")}</th>
                  <th>{t("Customer")}</th>
                  <th>{t("Project Name")}</th>
                  <th>{t("Project Type")}</th>
                  <th>{t("Sales Owner")}</th>
                  <th>{t("Estimate Owner")}</th>
                  <th>{t("Estimate Due")}</th>
                  <th>{t("Progress")}</th>
                  <th>{t("Rev.")}</th>
                  <th>{t("Priority")}</th>
                  <th>{t("Status")}</th>
                  <th>{t("Last Updated")}</th>
                  <th aria-label="Action" />
                </tr>
              </thead>
              <tbody>
                {paged.pageRows.map((inquiry) => {
                  const customerRecord = CUSTOMERS.find((c) => c.id === inquiry.customerId);
                  const late = new Date(inquiry.dueDate) < TODAY && inquiry.status !== "Approved";
                  return (
                    <tr
                      key={inquiry.id}
                      className={`clickable ${late ? "row-late" : inquiry.status === "Approved" || inquiry.status === "Estimate Completed" ? "row-ok" : inquiry.status === "Waiting Supplier Price" ? "row-wait" : ""}`}
                      onClick={() => go({ name: "inquiry", id: inquiry.id })}
                    >
                      <td><strong className="mono">{inquiry.no}</strong></td>
                      <td>{formatDate(inquiry.date)}</td>
                      <td>
                        <div className="cell-primary">
                          <strong>{customerRecord?.code}</strong>
                          <span>{customerRecord?.name}</span>
                        </div>
                      </td>
                      <td><strong>{inquiry.projectName}</strong></td>
                      <td>{inquiry.projectType}</td>
                      <td>{inquiry.salesOwner}</td>
                      <td><Person initials={userOf(inquiry.estimateOwnerId)?.initials ?? "—"} name={userName(inquiry.estimateOwnerId)} /></td>
                      <td className={late ? "red-text" : undefined}>{formatDate(inquiry.dueDate)}</td>
                      <td style={{ minWidth: 110 }}><ProgressCell value={inquiry.progress} /></td>
                      <td><span className="pill">{inquiry.revision}</span></td>
                      <td><Badge tone={PRIORITY_TONE[inquiry.priority]}>{inquiry.priority}</Badge></td>
                      <td><Badge tone={toneOf(inquiry.status)}>{inquiry.status}</Badge></td>
                      <td className="muted">{inquiry.updatedAt}</td>
                      <td><span className="row-action"><Icon name="chevronRight" /></span></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <Pagination page={paged.current} pageCount={paged.pageCount} from={paged.from} to={paged.to} total={paged.total} onPage={setPage} />
          </div>
        ) : (
          <EmptyState icon="inbox" title="No inquiry matches the filter" message="Adjust the filters above or register a new customer inquiry." />
        )}
      </Panel>
    </>
  );
}

/* ==========================================================================
   Create inquiry
   ========================================================================== */

export function InquiryCreate({ go, notify }: ScreenProps) {
  const [form, setForm] = useState({
    date: "2026-08-29",
    customerId: "c1",
    contact: "",
    projectName: "",
    projectType: "Automation",
    rfqNo: "",
    salesOwner: "Chatchai Pimsen",
    estimateOwnerId: "u1",
    dueDate: "2026-09-15",
    priority: "Normal" as Priority,
    status: "New",
    requirement: "",
    background: "",
    scopeSummary: "",
    technical: "",
    targetDelivery: "",
    siteLocation: "",
    standard: "",
    special: "",
    remark: "",
  });
  const [files, setFiles] = useState<{ name: string; category: string }[]>([]);
  const [dragging, setDragging] = useState(false);

  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((prev) => ({ ...prev, [key]: value }));
  const nextNumber = "INQ-2608-0015";

  function submit(event: React.FormEvent) {
    event.preventDefault();
    notify(`${nextNumber} registered — estimate owner notified`);
    go({ name: "inquiries" });
  }

  return (
    <form onSubmit={submit}>
      <button className="back-link" type="button" onClick={() => go({ name: "inquiries" })}><Icon name="arrowLeft" />Inquiry Management</button>
      <PageHeader
        eyebrow="NEW INQUIRY"
        title="Register customer inquiry"
        subtitle="The inquiry number is generated by the system. Duplicate numbers are impossible."
        actions={
          <>
            <button className="btn default" type="button" onClick={() => go({ name: "inquiries" })}>Cancel</button>
            <button className="btn primary" type="submit"><Icon name="check" />Register inquiry</button>
          </>
        }
      />

      <Panel title="General Information" subtitle="Customer, project and estimate ownership">
        <div className="form-grid">
          <Field label="Inquiry No." hint="Generated automatically — read only">
            <input value={nextNumber} readOnly />
          </Field>
          <Field label="Inquiry Date">
            <input type="date" value={form.date} onChange={(e) => set("date", e.target.value)} required />
          </Field>
          <Field label="Customer">
            <select value={form.customerId} onChange={(e) => set("customerId", e.target.value)}>
              {CUSTOMERS.map((c) => <option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}
            </select>
          </Field>
          <Field label="Customer Contact">
            <input value={form.contact} onChange={(e) => set("contact", e.target.value)} placeholder="e.g. K. Somsak Chareon" />
          </Field>
          <Field label="Project Name" span={2}>
            <input value={form.projectName} onChange={(e) => set("projectName", e.target.value)} placeholder="e.g. Cobot Picking Machine" required />
          </Field>
          <Field label="Project Type">
            <select value={form.projectType} onChange={(e) => set("projectType", e.target.value)}>
              {PROJECT_TYPES.map((type) => <option key={type}>{type}</option>)}
            </select>
          </Field>
          <Field label="Customer RFQ No.">
            <input value={form.rfqNo} onChange={(e) => set("rfqNo", e.target.value)} placeholder="RFQ-XXX-26-0000" />
          </Field>
          <Field label="Sales Owner">
            <select value={form.salesOwner} onChange={(e) => set("salesOwner", e.target.value)}>
              {USERS.filter((u) => u.role === "Sales Engineer" || u.role === "Project Manager").map((u) => <option key={u.id}>{u.name}</option>)}
            </select>
          </Field>
          <Field label="Estimate Owner">
            <select value={form.estimateOwnerId} onChange={(e) => set("estimateOwnerId", e.target.value)}>
              {USERS.filter((u) => u.role === "Engineer").map((u) => <option key={u.id} value={u.id}>{u.name} — {u.department}</option>)}
            </select>
          </Field>
          <Field label="Estimate Due Date">
            <input type="date" value={form.dueDate} onChange={(e) => set("dueDate", e.target.value)} required />
          </Field>
          <Field label="Priority">
            <select value={form.priority} onChange={(e) => set("priority", e.target.value as Priority)}>
              {["Low", "Normal", "High", "Urgent"].map((p) => <option key={p}>{p}</option>)}
            </select>
          </Field>
          <Field label="Status">
            <select value={form.status} onChange={(e) => set("status", e.target.value)}>
              {["New", "Estimating"].map((s) => <option key={s}>{s}</option>)}
            </select>
          </Field>
        </div>
      </Panel>

      <div style={{ height: 14 }} />

      <Panel title="Requirement Information" subtitle="What the customer asked for, and the engineering context behind it">
        <div className="form-grid">
          <Field label="Customer Requirement" span={2}>
            <textarea value={form.requirement} onChange={(e) => set("requirement", e.target.value)} placeholder="What must the system do?" />
          </Field>
          <Field label="Project Background" span={2}>
            <textarea value={form.background} onChange={(e) => set("background", e.target.value)} placeholder="Why is the customer asking for this now?" />
          </Field>
          <Field label="Scope Summary" span={2}>
            <textarea value={form.scopeSummary} onChange={(e) => set("scopeSummary", e.target.value)} />
          </Field>
          <Field label="Technical Requirement" span={2}>
            <textarea value={form.technical} onChange={(e) => set("technical", e.target.value)} placeholder="Cycle time, payload, interface, safety category…" />
          </Field>
          <Field label="Target Delivery">
            <input type="date" value={form.targetDelivery} onChange={(e) => set("targetDelivery", e.target.value)} />
          </Field>
          <Field label="Site Location">
            <input value={form.siteLocation} onChange={(e) => set("siteLocation", e.target.value)} placeholder="Plant, line, province" />
          </Field>
          <Field label="Customer Standard">
            <input value={form.standard} onChange={(e) => set("standard", e.target.value)} placeholder="e.g. ISO 10218-2" />
          </Field>
          <Field label="Special Requirement">
            <input value={form.special} onChange={(e) => set("special", e.target.value)} />
          </Field>
          <Field label="Remark" span={4}>
            <textarea value={form.remark} onChange={(e) => set("remark", e.target.value)} />
          </Field>
        </div>
      </Panel>

      <div style={{ height: 14 }} />

      <Panel title="Inquiry Attachments" subtitle="RFQ, drawings, layouts and standards — stored on SharePoint today, NAS later">
        <div
          className="attachment-drop"
          onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDragging(false);
            const dropped = Array.from(e.dataTransfer.files).map((file) => ({ name: file.name, category: "Customer RFQ" }));
            setFiles((prev) => [...prev, ...dropped]);
          }}
          style={dragging ? { borderColor: "var(--blue)", background: "var(--blue-soft)" } : undefined}
        >
          <Icon name="upload" />
          <strong>Drag and drop files here</strong>
          <span>PDF, Excel, Word, DWG or image — each file is tagged with a document category</span>
        </div>

        <div className="row" style={{ marginTop: 12 }}>
          {FILE_CATEGORIES.map((category) => (
            <button key={category} type="button" className="chip" onClick={() => setFiles((prev) => [...prev, { name: `${category.replace(/ /g, "-")}-draft.pdf`, category }])}>
              <Icon name="plus" /> {category}
            </button>
          ))}
        </div>

        {files.length ? (
          <div style={{ marginTop: 12 }}>
            {files.map((file, index) => (
              <div className="file-row" key={`${file.name}-${index}`}>
                <span className="file-icon"><Icon name="file" /></span>
                <div style={{ flex: 1 }}>
                  <strong>{file.name}</strong>
                  <small>{file.category} · queued for upload</small>
                </div>
                <button type="button" className="row-action" onClick={() => setFiles((prev) => prev.filter((_, i) => i !== index))} aria-label={`Remove ${file.name}`}>
                  <Icon name="trash" />
                </button>
              </div>
            ))}
          </div>
        ) : null}
      </Panel>
    </form>
  );
}

/* ==========================================================================
   Inquiry detail
   ========================================================================== */

type DetailTab = "overview" | "requirement" | "meeting" | "estimate" | "attachments" | "activity";

export function InquiryDetail({ id, go, notify }: ScreenProps & { id: string }) {
  const inquiry = INQUIRIES.find((i) => i.id === id) ?? INQUIRIES[0];
  const customer = CUSTOMERS.find((c) => c.id === inquiry.customerId);
  const estimate = ESTIMATES.find((e) => e.id === inquiry.estimateId);
  const [tab, setTab] = useState<DetailTab>("overview");
  const [meetingOpen, setMeetingOpen] = useState(false);
  const [meetings, setMeetings] = useState(inquiry.meetings);

  return (
    <>
      <button className="back-link" type="button" onClick={() => go({ name: "inquiries" })}><Icon name="arrowLeft" />Inquiry Management</button>
      <PageHeader
        eyebrow={inquiry.no}
        title={`${customer?.code} — ${inquiry.projectName}`}
        subtitle={customer?.name}
        meta={
          <>
            <div><span>Inquiry status</span><strong><Badge tone={toneOf(inquiry.status)}>{inquiry.status}</Badge></strong></div>
            <div><span>Estimate due</span><strong>{formatDate(inquiry.dueDate)}</strong></div>
            <div><span>Estimate owner</span><strong>{userName(inquiry.estimateOwnerId)}</strong></div>
            <div><span>Priority</span><strong><Badge tone={PRIORITY_TONE[inquiry.priority]}>{inquiry.priority}</Badge></strong></div>
            <div><span>Project type</span><strong>{inquiry.projectType}</strong></div>
          </>
        }
        actions={
          <>
            {estimate ? (
              <button className="btn default" type="button" onClick={() => go({ name: "estimate", id: estimate.id })}>
                <Icon name="file" />Open estimate
              </button>
            ) : (
              <button className="btn primary" type="button" onClick={() => notify("Estimate EST-2608-0007 R00 created from this inquiry")}>
                <Icon name="plus" />Create estimate cost
              </button>
            )}
            <button className="btn default" type="button" onClick={() => notify("Estimate owner re-assigned")}><Icon name="user" />Assign owner</button>
          </>
        }
      />

      <Tabs
        active={tab}
        onChange={setTab}
        tabs={[
          { id: "overview", label: "Overview" },
          { id: "requirement", label: "Requirement" },
          { id: "meeting", label: "Meeting Log", count: meetings.length },
          { id: "estimate", label: "Estimate Cost", count: estimate ? 1 : 0 },
          { id: "attachments", label: "Attachments", count: inquiry.attachments.length },
          { id: "activity", label: "Activity" },
        ]}
      />

      {tab === "overview" ? <Overview inquiry={inquiry} estimate={estimate} go={go} /> : null}
      {tab === "requirement" ? <Requirement inquiry={inquiry} /> : null}
      {tab === "meeting" ? (
        <Panel
          title="Meeting Log"
          subtitle="Why the estimate requirement changed, recorded meeting by meeting"
          actions={<button className="btn primary sm" type="button" onClick={() => setMeetingOpen(true)}><Icon name="plus" />Add Meeting Record</button>}
        >
          {meetings.length ? (
            <div className="timeline">
              {meetings.map((meeting, index) => (
                <article className="timeline-item done" key={meeting.id}>
                  <div className="timeline-head">
                    <strong>{meeting.type}</strong>
                    <time>{formatDate(meeting.date)}</time>
                    <Pill>{`#${index + 1}`}</Pill>
                    <span className="spacer" />
                    <span className="muted">{meeting.participants.length} participants</span>
                  </div>
                  <div className="timeline-card">
                    <dl className="def-list">
                      <div><dt>Participants</dt><dd>{meeting.participants.join(", ")}</dd></div>
                      <div><dt>Customer requirement</dt><dd>{meeting.requirement}</dd></div>
                      <div><dt>Technical discussion</dt><dd>{meeting.technical}</dd></div>
                      <div><dt>Decision</dt><dd>{meeting.decision}</dd></div>
                      <div><dt>Open point</dt><dd>{meeting.openPoint || "—"}</dd></div>
                      <div><dt>Action item</dt><dd>{meeting.actionItem}</dd></div>
                      <div><dt>Owner</dt><dd>{meeting.owner}</dd></div>
                      <div><dt>Due date</dt><dd>{formatDate(meeting.dueDate)}</dd></div>
                    </dl>
                    {meeting.attachment ? (
                      <div className="file-row" style={{ marginTop: 10 }}>
                        <span className="file-icon"><Icon name="paperclip" /></span>
                        <div><strong>{meeting.attachment}</strong><small>Meeting Record</small></div>
                      </div>
                    ) : null}
                  </div>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState icon="inbox" title="No meeting recorded yet" message="Add the kickoff meeting so engineers understand where the requirement came from."
              action={<button className="btn primary" type="button" onClick={() => setMeetingOpen(true)}><Icon name="plus" />Add Meeting Record</button>} />
          )}
        </Panel>
      ) : null}
      {tab === "estimate" ? <EstimateTab inquiry={inquiry} go={go} /> : null}
      {tab === "attachments" ? <Attachments inquiry={inquiry} /> : null}
      {tab === "activity" ? <Activity inquiry={inquiry} /> : null}

      {meetingOpen ? (
        <MeetingDrawer
          onClose={() => setMeetingOpen(false)}
          onSave={(record) => {
            setMeetings((prev) => [...prev, record]);
            setMeetingOpen(false);
            notify("Meeting record added to the inquiry");
          }}
        />
      ) : null}
    </>
  );
}

function Overview({ inquiry, estimate, go }: { inquiry: Inquiry; estimate?: (typeof ESTIMATES)[number]; go: ScreenProps["go"] }) {
  const customer = CUSTOMERS.find((c) => c.id === inquiry.customerId);
  const totals = estimate ? estimateTotals(estimate) : undefined;
  return (
    <section className="grid-main">
      <div className="stack">
        <Panel title="Inquiry information">
          <dl className="def-list">
            <div><dt>Inquiry No.</dt><dd className="mono">{inquiry.no}</dd></div>
            <div><dt>Inquiry date</dt><dd>{formatDate(inquiry.date)}</dd></div>
            <div><dt>Customer</dt><dd>{customer?.name}</dd></div>
            <div><dt>Customer contact</dt><dd>{inquiry.contact}</dd></div>
            <div><dt>Customer RFQ No.</dt><dd className="mono">{inquiry.rfqNo}</dd></div>
            <div><dt>Project type</dt><dd>{inquiry.projectType}</dd></div>
            <div><dt>Sales owner</dt><dd>{inquiry.salesOwner}</dd></div>
            <div><dt>Estimate owner</dt><dd>{userName(inquiry.estimateOwnerId)}</dd></div>
            <div><dt>Site location</dt><dd>{inquiry.siteLocation}</dd></div>
            <div><dt>Target delivery</dt><dd>{formatDate(inquiry.targetDelivery)}</dd></div>
          </dl>
        </Panel>
        <Panel title="Scope summary">
          <p style={{ fontSize: "var(--fs-sm)" }}>{inquiry.scopeSummary}</p>
          {inquiry.remark ? <div className="info-strip amber" style={{ marginTop: 12 }}><Icon name="alertTriangle" />{inquiry.remark}</div> : null}
        </Panel>
      </div>
      <div className="stack">
        <Panel title="Estimate progress">
          {estimate && totals ? (
            <>
              <dl className="def-list one">
                <div><dt>Estimate No.</dt><dd className="mono">{estimate.no} <span className="pill">{estimate.revision}</span></dd></div>
                <div><dt>Status</dt><dd><Badge tone={toneOf(estimate.status)}>{estimate.status}</Badge></dd></div>
                <div><dt>Total estimated cost</dt><dd><strong>{money(totals.total)}</strong></dd></div>
                <div><dt>Progress</dt><dd><ProgressCell value={estimate.progress} /></dd></div>
              </dl>
              <button className="btn default block" type="button" style={{ marginTop: 12 }} onClick={() => go({ name: "estimate", id: estimate.id })}>
                Open estimate workspace<Icon name="arrowRight" />
              </button>
            </>
          ) : (
            <EmptyState icon="file" title="No estimate yet" message="Create the estimate cost to start collecting engineering cost for this inquiry." />
          )}
        </Panel>
        <Panel title="Latest meetings">
          {inquiry.meetings.length ? (
            <ul className="check-list">
              {inquiry.meetings.slice(-3).reverse().map((meeting) => (
                <li className="check-item pass" key={meeting.id}>
                  <Icon name="checkCircle" />
                  <div>
                    <strong>{meeting.type} · {formatDate(meeting.date)}</strong>
                    <p>{meeting.decision}</p>
                  </div>
                </li>
              ))}
            </ul>
          ) : <p className="muted">No meeting recorded yet.</p>}
        </Panel>
      </div>
    </section>
  );
}

function Requirement({ inquiry }: { inquiry: Inquiry }) {
  const blocks: [string, string][] = [
    ["Customer Requirement", inquiry.requirement],
    ["Project Background", inquiry.background],
    ["Scope Summary", inquiry.scopeSummary],
    ["Technical Requirement", inquiry.technical],
    ["Customer Standard", inquiry.standard],
    ["Special Requirement", inquiry.special || "—"],
    ["Site Location", inquiry.siteLocation],
    ["Target Delivery", formatDate(inquiry.targetDelivery)],
    ["Remark", inquiry.remark || "—"],
  ];
  return (
    <Panel title="Requirement Information" subtitle="Frozen with each revision so engineers can see what the cost was based on">
      <dl className="def-list">
        {blocks.map(([label, value]) => (
          <div key={label} style={label === "Customer Requirement" || label === "Technical Requirement" ? { gridColumn: "span 2" } : undefined}>
            <dt>{label}</dt>
            <dd>{value}</dd>
          </div>
        ))}
      </dl>
    </Panel>
  );
}

function EstimateTab({ inquiry, go }: { inquiry: Inquiry; go: ScreenProps["go"] }) {
  const estimate = ESTIMATES.find((e) => e.id === inquiry.estimateId);
  if (!estimate) {
    return (
      <Panel>
        <EmptyState icon="file" title="No estimate cost created" message="Create an estimate to divide the engineering scope and start collecting cost." />
      </Panel>
    );
  }
  const totals = estimateTotals(estimate);
  return (
    <Panel title="Estimate cost linked to this inquiry" flush>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Estimate No.</th><th>Rev.</th><th>Owner</th><th>Created</th><th>Due</th>
              <th className="num">Material</th><th className="num">Engineering</th><th className="num">Outsource</th>
              <th className="num">Other</th><th className="num">Total</th><th>Progress</th><th>Status</th><th aria-label="Action" />
            </tr>
          </thead>
          <tbody>
            {estimate.revisions.map((revision, index) => {
              const isCurrent = index === estimate.revisions.length - 1;
              return (
                <tr key={revision.id} className={isCurrent ? "clickable" : undefined} onClick={isCurrent ? () => go({ name: "estimate", id: estimate.id }) : undefined}>
                  <td><strong className="mono">{estimate.no}</strong></td>
                  <td><span className="pill">{revision.code}</span></td>
                  <td>{revision.createdBy}</td>
                  <td>{formatDate(revision.createdAt)}</td>
                  <td>{formatDate(estimate.dueDate)}</td>
                  <td className="num">{isCurrent ? moneyShort(totals.material) : "—"}</td>
                  <td className="num">{isCurrent ? moneyShort(totals.engineering) : "—"}</td>
                  <td className="num">{isCurrent ? moneyShort(totals.outsource) : "—"}</td>
                  <td className="num">{isCurrent ? moneyShort(totals.other + totals.transportation + totals.accommodation) : "—"}</td>
                  <td className="num"><strong>{moneyShort(isCurrent ? totals.total : revision.total)}</strong></td>
                  <td style={{ minWidth: 110 }}>{isCurrent ? <ProgressCell value={estimate.progress} /> : <span className="muted">Closed</span>}</td>
                  <td><Badge tone={toneOf(isCurrent ? estimate.status : revision.status)}>{isCurrent ? estimate.status : revision.status}</Badge></td>
                  <td>{isCurrent ? <span className="row-action"><Icon name="chevronRight" /></span> : null}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function Attachments({ inquiry }: { inquiry: Inquiry }) {
  return (
    <Panel title="Attachments" subtitle="Document storage runs on Microsoft 365 / SharePoint today and can move to the company NAS without touching the estimate database"
      actions={<button className="btn default sm" type="button"><Icon name="upload" />Upload</button>}>
      <div className="attachment-drop">
        <Icon name="upload" />
        <strong>Drag and drop files here</strong>
        <span>Each file is tagged with a document category and linked to this inquiry</span>
      </div>
      <div style={{ marginTop: 12 }}>
        {inquiry.attachments.map((file) => (
          <div className="file-row" key={file.id}>
            <span className="file-icon"><Icon name="file" /></span>
            <div style={{ flex: 1 }}>
              <strong>{file.name}</strong>
              <small>{file.category} · {file.size} · {file.uploadedBy} · {formatDate(file.uploadedAt)}</small>
            </div>
            <Badge tone="slate">{file.category}</Badge>
            <button className="row-action" type="button" aria-label={`Download ${file.name}`}><Icon name="download" /></button>
          </div>
        ))}
      </div>
    </Panel>
  );
}

function Activity({ inquiry }: { inquiry: Inquiry }) {
  const entries = AUDIT_LOG.filter((entry) => ESTIMATES.some((e) => e.no === entry.estimate && e.inquiryNo === inquiry.no));
  return (
    <Panel title="Activity" subtitle="Every change recorded against this inquiry and its estimate" flush>
      <div className="table-wrap">
        <table>
          <thead>
            <tr><th>Date / Time</th><th>User</th><th>Estimate</th><th>Rev.</th><th>Module</th><th>Action</th><th>Previous</th><th>New</th><th>Reason</th></tr>
          </thead>
          <tbody>
            {entries.map((entry) => (
              <tr key={entry.id}>
                <td className="mono">{entry.at}</td>
                <td><Person initials={entry.user.split(" ").map((p) => p[0]).join("")} name={entry.user} /></td>
                <td className="mono">{entry.estimate}</td>
                <td><span className="pill">{entry.revision}</span></td>
                <td>{entry.module}</td>
                <td><strong>{entry.action}</strong></td>
                <td className="muted">{entry.before}</td>
                <td className="green-text">{entry.after}</td>
                <td className="muted">{entry.reason}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function MeetingDrawer({ onClose, onSave }: { onClose: () => void; onSave: (record: Inquiry["meetings"][number]) => void }) {
  const [form, setForm] = useState({
    date: "2026-08-29", type: "Technical Review", participants: "", requirement: "",
    technical: "", decision: "", openPoint: "", actionItem: "", owner: "Nattaphon Prasert", dueDate: "2026-09-05",
  });
  const set = <K extends keyof typeof form>(key: K, value: string) => setForm((prev) => ({ ...prev, [key]: value }));

  return (
    <Drawer
      title="Add Meeting Record"
      subtitle="Capture the decision so the estimate revision has a traceable reason"
      onClose={onClose}
      width={560}
      footer={
        <>
          <span className="spacer" />
          <button className="btn default" type="button" onClick={onClose}>Cancel</button>
          <button
            className="btn primary"
            type="button"
            onClick={() => onSave({
              id: `mt-${Date.now()}`,
              date: form.date, type: form.type,
              participants: form.participants ? form.participants.split(",").map((p) => p.trim()) : ["Nattaphon Prasert"],
              requirement: form.requirement, technical: form.technical, decision: form.decision,
              openPoint: form.openPoint, actionItem: form.actionItem, owner: form.owner, dueDate: form.dueDate,
            })}
          >
            <Icon name="check" />Save meeting record
          </button>
        </>
      }
    >
      <div className="form-grid two">
        <Field label="Meeting Date"><input type="date" value={form.date} onChange={(e) => set("date", e.target.value)} /></Field>
        <Field label="Meeting Type">
          <select value={form.type} onChange={(e) => set("type", e.target.value)}>
            {["Kickoff Meeting", "Technical Review", "Customer Meeting", "Site Survey", "Internal Review", "Design Review"].map((t) => <option key={t}>{t}</option>)}
          </select>
        </Field>
        <Field label="Participants" span={2} hint="Separate names with a comma">
          <input value={form.participants} onChange={(e) => set("participants", e.target.value)} placeholder="Nattaphon Prasert, K. Somsak Chareon" />
        </Field>
        <Field label="Customer Requirement" span={2}><textarea value={form.requirement} onChange={(e) => set("requirement", e.target.value)} /></Field>
        <Field label="Technical Discussion" span={2}><textarea value={form.technical} onChange={(e) => set("technical", e.target.value)} /></Field>
        <Field label="Decision" span={2}><textarea value={form.decision} onChange={(e) => set("decision", e.target.value)} /></Field>
        <Field label="Open Point" span={2}><textarea value={form.openPoint} onChange={(e) => set("openPoint", e.target.value)} /></Field>
        <Field label="Action Item" span={2}><input value={form.actionItem} onChange={(e) => set("actionItem", e.target.value)} /></Field>
        <Field label="Owner">
          <select value={form.owner} onChange={(e) => set("owner", e.target.value)}>
            {USERS.map((u) => <option key={u.id}>{u.name}</option>)}
          </select>
        </Field>
        <Field label="Due Date"><input type="date" value={form.dueDate} onChange={(e) => set("dueDate", e.target.value)} /></Field>
        <Field label="Attachment" span={2}>
          <div className="attachment-drop" style={{ padding: 14 }}>
            <Icon name="paperclip" />
            <span>Drop the meeting minutes here</span>
          </div>
        </Field>
      </div>
    </Drawer>
  );
}
