import sql from "mssql";
import type { FastifyInstance } from "fastify";
import type { AppConfig } from "../config.js";
import type { Database } from "../db.js";
import { ApiError } from "../errors.js";
import { bodyObject, booleanQuery, positiveLong, requiredInteger, requiredText } from "../http.js";
import { ARTICLE_VISIBILITY, bindKnowledgeVisibility, canManageKnowledge, CONFIDENTIALITIES, DOCUMENT_TYPES, KNOWLEDGE_VISIBILITY } from "../knowledge-common.js";
import type { CurrentUserService } from "../users.js";

function todayIn(timeZone: string): string { const p = new Intl.DateTimeFormat("en-GB", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const v = Object.fromEntries(p.map((x) => [x.type, x.value])); return `${v.year}-${v.month}-${v.day}`; }
function optionalString(value: unknown, max: number, label: string): string { if (value == null) return ""; if (typeof value !== "string" || value.trim().length > max) throw new ApiError(400, "validation_failed", `${label} is invalid.`); return value.trim(); }
function categoryBody(value: unknown) { const body = bodyObject(value), documentType = optionalString(body.defaultDocumentType, 30, "Default document type") || null, confidentiality = optionalString(body.defaultConfidentiality, 30, "Default confidentiality") || "Company"; if (documentType && !(DOCUMENT_TYPES as readonly string[]).includes(documentType)) throw new ApiError(400, "validation_failed", "Default document type is invalid."); if (!(CONFIDENTIALITIES as readonly string[]).includes(confidentiality)) throw new ApiError(400, "validation_failed", "Default confidentiality is invalid."); return { parentId: body.parentId == null ? null : requiredInteger(body.parentId, "Parent category", 1), code: requiredText(body.code, 40, "Category code").toUpperCase(), nameEn: requiredText(body.nameEn, 200, "Category name"), nameTh: optionalString(body.nameTh, 200, "Thai category name"), nameJa: optionalString(body.nameJa, 200, "Japanese category name"), documentType, confidentiality, sortOrder: typeof body.sortOrder === "number" ? Math.max(-100_000, Math.min(100_000, Math.trunc(body.sortOrder))) : 0, isActive: body.isActive !== false }; }
function bindCategory(request: InstanceType<typeof sql.Request>, value: ReturnType<typeof categoryBody>, actorId: number): void { request.input("parent", sql.BigInt, value.parentId); request.input("code", sql.NVarChar(40), value.code); request.input("name_en", sql.NVarChar(200), value.nameEn); request.input("name_th", sql.NVarChar(200), value.nameTh); request.input("name_ja", sql.NVarChar(200), value.nameJa); request.input("type", sql.NVarChar(30), value.documentType); request.input("conf", sql.NVarChar(30), value.confidentiality); request.input("sort", sql.Int, value.sortOrder); request.input("active", sql.Bit, value.isActive); request.input("actor", sql.BigInt, actorId); }
function sequenceBody(value: unknown) { const body = bodyObject(value); return { prefix: requiredText(body.prefix, 10, "Prefix").toUpperCase(), scope: requiredText(body.scopeCode, 20, "Scope code").toUpperCase(), name: optionalString(body.scopeName, 200, "Scope name"), last: requiredInteger(body.lastNumber, "Last number", 0, 999_999), padding: requiredInteger(body.padding ?? 4, "Padding", 3, 6), active: body.isActive !== false }; }
function bindSequence(request: InstanceType<typeof sql.Request>, value: ReturnType<typeof sequenceBody>): void { request.input("prefix", sql.NVarChar(10), value.prefix); request.input("scope", sql.NVarChar(20), value.scope); request.input("name", sql.NVarChar(200), value.name); request.input("last", sql.Int, value.last); request.input("padding", sql.TinyInt, value.padding); request.input("active", sql.Bit, value.active); }

export function registerKnowledgeAdminRoutes(app: FastifyInstance, config: AppConfig, database: Database, users: CurrentUserService): void {
  app.get("/api/v1/knowledge/dashboard", async (request) => { await users.demandPermission(request, "knowledge.view"); const actor = await users.required(request), manage = await canManageKnowledge(database, actor); const result = await database.query<Record<string, unknown>>(`WITH visible AS (SELECT d.id,d.current_status,d.document_type,d.owner_id,d.next_review_date,v.expiry_date FROM dbo.knowledge_documents d LEFT JOIN dbo.knowledge_document_versions v ON v.id=d.current_version_id WHERE d.archived_at IS NULL AND ${KNOWLEDGE_VISIBILITY}) SELECT COUNT_BIG(*) total_documents,COALESCE(SUM(CASE WHEN current_status=N'Published' THEN 1 ELSE 0 END),0) published,COALESCE(SUM(CASE WHEN current_status IN(N'In Review',N'Pending Approval',N'Request Changes') THEN 1 ELSE 0 END),0) in_workflow,COALESCE(SUM(CASE WHEN expiry_date<@today THEN 1 ELSE 0 END),0) expired,COALESCE(SUM(CASE WHEN next_review_date IS NOT NULL AND next_review_date<=DATEADD(day,90,@today) THEN 1 ELSE 0 END),0) review_due,COALESCE(SUM(CASE WHEN owner_id=@me AND current_status=N'Draft' THEN 1 ELSE 0 END),0) my_drafts,COALESCE(SUM(CASE WHEN document_type=N'Presentation' THEN 1 ELSE 0 END),0) presentations,(SELECT COUNT_BIG(*) FROM dbo.knowledge_document_approvals a WHERE a.approver_id=@me AND a.status=N'Pending' AND a.step_type=N'Review') assigned_reviews,(SELECT COUNT_BIG(*) FROM dbo.knowledge_document_approvals a WHERE a.approver_id=@me AND a.status=N'Pending' AND a.step_type=N'Approve') assigned_approvals,(SELECT COUNT_BIG(*) FROM dbo.knowledge_document_acknowledgements a WHERE a.user_id=@me AND a.status=N'Pending') acknowledgements,(SELECT COUNT_BIG(*) FROM dbo.knowledge_articles a INNER JOIN dbo.users ao ON ao.id=a.owner_id WHERE a.archived_at IS NULL AND ${ARTICLE_VISIBILITY}) articles FROM visible;`, (bind) => { bindKnowledgeVisibility(bind, actor, manage); bind.input("today", sql.Date, todayIn(config.businessTimeZone)); }); const row = result.recordset[0]!; return { totalDocuments: Number(row.total_documents), published: Number(row.published), inWorkflow: Number(row.in_workflow), expired: Number(row.expired), reviewDueWithin90Days: Number(row.review_due), myDrafts: Number(row.my_drafts), presentations: Number(row.presentations), assignedReviews: Number(row.assigned_reviews), assignedApprovals: Number(row.assigned_approvals), acknowledgementsRequired: Number(row.acknowledgements), articles: Number(row.articles) }; });

  app.get("/api/v1/knowledge/categories", async (request) => { await users.demandPermission(request, "knowledge.view"); const include = booleanQuery((request.query as Record<string, unknown>).includeInactive, false); if (include) await users.demandPermission(request, "knowledge.manage_categories"); const result = await database.query<Record<string, unknown>>(`SELECT c.id,c.parent_id,c.code,c.name_en,c.name_th,c.name_ja,c.default_document_type,c.default_confidentiality,c.sort_order,c.is_active,(SELECT COUNT_BIG(*) FROM dbo.knowledge_documents d WHERE d.category_id=c.id AND d.archived_at IS NULL) document_count FROM dbo.knowledge_categories c WHERE (@include=1 OR c.is_active=1) ORDER BY c.sort_order,c.name_en;`, (bind) => bind.input("include", sql.Bit, include)); return { items: result.recordset.map((row) => ({ id: Number(row.id), parentId: row.parent_id === null ? null : Number(row.parent_id), code: row.code, nameEn: row.name_en, nameTh: row.name_th, nameJa: row.name_ja, defaultDocumentType: row.default_document_type, defaultConfidentiality: row.default_confidentiality, sortOrder: Number(row.sort_order), isActive: Boolean(row.is_active), documentCount: Number(row.document_count) })) }; });

  app.post("/api/v1/knowledge/categories", async (request, reply) => { await users.demandPermission(request, "knowledge.manage_categories"); const actor = await users.required(request), value = categoryBody(request.body); const created = await database.transaction(async (transaction) => { if (value.parentId) { const check = new sql.Request(transaction); check.input("id", sql.BigInt, value.parentId); if (!(await check.query(`SELECT id FROM dbo.knowledge_categories WHERE id=@id;`)).recordset[0]) throw new ApiError(422, "invalid_reference", "Parent category was not found."); } const insert = new sql.Request(transaction); bindCategory(insert, value, actor.id); const row = (await insert.query<{ id: number | string }>(`INSERT INTO dbo.knowledge_categories(parent_id,code,name_en,name_th,name_ja,default_document_type,default_confidentiality,sort_order,is_active,created_by,updated_by) OUTPUT inserted.id VALUES(@parent,@code,@name_en,@name_th,@name_ja,@type,@conf,@sort,@active,@actor,@actor);`)).recordset[0]!; return { id: Number(row.id) }; }); return reply.status(201).header("Location", `/api/v1/knowledge/categories/${created.id}`).send(created); });
  app.put("/api/v1/knowledge/categories/:id", async (request) => { await users.demandPermission(request, "knowledge.manage_categories"); const actor = await users.required(request), id = positiveLong((request.params as { id?: string }).id, "Category id"), value = categoryBody(request.body); if (value.parentId === id) throw new ApiError(400, "validation_failed", "A category cannot be its own parent."); return database.transaction(async (transaction) => { if (value.parentId) { const check = new sql.Request(transaction); check.input("id", sql.BigInt, value.parentId); if (!(await check.query(`SELECT id FROM dbo.knowledge_categories WHERE id=@id;`)).recordset[0]) throw new ApiError(422, "invalid_reference", "Parent category was not found."); } const update = new sql.Request(transaction); bindCategory(update, value, actor.id); update.input("id", sql.BigInt, id); const result = await update.query(`UPDATE dbo.knowledge_categories SET parent_id=@parent,code=@code,name_en=@name_en,name_th=@name_th,name_ja=@name_ja,default_document_type=@type,default_confidentiality=@conf,sort_order=@sort,is_active=@active,updated_by=@actor,updated_at=SYSUTCDATETIME() WHERE id=@id;`); if (result.rowsAffected[0] !== 1) throw new ApiError(404, "category_not_found", "Category not found."); return { id }; }); });

  app.get("/api/v1/knowledge/number-sequences", async (request) => { await users.demandPermission(request, "knowledge.manage_categories"); const result = await database.query<Record<string, unknown>>(`SELECT id,prefix,scope_code,scope_name,last_number,padding,is_active,updated_at FROM dbo.knowledge_number_sequences ORDER BY prefix,scope_code;`); return { items: result.recordset.map((row) => ({ id: Number(row.id), prefix: row.prefix, scopeCode: row.scope_code, scopeName: row.scope_name, lastNumber: Number(row.last_number), padding: Number(row.padding), isActive: Boolean(row.is_active), updatedAt: row.updated_at })) }; });
  app.post("/api/v1/knowledge/number-sequences", async (request, reply) => { await users.demandPermission(request, "knowledge.manage_categories"); const value = sequenceBody(request.body); const result = await database.query<{ id: number | string }>(`INSERT INTO dbo.knowledge_number_sequences(prefix,scope_code,scope_name,last_number,padding,is_active) OUTPUT inserted.id VALUES(@prefix,@scope,@name,@last,@padding,@active);`, (bind) => bindSequence(bind, value)); const id = Number(result.recordset[0]!.id); return reply.status(201).header("Location", `/api/v1/knowledge/number-sequences/${id}`).send({ id }); });
  app.put("/api/v1/knowledge/number-sequences/:id", async (request) => { await users.demandPermission(request, "knowledge.manage_categories"); const id = positiveLong((request.params as { id?: string }).id, "Number sequence id"), value = sequenceBody(request.body); const result = await database.query(`UPDATE dbo.knowledge_number_sequences SET scope_name=@name,last_number=CASE WHEN @last>=last_number THEN @last ELSE last_number END,padding=@padding,is_active=@active,updated_at=SYSUTCDATETIME() WHERE id=@id AND prefix=@prefix AND scope_code=@scope;`, (bind) => { bindSequence(bind, value); bind.input("id", sql.BigInt, id); }); if (result.rowsAffected[0] !== 1) throw new ApiError(404, "sequence_not_found", "Number sequence not found."); return { id }; });
}
