import sql from "mssql";
import type { FastifyInstance } from "fastify";
import type { Transaction as TransactionType } from "mssql";
import { insertAudit } from "../audit.js";
import type { Database } from "../db.js";
import { ApiError } from "../errors.js";
import { bodyObject, optionalBodyText, parseRowVersion, positiveLong, requiredInteger, requiredText } from "../http.js";
import { demandProjectScope, isMyWorkElevated } from "../project-scope.js";
import { networkDays } from "../schedule-calculator.js";
import {
  appendUpdate, calendarDays, concurrency, currentScheduleVersion, demandAssignedLeaf, demandPlanOwner,
  hasChildren, hasPendingRequest, permissionFor, planInput, progressInput, readHolidays, readPics, readProject,
  readTask, readTasks, replacePics, resolveTasks, taskResponse, validateGraphAndHierarchy, validatePics,
  validateScheduleVersion, type PlanInput, type TaskRow,
} from "../schedule-service.js";
import type { CurrentUser } from "../types.js";
import type { CurrentUserService } from "../users.js";

function bindPlan(request: InstanceType<typeof sql.Request>, projectId: number, input: PlanInput, actorId: number): void {
  request.input("project", sql.BigInt, projectId); request.input("parent", sql.BigInt, input.parentId);
  request.input("sort", sql.Int, input.sortOrder); request.input("kind", sql.NVarChar(20), input.kind);
  request.input("name", sql.NVarChar(500), input.name); request.input("milestone", sql.Bit, input.isMilestone);
  request.input("visibility", sql.NVarChar(20), input.visibility); request.input("plan_start", sql.Date, input.planStart);
  request.input("plan_days", sql.Int, input.planDays); request.input("start_mode", sql.NVarChar(20), input.startMode);
  request.input("predecessor", sql.BigInt, input.predecessorId); request.input("lag", sql.Int, input.lagDays);
  request.input("pic_external", sql.NVarChar(300), input.picExternal); request.input("man_days", sql.Decimal(9, 2), input.planManDays);
  request.input("actor", sql.BigInt, actorId);
}

function planAudit(input: PlanInput): Record<string, unknown> {
  return { parentId: input.parentId, sortOrder: input.sortOrder, kind: input.kind, name: input.name, isMilestone: input.isMilestone,
    visibility: input.visibility, planStart: input.planStart, planDays: input.planDays, startMode: input.startMode,
    predecessorId: input.predecessorId, lagDays: input.lagDays, picUserIds: input.picUserIds,
    picExternal: input.picExternal, planManDays: input.planManDays };
}

function existingPlan(task: TaskRow, picUserIds: number[]): Record<string, unknown> {
  return { parentId: task.parentId, sortOrder: task.sortOrder, kind: task.kind, name: task.name, isMilestone: task.isMilestone,
    visibility: task.visibility, planStart: task.planStart, planDays: task.planDays, startMode: task.startMode,
    predecessorId: task.predecessorId, lagDays: task.lagDays, picUserIds, picExternal: task.picExternal, planManDays: task.planManDays };
}

async function readBaselines(transaction: TransactionType, projectId: number) {
  const request = new sql.Request(transaction); request.input("project", sql.BigInt, projectId);
  return (await request.query<Record<string, unknown>>(`SELECT b.id,b.revision,b.label,b.taken_at,u.name taken_by,b.reason,b.task_count,b.promised_finish,b.snapshot_json FROM dbo.schedule_baselines b INNER JOIN dbo.users u ON u.id=b.taken_by WHERE b.project_id=@project ORDER BY b.revision DESC;`)).recordset.map((row) => ({
    id: Number(row.id), revision: Number(row.revision), label: row.label, takenAt: row.taken_at, takenBy: row.taken_by,
    reason: row.reason, taskCount: Number(row.task_count), promisedFinish: row.promised_finish, snapshot: JSON.parse(String(row.snapshot_json)),
  }));
}

async function readUpdates(transaction: TransactionType, projectId: number) {
  const request = new sql.Request(transaction); request.input("project", sql.BigInt, projectId);
  return (await request.query<Record<string, unknown>>(`WITH ranked AS (SELECT s.*,ROW_NUMBER() OVER(ORDER BY s.occurred_at DESC,s.id DESC) recent_rank FROM dbo.schedule_updates s WHERE s.project_id=@project)
    SELECT s.id,s.task_id,s.field,s.from_value,s.to_value,s.comment,s.request_days,s.answer,s.answer_by,answered.name answer_by_name,s.answer_note,s.answered_at,s.occurred_at,u.id actor_id,u.name actor_name
    FROM ranked s INNER JOIN dbo.users u ON u.id=s.actor_id LEFT JOIN dbo.users answered ON answered.id=s.answer_by
    WHERE s.recent_rank<=100 OR (s.field=N'request' AND s.request_days>0 AND s.answer IS NULL) ORDER BY s.occurred_at DESC,s.id DESC;`)).recordset.map((row) => ({
      id: Number(row.id), taskId: row.task_id === null ? null : Number(row.task_id), field: row.field, fromValue: row.from_value,
      toValue: row.to_value, comment: row.comment, requestDays: Number(row.request_days), answer: row.answer,
      answerBy: row.answer_by === null ? null : { id: Number(row.answer_by), name: row.answer_by_name }, answerNote: row.answer_note,
      answeredAt: row.answered_at, occurredAt: row.occurred_at, actor: { id: Number(row.actor_id), name: row.actor_name },
    }));
}

async function projectSchedule(transaction: TransactionType, database: Database, actor: CurrentUser, projectId: number, canPlanPermission: boolean, canProgressPermission: boolean) {
  await demandProjectScope(database, actor, projectId, transaction);
  const project = await readProject(transaction, projectId);
  const tasks = await readTasks(transaction, projectId); const holidays = await readHolidays(transaction); const pics = await readPics(transaction, projectId);
  const calculation = resolveTasks(tasks, holidays); const leaves = [...calculation.byId.values()].filter((item) => !item.children.length);
  const totalWeight = leaves.reduce((sum, item) => sum + item.weight, 0);
  const progress = totalWeight ? Math.round(leaves.reduce((sum, item) => sum + item.percentComplete * item.weight, 0) / totalWeight * 100) / 100 : 0;
  const starts = calculation.roots.map((item) => item.planStart).filter((value): value is string => Boolean(value)).sort();
  const finishes = calculation.roots.map((item) => item.planFinish).filter((value): value is string => Boolean(value)).sort();
  const baselines = await readBaselines(transaction, projectId);
  return { projectId, projectNo: project.projectNo, projectName: project.name, managerId: project.managerId, projectStatus: project.status,
    scheduleVersion: (await currentScheduleVersion(transaction, projectId))?.toString("base64") ?? null,
    canPlan: canPlanPermission && project.status !== "Closed" && (project.managerId === actor.id || actor.role === "Engineering Manager" || actor.role === "Admin"),
    canUpdateProgress: canProgressPermission && project.status !== "Closed",
    summary: { planStart: starts[0] ?? null, planFinish: finishes.at(-1) ?? null,
      workDays: networkDays(starts[0] ?? null, finishes.at(-1) ?? null, holidays), percentComplete: progress,
      taskCount: leaves.length, doneCount: leaves.filter((item) => item.status === "Done").length,
      blockedCount: leaves.filter((item) => item.status === "Blocked").length },
    latestBaseline: baselines[0] ?? null, baselines, recentUpdates: await readUpdates(transaction, projectId),
    tasks: calculation.roots.map((item) => taskResponse(item, new Map(tasks.map((task) => [task.id, task])), pics)) };
}

export function registerScheduleRoutes(app: FastifyInstance, database: Database, users: CurrentUserService): void {
  app.get("/api/v1/projects/:projectId/schedule", async (request) => {
    await users.demandPermission(request, "schedule.read"); const actor = await users.required(request);
    const projectId = positiveLong((request.params as { projectId?: string }).projectId, "Project id");
    const [canPlan, canProgress] = await Promise.all([permissionFor(database, actor.role, "schedule.plan"), permissionFor(database, actor.role, "schedule.progress")]);
    return database.transaction((transaction) => projectSchedule(transaction, database, actor, projectId, canPlan, canProgress), sql.ISOLATION_LEVEL.READ_COMMITTED);
  });

  app.post("/api/v1/projects/:projectId/schedule/tasks", async (request, reply) => {
    await users.demandPermission(request, "schedule.plan"); const actor = await users.required(request);
    const projectId = positiveLong((request.params as { projectId?: string }).projectId, "Project id"); const input = planInput(request.body, false);
    const created = await database.transaction(async (transaction) => {
      const project = await demandPlanOwner(transaction, projectId, actor); await validateScheduleVersion(transaction, projectId, input.scheduleVersion);
      await validateGraphAndHierarchy(transaction, projectId, null, input); if (input.parentId && await hasPendingRequest(transaction, input.parentId)) throw new ApiError(409, "schedule_day_request_pending", "Answer the pending request for more days before changing this task's child rows.");
      await validatePics(transaction, project, input.picUserIds);
      const insert = new sql.Request(transaction); bindPlan(insert, projectId, input, actor.id);
      const row = (await insert.query<{ id: number | string; row_version: Buffer }>(`DECLARE @changed TABLE(id bigint,row_version binary(8)); INSERT INTO dbo.schedule_tasks(project_id,parent_id,sort_order,kind,name,is_milestone,origin,created_by,visibility,plan_start,plan_days,start_mode,predecessor_id,lag_days,pic_external,plan_man_days,updated_by)
        OUTPUT inserted.id,inserted.row_version INTO @changed VALUES(@project,@parent,@sort,@kind,@name,@milestone,N'PM',@actor,@visibility,@plan_start,@plan_days,@start_mode,@predecessor,@lag,@pic_external,@man_days,@actor); SELECT id,row_version FROM @changed;`)).recordset[0]!;
      const id = Number(row.id); await replacePics(transaction, id, input.picUserIds); await appendUpdate(transaction, projectId, id, actor.id, "created", null, input.name, "Schedule task created");
      await insertAudit(transaction, actor.id, "Schedule Task", id, `T-${id}`, "Created", null, planAudit(input));
      return { id, rowVersion: row.row_version.toString("base64"), scheduleVersion: row.row_version.toString("base64") };
    });
    return reply.status(201).header("Location", `/api/v1/schedule/tasks/${created.id}`).send(created);
  });

  app.put("/api/v1/schedule/tasks/:id", async (request) => {
    await users.demandPermission(request, "schedule.plan"); const actor = await users.required(request);
    const id = positiveLong((request.params as { id?: string }).id, "Schedule task id"); const input = planInput(request.body, true);
    return database.transaction(async (transaction) => {
      const existing = await readTask(transaction, id); const project = await demandPlanOwner(transaction, existing.projectId, actor);
      await validateScheduleVersion(transaction, existing.projectId, input.scheduleVersion); if (!existing.rowVersion.equals(input.rowVersion!)) throw concurrency();
      const pics = await readPics(transaction, existing.projectId); const oldPics = (pics.get(id) ?? []).map((pic) => pic.id);
      if (await hasPendingRequest(transaction, id)) throw new ApiError(409, "schedule_day_request_pending", "Answer the pending request for more days before changing this task's plan or assignment.");
      await validateGraphAndHierarchy(transaction, existing.projectId, id, input); if (input.parentId !== existing.parentId && input.parentId && await hasPendingRequest(transaction, input.parentId)) throw new ApiError(409, "schedule_day_request_pending", "Answer the pending request for more days before changing this task's child rows.");
      await validatePics(transaction, project, input.picUserIds);
      if (await hasChildren(transaction, id) && (existing.planStart !== input.planStart || existing.planDays !== input.planDays || existing.startMode !== input.startMode || existing.predecessorId !== input.predecessorId || existing.lagDays !== input.lagDays)) throw new ApiError(400, "schedule_rollup_plan_derived", "A roll-up row's dates and dependency are calculated from its children and cannot be changed directly.");
      const update = new sql.Request(transaction); bindPlan(update, existing.projectId, input, actor.id); update.input("id", sql.BigInt, id); update.input("version", sql.VarBinary(8), input.rowVersion);
      const row = (await update.query<{ row_version: Buffer }>(`DECLARE @changed TABLE(row_version binary(8)); UPDATE dbo.schedule_tasks SET parent_id=@parent,sort_order=@sort,kind=@kind,name=@name,is_milestone=@milestone,visibility=@visibility,plan_start=@plan_start,plan_days=@plan_days,start_mode=@start_mode,predecessor_id=@predecessor,lag_days=@lag,pic_external=@pic_external,plan_man_days=@man_days,updated_by=@actor,updated_at=SYSUTCDATETIME() OUTPUT inserted.row_version INTO @changed WHERE id=@id AND project_id=@project AND deleted_at IS NULL AND row_version=@version; SELECT row_version FROM @changed;`)).recordset[0];
      if (!row) throw concurrency(); await replacePics(transaction, id, input.picUserIds); const before = existingPlan(existing, oldPics), after = planAudit(input);
      await appendUpdate(transaction, existing.projectId, id, actor.id, "plan", JSON.stringify(before), JSON.stringify(after), null); await insertAudit(transaction, actor.id, "Schedule Task", id, `T-${id}`, "Updated plan", before, after);
      return { id, rowVersion: row.row_version.toString("base64"), scheduleVersion: (await currentScheduleVersion(transaction, existing.projectId))!.toString("base64") };
    });
  });

  app.post("/api/v1/schedule/tasks/:id/updates", async (request) => {
    await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request);
    const id = positiveLong((request.params as { id?: string }).id, "Schedule task id"); const input = progressInput(request.body);
    return database.transaction(async (transaction) => {
      const task = await readTask(transaction, id); await demandProjectScope(database, actor, task.projectId, transaction, true);
      const project = await readProject(transaction, task.projectId, true); if (project.status === "Closed") throw new ApiError(409, "project_closed", "A closed project's schedule cannot be changed.");
      await validateScheduleVersion(transaction, task.projectId, input.scheduleVersion); if (!task.rowVersion.equals(input.rowVersion)) throw concurrency(); await demandAssignedLeaf(transaction, task, actor.id);
      const changes: Array<[string, unknown, unknown]> = [["percent_complete", task.percentComplete, input.percentComplete], ["actual_start", task.actualStart, input.actualStart], ["actual_finish", task.actualFinish, input.actualFinish], ["forecast_finish", task.forecastFinish, input.forecastFinish], ["status", task.status, input.status], ["blocked_reason", task.blockedReason, input.status === "Blocked" ? input.remark : null], ["remark", task.remark, input.remark]].filter(([, before, after]) => (before ?? null) !== (after ?? null)) as Array<[string, unknown, unknown]>;
      if (!changes.length) throw new ApiError(409, "no_schedule_change", "The progress update does not change the task.");
      const update = new sql.Request(transaction); update.input("percent", sql.Decimal(5, 2), input.percentComplete); update.input("actual_start", sql.Date, input.actualStart); update.input("actual_finish", sql.Date, input.actualFinish); update.input("forecast_finish", sql.Date, input.forecastFinish); update.input("status", sql.NVarChar(30), input.status); update.input("blocked", sql.NVarChar(sql.MAX), input.status === "Blocked" ? input.remark : null); update.input("remark", sql.NVarChar(sql.MAX), input.remark); update.input("actor", sql.BigInt, actor.id); update.input("id", sql.BigInt, id); update.input("version", sql.VarBinary(8), input.rowVersion);
      const row = (await update.query<{ row_version: Buffer }>(`DECLARE @changed TABLE(row_version binary(8)); UPDATE dbo.schedule_tasks SET percent_done=@percent,actual_start=@actual_start,actual_end=@actual_finish,forecast_end=@forecast_finish,status=@status,blocked_reason=@blocked,note=@remark,updated_by=@actor,updated_at=SYSUTCDATETIME() OUTPUT inserted.row_version INTO @changed WHERE id=@id AND deleted_at IS NULL AND row_version=@version; SELECT row_version FROM @changed;`)).recordset[0]; if (!row) throw concurrency();
      for (const [field, before, after] of changes) await appendUpdate(transaction, task.projectId, id, actor.id, field, before == null ? null : String(before), after == null ? null : String(after), input.remark);
      await insertAudit(transaction, actor.id, "Schedule Task", id, `T-${id}`, "Updated progress", { percentComplete: task.percentComplete, actualStart: task.actualStart, actualFinish: task.actualFinish, forecastFinish: task.forecastFinish, status: task.status, blockedReason: task.blockedReason, remark: task.remark }, input);
      return { id, rowVersion: row.row_version.toString("base64"), scheduleVersion: (await currentScheduleVersion(transaction, task.projectId))!.toString("base64") };
    });
  });

  app.post("/api/v1/schedule/tasks/:id/day-requests", async (request, reply) => {
    await users.demandPermission(request, "schedule.read"); await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request);
    const id = positiveLong((request.params as { id?: string }).id, "Schedule task id"); const body = bodyObject(request.body);
    const requestDays = requiredInteger(body.requestDays, "Requested days", 1, 3650), comment = requiredText(body.comment, 20_000, "Request comment");
    const created = await database.transaction(async (transaction) => { const task = await readTask(transaction, id); await demandProjectScope(database, actor, task.projectId, transaction, true); const project = await readProject(transaction, task.projectId, true); if (project.status === "Closed") throw new ApiError(409, "project_closed", "A closed project's schedule cannot be changed."); await demandAssignedLeaf(transaction, task, actor.id); if (await hasPendingRequest(transaction, id)) throw new ApiError(409, "schedule_day_request_pending", "This task already has a pending request for more days.");
      const insert = new sql.Request(transaction); insert.input("project", sql.BigInt, task.projectId); insert.input("task", sql.BigInt, id); insert.input("actor", sql.BigInt, actor.id); insert.input("from", sql.NVarChar(sql.MAX), task.forecastFinish); insert.input("to", sql.NVarChar(sql.MAX), `+${requestDays} days`); insert.input("comment", sql.NVarChar(sql.MAX), comment); insert.input("days", sql.Int, requestDays);
      const row = (await insert.query<{ id: number | string; occurred_at: unknown }>(`INSERT INTO dbo.schedule_updates(project_id,task_id,actor_id,field,from_value,to_value,comment,request_days) OUTPUT inserted.id,inserted.occurred_at VALUES(@project,@task,@actor,N'request',@from,@to,@comment,@days);`)).recordset[0]!;
      const requestId = Number(row.id); await insertAudit(transaction, actor.id, "Schedule Day Request", requestId, `T-${id}/R-${requestId}`, "Requested more days", null, { taskId: id, requestDays, comment }); return { id: requestId, taskId: id, requestDays, comment, occurredAt: row.occurred_at }; });
    return reply.status(201).header("Location", `/api/v1/me/work/updates/${created.id}`).send(created);
  });

  app.post("/api/v1/schedule/day-requests/:id/answer", async (request) => {
    await users.demandPermission(request, "schedule.plan"); const actor = await users.required(request); const id = positiveLong((request.params as { id?: string }).id, "Day request id"); const body = bodyObject(request.body);
    const answer = requiredText(body.answer, 20, "Day request answer"); if (!["Accepted", "Rejected"].includes(answer)) throw new ApiError(400, "validation_failed", "Day request answer is invalid."); const note = optionalBodyText(body.note, 20_000, "Answer note"); const expected = parseRowVersion(body.rowVersion); const scheduleVersion = body.scheduleVersion == null ? null : requiredText(body.scheduleVersion, 64, "Schedule version");
    return database.transaction(async (transaction) => { const locate = new sql.Request(transaction); locate.input("id", sql.BigInt, id); const location = (await locate.query<{ project_id: number | string; task_id: number | string }>(`SELECT project_id,task_id FROM dbo.schedule_updates WITH (UPDLOCK,HOLDLOCK) WHERE id=@id AND task_id IS NOT NULL AND field=N'request' AND request_days>0;`)).recordset[0]; if (!location) throw new ApiError(404, "schedule_day_request_not_found", "Schedule day request not found.");
      const projectId = Number(location.project_id), taskId = Number(location.task_id), task = await readTask(transaction, taskId); const project = await demandPlanOwner(transaction, projectId, actor); if (task.projectId !== projectId) throw new ApiError(409, "schedule_day_request_invalid", "The day request no longer matches its task."); if (task.kind === "phase" || await hasChildren(transaction, taskId)) throw new ApiError(409, "schedule_day_request_not_leaf", "A day request can only be answered while its task remains a non-phase leaf row.");
      const read = new sql.Request(transaction); read.input("id", sql.BigInt, id); const row = (await read.query<{ request_days: number; answer: string | null }>(`SELECT request_days,answer FROM dbo.schedule_updates WITH (UPDLOCK,HOLDLOCK) WHERE id=@id;`)).recordset[0]!; if (row.answer) throw new ApiError(409, "schedule_day_request_answered", "This day request has already been answered."); await validateScheduleVersion(transaction, projectId, scheduleVersion); if (!task.rowVersion.equals(expected)) throw concurrency(); if (answer === "Accepted" && task.planDays > 3650 - row.request_days) throw new ApiError(400, "validation_failed", "Accepting this request would make the task longer than 3650 calendar days.");
      const action = new sql.Request(transaction); action.input("request_id", sql.BigInt, id); action.input("task_id", sql.BigInt, taskId); action.input("project_id", sql.BigInt, projectId); action.input("answer_by", sql.BigInt, actor.id); action.input("answer", sql.NVarChar(20), answer); action.input("answer_note", sql.NVarChar(sql.MAX), note); action.input("expected_row_version", sql.VarBinary(8), expected); const changed = (await action.execute<{ id: number | string; row_version: Buffer }>("dbo.answer_schedule_day_request")).recordset[0]; if (!changed || Number(changed.id) !== taskId) throw concurrency(); const planDays = answer === "Accepted" ? task.planDays + row.request_days : task.planDays;
      if (answer === "Accepted") await appendUpdate(transaction, projectId, taskId, actor.id, "plan_days", String(task.planDays), String(planDays), note); await appendUpdate(transaction, projectId, taskId, actor.id, "request_answer", null, answer, note); await insertAudit(transaction, actor.id, "Schedule Day Request", id, `T-${taskId}/R-${id}`, "Answered day request", { requestId: id, answer: null, planDays: task.planDays }, { requestId: id, answer, answerNote: note, requestDays: row.request_days, planDays });
      return { id, projectId, taskId, answer, answerNote: note, requestDays: row.request_days, planDays, rowVersion: changed.row_version.toString("base64"), scheduleVersion: (await currentScheduleVersion(transaction, project.id))!.toString("base64") };
    });
  });

  app.post("/api/v1/schedule/tasks/:id/details", async (request, reply) => {
    await users.demandPermission(request, "schedule.read"); await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request); const id = positiveLong((request.params as { id?: string }).id, "Schedule task id"); const body = bodyObject(request.body); const name = requiredText(body.name, 500, "Task name"), planDays = requiredInteger(body.planDays, "Plan days", 1, 3650), expected = parseRowVersion(body.rowVersion), scheduleVersion = body.scheduleVersion == null ? null : requiredText(body.scheduleVersion, 64, "Schedule version");
    const created = await database.transaction(async (transaction) => { const parent = await readTask(transaction, id); await demandProjectScope(database, actor, parent.projectId, transaction, true); const project = await readProject(transaction, parent.projectId, true); if (project.status === "Closed") throw new ApiError(409, "project_closed", "A closed project's schedule cannot be changed."); await validateScheduleVersion(transaction, parent.projectId, scheduleVersion); if (!parent.rowVersion.equals(expected)) throw concurrency(); await demandAssignedLeaf(transaction, parent, actor.id); if (parent.kind !== "task") throw new ApiError(422, "schedule_detail_parent_required", "A member detail can only be added beneath an assigned task row."); if (parent.startMode !== "manual" || parent.predecessorId) throw new ApiError(409, "schedule_detail_parent_linked", "A member cannot add a detail beneath a linked or predecessor-driven task."); if (parent.status !== "Not Started" || parent.percentComplete !== 0 || parent.actualStart || parent.actualFinish || parent.forecastFinish || parent.actualManDays !== 0) throw new ApiError(409, "schedule_detail_parent_started", "A member detail can only be added before the parent task has started."); if (await hasPendingRequest(transaction, id)) throw new ApiError(409, "schedule_day_request_pending", "Answer the pending request before changing child rows."); const tasks = await readTasks(transaction, parent.projectId), holidays = await readHolidays(transaction), resolved = resolveTasks(tasks, holidays).byId.get(id)!; if (!resolved.planStart || !resolved.planFinish) throw new ApiError(422, "schedule_detail_start_unresolved", "The parent task must have resolved dates before a detail can be added."); if (planDays !== calendarDays(resolved.planStart, resolved.planFinish)) throw new ApiError(422, "schedule_detail_outside_parent_plan", "The first member detail must cover the current parent plan period exactly."); const order = new sql.Request(transaction); order.input("parent", sql.BigInt, id); const sort = Number((await order.query<{ value: number }>(`SELECT COALESCE(MAX(sort_order),0)+1 value FROM dbo.schedule_tasks WITH (UPDLOCK,HOLDLOCK) WHERE parent_id=@parent AND deleted_at IS NULL;`)).recordset[0]!.value);
const insert = new sql.Request(transaction); insert.input("project", sql.BigInt, parent.projectId); insert.input("parent", sql.BigInt, id); insert.input("sort", sql.Int, sort); insert.input("name", sql.NVarChar(500), name); insert.input("actor", sql.BigInt, actor.id); insert.input("start", sql.Date, resolved.planStart); insert.input("days", sql.Int, planDays); const row = (await insert.query<{ id: number | string; row_version: Buffer }>(`DECLARE @changed TABLE(id bigint,row_version binary(8)); INSERT INTO dbo.schedule_tasks(project_id,parent_id,sort_order,kind,name,is_milestone,origin,created_by,visibility,plan_start,plan_days,start_mode,predecessor_id,lag_days,pic_external,plan_man_days,updated_by) OUTPUT inserted.id,inserted.row_version INTO @changed VALUES(@project,@parent,@sort,N'detail',@name,0,N'Member',@actor,N'Internal',@start,@days,N'manual',NULL,0,N'',0,@actor); SELECT id,row_version FROM @changed;`)).recordset[0]!; const detailId = Number(row.id); await replacePics(transaction, detailId, [actor.id]); await appendUpdate(transaction, parent.projectId, detailId, actor.id, "created", null, name, "Member detail created"); await insertAudit(transaction, actor.id, "Schedule Task", detailId, `T-${detailId}`, "Created member detail", null, { id: detailId, projectId: parent.projectId, parentId: id, kind: "detail", name, origin: "Member", visibility: "Internal", planStart: resolved.planStart, planDays, picUserIds: [actor.id] }); return { id: detailId, parentId: id, rowVersion: row.row_version.toString("base64"), scheduleVersion: (await currentScheduleVersion(transaction, parent.projectId))!.toString("base64") }; }); return reply.status(201).header("Location", `/api/v1/schedule/tasks/${created.id}`).send(created);
  });

  app.delete("/api/v1/schedule/tasks/:id/details", async (request) => {
    await users.demandPermission(request, "schedule.read"); await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request); const id = positiveLong((request.params as { id?: string }).id, "Schedule task id"); const body = bodyObject(request.body); const expected = parseRowVersion(body.rowVersion), scheduleVersion = body.scheduleVersion == null ? null : requiredText(body.scheduleVersion, 64, "Schedule version");
    return database.transaction(async (transaction) => { const task = await readTask(transaction, id); await demandProjectScope(database, actor, task.projectId, transaction, true); const project = await readProject(transaction, task.projectId, true); if (project.status === "Closed") throw new ApiError(409, "project_closed", "A closed project's schedule cannot be changed."); await validateScheduleVersion(transaction, task.projectId, scheduleVersion); if (!task.rowVersion.equals(expected)) throw concurrency(); const ownership = new sql.Request(transaction); ownership.input("task", sql.BigInt, id); ownership.input("actor", sql.BigInt, actor.id); const assigned = Boolean((await ownership.query<{ allowed: boolean }>(`SELECT CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.schedule_task_pics WHERE task_id=@task AND user_id=@actor) THEN 1 ELSE 0 END AS bit) allowed;`)).recordset[0]?.allowed); if (task.kind !== "detail" || task.origin !== "Member" || task.createdBy !== actor.id || !assigned) throw new ApiError(403, "schedule_member_detail_owner_required", "Only the member who created and owns this detail can delete it."); if (task.status !== "Not Started" || task.percentComplete !== 0 || task.actualStart || task.actualFinish) throw new ApiError(409, "schedule_detail_started", "A member detail cannot be deleted after work has started."); if (await hasChildren(transaction, id)) throw new ApiError(409, "schedule_detail_has_children", "A member detail with active children cannot be deleted."); if (await hasPendingRequest(transaction, id)) throw new ApiError(409, "schedule_day_request_pending", "Answer the pending request before deleting this task."); const reference = new sql.Request(transaction); reference.input("task", sql.BigInt, id); if ((await reference.query<{ value: boolean }>(`SELECT CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.schedule_tasks WITH (UPDLOCK,HOLDLOCK) WHERE predecessor_id=@task AND deleted_at IS NULL) THEN 1 ELSE 0 END AS bit) value;`)).recordset[0]?.value) throw new ApiError(409, "schedule_detail_referenced", "A member detail used as a predecessor cannot be deleted."); await appendUpdate(transaction, task.projectId, id, actor.id, "deleted", task.name, null, "Member detail deleted"); await insertAudit(transaction, actor.id, "Schedule Task", id, `T-${id}`, "Deleted member detail", task, null); const remove = new sql.Request(transaction); remove.input("actor", sql.BigInt, actor.id); remove.input("task", sql.BigInt, id); remove.input("version", sql.VarBinary(8), expected); const result = await remove.query(`UPDATE dbo.schedule_tasks SET deleted_at=SYSUTCDATETIME(),updated_by=@actor,updated_at=SYSUTCDATETIME() WHERE id=@task AND deleted_at IS NULL AND row_version=@version;`); if (result.rowsAffected[0] !== 1) throw concurrency(); return { id, deleted: true, scheduleVersion: (await currentScheduleVersion(transaction, task.projectId))?.toString("base64") ?? null }; });
  });

  app.post("/api/v1/projects/:projectId/schedule/baseline", async (request, reply) => {
    await users.demandPermission(request, "schedule.plan"); const actor = await users.required(request); const projectId = positiveLong((request.params as { projectId?: string }).projectId, "Project id"); const body = bodyObject(request.body); const label = requiredText(body.label, 200, "Baseline label"), reason = requiredText(body.reason, 20_000, "Baseline reason"), scheduleVersion = body.scheduleVersion == null ? null : requiredText(body.scheduleVersion, 64, "Schedule version");
    const created = await database.transaction(async (transaction) => { const project = await demandPlanOwner(transaction, projectId, actor); await validateScheduleVersion(transaction, projectId, scheduleVersion); const tasks = await readTasks(transaction, projectId); if (!tasks.length) throw new ApiError(409, "schedule_empty", "A baseline cannot be taken before the schedule has tasks."); const calculation = resolveTasks(tasks, await readHolidays(transaction)); const next = new sql.Request(transaction); next.input("project", sql.BigInt, projectId); const revision = Number((await next.query<{ value: number }>(`SELECT COALESCE(MAX(revision),0)+1 value FROM dbo.schedule_baselines WITH (UPDLOCK,HOLDLOCK) WHERE project_id=@project;`)).recordset[0]!.value); const snapshot = JSON.stringify([...calculation.byId.values()].sort((a, b) => a.wbs.localeCompare(b.wbs)).map((item) => ({ id: item.source.id, parentId: item.source.parentId, wbs: item.wbs, planStart: item.planStart, planFinish: item.planFinish, planDays: item.source.planDays, workDays: item.workDays, percentComplete: item.percentComplete, status: item.status }))); for (const task of tasks) { const item = calculation.byId.get(task.id)!; const freeze = new sql.Request(transaction); freeze.input("start", sql.Date, item.planStart); freeze.input("finish", sql.Date, item.planFinish); freeze.input("days", sql.Int, calendarDays(item.planStart, item.planFinish)); freeze.input("revision", sql.Int, revision); freeze.input("actor", sql.BigInt, actor.id); freeze.input("id", sql.BigInt, task.id); freeze.input("version", sql.VarBinary(8), task.rowVersion); const result = await freeze.query(`UPDATE dbo.schedule_tasks SET baseline_start=@start,baseline_end=@finish,baseline_days=@days,baseline_rev=@revision,updated_by=@actor,updated_at=SYSUTCDATETIME() WHERE id=@id AND deleted_at IS NULL AND row_version=@version;`); if (result.rowsAffected[0] !== 1) throw concurrency(); }
      const finishes = calculation.roots.map((item) => item.planFinish).filter((value): value is string => Boolean(value)).sort(); const promisedFinish = finishes.at(-1) ?? null; const insert = new sql.Request(transaction); insert.input("project", sql.BigInt, projectId); insert.input("revision", sql.Int, revision); insert.input("label", sql.NVarChar(200), label); insert.input("actor", sql.BigInt, actor.id); insert.input("reason", sql.NVarChar(sql.MAX), reason); insert.input("count", sql.Int, tasks.length); insert.input("finish", sql.Date, promisedFinish); insert.input("snapshot", sql.NVarChar(sql.MAX), snapshot); const baselineId = Number((await insert.query<{ id: number | string }>(`INSERT INTO dbo.schedule_baselines(project_id,revision,label,taken_by,reason,task_count,promised_finish,snapshot_json) OUTPUT inserted.id VALUES(@project,@revision,@label,@actor,@reason,@count,@finish,@snapshot);`)).recordset[0]!.id); await appendUpdate(transaction, projectId, null, actor.id, "baseline", revision > 1 ? String(revision - 1) : null, String(revision), reason); await insertAudit(transaction, actor.id, "Schedule Baseline", baselineId, `${project.projectNo}/BL-${String(revision).padStart(3, "0")}`, "Created baseline", null, { revision, label, reason, taskCount: tasks.length, promisedFinish }); return { id: baselineId, revision, taskCount: tasks.length, promisedFinish, scheduleVersion: (await currentScheduleVersion(transaction, projectId))!.toString("base64") }; }); return reply.status(201).header("Location", `/api/v1/projects/${projectId}/schedule/baseline/${created.id}`).send(created);
  });

  app.get("/api/v1/me/work", async (request) => {
    await users.demandPermission(request, "schedule.read"); await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request);
    return database.transaction(async (transaction) => { const projectsRequest = new sql.Request(transaction); projectsRequest.input("actor", sql.BigInt, actor.id); projectsRequest.input("elevated", sql.Bit, isMyWorkElevated(actor)); const projects = (await projectsRequest.query<Record<string, unknown>>(`SELECT DISTINCT p.id,p.project_no,p.name,p.manager_id,manager.name manager_name,p.status,CAST(CASE WHEN p.status<>N'Closed' AND (@elevated=1 OR p.manager_id=@actor OR p.lead_engineer_id=@actor OR EXISTS(SELECT 1 FROM dbo.project_members m WHERE m.project_id=p.id AND m.user_id=@actor)) THEN 1 ELSE 0 END AS bit) can_update FROM dbo.projects p INNER JOIN dbo.users manager ON manager.id=p.manager_id INNER JOIN dbo.schedule_tasks t ON t.project_id=p.id AND t.deleted_at IS NULL INNER JOIN dbo.schedule_task_pics pic ON pic.task_id=t.id WHERE pic.user_id=@actor AND p.deleted_at IS NULL AND (@elevated=1 OR p.manager_id=@actor OR p.lead_engineer_id=@actor OR EXISTS(SELECT 1 FROM dbo.project_members m WHERE m.project_id=p.id AND m.user_id=@actor));`)).recordset; const holidays = await readHolidays(transaction); const work: Array<Record<string, unknown>> = [];
      for (const p of projects) { const projectId = Number(p.id), tasks = await readTasks(transaction, projectId), pics = await readPics(transaction, projectId), calculation = resolveTasks(tasks, holidays), byId = new Map(tasks.map((task) => [task.id, task])); const pendingRequest = new sql.Request(transaction); pendingRequest.input("project", sql.BigInt, projectId); pendingRequest.input("actor", sql.BigInt, actor.id); const pendingRows = (await pendingRequest.query<Record<string, unknown>>(`SELECT id,task_id,actor_id,request_days,comment,occurred_at FROM dbo.schedule_updates WHERE project_id=@project AND task_id IS NOT NULL AND field=N'request' AND request_days>0 AND answer IS NULL ORDER BY occurred_at DESC,id DESC;`)).recordset; const pendingAll = new Set(pendingRows.map((row) => Number(row.task_id))), pendingMine = new Map<number, Record<string, unknown>>(); for (const row of pendingRows) if (Number(row.actor_id) === actor.id && !pendingMine.has(Number(row.task_id))) pendingMine.set(Number(row.task_id), { id: Number(row.id), requestDays: Number(row.request_days), comment: row.comment, occurredAt: row.occurred_at }); const dependent = new Set(tasks.filter((task) => task.predecessorId).map((task) => task.predecessorId!)); const version = (await currentScheduleVersion(transaction, projectId))?.toString("base64") ?? null;
        for (const task of tasks.filter((item) => item.kind !== "phase" && !calculation.byId.get(item.id)!.children.length && (pics.get(item.id) ?? []).some((pic) => pic.id === actor.id))) { const item = calculation.byId.get(task.id)!; let current: TaskRow | undefined = task, phase: { wbs: string; name: string } | null = null; while (current?.parentId) { const parent = byId.get(current.parentId); if (!parent) break; if (parent.kind === "phase") phase = { wbs: calculation.byId.get(parent.id)!.wbs, name: parent.name }; current = parent; } const isOwnDetail = task.kind === "detail" && task.origin === "Member" && task.createdBy === actor.id, canUpdate = Boolean(p.can_update), hasPending = pendingAll.has(task.id); const canAddDetail = canUpdate && task.kind === "task" && task.startMode === "manual" && !task.predecessorId && task.status === "Not Started" && task.percentComplete === 0 && !task.actualStart && !task.actualFinish && !task.forecastFinish && task.actualManDays === 0 && Boolean(item.planStart && item.planFinish) && !hasPending; const canDeleteDetail = canUpdate && isOwnDetail && task.status === "Not Started" && task.percentComplete === 0 && !task.actualStart && !task.actualFinish && !hasPending && !dependent.has(task.id); work.push({ projectId, projectNo: p.project_no, projectName: p.name, managerId: Number(p.manager_id), managerName: p.manager_name, projectStatus: p.status, scheduleVersion: version, canUpdate, isOwnDetail, canAddDetail, canDeleteDetail, taskId: task.id, parentId: task.parentId, wbs: item.wbs, name: task.name, kind: task.kind, origin: task.origin, isMilestone: task.isMilestone, phaseWbs: phase?.wbs ?? null, phaseName: phase?.name ?? null, planStart: item.planStart, planFinish: item.planFinish, workDays: item.workDays, percentComplete: item.percentComplete, status: item.status, actualStart: item.actualStart, actualFinish: item.actualFinish, forecastFinish: item.forecastFinish, remark: task.remark, pendingRequest: pendingMine.get(task.id) ?? null, rowVersion: task.rowVersion.toString("base64"), updatedAt: task.updatedAt }); } }
      return work.sort((a, b) => Number(a.status === "Done") - Number(b.status === "Done") || String(a.planFinish ?? "9999").localeCompare(String(b.planFinish ?? "9999")) || String(a.projectNo).localeCompare(String(b.projectNo)) || String(a.wbs).localeCompare(String(b.wbs))); }, sql.ISOLATION_LEVEL.READ_COMMITTED);
  });

  app.get("/api/v1/me/work/updates", async (request) => {
    await users.demandPermission(request, "schedule.read"); await users.demandPermission(request, "schedule.progress"); const actor = await users.required(request);
    return database.transaction(async (transaction) => { const read = new sql.Request(transaction); read.input("actor", sql.BigInt, actor.id); read.input("elevated", sql.Bit, isMyWorkElevated(actor)); const rows = (await read.query<Record<string, unknown>>(`SELECT TOP(100) s.id,s.project_id,p.project_no,p.name project_name,s.task_id,t.name task_name,s.field,s.from_value,s.to_value,s.comment,s.request_days,s.answer,s.answer_note,s.occurred_at FROM dbo.schedule_updates s INNER JOIN dbo.projects p ON p.id=s.project_id LEFT JOIN dbo.schedule_tasks t ON t.id=s.task_id WHERE s.actor_id=@actor AND p.deleted_at IS NULL AND (@elevated=1 OR p.manager_id=@actor OR p.lead_engineer_id=@actor OR EXISTS(SELECT 1 FROM dbo.project_members m WHERE m.project_id=p.id AND m.user_id=@actor)) ORDER BY s.occurred_at DESC,s.id DESC;`)).recordset; const wbs = new Map<number, string>(); for (const projectId of [...new Set(rows.map((row) => Number(row.project_id)))]) { const tasks = await readTasks(transaction, projectId); if (tasks.length) for (const item of resolveTasks(tasks, await readHolidays(transaction)).byId.values()) wbs.set(item.source.id, item.wbs); } return rows.map((row) => ({ id: Number(row.id), projectId: Number(row.project_id), projectNo: row.project_no, projectName: row.project_name, taskId: row.task_id === null ? null : Number(row.task_id), wbs: row.task_id === null ? null : wbs.get(Number(row.task_id)) ?? null, taskName: row.task_name, field: row.field, fromValue: row.from_value, toValue: row.to_value, comment: row.comment, requestDays: Number(row.request_days), answer: row.answer, answerNote: row.answer_note, occurredAt: row.occurred_at })); }, sql.ISOLATION_LEVEL.READ_COMMITTED);
  });
}
