SET NOCOUNT ON;
SET XACT_ABORT ON;
IF (SELECT MAX(version) FROM dbo.schema_versions)<>53 THROW 51529,'Expected schema 053.',1;
BEGIN TRANSACTION;
DECLARE @admin bigint,@sales bigint,@engineer bigint,@other bigint,@customer bigint,@site bigint,@contact bigint,@opp bigint,@number1 bigint,@number2 bigint;
INSERT dbo.users(entra_object_id,email,name,role_id,department) SELECT N'crm-test-admin',N'crm-admin@example.invalid',N'CRM Admin',id,N'Admin' FROM dbo.roles WHERE code='Admin';SET @admin=SCOPE_IDENTITY();
INSERT dbo.users(entra_object_id,email,name,role_id,department) SELECT N'crm-test-sales',N'crm-sales@example.invalid',N'CRM Sales',id,N'Sales' FROM dbo.roles WHERE code='Sales Engineer';SET @sales=SCOPE_IDENTITY();
INSERT dbo.users(entra_object_id,email,name,role_id,department) SELECT N'crm-test-engineer',N'crm-engineer@example.invalid',N'CRM Engineer',id,N'Engineering' FROM dbo.roles WHERE code='Engineer';SET @engineer=SCOPE_IDENTITY();
INSERT dbo.users(entra_object_id,email,name,role_id,department) SELECT N'crm-test-other',N'crm-other@example.invalid',N'CRM Other',id,N'Other' FROM dbo.roles WHERE code='Engineer';SET @other=SCOPE_IDENTITY();
INSERT dbo.customers(code,name,created_by,updated_by) VALUES('CRM-TEST',N'CRM Test Customer',@admin,@admin);SET @customer=SCOPE_IDENTITY();
INSERT dbo.customer_sites(customer_id,code,name,created_by,updated_by) VALUES(@customer,'MAIN',N'Test site',@admin,@admin);SET @site=SCOPE_IDENTITY();
INSERT dbo.customer_site_contacts(site_id,name,created_by,updated_by) VALUES(@site,N'Technical contact',@admin,@admin);SET @contact=SCOPE_IDENTITY();
SELECT @number1=NEXT VALUE FOR dbo.crm_opportunity_numbers;
INSERT dbo.crm_opportunities(opportunity_no,name,customer_id,site_id,contact_id,sales_owner_id,technical_owner_id,expected_value,created_by,updated_by)
VALUES(CONCAT('OPP-CRM-TEST-2026-',@number1),N'Test opportunity',@customer,@site,@contact,@sales,@engineer,620000,@sales,@sales);SET @opp=SCOPE_IDENTITY();
IF NOT EXISTS(SELECT 1 FROM dbo.crm_opportunities WHERE id=@opp AND (sales_owner_id=@engineer OR technical_owner_id=@engineer)) THROW 51529,'Technical owner must see assigned opportunity.',1;
IF EXISTS(SELECT 1 FROM dbo.crm_opportunities WHERE id=@opp AND (sales_owner_id=@other OR technical_owner_id=@other)) THROW 51529,'Unrelated engineer must not see opportunity.',1;
IF EXISTS(SELECT 1 FROM dbo.user_effective_permissions WHERE user_id=@engineer AND code='crm.commercial.read') THROW 51529,'Engineer must not receive commercial permission.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.user_effective_permissions WHERE user_id=@sales AND code='crm.convert') THROW 51529,'Sales must be able to convert.',1;
INSERT dbo.crm_activities(customer_id,opportunity_id,contact_id,activity_type,occurred_at,owner_id,summary,created_by) VALUES(@customer,@opp,@contact,'Meeting',SYSUTCDATETIME(),@engineer,N'Confirmed requirements',@engineer);
INSERT dbo.crm_followups(opportunity_id,action,owner_id,due_date,created_by,updated_by) VALUES(@opp,N'Send proposal',@sales,DATEADD(day,-1,CONVERT(date,SYSUTCDATETIME())),@sales,@sales);
IF (SELECT COUNT(*) FROM dbo.crm_followups WHERE owner_id=@sales AND due_date<CONVERT(date,SYSUTCDATETIME()) AND status='Open')<>1 THROW 51529,'Overdue follow-up must be actionable.',1;
DECLARE @version binary(8)=(SELECT row_version FROM dbo.crm_opportunities WHERE id=@opp);
UPDATE dbo.crm_opportunities SET stage='PROPOSAL' WHERE id=@opp;
UPDATE dbo.crm_opportunities SET stage='WON' WHERE id=@opp AND row_version=@version;
IF @@ROWCOUNT<>0 THROW 51529,'Stale version must not overwrite opportunity.',1;
SELECT @number2=NEXT VALUE FOR dbo.crm_opportunity_numbers;
IF @number2<=@number1 THROW 51529,'Numbers must be monotonic and never reused.',1;
UPDATE dbo.crm_opportunities SET stage='LOST',lost_reason='Price' WHERE id=@opp;
IF NOT EXISTS(SELECT 1 FROM dbo.crm_opportunities WHERE id=@opp AND stage='LOST') THROW 51529,'Lost opportunity must remain available.',1;
ROLLBACK;
PRINT 'CRM SQL fixture passed: shared references, effective permissions, scoped ownership, overdue actions, row versions and numbering.';
