import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {buildApp} from '../src/app.js';
import type {AppConfig} from '../src/config.js';
const repo=process.cwd();
const name=`IoTTeamCenter_ResourceCI_${randomUUID().replaceAll('-','')}`;
assert.match(name,/^IoTTeamCenter_ResourceCI_[a-f0-9]{32}$/);
const args=['-S','localhost','-E','-C','-I','-b'];
const run=(statement:string)=>execFileSync('sqlcmd',[...args,'-d',name,'-Q',statement],{cwd:repo,stdio:'pipe'});
let application:Awaited<ReturnType<typeof buildApp>>|undefined;
let checks=0;
try {
  execFileSync('sqlcmd',[...args,'-i','database/scripts/020_deploy_fresh_database.sql','-v',`DatabaseName=${name}`],{cwd:repo,stdio:'pipe'});
  execFileSync('sqlcmd',[...args,'-d',name,'-i','tests/integration/drawing-fixture.sql'],{cwd:repo,stdio:'pipe'});
  run(`UPDATE dbo.inquiries SET status=N'New'; UPDATE dbo.schedule_tasks SET plan_start='20260907',plan_days=5,plan_man_days=4;INSERT dbo.resource_capacity(user_id,days_per_week,updated_by) SELECT id,5,id FROM dbo.users WHERE entra_object_id LIKE N'drawing-%';`);
  const password=randomUUID().replaceAll('-','');run(`CREATE APPLICATION ROLE resource_ci_role WITH PASSWORD='${password}';`);
  execFileSync('sqlcmd',[...args,'-d',name,'-i','database/scripts/010_application_login.sql','-v',`DatabaseName=${name}`,'AppLogin=resource_ci_role'],{cwd:repo,stdio:'pipe'});
  const config:AppConfig={environment:'development',host:'127.0.0.1',port:0,allowedHosts:['localhost'],corsOrigins:['http://localhost:3000'],businessTimeZone:'Asia/Bangkok',auth:{mode:'Development'},database:{connectionString:`Server=localhost;Database=${name};Integrated Security=true;TrustServerCertificate=true`,trustServerCertificate:true,applicationRoleName:'resource_ci_role',applicationRolePassword:password},documentStorage:{mode:'Local',rootPath:resolve(repo,'tmp',name),maxFileSizeBytes:10000000},email:{mode:'Disabled'},pdfParserUrl:'http://pdf-parser:8000'};
  application=await buildApp(config);const {app,database}=application;
  const actors=Object.fromEntries((await database.query<{id:number;entra_object_id:string}>('SELECT id,entra_object_id FROM dbo.users')).recordset.map(u=>[u.entra_object_id,Number(u.id)]));
  const project=Number((await database.query<{id:number}>('SELECT id FROM dbo.projects')).recordset[0]!.id),inquiry=Number((await database.query<{id:number}>('SELECT id FROM dbo.inquiries')).recordset[0]!.id);
  async function api(actor:string,url:string,body?:object,expected=200,method:'GET'|'POST'|'PUT'=body?'POST':'GET') {
    const response=await app.inject({method,url,headers:{'x-dev-user-id':`drawing-${actor}`},...(body?{payload:body}:{})});assert.equal(response.statusCode,expected,`${url}: ${response.body}`);checks++;return response.json();
  }
  const base={sourceKind:'Project',sourceId:project,title:'TEST ONLY customer issue',description:'TEST ONLY customer reports a faulty sensor',reporter:'TEST ONLY customer',isIssue:true,plan:{assigneeId:actors['drawing-member'],start:'2026-09-07',workDays:5,manDays:3,note:''}};
  const preview=await api('manager','/api/v1/resource-tasks/preview',base);assert.equal(preview.weeks[0].afterPercent,140);
  let task=await api('member','/api/v1/resource-tasks',base,201);assert.equal(task.state,'PendingApproval');assert.equal(task.scheduleTaskId,null);
  await api('member',`/api/v1/resource-tasks/${task.id}/approve`,{rowVersion:task.rowVersion,note:'invalid reviewer'},403);
  await api('manager',`/api/v1/resource-tasks/${task.id}/approve`,{rowVersion:task.rowVersion},409);
  const pendingVersion=task.rowVersion;
  task=await api('manager',`/api/v1/resource-tasks/${task.id}/approve`,{rowVersion:task.rowVersion,note:'TEST ONLY approved overload'});assert.ok(task.scheduleTaskId);assert.equal(task.acknowledgedAt,null);
  await api('manager',`/api/v1/resource-tasks/${task.id}/approve`,{rowVersion:pendingVersion,note:'duplicate'},409);
  await api('other',`/api/v1/resource-tasks/${task.id}/acknowledge`,{rowVersion:task.rowVersion},403);
  await api('member',`/api/v1/resource-tasks/${task.id}/progress`,{rowVersion:task.rowVersion,percentComplete:10,status:'In Progress',actualStart:'2026-09-07'},409);
  await api('member',`/api/v1/schedule/tasks/${task.scheduleTaskId}/updates`,{},409);
  const encodedId=String(task.scheduleTaskId).split('').map(c=>`%${c.charCodeAt(0).toString(16)}`).join('');
  await api('member',`/api/v1/schedule/tasks/${encodedId}/updates`,{},409);
  await api('manager',`/api/v1/schedule/tasks/${encodedId}`,{},409,'PUT');
  task=await api('member',`/api/v1/resource-tasks/${task.id}/acknowledge`,{rowVersion:task.rowVersion});assert.ok(task.acknowledgedAt);
  task=await api('member',`/api/v1/resource-tasks/${task.id}/progress`,{rowVersion:task.rowVersion,scheduleVersion:task.scheduleVersion,percentComplete:10,status:'In Progress',actualStart:'2026-09-07',actualFinish:null});
  let reloaded=(await api('member','/api/v1/resource-tasks?mine=true')).items.find((t:{id:number})=>t.id===task.id);assert.equal(reloaded.actualStart,'2026-09-07');
  task=await api('member',`/api/v1/resource-tasks/${task.id}/progress`,{rowVersion:reloaded.rowVersion,scheduleVersion:reloaded.scheduleVersion,percentComplete:20,status:'In Progress',actualStart:reloaded.actualStart,actualFinish:reloaded.actualFinish});assert.equal(task.actualStart,'2026-09-07');
  await api('manager',`/api/v1/schedule/tasks/${task.scheduleTaskId}`,{},409,'PUT');
  const oldEnd=task.end;
  task=await api('member',`/api/v1/resource-tasks/${task.id}/propose`,{rowVersion:task.rowVersion,plan:{...base.plan,start:'2026-09-14',workDays:3,manDays:2,note:'TEST ONLY new plan'}});assert.equal(task.end,oldEnd);
  task=await api('manager',`/api/v1/resource-tasks/${task.id}/reject`,{rowVersion:task.rowVersion,note:'TEST ONLY keep current plan'});assert.equal(task.end,oldEnd);assert.ok(task.acknowledgedAt);
  task=await api('member',`/api/v1/resource-tasks/${task.id}/propose`,{rowVersion:task.rowVersion,plan:{...base.plan,start:'2026-09-14',workDays:3,manDays:2,note:'TEST ONLY revised'}});
  task=await api('manager',`/api/v1/resource-tasks/${task.id}/approve`,{rowVersion:task.rowVersion,note:'TEST ONLY revised plan approved'});assert.equal(task.end,'2026-09-16');assert.equal(task.acknowledgedAt,null);
  task=await api('member',`/api/v1/resource-tasks/${task.id}/acknowledge`,{rowVersion:task.rowVersion});
  task=await api('member',`/api/v1/resource-tasks/${task.id}/progress`,{rowVersion:task.rowVersion,scheduleVersion:task.scheduleVersion,percentComplete:100,status:'Done',actualStart:'2026-09-14',actualFinish:'2026-09-16',note:'TEST ONLY fixed'});
  task=await api('manager',`/api/v1/resource-tasks/${task.id}/close`,{rowVersion:task.rowVersion,note:'TEST ONLY customer verified'});assert.equal(task.state,'Closed');
  assert.equal(Number((await database.query<{n:number}>(`SELECT COUNT(*) n FROM dbo.schedule_tasks WHERE name=N'TEST ONLY customer issue'`)).recordset[0]!.n),1);
  let iq=await api('member','/api/v1/resource-tasks',{...base,sourceKind:'Inquiry',sourceId:inquiry,isIssue:false,title:'TEST ONLY inquiry task',plan:{...base.plan,manDays:1}},201);
  iq=await api('manager',`/api/v1/resource-tasks/${iq.id}/approve`,{rowVersion:iq.rowVersion,note:'TEST ONLY switch to tasks'});assert.equal(iq.scheduleTaskId,null);
  const commitments=await api('member','/api/v1/resource-tasks/commitments');assert.ok(commitments.taskInquiryIds.includes(inquiry));assert.equal(commitments.items.length,1);
  const mine=await api('member','/api/v1/resource-tasks?mine=true&filter=Acknowledgment');assert.ok(mine.items.some((t:{id:number})=>t.id===iq.id));
  const stale=iq.rowVersion;iq=await api('member',`/api/v1/resource-tasks/${iq.id}/acknowledge`,{rowVersion:iq.rowVersion});await api('member',`/api/v1/resource-tasks/${iq.id}/acknowledge`,{rowVersion:stale},409);
  iq=await api('member',`/api/v1/resource-tasks/${iq.id}/progress`,{rowVersion:iq.rowVersion,percentComplete:10,status:'In Progress',actualStart:'2026-09-07',actualFinish:null});
  reloaded=(await api('member','/api/v1/resource-tasks?mine=true')).items.find((t:{id:number})=>t.id===iq.id);assert.equal(reloaded.actualStart,'2026-09-07');
  const unchanged=await api('member','/api/v1/resource-tasks/preview',{sourceKind:'Inquiry',sourceId:inquiry,taskId:iq.id,plan:{...base.plan,manDays:1}});assert.equal(unchanged.weeks[0].before,unchanged.weeks[0].after);
  iq=await api('member',`/api/v1/resource-tasks/${iq.id}/propose`,{rowVersion:iq.rowVersion,plan:{...base.plan,start:'2026-09-21',manDays:1,note:'TEST ONLY pending when work completes'}});
  iq=await api('member',`/api/v1/resource-tasks/${iq.id}/progress`,{rowVersion:iq.rowVersion,percentComplete:100,status:'Done',actualStart:'2026-09-07',actualFinish:'2026-09-11'});
  await api('manager',`/api/v1/resource-tasks/${iq.id}/approve`,{rowVersion:iq.rowVersion,note:'cannot replan completed task'},409);
  let reassigned=await api('manager','/api/v1/resource-tasks',{...base,title:'TEST ONLY reassign',plan:{...base.plan,start:'2026-09-21',manDays:1}},201);
  const competing=await Promise.all([1,2].map(()=>app.inject({method:'POST',url:`/api/v1/resource-tasks/${reassigned.id}/approve`,headers:{'x-dev-user-id':'drawing-manager'},payload:{rowVersion:reassigned.rowVersion,note:'TEST ONLY parallel approval'}})));
  assert.deepEqual(competing.map(r=>r.statusCode).sort(),[200,409]);checks+=2;reassigned=competing.find(r=>r.statusCode===200)!.json();
  reassigned=await api('member',`/api/v1/resource-tasks/${reassigned.id}/acknowledge`,{rowVersion:reassigned.rowVersion});
  reassigned=await api('manager',`/api/v1/resource-tasks/${reassigned.id}/propose`,{rowVersion:reassigned.rowVersion,plan:{...base.plan,start:'2026-09-21',manDays:1,assigneeId:actors['drawing-other'],note:'TEST ONLY reassign'}});
  reassigned=await api('manager',`/api/v1/resource-tasks/${reassigned.id}/approve`,{rowVersion:reassigned.rowVersion,note:'TEST ONLY approved reassign'});assert.equal(reassigned.acknowledgedAt,null);
  await api('member',`/api/v1/resource-tasks/${reassigned.id}/acknowledge`,{rowVersion:reassigned.rowVersion},403);
  const pics=(await database.query<{user_id:number}>(`SELECT user_id FROM dbo.schedule_task_pics WHERE task_id=${reassigned.scheduleTaskId}`)).recordset;assert.deepEqual(pics.map(p=>Number(p.user_id)),[actors['drawing-other']]);
  run(`DELETE dbo.project_members WHERE project_id=${project} AND user_id=${actors['drawing-member']};`);
  await api('member','/api/v1/resource-tasks/preview',base,403);
  assert.ok((await database.query<{n:number}>(`SELECT COUNT(*) n FROM dbo.audit_log WHERE entity_type=N'Resource Task'`)).recordset[0]!.n>0);
  console.log(`Resource task SQL integration passed: ${checks} API checks; isolated database and restricted app role.`);
} finally {
  if(application){await application.app.close();await application.database.close();}
  execFileSync('sqlcmd',[...args,'-d','master','-Q',`IF DB_ID(N'${name}') IS NOT NULL BEGIN ALTER DATABASE [${name}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [${name}]; END;`],{stdio:'pipe'});
}
