import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
import { buildApp } from '../src/app.js';
import type { AppConfig } from '../src/config.js';
const repo=process.cwd(),name=`IoTTeamCenter_ReportCI_${randomUUID().replaceAll('-','')}`;
assert.match(name,/^IoTTeamCenter_ReportCI_[a-f0-9]{32}$/);
const args=['-S','localhost','-E','-C','-I','-b'];
const run=(statement:string)=>execFileSync('sqlcmd',[...args,'-d',name,'-Q',statement],{cwd:repo,stdio:'pipe'});
function imageMultipart(image:Buffer) {
 const boundary=`----report-evidence-${randomUUID()}`,head=Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="test-evidence.png"\r\nContent-Type: image/png\r\n\r\n`),tail=Buffer.from(`\r\n--${boundary}--\r\n`);
 return {payload:Buffer.concat([head,image,tail]),contentType:`multipart/form-data; boundary=${boundary}`};
}
let application:Awaited<ReturnType<typeof buildApp>>|undefined,checks=0;
try {
 execFileSync('sqlcmd',[...args,'-i','database/scripts/020_deploy_fresh_database.sql','-v',`DatabaseName=${name}`],{cwd:repo,stdio:'pipe',encoding:'utf8'});
 execFileSync('sqlcmd',[...args,'-d',name,'-i','tests/integration/drawing-fixture.sql'],{cwd:repo,stdio:'pipe'});
 run(`UPDATE dbo.inquiries SET status=N'New';INSERT dbo.signature_specimens(user_id,version,source,image_key) SELECT id,1,N'TYPED',N'TEST-ONLY-no-real-specimen.png' FROM dbo.users WHERE entra_object_id IN(N'drawing-member',N'drawing-leader',N'drawing-manager');`);
 const password=randomUUID().replaceAll('-','');run(`CREATE APPLICATION ROLE report_ci_role WITH PASSWORD='${password}';`);
 execFileSync('sqlcmd',[...args,'-d',name,'-i','database/scripts/010_application_login.sql','-v',`DatabaseName=${name}`,'AppLogin=report_ci_role'],{cwd:repo,stdio:'pipe'});
 const config:AppConfig={environment:'development',host:'127.0.0.1',port:0,allowedHosts:['localhost'],corsOrigins:['http://localhost:3000'],businessTimeZone:'Asia/Bangkok',auth:{mode:'Development'},database:{connectionString:`Server=localhost;Database=${name};Integrated Security=true;TrustServerCertificate=true`,trustServerCertificate:true,applicationRoleName:'report_ci_role',applicationRolePassword:password},documentStorage:{mode:'Local',rootPath:resolve(repo,'tmp',name),maxFileSizeBytes:10000000},email:{mode:'Disabled'},pdfParserUrl:'http://pdf-parser:8000'};
 mkdirSync(config.documentStorage.rootPath,{recursive:true});
 application=await buildApp(config);const {app,database}=application;
 const actors=Object.fromEntries((await database.query<{id:number;entra_object_id:string}>('SELECT id,entra_object_id FROM dbo.users')).recordset.map(u=>[u.entra_object_id,Number(u.id)]));
 const project=Number((await database.query<{id:number}>('SELECT id FROM dbo.projects')).recordset[0]!.id),inquiry=Number((await database.query<{id:number}>('SELECT id FROM dbo.inquiries')).recordset[0]!.id);
 async function api(actor:string|null,url:string,body?:object,expected=200,method:'GET'|'POST'|'PUT'=body?'POST':'GET') {
  const response=await app.inject({method,url,headers:actor?{'x-dev-user-id':`drawing-${actor}`}:{},...(body?{payload:body}:{})});assert.equal(response.statusCode,expected,`Report integration request ${checks+1}: ${response.body}`);checks++;return response.json();
 }
 const commonBody={overview:{objective:'TEST ONLY verify installation',summary:'TEST ONLY synthetic report'},context:{start:'2026-09-06T09:00',end:'2026-09-06T10:00'}};
 const base={reportType:'INSTALLATION',sourceKind:'PROJECT',sourceId:project,title:'TEST ONLY Installation',reportDate:'2026-09-06',locale:'en',body:{...commonBody,hardware:[{item:'TEST ONLY controller',action:'TEST ONLY installed'}],software:[],commissioning:[]},reviewerId:actors['drawing-leader'],approverId:actors['drawing-manager']};
 await api('member','/api/v1/reports/workspace',{...base,reportType:'POC'},400);
 await api('member','/api/v1/reports/workspace',{...base,approverId:actors['drawing-member']},400);
 const people=await api('member',`/api/v1/reports/workspace/people?sourceKind=PROJECT&sourceId=${project}`);assert.ok(people.items.some((p:{id:number;canApprove:boolean})=>p.id===actors['drawing-manager']&&p.canApprove));
 // Test a real active approver whose signing authority is temporarily removed in this isolated fixture.
 const signingPermission=Number((await database.query<{id:number}>("SELECT id FROM dbo.permissions WHERE code=N'signing.sign'")).recordset[0]!.id);
 const signingRoles=(await database.query<{role_id:number}>(`SELECT rp.role_id FROM dbo.role_permissions rp WHERE rp.permission_id=${signingPermission} AND (rp.role_id=(SELECT role_id FROM dbo.users WHERE id=${actors['drawing-manager']}) OR rp.role_id IN(SELECT role_id FROM dbo.user_business_roles WHERE user_id=${actors['drawing-manager']} AND revoked_at IS NULL))`)).recordset.map(row=>Number(row.role_id));
 assert.ok(signingRoles.length>0);
 run(`DELETE dbo.role_permissions WHERE permission_id=${signingPermission} AND role_id IN(${signingRoles.join(',')});`);
 const unavailable=await api('member',`/api/v1/reports/workspace/people?sourceKind=PROJECT&sourceId=${project}`);
 assert.ok(!unavailable.items.some((p:{id:number;canApprove:boolean})=>p.id===actors['drawing-manager']&&p.canApprove));
 const ineligible=await api('member','/api/v1/reports/workspace',{...base,body:{}},422);assert.equal(ineligible.code,'report_signer_ineligible');
 for(const roleId of signingRoles)run(`INSERT dbo.role_permissions(role_id,permission_id) VALUES(${roleId},${signingPermission})`);
 let r=await api('member','/api/v1/reports/workspace',{...base,body:{}},201);assert.deepEqual(r.allowedActions,['edit','submit']);
 r=await api('member',`/api/v1/reports/workspace/${r.id}`,{...base,body:{},rowVersion:r.rowVersion},200,'PUT');assert.deepEqual(r.body,{});
 const incomplete=await api('member',`/api/v1/reports/workspace/${r.id}/submit`,{rowVersion:r.rowVersion,consent:true},422);assert.equal(incomplete.code,'report_incomplete');assert.ok(incomplete.details.issues.some((issue:{path:string})=>issue.path==='overview.objective'));
 const unchanged=await api('member',`/api/v1/reports/workspace/${r.id}`);assert.equal(unchanged.rowVersion,r.rowVersion);assert.equal(unchanged.signatures.length,0);assert.equal(unchanged.status,'DRAFT');
 const reportImage=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'),multipart=imageMultipart(reportImage);
 const uploadedResponse=await app.inject({method:'POST',url:`/api/v1/reports/workspace/${r.id}/evidence`,headers:{'x-dev-user-id':'drawing-member','content-type':multipart.contentType},payload:multipart.payload});assert.equal(uploadedResponse.statusCode,201,uploadedResponse.body);checks++;
 const attachment=uploadedResponse.json();
 const reportBody={...base.body,evidence:[{topic:'Commissioning',description:'TEST ONLY status lamp',purpose:'TEST ONLY prove successful startup',...attachment}]};
 r=await api('member',`/api/v1/reports/workspace/${r.id}`,{...base,body:reportBody,rowVersion:r.rowVersion},200,'PUT');
 const internalImage=await app.inject({method:'GET',url:`/api/v1/reports/workspace/${r.id}/evidence/${attachment.attachmentId}/content`,headers:{'x-dev-user-id':'drawing-member'}});assert.equal(internalImage.statusCode,200);assert.deepEqual(internalImage.rawPayload,reportImage);checks++;
 await api('other',`/api/v1/reports/workspace/${r.id}/submit`,{rowVersion:r.rowVersion,consent:true},409);
 await api('member',`/api/v1/reports/workspace/${r.id}/submit`,{rowVersion:r.rowVersion,consent:false},400);
 const draftVersion=r.rowVersion;r=await api('member',`/api/v1/reports/workspace/${r.id}/submit`,{rowVersion:r.rowVersion,consent:true});assert.equal(r.signatures.length,1);
 await api('member',`/api/v1/reports/workspace/${r.id}`,{...base,rowVersion:draftVersion},409,'PUT');
 await api('manager',`/api/v1/reports/workspace/${r.id}/approve`,{rowVersion:r.rowVersion,consent:true},409);
 r=await api('leader',`/api/v1/reports/workspace/${r.id}/review`,{rowVersion:r.rowVersion,consent:true});
 r=await api('manager',`/api/v1/reports/workspace/${r.id}/approve`,{rowVersion:r.rowVersion,consent:true});assert.equal(r.signatures.length,3);assert.equal(new Set(r.signatures.map((s:{snapshotSha256:string})=>s.snapshotSha256)).size,1);
 let link=await api('member',`/api/v1/reports/workspace/${r.id}/customer-link`,{rowVersion:r.rowVersion,expiresInHours:1});r=link.report;assert.equal(r.status,'AWAITING_CUSTOMER');assert.ok(r.customerLink.expiresAt);
 run(`UPDATE dbo.projects SET end_user_customer_id=customer_id WHERE id=${project}`);
 const frozenEndUser=await api('member',`/api/v1/reports/workspace/${r.id}`);assert.equal(frozenEndUser.endUserName,null);
 let publicReport=await api(null,link.acknowledgmentPath);assert.equal(publicReport.endUserName,null);assert.equal(publicReport.snapshotSha256,r.snapshotSha256);assert.equal(publicReport.preparedById,undefined);
 const publicImagePath=`${link.acknowledgmentPath}/evidence/${attachment.attachmentId}`,publicImage=await app.inject({method:'GET',url:publicImagePath});assert.equal(publicImage.statusCode,200);assert.deepEqual(publicImage.rawPayload,reportImage);checks++;
 r=await api('member',`/api/v1/reports/workspace/${r.id}/revoke-customer-link`,{rowVersion:r.rowVersion});await api(null,link.acknowledgmentPath,undefined,404);await api(null,publicImagePath,undefined,404);
 link=await api('member',`/api/v1/reports/workspace/${r.id}/customer-link`,{rowVersion:r.rowVersion});r=link.report;publicReport=await api(null,link.acknowledgmentPath);
 const evidence={name:'TEST ONLY Customer',title:'TEST QA',company:'TEST ONLY COMPANY',date:'2026-09-06',mode:'ACKNOWLEDGMENT',consent:true,snapshotSha256:publicReport.snapshotSha256};
 await api(null,link.acknowledgmentPath,{...evidence,snapshotSha256:'bad'},409);
 const outcomes=await Promise.all([1,2].map(()=>app.inject({method:'POST',url:link.acknowledgmentPath,payload:evidence})));assert.deepEqual(outcomes.map(o=>o.statusCode).sort(),[200,404]);checks+=2;
 await api(null,link.acknowledgmentPath,undefined,404);
 r=await api('member',`/api/v1/reports/workspace/${r.id}`);assert.equal(r.status,'COMPLETED');assert.equal(r.customerAcknowledgment.name,evidence.name);assert.equal(r.customerAcknowledgment.signatureDataUrl,null);
 await assert.rejects(()=>database.query(`UPDATE dbo.unified_report_revisions SET title=N'tampered' WHERE report_id=${r.id}`));checks++;
 await assert.rejects(()=>database.query(`UPDATE dbo.unified_report_acknowledgments SET signer_name=N'tampered'`));checks++;
 run(`UPDATE dbo.users SET is_active=0 WHERE id IN(${actors['drawing-manager']},${actors['drawing-leader']})`);
 const oldHash=r.snapshotSha256;r=await api('member',`/api/v1/reports/workspace/${r.id}/revise`,{rowVersion:r.rowVersion,note:'TEST ONLY next revision'});assert.equal(r.revision,1);assert.equal(r.status,'DRAFT');assert.equal(r.signatures.length,0);assert.equal(r.endUserName,r.customer);
 const unavailableSigner=await api('member',`/api/v1/reports/workspace/${r.id}/submit`,{rowVersion:r.rowVersion,consent:true},422);assert.equal(unavailableSigner.code,'report_signer_ineligible');
 run(`INSERT dbo.users(entra_object_id,email,name,role_id) SELECT N'drawing-replacement',N'replacement@test.invalid',N'TEST ONLY replacement approver',role_id FROM dbo.users WHERE id=${actors['drawing-manager']}`);
 const replacement=Number((await database.query<{id:number}>("SELECT id FROM dbo.users WHERE entra_object_id=N'drawing-replacement'")).recordset[0]!.id);
 r=await api('member',`/api/v1/reports/workspace/${r.id}`,{...base,reviewerId:null,approverId:replacement,rowVersion:r.rowVersion},200,'PUT');assert.equal(r.approverId,replacement);assert.equal(r.status,'DRAFT');assert.equal(r.signatures.length,0);
 run(`UPDATE dbo.users SET is_active=1 WHERE id IN(${actors['drawing-manager']},${actors['drawing-leader']})`);
 const previous=await api('member',`/api/v1/reports/workspace/${r.id}?revision=0`);assert.equal(previous.snapshotSha256,oldHash);assert.equal(previous.status,'COMPLETED');assert.deepEqual(previous.allowedActions,[]);
 run(`UPDATE dbo.inquiries SET end_user_customer_id=customer_id WHERE id=${inquiry}`);
 let poc=await api('member','/api/v1/reports/workspace',{...base,reportType:'POC',sourceKind:'INQUIRY',sourceId:inquiry,reviewerId:null,body:{...commonBody,trials:[{hypothesis:'TEST ONLY improvement',successCriteria:'TEST ONLY threshold',trial:'TEST ONLY measure',result:'TEST ONLY measured'}]}},201);
 poc=await api('member',`/api/v1/reports/workspace/${poc.id}/submit`,{rowVersion:poc.rowVersion,consent:true});poc=await api('manager',`/api/v1/reports/workspace/${poc.id}/approve`,{rowVersion:poc.rowVersion,consent:true});assert.equal(poc.status,'APPROVED');
 assert.equal(poc.endUserName,poc.customer);run(`UPDATE dbo.inquiries SET end_user_customer_id=NULL WHERE id=${inquiry}`);
 let pocLink=await api('member',`/api/v1/reports/workspace/${poc.id}/customer-link`,{rowVersion:poc.rowVersion});poc=pocLink.report;assert.equal(poc.endUserName,poc.customer);const frozenPublic=await api(null,pocLink.acknowledgmentPath);assert.equal(frozenPublic.endUserName,poc.customer);
 run(`UPDATE dbo.unified_report_customer_links SET expires_at=DATEADD(hour,-1,SYSUTCDATETIME()) WHERE revision_id=(SELECT id FROM dbo.unified_report_revisions WHERE report_id=${poc.id} AND revision=0)`);
 await api(null,pocLink.acknowledgmentPath,undefined,404);
 poc=await api('member',`/api/v1/reports/workspace/${poc.id}/revoke-customer-link`,{rowVersion:poc.rowVersion});
 pocLink=await api('member',`/api/v1/reports/workspace/${poc.id}/customer-link`,{rowVersion:poc.rowVersion});
 const signatureDataUrl='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
 await api(null,pocLink.acknowledgmentPath,{...evidence,mode:'DRAWN_SIGNATURE',signatureDataUrl,snapshotSha256:pocLink.report.snapshotSha256});
 poc=await api('member',`/api/v1/reports/workspace/${poc.id}`);assert.equal(poc.customerAcknowledgment.signatureDataUrl,signatureDataUrl);assert.equal(poc.status,'COMPLETED');
 run(`DELETE dbo.project_members WHERE project_id=${project} AND user_id=${actors['drawing-other']};`);
 await api('other',`/api/v1/reports/workspace/${r.id}`,undefined,403);
 const list=await api('member','/api/v1/reports/workspace?pageSize=1');assert.equal(list.items.length,1);assert.ok(list.total>=2);
 const templates=await api('member','/api/v1/reports/workspace/templates');assert.equal(templates.templates.length,5);assert.ok(templates.templates.every((t:{body:object})=>JSON.stringify(t.body)==='{}'));
 const scenario={scenario:'TEST ONLY startup',step:'TEST ONLY enable',expected:'TEST ONLY ready',actual:'TEST ONLY ready',result:'PASS'};
 let uat=await api('member','/api/v1/reports/workspace',{...base,reportType:'UAT',body:{...commonBody,scenarios:[scenario,{scenario:'TEST ONLY incomplete next row'}]}},201);
 const uatBlocked=await api('member',`/api/v1/reports/workspace/${uat.id}/submit`,{rowVersion:uat.rowVersion,consent:true},422);assert.equal(uatBlocked.code,'report_incomplete');assert.ok(uatBlocked.details.issues.some((issue:{path:string})=>issue.path==='scenarios[1].step'));
 uat=await api('member',`/api/v1/reports/workspace/${uat.id}`,{...base,body:{...commonBody,scenarios:[scenario,{}]},rowVersion:uat.rowVersion},200,'PUT');
 uat=await api('member',`/api/v1/reports/workspace/${uat.id}/submit`,{rowVersion:uat.rowVersion,consent:true});assert.equal(uat.status,'SUBMITTED');
 run(`INSERT dbo.signature_specimens(user_id,version,source,image_key) VALUES(${actors['drawing-admin']},1,N'TYPED',N'TEST-ONLY-admin.png')`);
 run(`INSERT dbo.user_business_roles(user_id,role_id,granted_by,reason) SELECT ${actors['drawing-admin']},id,${actors['drawing-manager']},N'TEST ONLY additional signing role' FROM dbo.roles WHERE code=N'Management'`);
 let adminReport=await api('member','/api/v1/reports/workspace',{...base,reportType:'SERVICE',reviewerId:null,approverId:actors['drawing-admin'],body:{...commonBody,service:{symptom:'TEST ONLY fault',action:'TEST ONLY fix',verification:'TEST ONLY retest',testResult:'TEST ONLY result'}}},201);
 adminReport=await api('member',`/api/v1/reports/workspace/${adminReport.id}/submit`,{rowVersion:adminReport.rowVersion,consent:true});
 run(`UPDATE dbo.user_business_roles SET revoked_at=SYSUTCDATETIME() WHERE user_id=${actors['drawing-admin']}`);
 await api('admin',`/api/v1/reports/workspace/${adminReport.id}/approve`,{rowVersion:adminReport.rowVersion,consent:true},403);
 run(`UPDATE dbo.user_business_roles SET revoked_at=NULL WHERE user_id=${actors['drawing-admin']}`);
 adminReport=await api('admin',`/api/v1/reports/workspace/${adminReport.id}/approve`,{rowVersion:adminReport.rowVersion,consent:true});assert.equal(adminReport.status,'APPROVED');
 // Reusable library: no source identity/result data can cross into new drafts.
 const library='/api/v1/reports/workspace/library';
 // Development auth supplies an unregistered fallback identity; production
 // TeamTest/Entra reject unauthenticated requests as 401 before this handler.
 await api(null,library,undefined,403);await api(null,`${library}/1`,undefined,403);
 const sourcePreview=await api('member',`${library}/preview`,{sourceReportId:r.id,sourceRevision:0});assert.equal(sourcePreview.body.overview.summary,undefined);assert.equal(sourcePreview.body.context,undefined);
 await api('other',`${library}/preview`,{sourceReportId:r.id},403);
 await api('other',library,{name:'TEST ONLY unauthorized copy',sourceReportId:r.id},403);
 const explicitPreview=await api('member',`${library}/preview`,{reportType:'UAT',body:{context:{contact:'PRIVATE'},scenarios:[{scenario:'Reuse',step:'Enable',expected:'Ready',actual:'SECRET',result:'PASS',evidence:'https://private'}],signatures:[{signer:'PRIVATE'}]}});
 assert.deepEqual(explicitPreview.body,{scenarios:[{scenario:'Reuse',step:'Enable',expected:'Ready'}]});
 const templateName='T'.repeat(200);
 let template=await api('member',library,{name:templateName,description:'',sourceReportId:r.id,sourceRevision:0},201);assert.equal(template.version,1);assert.equal(template.description,'');assert.equal(template.canEdit,true);
 const managerView=await api('manager',`${library}/${template.id}`);assert.equal(managerView.canEdit,true);
 const otherView=await api('other',`${library}/${template.id}`);assert.equal(otherView.canEdit,false);
 await api('other',`${library}/${template.id}`,{name:'bad',body:{},rowVersion:template.rowVersion},403,'PUT');await api('other',`${library}/${template.id}/archive`,{rowVersion:template.rowVersion},403);
 run(`INSERT dbo.roles(code,name) VALUES(N'TemplateMasterOnly',N'TEST ONLY role');INSERT dbo.role_permissions(role_id,permission_id) SELECT r.id,p.id FROM dbo.roles r CROSS JOIN dbo.permissions p WHERE r.code=N'TemplateMasterOnly' AND p.code IN(N'master.write',N'report.read');INSERT dbo.users(entra_object_id,email,name,role_id) SELECT N'drawing-master-only',N'master-only@test.invalid',N'TEST ONLY master',id FROM dbo.roles WHERE code=N'TemplateMasterOnly'`);
 await api('master-only',`${library}/${template.id}`,{name:'bad',body:{},rowVersion:template.rowVersion},403,'PUT');
 const selected={...base,templateId:template.id,templateVersion:template.version,body:{context:{contact:'MALICIOUS'},overview:{summary:'DO NOT INHERIT'},hardware:[{serial:'SECRET',result:'PASS'}]}};
 const reportCount=Number((await database.query<{n:number}>('SELECT COUNT(*) n FROM dbo.unified_reports')).recordset[0]!.n);
 await api('member','/api/v1/reports/workspace',{...selected,reportType:'UAT'},400);
 await api('member','/api/v1/reports/workspace',{...selected,templateVersion:999},409);
 assert.equal(Number((await database.query<{n:number}>('SELECT COUNT(*) n FROM dbo.unified_reports')).recordset[0]!.n),reportCount);
 let derived=await api('member','/api/v1/reports/workspace',selected,201);assert.deepEqual(derived.body,template.body);assert.deepEqual(derived.template,{id:template.id,name:templateName,version:1});assert.equal(derived.customerAcknowledgment,null);assert.deepEqual(derived.signatures,[]);
 const initialBody=JSON.stringify(derived.body),version1=template.rowVersion;
 const edits=await Promise.all([1,2].map(()=>app.inject({method:'PUT',url:`${library}/${template.id}`,headers:{'x-dev-user-id':'drawing-member'},payload:{rowVersion:version1,name:'TEST ONLY revised template',description:'',locale:'en',body:{overview:{objective:'New reusable requirement',summary:'STRIP'},hardware:[{item:'New item',action:'Install',serial:'STRIP'}]}}})));
 assert.deepEqual(edits.map(x=>x.statusCode).sort(),[200,409]);checks+=2;template=edits.find(x=>x.statusCode===200)!.json();assert.equal(template.version,2);
 await api('member','/api/v1/reports/workspace',selected,409);
 derived=await api('member',`/api/v1/reports/workspace/${derived.id}`);assert.equal(JSON.stringify(derived.body),initialBody);assert.equal(derived.template.name,templateName);assert.equal(derived.template.version,1);
 derived=await api('member',`/api/v1/reports/workspace/${derived.id}`,{...base,body:{...base.body,overview:{objective:'Reusable objective',summary:'TEST ONLY fresh facts'}},rowVersion:derived.rowVersion},200,'PUT');
 derived=await api('member',`/api/v1/reports/workspace/${derived.id}/submit`,{rowVersion:derived.rowVersion,consent:true});
 const signedSnapshot=(await database.query<{snapshot_json:string}>(`SELECT snapshot_json FROM dbo.unified_report_revisions WHERE report_id=${derived.id} AND revision=0`)).recordset[0]!;assert.deepEqual(JSON.parse(signedSnapshot.snapshot_json).template,{id:template.id,name:templateName,version:1});
 await assert.rejects(()=>database.query(`UPDATE dbo.unified_reports SET template_version=999 WHERE id=${derived.id}`));checks++;
 const filtered=await api('member',`${library}?search=revised&reportType=INSTALLATION&pageSize=1`);assert.equal(filtered.total,1);assert.equal(filtered.items.length,1);
 template=await api('manager',`${library}/${template.id}/archive`,{rowVersion:template.rowVersion});assert.equal(template.isActive,false);assert.equal(template.version,3);
 await api('member','/api/v1/reports/workspace',{...selected,templateVersion:3},409);
 assert.equal((await api('member',library)).total,0);assert.equal((await api('member',`${library}?includeArchived=true`)).total,1);assert.equal((await api('other',`${library}?includeArchived=true`)).total,0);
 await api('other',`${library}/${template.id}`,undefined,404);
 await api('member',`${library}/${template.id}`,{name:'cannot unarchive via edit',body:{},rowVersion:template.rowVersion},409,'PUT');
 const oldReport=await api('member',`/api/v1/reports/workspace/${r.id}`);assert.equal(oldReport.template,null);
 const ready=await api(null,'/health/ready');assert.equal(ready.status,'ready');assert.equal(ready.schemaVersion,Number((await database.query<{v:number}>('SELECT MAX(version) v FROM dbo.schema_versions')).recordset[0]!.v));
 run(`DELETE dbo.schema_versions WHERE version=27`);
 const missingTemplateSchema=await api(null,'/health/ready',undefined,503);assert.ok(missingTemplateSchema.requiredSchemaVersions.includes(27));
 run(`INSERT dbo.schema_versions(version,name) VALUES(27,N'Reusable sanitized report templates and frozen provenance')`);
 console.log(`Unified Reports SQL integration passed: ${checks} checks; synthetic identities, isolated database, restricted application role.`);
} finally {
 if(application){await application.app.close();await application.database.close();}
 execFileSync('sqlcmd',[...args,'-d','master','-Q',`IF DB_ID(N'${name}') IS NOT NULL BEGIN ALTER DATABASE [${name}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [${name}]; END;`],{stdio:'pipe'});
}
