import sql from "mssql/msnodesqlv8.js";
import type { Transaction as TransactionType } from "mssql";
import type { Database } from "./db.js";
import { ApiError } from "./errors.js";
import { parseRowVersion } from "./http.js";
import { permissionFor } from "./schedule-service.js";
import type { CurrentUser } from "./types.js";

export const SITE_VISIT_PERMISSIONS = { intakeRead: "intake.read", intakeWrite: "intake.write", intakeReview: "intake.review", visitRead: "visit.read", visitSchedule: "visit.schedule", visitOverride: "visit.override", visitExecute: "visit.execute", visitReport: "visit.report", visitReportApprove: "visit.report_approve", visitLink: "visit.link", visitAdmin: "visit.admin" } as const;
export const INTAKE_TRANSITIONS: Record<string, Array<[string, string, boolean]>> = { Draft: [["Pending Technical Review", "intake.write", false], ["Cancelled", "intake.write", true]], "Pending Technical Review": [["More Information Required", "intake.review", true], ["Ready to Schedule", "intake.review", false], ["On Hold", "intake.review", true], ["Cancelled", "intake.review", true]], "More Information Required": [["Pending Technical Review", "intake.write", false], ["Cancelled", "intake.write", true]], "Ready to Schedule": [["Scheduled", "visit.schedule", false], ["More Information Required", "intake.review", true], ["On Hold", "intake.review", true], ["Cancelled", "intake.review", true]], Scheduled: [["Completed", "visit.schedule", false], ["Ready to Schedule", "visit.schedule", true], ["On Hold", "intake.review", true], ["Cancelled", "intake.review", true]], Completed: [["Closed", "intake.review", false]], "On Hold": [["Pending Technical Review", "intake.review", true], ["Ready to Schedule", "intake.review", true], ["Cancelled", "intake.review", true]], Cancelled: [], Closed: [] };
export const VISIT_TRANSITIONS: Record<string, Array<[string, string, boolean]>> = { Tentative: [["Pending Engineer Confirmation", "visit.schedule", false], ["Reschedule Requested", "visit.schedule", true], ["Cancelled", "visit.schedule", true], ["On Hold", "visit.schedule", true]], "Pending Engineer Confirmation": [["Pending Customer Confirmation", "visit.schedule", false], ["Tentative", "visit.schedule", true], ["Reschedule Requested", "visit.schedule", true], ["Cancelled", "visit.schedule", true], ["On Hold", "visit.schedule", true]], "Pending Customer Confirmation": [["Confirmed", "visit.schedule", false], ["Reschedule Requested", "visit.schedule", true], ["Cancelled", "visit.schedule", true], ["On Hold", "visit.schedule", true]], Confirmed: [["In Progress", "visit.execute", false], ["Reschedule Requested", "visit.schedule", true], ["Customer No-show", "visit.execute", true], ["Cancelled", "visit.schedule", true]], "In Progress": [["Report Pending", "visit.execute", false], ["Customer No-show", "visit.execute", true]], "Report Pending": [["Report Under Review", "visit.report", false]], "Report Under Review": [["Completed", "visit.report_approve", false], ["Report Pending", "visit.report_approve", true]], Completed: [["Closed", "visit.schedule", false]], "Reschedule Requested": [["Tentative", "visit.schedule", false], ["Cancelled", "visit.schedule", true]], "On Hold": [["Tentative", "visit.schedule", true], ["Cancelled", "visit.schedule", true]], "Customer No-show": [["Reschedule Requested", "visit.schedule", true], ["Closed", "visit.schedule", true]], Cancelled: [], Closed: [] };

export async function rolePermissions(database: Database, role: string): Promise<Set<string>> { const result = await database.query<{ code: string }>(`SELECT p.code FROM dbo.role_permissions rp INNER JOIN dbo.permissions p ON p.id=rp.permission_id INNER JOIN dbo.roles r ON r.id=rp.role_id WHERE r.code=@role;`, (bind) => bind.input("role", sql.NVarChar(50), role)); return new Set(result.recordset.map((row) => row.code)); }
export async function hasRolePermission(database: Database, actor: CurrentUser, permission: string): Promise<boolean> { return permissionFor(database, actor.role, permission); }
export function requireTransition(map: Record<string, Array<[string, string, boolean]>>, from: string, to: string, permissions: ReadonlySet<string>, reason?: string | null): void { const edge = map[from]?.find(([target]) => target === to); if (!edge) throw new ApiError(409, "transition_not_allowed", `'${from}' cannot move directly to '${to}'.`); if (!permissions.has(edge[1])) throw new ApiError(403, "permission_denied", `Permission '${edge[1]}' is required.`); if (edge[2] && !reason?.trim()) throw new ApiError(400, "reason_required", "A reason is required for this status change."); }
export function allowedTransitions(map: Record<string, Array<[string, string, boolean]>>, from: string, permissions: ReadonlySet<string>): string[] { return (map[from] ?? []).filter((edge) => permissions.has(edge[1])).map((edge) => edge[0]); }
export function requireRowVersion(value: unknown, actual: Buffer): void { const expected = parseRowVersion(value); if (!expected.equals(actual)) throw new ApiError(409, "concurrency_conflict", "This record changed while you were editing it. Reload and apply your change again."); }
export function rowVersion(value: unknown): string { return Buffer.isBuffer(value) ? value.toString("base64") : ""; }
export async function siteVisitAudit(transaction: TransactionType, actorId: number, entityType: string, entityId: number, entityNumber: string, action: string, before?: unknown, after?: unknown, reason?: string | null): Promise<void> { const request = new sql.Request(transaction); request.input("actor", sql.BigInt, actorId); request.input("type", sql.NVarChar(50), entityType); request.input("id", sql.BigInt, entityId); request.input("number", sql.NVarChar(50), entityNumber.slice(0, 50)); request.input("action", sql.NVarChar(100), action.slice(0, 100)); request.input("before", sql.NVarChar(sql.MAX), before == null ? null : JSON.stringify(before)); request.input("after", sql.NVarChar(sql.MAX), after == null ? null : JSON.stringify(after)); request.input("reason", sql.NVarChar(sql.MAX), reason?.trim() || null); await request.query(`INSERT INTO dbo.audit_log(actor_id,entity_type,entity_id,entity_no,action,before_json,after_json,reason) VALUES(@actor,@type,@id,@number,@action,@before,@after,@reason);`); }
export async function recordSiteVisitStatus(transaction: TransactionType, entityType: string, entityId: number, entityNumber: string, previous: string | null, next: string, reason: string | null, actorId: number): Promise<void> { const request = new sql.Request(transaction); request.input("type", sql.NVarChar(30), entityType); request.input("id", sql.BigInt, entityId); request.input("number", sql.NVarChar(30), entityNumber); request.input("previous", sql.NVarChar(50), previous); request.input("next", sql.NVarChar(50), next); request.input("reason", sql.NVarChar(sql.MAX), reason?.trim() || null); request.input("actor", sql.BigInt, actorId); await request.query(`INSERT INTO dbo.site_visit_status_history(entity_type,entity_id,entity_no,previous_status,new_status,reason,changed_by) VALUES(@type,@id,@number,@previous,@next,@reason,@actor);`); }
export const reportSlaState = (due: Date | string | null, reportStatus: string | null, submitted: Date | string | null, now = new Date(), warningHours = 24): string => { if (!due) return "not_applicable"; const dueDate = new Date(due); if (["Submitted", "Under Review", "Approved", "Acknowledged"].includes(reportStatus ?? "")) return new Date(submitted ?? now) <= dueDate ? "met" : "missed"; if (now > dueDate) return "overdue"; return dueDate.valueOf() - now.valueOf() <= Math.max(1, warningHours) * 3_600_000 ? "due_soon" : "on_track"; };

export type ReadinessInput = {
  customerId: number; siteName: string; siteAddress: string; contactName: string; contactPhone: string;
  contactEmail: string; problemStatement: string; expectedResult: string; purposeCount: number;
  machineName: string; machineModel: string; existingSystem: string; attachmentCount: number;
  windowCount: number; safetyRequirement: string; siteAccessRequirement: string; skillCount: number;
};

const readinessRules: Array<{ key: string; label: string; weight: number; severity: "blocker" | "warning"; hint: string; test: (input: ReadinessInput) => boolean }> = [
  { key: "customer_site", label: "Customer and site are identified", weight: 12, severity: "blocker", hint: "Choose the customer and name the site or factory the engineer must reach.", test: (x) => x.customerId > 0 && x.siteName.trim().length > 0 && x.siteAddress.trim().length >= 5 },
  { key: "contact", label: "Site contact person is reachable", weight: 12, severity: "blocker", hint: "A name plus at least one of phone or email.", test: (x) => x.contactName.trim().length > 0 && (x.contactPhone.trim().length >= 6 || x.contactEmail.trim().length >= 5) },
  { key: "problem", label: "Current problem is described", weight: 14, severity: "blocker", hint: "What is happening today that made the customer call.", test: (x) => x.problemStatement.trim().length >= 20 },
  { key: "expected_result", label: "Expected result is stated", weight: 14, severity: "blocker", hint: "What the customer wants to be true after the work is done.", test: (x) => x.expectedResult.trim().length >= 20 },
  { key: "purpose", label: "Visit purpose is selected", weight: 10, severity: "blocker", hint: "At least one purpose, so the right checklist and skills are chosen.", test: (x) => x.purposeCount > 0 },
  { key: "machine", label: "Machine or system information is sufficient", weight: 10, severity: "warning", hint: "Machine name plus a model, or a description of the existing system.", test: (x) => x.machineName.trim().length > 0 && (x.machineModel.trim().length > 0 || x.existingSystem.trim().length >= 10) },
  { key: "attachment", label: "A photo, drawing or document is attached", weight: 8, severity: "warning", hint: "One picture of the real machine saves an hour of guessing.", test: (x) => x.attachmentCount > 0 },
  { key: "window", label: "Customer availability window is proposed", weight: 8, severity: "warning", hint: "At least one date range the customer said would suit them.", test: (x) => x.windowCount > 0 },
  { key: "safety", label: "Safety and site access are recorded", weight: 6, severity: "warning", hint: "PPE, permits, escorts, photography rules — anything that stops an engineer at the gate.", test: (x) => x.safetyRequirement.trim().length >= 3 || x.siteAccessRequirement.trim().length >= 3 },
  { key: "skill", label: "Expected engineering skills are indicated", weight: 6, severity: "warning", hint: "Sales' best guess is enough; the coordinator can correct it.", test: (x) => x.skillCount > 0 },
];

export function evaluateReadiness(input: ReadinessInput) {
  let earned = 0, total = 0, blockerCount = 0, warningCount = 0;
  const checks = readinessRules.map((rule) => { const passed = rule.test(input); total += rule.weight; if (passed) earned += rule.weight; else if (rule.severity === "blocker") blockerCount++; else warningCount++; return { key: rule.key, label: rule.label, weight: rule.weight, severity: rule.severity, hint: rule.hint, passed }; });
  return { score: total === 0 ? 0 : Math.round(earned * 100 / total), blockerCount, warningCount, canSubmit: blockerCount === 0, checks };
}

export async function notifyUsers(transaction: TransactionType, recipientIds: Iterable<number>, kind: string, title: string, detail: string, entityType: string, entityId: number, dedupeKey: string): Promise<void> {
  for (const userId of new Set([...recipientIds].filter((id) => Number.isSafeInteger(id) && id > 0))) {
    const q = new sql.Request(transaction); q.input("user", sql.BigInt, userId); q.input("kind", sql.NVarChar(100), kind.slice(0, 100)); q.input("title", sql.NVarChar(300), title.slice(0, 300)); q.input("detail", sql.NVarChar(sql.MAX), detail); q.input("type", sql.NVarChar(50), entityType); q.input("entity", sql.BigInt, entityId); q.input("key", sql.NVarChar(200), dedupeKey.toLowerCase().replaceAll(" ", "-").slice(0, 200));
    await q.query(`IF NOT EXISTS(SELECT 1 FROM dbo.notifications WITH(UPDLOCK,HOLDLOCK) WHERE user_id=@user AND dedupe_key=@key) INSERT INTO dbo.notifications(user_id,kind,title,detail,entity_type,entity_id,dedupe_key) VALUES(@user,@kind,@title,@detail,@type,@entity,@key);`);
  }
}

export async function usersWithPermission(transaction: TransactionType, permission: string): Promise<number[]> { const q = new sql.Request(transaction); q.input("permission", sql.NVarChar(100), permission); const result = await q.query<{ id: number | string }>(`SELECT u.id FROM dbo.users u INNER JOIN dbo.roles r ON r.id=u.role_id INNER JOIN dbo.role_permissions rp ON rp.role_id=r.id INNER JOIN dbo.permissions p ON p.id=rp.permission_id WHERE p.code=@permission AND u.is_active=1 AND u.deleted_at IS NULL;`); return result.recordset.map((row) => Number(row.id)); }

export async function loadStatusHistory(database: Database, entityType: string, entityId: number) { const result = await database.query<Record<string, unknown>>(`SELECT TOP(200) h.id,h.entity_type,h.entity_id,h.entity_no,h.previous_status,h.new_status,h.reason,u.name changed_by_name,h.changed_at FROM dbo.site_visit_status_history h INNER JOIN dbo.users u ON u.id=h.changed_by WHERE h.entity_type=@type AND h.entity_id=@id ORDER BY h.changed_at DESC,h.id DESC;`, (q) => { q.input("type", sql.NVarChar(30), entityType); q.input("id", sql.BigInt, entityId); }); return result.recordset.map((r) => ({ id: Number(r.id), entityType: r.entity_type, entityId: Number(r.entity_id), entityNumber: r.entity_no, previousStatus: r.previous_status, newStatus: r.new_status, reason: r.reason, changedByName: r.changed_by_name, changedAt: r.changed_at })); }
export async function loadTraceabilityLinks(database: Database, sourceType: string, sourceId: number) { const result = await database.query<Record<string, unknown>>(`SELECT l.id,l.source_type,l.source_id,l.target_type,l.target_id,l.target_no,l.relation,l.note,u.name created_by_name,l.created_at FROM dbo.site_visit_links l INNER JOIN dbo.users u ON u.id=l.created_by WHERE l.source_type=@type AND l.source_id=@id ORDER BY l.created_at DESC,l.id DESC;`, (q) => { q.input("type", sql.NVarChar(30), sourceType); q.input("id", sql.BigInt, sourceId); }); return result.recordset.map((r) => ({ id: Number(r.id), sourceType: r.source_type, sourceId: Number(r.source_id), targetType: r.target_type, targetId: Number(r.target_id), targetNumber: r.target_no, relation: r.relation, note: r.note, createdByName: r.created_by_name, createdAt: r.created_at })); }
