const REASON_EN: Record<string, string> = {
  owner_required: "Requires edit permission and the document owner, engineering manager or administrator.",
  already_deleted: "This document is already in the trash.", already_archived: "This document is archived.",
  project_linked: "A project references this document. Manage the project separately and retain its references.",
  estimate_linked: "An estimate exists. Use cancellation instead.", work_started: "Related work has started. Use cancellation instead.",
  draft_only: "Only drafts that have never been submitted can be deleted.",
  no_approved_fallback: "There is no approved revision to return to. Use cancellation instead.",
  already_cancelled: "This work is already cancelled.",
  cancel_estimate_first: "Handle the estimate first: withdraw its review or ask an approver to cancel the approved estimate.",
  withdraw_first: "Withdraw the review before cancellation.", approver_required: "Requires an engineering manager or administrator with approval permission.",
  no_active_estimate: "No active estimate to cancel together.", estimate_owner_required: "Requires estimate edit permission and estimate ownership or management role.",
  review_only: "Only estimates under review can be withdrawn.", terminal_only: "Archive approved or cancelled documents only.",
  estimate_active: "The linked estimate is still active.", restore_changed: "Related data changed after deletion. Automatic restore would overwrite later work.",
  parent_closed: "The inquiry is cancelled, deleted or archived. Handle the inquiry first.",
};
export const DOCUMENT_LIFECYCLE_COPY: Record<string, { th: string; en: string; jp: string }> = Object.fromEntries([
  ["Manage document", "จัดการเอกสาร", "文書の管理"],
  ["Trash / Archive", "ถังขยะ / เอกสารเก็บถาวร", "ゴミ箱 / アーカイブ"],
  ["The estimate is in the trash. Restore it to continue with the same document number.", "Estimate อยู่ในถังขยะ กู้คืนเพื่อทำงานต่อโดยใช้เลขเอกสารเดิม", "見積はゴミ箱にあります。同じ文書番号で続行するには復元してください。"],
  ["The estimate was cancelled. Review this inquiry and use Manage document to close the work if appropriate.", "Estimate ถูกยกเลิกแล้ว ตรวจ Inquiry นี้และใช้เมนูจัดการเอกสารเพื่อยกเลิกงานตามความเหมาะสม", "見積は中止済みです。案件を確認し、必要に応じて文書の管理から作業を中止してください。"],
  ["Delete draft", "ลบร่าง", "下書きを削除"],
  ["Cancel work", "ยกเลิกงาน", "作業を中止"],
  ["Cancel inquiry and estimate", "ยกเลิก Inquiry และ Estimate", "案件と見積を中止"],
  ["Archive document", "เก็บเอกสารถาวร", "文書をアーカイブ"],
  ["Archived document — read only", "เอกสารเก็บถาวร — อ่านอย่างเดียว", "アーカイブ文書 — 読み取り専用"],
  ["Withdraw review", "ถอนจากการตรวจ", "レビューを取り下げ"],
  ["Withdrawal preserves the submitted snapshot and creates a new working revision.", "การถอนจะเก็บฉบับที่ส่งตรวจไว้ และสร้าง Revision ใหม่สำหรับแก้ไขหรือยกเลิก", "取り下げると提出済みスナップショットを保持し、新しい作業リビジョンを作成します。"],
  ["Restore document", "กู้คืนเอกสาร", "文書を復元"],
  ["Confirm action", "ยืนยันการดำเนินการ", "操作を確定"],
  ["Document changes saved", "บันทึกการจัดการเอกสารแล้ว", "文書の変更を保存しました"],
  ["Review related documents before confirming. A reason is required and recorded in history.", "ตรวจเอกสารที่เกี่ยวข้องก่อนยืนยัน ต้องระบุเหตุผลและระบบจะบันทึกประวัติ", "確定前に関連文書を確認してください。理由は必須で履歴に記録されます。"],
  ["Deleted drafts retain their number and data. Restore them from Trash / Archive.", "ร่างที่ลบยังเก็บเลขเอกสารและข้อมูลไว้ กู้คืนได้จากถังขยะ / เอกสารเก็บถาวร", "削除した下書きの番号とデータは保持され、ゴミ箱から復元できます。"],
  ["Related estimate", "Estimate ที่เกี่ยวข้อง", "関連見積"],
  ["Related projects", "Project ที่เกี่ยวข้อง", "関連プロジェクト"],
  ["Other linked work", "งานอื่นที่เชื่อมโยง", "その他の関連作業"],
  ["Active revision after deletion", "Revision ที่จะใช้งานหลังลบร่าง", "削除後の有効リビジョン"],
  ["Reason for this action", "เหตุผลในการดำเนินการ", "操作の理由"],
  ["Created by mistake", "สร้างผิด", "誤って作成"],
  ["Duplicate document", "เอกสารซ้ำ", "文書の重複"],
  ["Customer cancelled", "ลูกค้ายกเลิก", "顧客による中止"],
  ["Work completed", "งานเสร็จแล้ว", "作業完了"],
  ["Other reason", "เหตุผลอื่น", "その他の理由"],
  ["Additional details", "รายละเอียดเพิ่มเติม", "補足説明"],
  ["Refresh preview", "ตรวจสอบข้อมูลล่าสุด", "プレビューを更新"],
  ["Search document number or project", "ค้นหาเลขเอกสารหรือโครงการ", "文書番号・案件名を検索"],
  ["No deleted or archived documents", "ไม่มีเอกสารในถังขยะหรือเก็บถาวร", "削除・アーカイブされた文書はありません"],
  ["View archived document", "เปิดอ่านเอกสารเก็บถาวร", "アーカイブ文書を表示"],
  ["owner_required", "เฉพาะเจ้าของงาน ผู้จัดการวิศวกรรม หรือ Admin ที่มีสิทธิ์แก้ไข", "編集権限のある担当者・技術管理者・管理者のみ実行できます"],
  ["already_deleted", "เอกสารอยู่ในถังขยะแล้ว", "文書はゴミ箱にあります"],
  ["already_archived", "เอกสารถูกเก็บถาวรแล้ว", "文書はアーカイブ済みです"],
  ["project_linked", "มี Project เชื่อมโยง ต้องจัดการ Project แยกและคงเอกสารอ้างอิงไว้", "関連プロジェクトがあります。参照文書を保持し、プロジェクトを別途管理してください"],
  ["estimate_linked", "มี Estimate เชื่อมโยง ใช้การยกเลิกงานแทน", "関連見積があります。作業の中止を使用してください"],
  ["work_started", "มีงานต่อเนื่องแล้ว ให้ใช้การยกเลิกงาน", "関連作業が開始済みです。中止を使用してください"],
  ["draft_only", "ลบได้เฉพาะร่างที่ยังไม่เคยส่งตรวจ", "レビュー未提出の下書きのみ削除できます"],
  ["no_approved_fallback", "ไม่มี Revision ที่อนุมัติแล้วให้ย้อนกลับ ใช้การยกเลิกงาน", "戻せる承認済みリビジョンがありません。中止を使用してください"],
  ["already_cancelled", "งานถูกยกเลิกแล้ว", "作業は中止済みです"],
  ["cancel_estimate_first", "จัดการ Estimate ก่อน หากอยู่ระหว่างตรวจให้ถอน และหากอนุมัติแล้วให้ผู้อนุมัติยกเลิก", "先に見積を処理してください。レビュー中は取り下げ、承認済みは承認者が中止します"],
  ["withdraw_first", "ถอนจากการตรวจก่อนยกเลิก", "中止前にレビューを取り下げてください"],
  ["approver_required", "ต้องเป็นผู้จัดการวิศวกรรมหรือ Admin ที่มีสิทธิ์อนุมัติ", "承認権限のある技術管理者または管理者が必要です"],
  ["no_active_estimate", "ไม่มี Estimate ที่ต้องยกเลิกร่วมกัน", "同時に中止する見積はありません"],
  ["estimate_owner_required", "ต้องมีสิทธิ์แก้ไขและเป็นเจ้าของ Estimate หรือผู้จัดการ", "見積の編集権限と担当者または管理者権限が必要です"],
  ["review_only", "ใช้ได้เฉพาะ Estimate ที่อยู่ระหว่างตรวจ", "レビュー中の見積のみ取り下げできます"],
  ["terminal_only", "เก็บถาวรได้เมื่ออนุมัติหรือยกเลิกแล้ว", "承認済みまたは中止済みの文書をアーカイブできます"],
  ["estimate_active", "Estimate ยังดำเนินงานอยู่", "見積は進行中です"],
  ["restore_changed", "ข้อมูลที่เชื่อมโยงเปลี่ยนหลังลบแล้ว จึงกู้คืนอัตโนมัติไม่ได้", "削除後に関連データが変更されたため自動復元できません"],
  ["parent_closed", "Inquiry ถูกยกเลิก ลบ หรือเก็บถาวร ต้องจัดการ Inquiry ก่อน", "案件が中止・削除・アーカイブされています。先に案件を処理してください"],
  ["Permanently delete (Admin)", "ลบถาวร (Admin)", "完全に削除（管理者）"],
  ["Permanent deletion removes this document and all estimate revisions and cost lines. It cannot be restored. The deletion audit is retained.", "ลบเอกสารนี้ถาวร รวมทุก Revision และรายการต้นทุนของ Estimate กู้คืนไม่ได้ โดยยังเก็บประวัติผู้ลบไว้", "文書と見積の全リビジョン・原価明細を完全に削除します。復元できません。削除の監査履歴は保持します。"],
  ["Handle linked records before deleting this document.", "ต้องจัดการรายการที่อ้างอิงด้านล่างก่อนลบเอกสารนี้", "削除する前に以下の関連レコードを処理してください。"],
  ["Type the document number to confirm permanent deletion", "พิมพ์เลขเอกสารเพื่อยืนยันการลบถาวร", "完全削除を確認するため文書番号を入力"],
  ["Inquiry attachments", "ไฟล์แนบ Inquiry", "案件の添付ファイル"],
  ["Inquiry meetings", "การประชุมของ Inquiry", "案件の会議"],
  ["Site visit requests", "คำขอสำรวจหน้างาน", "現場調査依頼"],
  ["Resource tasks", "งานในแผนทรัพยากร", "リソース計画のタスク"],
  ["Related reports", "รายงานที่อ้างอิง", "関連レポート"],
  ["Supplier quotations", "ใบเสนอราคาผู้ขาย", "仕入先見積"],
  ["CRM opportunities", "โอกาสการขาย CRM", "CRM商談"],
  ["Bill of materials", "รายการวัสดุ BOM", "部品表"],
  ["Signing documents", "เอกสารลงนาม", "署名文書"],
].map(([en, th, jp]) => [en, { en: REASON_EN[en] ?? en, th, jp }]));
