export const CRM_COPY: Record<string,{en:string;th:string;jp:string}> = Object.fromEntries([
 ["CRM.remove","Delete","ลบ","削除"],
 ["CRM.removeCustomer","Delete customer","ลบลูกค้า","顧客を削除"],
 ["CRM.removeContact","Delete contact","ลบผู้ติดต่อ","連絡先を削除"],
 ["CRM.removeCustomerHint","Remove this customer and its sites and contacts from active lists? Business records block deletion. History is retained.","ลบลูกค้านี้พร้อมสาขาและผู้ติดต่อออกจากรายการใช้งานหรือไม่? หากมีงานอ้างอิงจะลบไม่ได้ โดยระบบเก็บประวัติไว้","この顧客と拠点・連絡先を一覧から削除しますか？関連業務がある場合は削除できません。履歴は保持されます。"],
 ["CRM.removeContactHint","Remove this contact from active lists? History is retained.","ลบผู้ติดต่อนี้ออกจากรายการใช้งานหรือไม่? ระบบเก็บประวัติไว้","この連絡先を一覧から削除しますか？履歴は保持されます。"],
 ["CRM.customer_in_use","This customer has related business records. Deletion is unavailable.","ลูกค้านี้มีงานหรือเอกสารอ้างอิงอยู่ จึงไม่สามารถลบได้","関連業務・文書があるため、この顧客は削除できません。"],
 ["CRM.contact_in_use","This contact has related business records. Deletion is unavailable.","ผู้ติดต่อนี้มีงานอ้างอิงอยู่ จึงไม่สามารถลบได้","関連業務があるため、この連絡先は削除できません。"],
 ["CRM.primary_contact_protected","Edit another contact at this site and set it as the main contact before deleting this one.","กรุณาแก้ไขผู้ติดต่อรายอื่นในสาขาเดียวกันให้เป็นผู้ติดต่อหลักก่อนลบรายนี้","同じ拠点の別の連絡先を主担当に設定してから削除してください。"],
 ["CRM.concurrency_conflict","This record changed. Refresh the page before trying again.","ข้อมูลนี้มีการเปลี่ยนแปลง กรุณารีเฟรชหน้าก่อนทำรายการอีกครั้ง","情報が更新されています。ページを更新して再試行してください。"],
 ["CRM.isPrimary","Main contact","ผู้ติดต่อหลัก","主担当者"],
 ["CRM.reportTitle","Report title","ชื่อรายงาน","報告書名"],

 ["CRM.serviceHistory","Existing service reports · open the source project or inquiry","ประวัติรายงาน Service เดิม · เปิดโครงการหรือ Inquiry ต้นทาง","既存サービス報告書・関連案件または引合を開く"], ["CRM.reportNo","Report no.","เลขที่รายงาน","報告書番号"], ["CRM.reportDate","Report date","วันที่รายงาน","報告日"],

 ["CRM.sort","Sort","เรียงตาม","並び順"],
 ["CRM.NEW","New","ใหม่","新規"], ["CRM.QUALIFICATION","Qualification","คัดกรอง","案件評価"], ["CRM.REQUIREMENT","Requirement","เก็บความต้องการ","要件確認"], ["CRM.ESTIMATING","Estimating","ประมาณราคา","見積作成"], ["CRM.PROPOSAL","Proposal submitted","เสนอราคาแล้ว","提案済み"], ["CRM.NEGOTIATION","Negotiation","เจรจา","交渉中"], ["CRM.WON","Won","ชนะงาน","受注"], ["CRM.LOST","Lost","แพ้งาน","失注"], ["CRM.ON_HOLD","On hold","พักงาน","保留"],
 ["CRM.Created","Created","สร้างแล้ว","作成"], ["CRM.Updated","Updated","แก้ไขแล้ว","更新"], ["CRM.StageChanged","Stage changed","เปลี่ยนขั้นตอน","ステージ変更"], ["CRM.ConvertedToInquiry","Inquiry created","สร้าง Inquiry","技術依頼作成"], ["CRM.ActivityAdded","Activity added","เพิ่มกิจกรรม","活動追加"], ["CRM.NextActionAdded","Next action added","เพิ่มงานติดตาม","次のアクション追加"], ["CRM.NextActionChanged","Next action changed","แก้ไขงานติดตาม","次のアクション変更"], ["CRM.DocumentAdded","Document added","เพิ่มเอกสาร","文書追加"],

 ["CRM.back","Back","กลับ","戻る"], ["CRM.previous","Previous","ก่อนหน้า","前へ"], ["CRM.next","Next","ถัดไป","次へ"], ["CRM.recordName","Name","ชื่อ","名前"],
 ["CRM & SALES","CRM & Sales","CRM และงานขาย","CRM・営業"],
 ["CRM Dashboard","CRM Dashboard","ภาพรวม CRM","CRM ダッシュボード"],
 ["CRM Customers","Customers · 360°","ลูกค้า · 360°","顧客 · 360°"],
 ["CRM Contacts","Contacts","ผู้ติดต่อ","連絡先"],
 ["CRM Opportunities","Opportunities / sales follow-up","โอกาสขาย / ติดตามงานขาย","商談・営業フォロー"],
 ["CRM Activities","Activities","กิจกรรมลูกค้า","顧客活動"],
 ["CRM Pipeline","Pipeline","กระดานงานขาย","商談パイプライン"],
 ["CRM.title","Customer relationships","ความสัมพันธ์กับลูกค้า","顧客関係"],
 ["CRM.new","New opportunity","เพิ่มโอกาสทางการขาย","商談を作成"],
 ["CRM.search","Search customer, contact, opportunity or owner","ค้นหาลูกค้า ผู้ติดต่อ โอกาสขาย หรือผู้รับผิดชอบ","顧客・連絡先・商談・担当者を検索"],
 ["CRM.empty","No matching records","ไม่พบข้อมูลที่ตรงกัน","該当するデータがありません"],
 ["CRM.loading","Loading CRM…","กำลังโหลด CRM…","CRM を読み込み中…"],
 ["CRM.error","Unable to save or load CRM. Check required fields and refresh if the record changed.","บันทึกหรือโหลด CRM ไม่สำเร็จ ตรวจช่องที่จำเป็น และรีเฟรชหากข้อมูลเปลี่ยน","CRM を保存または読み込めません。必須項目を確認し、変更済みの場合は再読み込みしてください。"],
 ["CRM.saved","CRM saved","บันทึก CRM แล้ว","CRM を保存しました"],
 ["CRM.overview","Overview","ภาพรวม","概要"], ["CRM.contacts","Contacts","ผู้ติดต่อ","連絡先"],
 ["CRM.activities","Activities","กิจกรรม","活動"], ["CRM.links","Inquiry / Estimate / Project","Inquiry / Estimate / Project","引合・見積・案件"],
 ["CRM.documents","Documents","เอกสาร","文書"], ["CRM.history","History","ประวัติ","履歴"],
 ["CRM.name","Opportunity name","ชื่อโอกาสทางการขาย","商談名"], ["CRM.customerId","Customer","ลูกค้า","顧客"],
 ["CRM.siteId","Site","สถานที่","拠点"], ["CRM.contactId","Contact","ผู้ติดต่อ","連絡先"],
 ["CRM.salesOwnerId","Sales owner","ผู้รับผิดชอบงานขาย","営業担当者"], ["CRM.technicalOwnerId","Technical owner","ผู้รับผิดชอบเทคนิค","技術担当者"],
 ["CRM.source","Source","แหล่งที่มา","情報源"], ["CRM.need","Customer need / Summary","ความต้องการลูกค้า / สรุป","顧客ニーズ・概要"],
 ["CRM.scope","Scope","ขอบเขตงาน","作業範囲"], ["CRM.expectedValue","Expected value (THB)","มูลค่าคาดการณ์ (บาท)","想定金額 (THB)"],
 ["CRM.expectedClose","Expected close","วันที่คาดว่าจะปิดงาน","受注予定日"], ["CRM.stage","Stage","ขั้นตอน","ステージ"],
 ["CRM.probability","Probability (%)","โอกาสชนะ (%)","受注確率 (%)"], ["CRM.competitor","Competitor","คู่แข่ง","競合"],
 ["CRM.priority","Priority","ความสำคัญ","優先度"], ["CRM.lostReason","Lost reason","เหตุผลที่แพ้งาน","失注理由"],
 ["CRM.lostDetail","Lost reason details","รายละเอียดเหตุผลที่แพ้งาน","失注理由の詳細"], ["CRM.internalNote","Internal note","บันทึกภายใน","社内メモ"],
 ["CRM.followups","Next actions / Follow-up","สิ่งที่ต้องทำ / ติดตาม","次のアクション・フォローアップ"],
 ["CRM.addAction","Add next action","เพิ่มสิ่งที่ต้องทำ","次のアクションを追加"], ["CRM.action","Next action","สิ่งที่ต้องทำถัดไป","次のアクション"],
 ["CRM.ownerId","Owner","ผู้รับผิดชอบ","担当者"], ["CRM.dueDate","Due date","กำหนดเสร็จ","期限"], ["CRM.status","Status","สถานะ","状態"],
 ["CRM.addActivity","Log activity","บันทึกกิจกรรม","活動を記録"], ["CRM.activityType","Activity type","ประเภทกิจกรรม","活動種別"],
 ["CRM.occurredAt","Date / time","วันที่ / เวลา","日時"], ["CRM.participants","Participants","ผู้เข้าร่วม","参加者"],
 ["CRM.summary","Summary","สรุป","概要"], ["CRM.decision","Key decision","ข้อสรุปสำคัญ","主な決定"], ["CRM.actionItems","Action items","รายการดำเนินการ","対応事項"],
 ["CRM.convert","Create inquiry","สร้าง Inquiry","引合を作成"], ["CRM.projectType","Project type","ประเภทโครงการ","案件種別"],
 ["CRM.openInquiry","Open active inquiry","เปิด Inquiry ที่กำลังดำเนินการ","進行中の引合を開く"], ["CRM.convertHint","Create the engineering Inquiry once the RFQ or requirements are ready. This opportunity can have only one active Inquiry.","สร้าง Inquiry สำหรับทีมวิศวกรรมเมื่อได้รับ RFQ หรือข้อมูลพร้อมประเมินแล้ว โดยหนึ่ง Opportunity มี Inquiry ที่กำลังดำเนินการได้เพียงหนึ่งรายการ","RFQ または要件が整ったら技術チーム向けの引合を作成します。商談ごとに進行中の引合は1件のみです。"],
 ["CRM.duplicateWarning","A similar active opportunity already exists. Create another one anyway?","พบโอกาสขายที่กำลังดำเนินการและมีชื่อคล้ายกัน ต้องการสร้างรายการใหม่ต่อหรือไม่","類似する進行中の商談があります。新しく作成しますか？"],
 ["CRM.flowSummary","Opportunity conversion","การส่งต่องานขาย","商談コンバージョン"], ["CRM.flowSummaryHint","CRM-sourced and direct engineering intake","แยกงานจาก CRM และงานที่รับตรงเข้าสู่วิศวกรรม","CRM経由と直接受付"],
 ["CRM.directInquiries","Direct inquiries","Inquiry ที่รับตรง","直接受付"], ["CRM.convertedToInquiry","CRM → Inquiry","CRM → Inquiry","CRM → 引合"], ["CRM.convertedToEstimate","CRM → Estimate","CRM → Estimate","CRM → 見積"], ["CRM.convertedToProject","CRM → Project","CRM → Project","CRM → プロジェクト"],
 ["CRM.projectConversionRate","Opportunity → Project","อัตรา Opportunity → Project","商談 → プロジェクト率"],
 ["CRM.autoFilledHint","Customer, end user, contact, owners, requirements, scope and site are copied automatically. Only confirm the engineer and due date.","ระบบนำลูกค้า End-user ผู้ติดต่อ ผู้รับผิดชอบ Requirement Scope และสถานที่มาให้อัตโนมัติ ให้ตรวจเพียงวิศวกรและกำหนดส่ง","顧客、エンドユーザー、連絡先、担当者、要件、範囲、場所は自動転記されます。技術者と期限のみ確認してください。"],
 ["CRM.estimateOwnerId","Engineer","วิศวกร","エンジニア"], ["CRM.sourceOpportunity","Source opportunity","โอกาสขายต้นทาง","元の商談"],
 ["CRM.attention","Attention","งานที่ต้องติดตาม","要対応"], ["CRM.open","Open opportunities","โอกาสขายที่ยังเปิด","進行中の商談"],
 ["CRM.NoNextAction","No next action","ยังไม่มีสิ่งที่ต้องทำถัดไป","次のアクション未設定"], ["CRM.NoActivity","No activity","ยังไม่มีกิจกรรม","活動なし"],
 ["CRM.Overdue","Overdue","เกินกำหนด","期限超過"], ["CRM.DueToday","Due today","ครบกำหนดวันนี้","本日期限"],
 ["CRM.DueSoon","Due soon","ใกล้ครบกำหนด","期限間近"], ["CRM.Scheduled","Scheduled","นัดหมายแล้ว","予定済み"],
 ["CRM.NeedsFollowup","Needs follow-up","ควรติดตาม","フォローアップが必要"], ["CRM.EstimateDueSoon","Estimate due soon","Estimate ใกล้ครบกำหนด","見積期限間近"],
 ["CRM.WaitingCustomer","Waiting customer","รอลูกค้า","顧客待ち"], ["CRM.WaitingInternal","Waiting internal","รอภายใน","社内待ち"],
 ["CRM.WaitingSupplier","Waiting supplier","รอผู้ขาย","仕入先待ち"], ["CRM.Open","Open","เปิด","未完了"], ["CRM.Done","Done","เสร็จแล้ว","完了"], ["CRM.Cancelled","Cancelled","ยกเลิก","キャンセル"],
 ["CRM.Meeting","Meeting","ประชุม","会議"], ["CRM.Call","Call","โทรศัพท์","電話"], ["CRM.Email","Email","อีเมล","メール"],
 ["CRM.SiteVisit","Site visit","เข้าหน้างาน","現地訪問"], ["CRM.CustomerUpdate","Customer update","ข้อมูลจากลูกค้า","顧客情報更新"],
 ["CRM.InternalDiscussion","Internal discussion","หารือภายใน","社内協議"], ["CRM.MessageLINE","Message / LINE","ข้อความ / LINE","メッセージ・LINE"],
 ["CRM.Note","Note","บันทึก","メモ"], ["CRM.Other","Other","อื่นๆ","その他"],
 ["CRM.newCustomer","New customer","เพิ่มลูกค้า","顧客を追加"], ["CRM.newContact","New contact","เพิ่มผู้ติดต่อ","連絡先を追加"], ["CRM.newSite","Add site","เพิ่มสถานที่","拠点を追加"],
 ["CRM.companyName","Company name","ชื่อบริษัท","会社名"], ["CRM.contactName","Contact name","ชื่อผู้ติดต่อ","担当者名"],
 ["CRM.shortName","Short name","ชื่อย่อ","略称"], ["CRM.code","Code","รหัส","コード"], ["CRM.industry","Industry","อุตสาหกรรม","業種"],
 ["CRM.country","Country","ประเทศ","国"], ["CRM.website","Website","เว็บไซต์","ウェブサイト"], ["CRM.site","Address","ที่อยู่","住所"],
 ["CRM.accountOwnerId","Account owner","ผู้ดูแลลูกค้า","顧客担当者"], ["CRM.email","Email","อีเมล","メール"], ["CRM.phone","Phone","โทรศัพท์","電話番号"],
 ["CRM.department","Department","แผนก","部署"], ["CRM.position","Position","ตำแหน่ง","役職"], ["CRM.contactRole","Contact role","บทบาทผู้ติดต่อ","連絡先の役割"],
 ["CRM.messagingAddress","LINE / Messaging","LINE / ช่องทางข้อความ","LINE・メッセージ先"], ["CRM.note","Note","หมายเหตุ","備考"],
 ["CRM.isActive","Active","ใช้งาน","有効"], ["CRM.sites","Sites","สถานที่","拠点"], ["CRM.siteName","Site name","ชื่อสถานที่","拠点名"],
 ["CRM.address","Address","ที่อยู่","住所"], ["CRM.province","Province / Region","จังหวัด / ภูมิภาค","都道府県・地域"], ["CRM.accessNote","Site note","หมายเหตุสถานที่","拠点メモ"],
 ["CRM.opportunities","Opportunities","โอกาสขาย","商談"], ["CRM.inquiries","Inquiries","งานสอบถามราคา","引合"], ["CRM.estimates","Estimates","ประมาณการต้นทุน","見積"],
 ["CRM.projects","Projects","โครงการ","案件"], ["CRM.service","Service","งานบริการ","サービス"],
 ["CRM.serviceUnavailable","No service history source is configured in this application.","ระบบนี้ยังไม่มีแหล่งประวัติงานบริการที่เชื่อมต่อ","このシステムにはサービス履歴の連携元が設定されていません。"],
 ["CRM.year","Year","ปี","年"], ["CRM.lastActivity","Last activity","กิจกรรมล่าสุด","最終活動"],
 ["CRM.upload","Upload document","เพิ่มเอกสาร","文書をアップロード"], ["CRM.configuration","CRM configuration","ตั้งค่า CRM","CRM 設定"],
 ["CRM.kind","Option type","ประเภทตัวเลือก","選択肢の種別"], ["CRM.labelTh","Thai label","ชื่อภาษาไทย","タイ語ラベル"], ["CRM.labelEn","English label","ชื่อภาษาอังกฤษ","英語ラベル"], ["CRM.labelJa","Japanese label","ชื่อภาษาญี่ปุ่น","日本語ラベル"],
 ["CRM.quietDays","Days without activity","จำนวนวันที่ไม่มีกิจกรรม","活動なしの日数"], ["CRM.optionalDetails","Additional details (optional)","รายละเอียดเพิ่มเติม (ไม่บังคับ)","追加情報（任意）"],
 ["CRM.waitingHint","No next action is a reminder, not a save blocker.","ยังไม่มีสิ่งที่ต้องทำถัดไปเป็นเพียงการเตือน ยังบันทึกได้","次のアクション未設定は警告のみで、保存できます。"],
 ["CRM.permissions","CRM permission is required","ต้องมีสิทธิ์ CRM","CRM の権限が必要です"],
 ["CRM.filesInherited","Related CRM activities and documents remain linked through the source opportunity.","กิจกรรมและเอกสาร CRM อ้างอิงผ่านโอกาสขายต้นทาง","関連する CRM 活動と文書は元の商談を通じて参照できます。"],
 ["CRM.editCustomer","Edit customer","แก้ไขข้อมูลลูกค้า","顧客情報を編集"],
 ["CRM.searchCustomer","Search by customer code or name…","ค้นหาด้วยรหัสหรือชื่อลูกค้า…","顧客コードまたは名称で検索…"], ["CRM.selectFromList","Select a customer from the list","กรุณาเลือกลูกค้าจากรายการ","リストから顧客を選択してください"], ["CRM.showOptions","Show customer list","แสดงรายชื่อลูกค้า","顧客リストを表示"],
 ["CRM.endUserCustomerId","End user (optional)","บริษัทผู้ใช้งานปลายทาง (ไม่บังคับ)","エンドユーザー（任意）"], ["CRM.endUserName","End user","ผู้ใช้งานปลายทาง","エンドユーザー"], ["CRM.searchEndUser","Search end user code or company name…","ค้นหารหัสหรือชื่อบริษัทผู้ใช้งานปลายทาง…","エンドユーザーのコードまたは会社名を検索…"],
 ["CRM.sameCustomer","Same as customer","บริษัทเดียวกับลูกค้า","顧客と同じ"], ["CRM.notSpecified","Not specified","ยังไม่ระบุ","未指定"], ["CRM.endUserHint","Uses the same company master as Estimate Cost and carries forward to Inquiry.","ใช้ข้อมูลบริษัทชุดเดียวกับ Estimate Cost และส่งต่อไปยัง Inquiry","Estimate Cost と同じ会社マスターを使用し、引合へ引き継ぎます。"],
 ["CRM.useCustomerAsEndUser","Use customer as End User","ใช้ลูกค้าเป็น End User","顧客をエンドユーザーに設定"],
 ["CRM.nameTh","Name (Thai)","ชื่อภาษาไทย","名前（タイ語）"], ["CRM.nameEn","Name (English)","ชื่อภาษาอังกฤษ","名前（英語）"], ["CRM.nameJa","Name (Japanese)","ชื่อภาษาญี่ปุ่น","名前（日本語）"],
 ["CRM.accountOwnerName","Account owner","ผู้ดูแลลูกค้า","顧客担当者"], ["CRM.customerName","Customer","ลูกค้า","顧客"], ["CRM.nextAction","Next action","สิ่งที่ต้องทำถัดไป","次のアクション"], ["CRM.nextDue","Next due","กำหนดครั้งถัดไป","次回期限"],
 ["CRM.salesOwnerName","Sales owner","ผู้รับผิดชอบงานขาย","営業担当者"],
 ["CRM.opportunityNo","Opportunity number","เลขที่โอกาสขาย","商談番号"], ["CRM.inquiryNo","Inquiry number","เลขที่ Inquiry","引合番号"], ["CRM.estimateNo","Estimate number","เลขที่ Estimate","見積番号"], ["CRM.projectNo","Project number","เลขที่โครงการ","案件番号"],
 ["CRM.projectName","Project name","ชื่อโครงการ","案件名"], ["CRM.revision","Revision","ฉบับแก้ไข","改訂"], ["CRM.total","Total (THB)","ยอดรวม (บาท)","合計 (THB)"], ["CRM.targetDelivery","Target delivery","กำหนดส่งมอบ","納入予定日"],
 ["CRM.uploadedByName","Uploaded by","ผู้อัปโหลด","アップロード者"], ["CRM.uploadedAt","Uploaded at","วันที่อัปโหลด","アップロード日時"], ["CRM.sizeBytes","Size (bytes)","ขนาด (ไบต์)","サイズ（バイト）"],
 ["CRM.inquiryId","Related inquiry","Inquiry ที่เกี่ยวข้อง","関連引合"], ["CRM.estimateId","Related estimate","Estimate ที่เกี่ยวข้อง","関連見積"], ["CRM.projectId","Related project","โครงการที่เกี่ยวข้อง","関連案件"],
 ["CRM.emptyHint","Nothing matches the current filters yet.","ยังไม่มีรายการที่ตรงกับตัวกรองที่เลือก","現在の絞り込み条件に一致する項目はありません。"],
 ["CRM.introDashboard","Overview of sales activity, open opportunities and what needs a follow-up.","ภาพรวมงานขาย โอกาสที่ยังเปิดอยู่ และรายการที่ต้องติดตาม","営業活動・進行中の商談・要対応事項の概要"],
 ["CRM.introCustomers","Customer accounts, sites and the people who own them.","ข้อมูลลูกค้า สถานที่ตั้ง และผู้รับผิดชอบ","顧客情報・拠点・担当者"],
 ["CRM.introContacts","Contacts shared across every customer account.","ผู้ติดต่อที่ใช้ร่วมกันทุกบัญชีลูกค้า","全顧客で共有する連絡先"],
 ["CRM.introOpportunities","Track sales from initial interest to close; link engineering work through an Inquiry.","ติดตามการขายตั้งแต่เริ่มสนใจจนถึงปิดงาน และเชื่อมงานประเมินผ่าน Inquiry","初期相談から受注・失注まで追跡し、引合で技術作業と連携します。"],
 ["CRM.introActivities","Meetings, calls, emails and site visits in one timeline.","การประชุม โทรศัพท์ อีเมล และการเข้าพบ รวมอยู่ในไทม์ไลน์เดียว","会議・電話・メール・訪問を一つの時系列で確認"],
 ["CRM.introPipeline","Opportunities by stage, from first contact through to close.","โอกาสขายแยกตามขั้นตอน ตั้งแต่ติดต่อครั้งแรกจนปิดการขาย","初回接触から成約までのステージ別商談"],
 ["CRM.totalCustomers","Customers","ลูกค้าทั้งหมด","顧客総数"], ["CRM.totalContacts","Contacts","ผู้ติดต่อทั้งหมด","連絡先総数"],
 ["CRM.allActivities","Activities","กิจกรรมทั้งหมด","活動総数"], ["CRM.shown","On this page","แสดงในหน้านี้","表示中"],
 ["CRM.withIndustry","With industry","ระบุประเภทธุรกิจ","業種あり"], ["CRM.withOwner","With account owner","มีผู้ดูแลบัญชี","担当者あり"],
 ["CRM.withEmail","With email","มีอีเมล","メールあり"], ["CRM.withRole","With contact role","ระบุบทบาท","役割あり"],
 ["CRM.pipelineOverview","Pipeline overview","ภาพรวมไปป์ไลน์","パイプライン概要"], ["CRM.pipelineOverviewHint","Open opportunities by stage, what needs attention, and how many reached engineering. Click a stage or a count to filter the list.","โอกาสที่ยังเปิดแยกตามขั้นตอน รายการที่ต้องติดตาม และจำนวนที่ส่งถึงวิศวกรรม — คลิกขั้นตอนหรือตัวเลขเพื่อกรองรายการด้านล่าง","ステージ別の進行中商談・要対応件数・技術部門への引き継ぎ状況。ステージや件数をクリックすると一覧を絞り込めます。"],
 ["CRM.directInquiriesHint","inquiries raised without an opportunity","Inquiry ที่รับตรงโดยไม่ผ่านโอกาสขาย","商談を経ずに受け付けた引合"],
 ["CRM.dragHint","Drag a card into another column to change its stage.","ลากการ์ดไปยังคอลัมน์อื่นเพื่อเปลี่ยนขั้นตอนได้","カードを別の列へドラッグするとステージを変更できます。"],
 ["CRM.moveConflict","This opportunity changed while the board was open. Refresh and try the move again.","โอกาสขายนี้ถูกแก้ไขระหว่างที่เปิดกระดานอยู่ กรุณารีเฟรชแล้วลากใหม่อีกครั้ง","ボードを開いている間にこの商談が更新されました。更新してからもう一度移動してください。"],
 ["CRM.moveFailed","The stage could not be changed. The card has been put back.","เปลี่ยนขั้นตอนไม่สำเร็จ ระบบนำการ์ดกลับที่เดิมแล้ว","ステージを変更できませんでした。カードを元の位置に戻しました。"],
 ["CRM.proposalSentOn", "Quotation sent date", "วันที่ส่งใบเสนอราคา", "見積送付日"],
 ["CRM.proposalReference", "Quotation number / dispatch reference", "เลขใบเสนอราคา / หลักฐานการส่ง", "見積番号・送付記録"],
 ["CRM.wonOn", "Order confirmation date", "วันที่ลูกค้ายืนยันสั่งซื้อ", "受注確認日"],
 ["CRM.wonReference", "PO / customer confirmation reference", "เลข PO / หลักฐานลูกค้ายืนยัน", "注文書・顧客確認記録"],
 ["CRM.recordProposal", "Record quotation dispatch", "บันทึกส่งใบเสนอราคา", "見積送付を記録"],
 ["CRM.recordWon", "Record order confirmation", "บันทึกลูกค้ายืนยันสั่งซื้อ", "受注確認を記録"],
 ["CRM.evidenceHint", "Use the actual event date and a document number or confirmation reference. Cost approval does not send a quotation.", "ระบุวันที่เกิดเหตุการณ์จริงและเลขเอกสารหรือหลักฐานอ้างอิง การอนุมัติต้นทุนยังไม่ใช่การส่งราคาให้ลูกค้า", "実際の日付と文書番号・確認記録を入力してください。原価承認は見積送付ではありません。"],
 ["CRM.unverifiedProposal", "Quotation dispatch not recorded", "ยังไม่มีบันทึกการส่งราคา", "見積送付記録なし"],
 ["CRM.unverifiedWon", "Order confirmation not recorded", "ยังไม่มีหลักฐานยืนยันสั่งซื้อ", "受注確認記録なし"],
 ["CRM.costApproved", "Cost approved", "อนุมัติต้นทุนแล้ว", "原価承認済み"],
 ["CRM.inquiryStatus", "Estimating status", "สถานะงานประเมิน", "見積作成状況"],
 ["CRM.latestInquiry", "Open latest inquiry", "เปิด Inquiry ล่าสุด", "最新の引合を開く"],
 ["CRM.additionalInquiry", "Create additional estimating work", "สร้างงานประเมินเพิ่มเติม", "追加の見積作業を作成"],
 ["CRM.allScopeHint", "Overview of all accessible opportunities; the filters below apply to the table.", "ภาพรวมโอกาสขายทั้งหมดที่คุณเข้าถึงได้ · ตัวกรองด้านล่างใช้กับตาราง", "アクセス可能な商談全体の概要です。下のフィルターは一覧に適用されます。"],
 ["CRM.totalOpportunities", "All opportunities", "โอกาสขายทั้งหมด", "商談総数"],
 ["CRM.Actionable", "Needs action", "ต้องดำเนินการ", "要対応"],
 ["CRM.filteredResults", "Results matching the selected filters", "รายการตามตัวกรองที่เลือก", "選択した条件に一致する結果"],
 ["CRM.existingRfqWork", "Existing customer work", "งานเดิมของลูกค้า", "顧客の既存案件"],
 ["CRM.existingRfqHint", "Search existing opportunities and inquiries before creating a new record.", "ค้นหาโอกาสขายและ Inquiry เดิมก่อนสร้างรายการใหม่", "新規作成の前に既存の商談・引合を検索してください。"],
 ["CRM.useOpportunity", "Use this opportunity", "ใช้โอกาสขายนี้", "この商談を使用"],
 ["CRM.unlinkOpportunity", "Receive as a direct inquiry", "รับเป็น Inquiry โดยตรง", "直接引合として受付"],
 ["CRM.linkedIntakeHint", "Customer, job name and requirements come from the selected opportunity. The selected estimator and due date will be used.", "ลูกค้า ชื่องาน และความต้องการอ้างอิงจากโอกาสขายที่เลือก โดยใช้ผู้ประเมินและกำหนดส่งที่คุณระบุ", "顧客・案件名・要件は選択した商談から引き継ぎ、選択した見積担当者と期限を使用します。"],
 ["CRM.directIntakeHint", "Receive an RFQ or ready requirements here. Continue tracking the sale in CRM.", "รับ RFQ หรือข้อมูลพร้อมประเมินที่นี่ และติดตามการขายต่อใน CRM", "RFQ・見積可能な要件を受け付け、営業状況はCRMで追跡します。"],
 ["CRM.followSales", "Coordinate quotation with sales", "ประสานฝ่ายขายเพื่อเสนอราคา", "営業と見積送付を調整"],
 ["CRM.followCustomer", "Follow up customer decision", "ติดตามผลการตัดสินใจของลูกค้า", "顧客の判断を確認"],
 ["CRM.verifySales", "Verify quotation dispatch", "ตรวจสอบการส่งราคาให้ลูกค้า", "見積送付を確認"],
 ["CRM.projectCreated", "Project already created", "เปิด Project แล้ว", "プロジェクト作成済み"],
 ["CRM.salesStage", "Sales status", "สถานะงานขาย", "営業状況"],
 ["CRM.OrderConfirmed", "Order confirmed", "ยืนยันคำสั่งซื้อแล้ว", "受注確認済み"],
 ["CRM.rfqTitle", "RFQ intake / estimating work", "รับ RFQ / งานประเมินราคา", "RFQ受付・見積作業"],
 ["CRM.rfqSubtitle", "Receive requirements, assign engineers and track cost estimation. Track the customer decision in CRM.", "รับข้อมูล มอบหมาย และติดตามงานประเมินต้นทุน · ติดตามผลการขายต่อใน CRM", "要件受付・技術担当の割当・原価見積を管理し、顧客の判断はCRMで追跡します。"],
 ["RFQ intake & estimating", "RFQ intake / estimating work", "รับ RFQ / งานประเมินราคา", "RFQ受付・見積作業"],
 ["CRM.leaveIntake", "Open the existing inquiry and discard this unsaved intake draft?", "เปิด Inquiry เดิมและทิ้งแบบร่างรับเรื่องที่ยังไม่ได้บันทึกหรือไม่", "既存の引合を開き、未保存の受付内容を破棄しますか？"],
 ["CRM.matchLimit", "Showing up to 10 matches of each type. Refine the job name to find another record.", "แสดงสูงสุดประเภทละ 10 รายการ · ระบุชื่องานให้เจาะจงเพื่อค้นหารายการอื่น", "種類ごとに最大10件を表示します。案件名を絞り込んでください。"],
 ["CRM.verifyOrder", "Verify order confirmation", "ตรวจสอบหลักฐานยืนยันสั่งซื้อ", "受注確認記録を確認"],
 ["CRM.awaitCostApproval", "Await cost approval before creating a project", "รออนุมัติต้นทุนก่อนสร้าง Project", "プロジェクト作成には原価承認が必要です"],
 ["CRM.projectGate", "A customer PO and approved costs are required", "ต้องมี PO ลูกค้าและต้นทุนที่อนุมัติแล้ว", "顧客注文書と原価承認が必要です"],
 ["CRM.projectHandover", "Project handover", "การส่งต่อสร้าง Project", "プロジェクト引継ぎ"],
 ["CRM.projectExists", "Project already created. Open it, or restore it if it is in the trash.", "สร้าง Project แล้ว · เปิดรายการเดิม หรือกู้คืนหากอยู่ในถังขยะ", "プロジェクト作成済みです。既存の案件を開くか、ごみ箱から復元してください。"],
 ["CRM.sourceUnavailable", "The source is unavailable or already assigned to a project. Refresh and review the inquiry.", "ต้นทางใช้งานไม่ได้หรือสร้าง Project แล้ว · รีเฟรชและตรวจสอบ Inquiry", "元の引合を利用できないか、プロジェクト作成済みです。更新して確認してください。"],
 ["CRM.recordPo", "Costs approved. Record the customer PO to create a project.", "ต้นทุนอนุมัติแล้ว · ระบุ PO ลูกค้าเพื่อสร้าง Project", "原価承認済みです。顧客注文書を登録してプロジェクトを作成してください。"],
 ["CRM.projectPermission", "A user with project creation and estimate access must create the project.", "ให้ผู้มีสิทธิ์สร้าง Project และอ่าน Estimate เป็นผู้สร้างรายการ", "プロジェクト作成と見積閲覧の権限を持つ担当者が作成してください。"],
 ["CRM.noEligibleEstimate", "No eligible estimates. Costs must be Approved or Locked, the source must be active, and no project may already exist.", "ไม่มี Estimate ที่สร้าง Project ได้ · ต้องอนุมัติต้นทุนแล้ว ต้นทางยังใช้งานได้ และยังไม่เคยสร้าง Project", "利用可能な見積がありません。原価承認済みで、有効な引合かつプロジェクト未作成である必要があります。"],
 ["CRM.projectRequired", "Required: approved estimate, PO number and date, project manager, lead engineer, start date, delivery date and site.", "ข้อมูลจำเป็น: Estimate ที่อนุมัติ เลขและวันที่ PO ผู้จัดการ วิศวกรหลัก วันเริ่ม วันส่งมอบ และสถานที่", "必須：承認済み見積、注文番号と日付、責任者、技術担当、開始日、納期、現場。"],
 ["CRM.projectDefaults", "Lead engineer, site and delivery date are copied from the selected estimate. Review them and complete the PO and project manager.", "ใช้วิศวกรหลัก สถานที่ และวันส่งมอบจาก Estimate ที่เลือก · ตรวจสอบและกรอก PO กับผู้จัดการโครงการ", "選択した見積から技術担当、現場、納期を引き継ぎます。注文書と責任者を確認してください。"],
 ["CRM.projectNoAutomatic", "Assigned when saved", "ระบบออกเลขเมื่อบันทึก", "保存時に自動採番"],
 ["CRM.selectProjectManager", "Select project manager", "เลือกผู้จัดการโครงการ", "プロジェクトマネージャーを選択"],
 ["CRM.selectLeadEngineer", "Select lead engineer", "เลือกวิศวกรหลัก", "主担当技術者を選択"],
 ["CRM.projectOptionalDetails", "More details (optional)", "ข้อมูลเพิ่มเติม (ไม่บังคับ)", "追加情報（任意）"],
 ["CRM.projectPlanLater", "After saving, add the work plan in Project Schedule and project members under Team. Status starts at Planning.", "หลังบันทึก เพิ่มแผนงานใน Project Schedule และเพิ่มสมาชิกที่เมนู Team · สถานะเริ่มต้นเป็นวางแผน", "保存後、プロジェクトスケジュールで作業計画を、Teamでメンバーを追加できます。初期状態は計画中です。"],
 ["CRM.customerFollowup", "Customer follow-up", "ติดตามลูกค้า", "顧客フォローアップ"],
 ["CRM.openFollowup", "Open sales and follow-up", "เปิดงานขายและติดตามลูกค้า", "営業・フォローアップを開く"],
 ["CRM.linkUnavailable", "This inquiry has an opportunity that you cannot access. Contact the sales owner.", "Inquiry นี้เชื่อม Opportunity แล้ว แต่คุณไม่มีสิทธิ์เข้าถึง · ติดต่อเจ้าของงานขาย", "この引合にはアクセスできない商談が関連付けられています。営業担当者に連絡してください。"],
 ["CRM.directFollowupHint", "Link an opportunity to record customer contacts and schedule follow-up with an owner and due date.", "เชื่อม Opportunity เพื่อบันทึกการติดต่อลูกค้าและนัดติดตาม พร้อมผู้รับผิดชอบและวันครบกำหนด", "商談を関連付けて顧客との連絡や、担当者・期日付きのフォローアップを管理します。"],
 ["CRM.linkSales", "Set up customer follow-up", "ตั้งค่าการติดตามลูกค้า", "顧客フォローアップを設定"],
 ["CRM.linkSalesHint", "Select an existing opportunity for this customer, or create one from this inquiry. The inquiry and estimate are retained.", "เลือก Opportunity เดิมของลูกค้ารายนี้ หรือสร้างจากข้อมูล Inquiry นี้ โดยใช้ Inquiry และ Estimate เดิม", "同じ顧客の既存商談を選択するか、この引合から作成します。引合と見積は引き継がれます。"],
 ["CRM.linkExisting", "Link existing opportunity", "เชื่อม Opportunity เดิม", "既存商談を関連付ける"],
 ["CRM.createFromInquiry", "Create opportunity from this inquiry", "สร้าง Opportunity จาก Inquiry นี้", "この引合から商談を作成"],
 ["A project already exists for this inquiry. Open or restore the existing project.", "A project already exists for this inquiry. Open or restore the existing project.", "Inquiry นี้มี Project แล้ว กรุณาเปิดหรือกู้คืนรายการเดิม", "この引合にはプロジェクトがあります。既存の案件を開くか復元してください。"],
 ["An approved estimate is required to create a project.", "An approved estimate is required to create a project.", "รออนุมัติต้นทุนก่อนสร้าง Project", "プロジェクト作成には原価承認が必要です。"],
 ["CRM.missingProjectFields", "Complete these fields", "กรุณากรอกข้อมูลที่ยังขาด", "未入力の項目"],
].map(([key,en,th,jp])=>[key,{en,th,jp}]));
