export const CRM_COPY: Record<string,{en:string;th:string;jp:string}> = Object.fromEntries([
 ["CRM.reportTitle","Report title","ชื่อรายงาน","報告書名"],

 ["CRM.serviceHistory","Existing service reports · open the source project or inquiry","ประวัติรายงาน Service เดิม · เปิดโครงการหรือ Inquiry ต้นทาง","既存サービス報告書・関連案件または引合を開く"], ["CRM.reportNo","Report no.","เลขที่รายงาน","報告書番号"], ["CRM.reportDate","Report date","วันที่รายงาน","報告日"],

 ["CRM.sort","Sort","เรียงตาม","並び順"],
 ["CRM.NEW","New","ใหม่","新規"], ["CRM.QUALIFICATION","Qualification","คัดกรอง","案件評価"], ["CRM.REQUIREMENT","Requirement","เก็บความต้องการ","要件確認"], ["CRM.ESTIMATING","Estimating","ประมาณราคา","見積作成"], ["CRM.PROPOSAL","Proposal submitted","เสนอราคาแล้ว","提案済み"], ["CRM.NEGOTIATION","Negotiation","เจรจา","交渉中"], ["CRM.WON","Won","ชนะงาน","受注"], ["CRM.LOST","Lost","แพ้งาน","失注"], ["CRM.ON_HOLD","On hold","พักงาน","保留"],
 ["CRM.Created","Created","สร้างแล้ว","作成"], ["CRM.Updated","Updated","แก้ไขแล้ว","更新"], ["CRM.StageChanged","Stage changed","เปลี่ยนขั้นตอน","ステージ変更"], ["CRM.ConvertedToInquiry","Inquiry created","สร้าง Inquiry","技術依頼作成"], ["CRM.ActivityAdded","Activity added","เพิ่มกิจกรรม","活動追加"], ["CRM.NextActionAdded","Next action added","เพิ่มงานติดตาม","次のアクション追加"], ["CRM.NextActionChanged","Next action changed","แก้ไขงานติดตาม","次のアクション変更"], ["CRM.DocumentAdded","Document added","เพิ่มเอกสาร","文書追加"],

 ["CRM.back","Back","กลับ","戻る"], ["CRM.previous","Previous","ก่อนหน้า","前へ"], ["CRM.next","Next","ถัดไป","次へ"], ["CRM.recordName","Name","ชื่อ","名前"],
 ["CRM & SALES","CRM & Sales","CRM และงานขาย","CRM・営業"],
 ["CRM Dashboard","CRM Dashboard","ภาพรวม CRM","CRM ダッシュボード"],
 ["CRM Customers","Customers · 360°","ลูกค้า · 360°","顧客 · 360°"],
 ["CRM Contacts","Contacts","ผู้ติดต่อ","連絡先"],
 ["CRM Opportunities","Opportunities","โอกาสทางการขาย","商談"],
 ["CRM Activities","Activities","กิจกรรมลูกค้า","顧客活動"],
 ["CRM Pipeline","Pipeline","กระดานงานขาย","商談パイプライン"],
 ["CRM.title","Customer relationships","ความสัมพันธ์กับลูกค้า","顧客関係"],
 ["CRM.new","New opportunity","เพิ่มโอกาสทางการขาย","商談を作成"],
 ["CRM.search","Search customer, contact, opportunity or owner","ค้นหาลูกค้า ผู้ติดต่อ โอกาสขาย หรือผู้รับผิดชอบ","顧客・連絡先・商談・担当者を検索"],
 ["CRM.empty","No matching records","ไม่พบข้อมูลที่ตรงกัน","該当するデータがありません"],
 ["CRM.loading","Loading CRM…","กำลังโหลด CRM…","CRM を読み込み中…"],
 ["CRM.error","Unable to save or load CRM. Check required fields and refresh if the record changed.","บันทึกหรือโหลด CRM ไม่สำเร็จ ตรวจช่องที่จำเป็น และรีเฟรชหากข้อมูลเปลี่ยน","CRM を保存または読み込めません。必須項目を確認し、変更済みの場合は再読み込みしてください。"],
 ["CRM.saved","CRM saved","บันทึก CRM แล้ว","CRM を保存しました"],
 ["CRM.overview","Overview","ภาพรวม","概要"], ["CRM.contacts","Contacts","ผู้ติดต่อ","連絡先"],
 ["CRM.activities","Activities","กิจกรรม","活動"], ["CRM.links","Inquiry / Estimate / Project","Inquiry / Estimate / Project","引合・見積・案件"],
 ["CRM.documents","Documents","เอกสาร","文書"], ["CRM.history","History","ประวัติ","履歴"],
 ["CRM.name","Opportunity name","ชื่อโอกาสทางการขาย","商談名"], ["CRM.customerId","Customer","ลูกค้า","顧客"],
 ["CRM.siteId","Site","สถานที่","拠点"], ["CRM.contactId","Contact","ผู้ติดต่อ","連絡先"],
 ["CRM.salesOwnerId","Sales owner","ผู้รับผิดชอบงานขาย","営業担当者"], ["CRM.technicalOwnerId","Technical owner","ผู้รับผิดชอบเทคนิค","技術担当者"],
 ["CRM.source","Source","แหล่งที่มา","情報源"], ["CRM.need","Customer need / Summary","ความต้องการลูกค้า / สรุป","顧客ニーズ・概要"],
 ["CRM.scope","Scope","ขอบเขตงาน","作業範囲"], ["CRM.expectedValue","Expected value (THB)","มูลค่าคาดการณ์ (บาท)","想定金額 (THB)"],
 ["CRM.expectedClose","Expected close","วันที่คาดว่าจะปิดงาน","受注予定日"], ["CRM.stage","Stage","ขั้นตอน","ステージ"],
 ["CRM.probability","Probability (%)","โอกาสชนะ (%)","受注確率 (%)"], ["CRM.competitor","Competitor","คู่แข่ง","競合"],
 ["CRM.priority","Priority","ความสำคัญ","優先度"], ["CRM.lostReason","Lost reason","เหตุผลที่แพ้งาน","失注理由"],
 ["CRM.lostDetail","Lost reason details","รายละเอียดเหตุผลที่แพ้งาน","失注理由の詳細"], ["CRM.internalNote","Internal note","บันทึกภายใน","社内メモ"],
 ["CRM.followups","Next actions / Follow-up","สิ่งที่ต้องทำ / ติดตาม","次のアクション・フォローアップ"],
 ["CRM.addAction","Add next action","เพิ่มสิ่งที่ต้องทำ","次のアクションを追加"], ["CRM.action","Next action","สิ่งที่ต้องทำถัดไป","次のアクション"],
 ["CRM.ownerId","Owner","ผู้รับผิดชอบ","担当者"], ["CRM.dueDate","Due date","กำหนดเสร็จ","期限"], ["CRM.status","Status","สถานะ","状態"],
 ["CRM.addActivity","Log activity","บันทึกกิจกรรม","活動を記録"], ["CRM.activityType","Activity type","ประเภทกิจกรรม","活動種別"],
 ["CRM.occurredAt","Date / time","วันที่ / เวลา","日時"], ["CRM.participants","Participants","ผู้เข้าร่วม","参加者"],
 ["CRM.summary","Summary","สรุป","概要"], ["CRM.decision","Key decision","ข้อสรุปสำคัญ","主な決定"], ["CRM.actionItems","Action items","รายการดำเนินการ","対応事項"],
 ["CRM.convert","Create inquiry","สร้าง Inquiry","引合を作成"], ["CRM.projectType","Project type","ประเภทโครงการ","案件種別"],
 ["CRM.estimateOwnerId","Engineer","วิศวกร","エンジニア"], ["CRM.sourceOpportunity","Source opportunity","โอกาสขายต้นทาง","元の商談"],
 ["CRM.attention","Attention","งานที่ต้องติดตาม","要対応"], ["CRM.open","Open opportunities","โอกาสขายที่ยังเปิด","進行中の商談"],
 ["CRM.NoNextAction","No next action","ยังไม่มีสิ่งที่ต้องทำถัดไป","次のアクション未設定"], ["CRM.NoActivity","No activity","ยังไม่มีกิจกรรม","活動なし"],
 ["CRM.Overdue","Overdue","เกินกำหนด","期限超過"], ["CRM.DueToday","Due today","ครบกำหนดวันนี้","本日期限"],
 ["CRM.DueSoon","Due soon","ใกล้ครบกำหนด","期限間近"], ["CRM.Scheduled","Scheduled","นัดหมายแล้ว","予定済み"],
 ["CRM.NeedsFollowup","Needs follow-up","ควรติดตาม","フォローアップが必要"], ["CRM.EstimateDueSoon","Estimate due soon","Estimate ใกล้ครบกำหนด","見積期限間近"],
 ["CRM.WaitingCustomer","Waiting customer","รอลูกค้า","顧客待ち"], ["CRM.WaitingInternal","Waiting internal","รอภายใน","社内待ち"],
 ["CRM.WaitingSupplier","Waiting supplier","รอผู้ขาย","仕入先待ち"], ["CRM.Open","Open","เปิด","未完了"], ["CRM.Done","Done","เสร็จแล้ว","完了"], ["CRM.Cancelled","Cancelled","ยกเลิก","キャンセル"],
 ["CRM.Meeting","Meeting","ประชุม","会議"], ["CRM.Call","Call","โทรศัพท์","電話"], ["CRM.Email","Email","อีเมล","メール"],
 ["CRM.SiteVisit","Site visit","เข้าหน้างาน","現地訪問"], ["CRM.CustomerUpdate","Customer update","ข้อมูลจากลูกค้า","顧客情報更新"],
 ["CRM.InternalDiscussion","Internal discussion","หารือภายใน","社内協議"], ["CRM.MessageLINE","Message / LINE","ข้อความ / LINE","メッセージ・LINE"],
 ["CRM.Note","Note","บันทึก","メモ"], ["CRM.Other","Other","อื่นๆ","その他"],
 ["CRM.newCustomer","New customer","เพิ่มลูกค้า","顧客を追加"], ["CRM.newContact","New contact","เพิ่มผู้ติดต่อ","連絡先を追加"], ["CRM.newSite","Add site","เพิ่มสถานที่","拠点を追加"],
 ["CRM.companyName","Company name","ชื่อบริษัท","会社名"], ["CRM.contactName","Contact name","ชื่อผู้ติดต่อ","担当者名"],
 ["CRM.shortName","Short name","ชื่อย่อ","略称"], ["CRM.code","Code","รหัส","コード"], ["CRM.industry","Industry","อุตสาหกรรม","業種"],
 ["CRM.country","Country","ประเทศ","国"], ["CRM.website","Website","เว็บไซต์","ウェブサイト"], ["CRM.site","Address","ที่อยู่","住所"],
 ["CRM.accountOwnerId","Account owner","ผู้ดูแลลูกค้า","顧客担当者"], ["CRM.email","Email","อีเมล","メール"], ["CRM.phone","Phone","โทรศัพท์","電話番号"],
 ["CRM.department","Department","แผนก","部署"], ["CRM.position","Position","ตำแหน่ง","役職"], ["CRM.contactRole","Contact role","บทบาทผู้ติดต่อ","連絡先の役割"],
 ["CRM.messagingAddress","LINE / Messaging","LINE / ช่องทางข้อความ","LINE・メッセージ先"], ["CRM.note","Note","หมายเหตุ","備考"],
 ["CRM.isActive","Active","ใช้งาน","有効"], ["CRM.sites","Sites","สถานที่","拠点"], ["CRM.siteName","Site name","ชื่อสถานที่","拠点名"],
 ["CRM.address","Address","ที่อยู่","住所"], ["CRM.province","Province / Region","จังหวัด / ภูมิภาค","都道府県・地域"], ["CRM.accessNote","Site note","หมายเหตุสถานที่","拠点メモ"],
 ["CRM.opportunities","Opportunities","โอกาสขาย","商談"], ["CRM.inquiries","Inquiries","งานสอบถามราคา","引合"], ["CRM.estimates","Estimates","ประมาณการต้นทุน","見積"],
 ["CRM.projects","Projects","โครงการ","案件"], ["CRM.service","Service","งานบริการ","サービス"],
 ["CRM.serviceUnavailable","No service history source is configured in this application.","ระบบนี้ยังไม่มีแหล่งประวัติงานบริการที่เชื่อมต่อ","このシステムにはサービス履歴の連携元が設定されていません。"],
 ["CRM.year","Year","ปี","年"], ["CRM.lastActivity","Last activity","กิจกรรมล่าสุด","最終活動"],
 ["CRM.upload","Upload document","เพิ่มเอกสาร","文書をアップロード"], ["CRM.configuration","CRM configuration","ตั้งค่า CRM","CRM 設定"],
 ["CRM.kind","Option type","ประเภทตัวเลือก","選択肢の種別"], ["CRM.labelTh","Thai label","ชื่อภาษาไทย","タイ語ラベル"], ["CRM.labelEn","English label","ชื่อภาษาอังกฤษ","英語ラベル"], ["CRM.labelJa","Japanese label","ชื่อภาษาญี่ปุ่น","日本語ラベル"],
 ["CRM.quietDays","Days without activity","จำนวนวันที่ไม่มีกิจกรรม","活動なしの日数"], ["CRM.optionalDetails","Additional details (optional)","รายละเอียดเพิ่มเติม (ไม่บังคับ)","追加情報（任意）"],
 ["CRM.waitingHint","No next action is a reminder, not a save blocker.","ยังไม่มีสิ่งที่ต้องทำถัดไปเป็นเพียงการเตือน ยังบันทึกได้","次のアクション未設定は警告のみで、保存できます。"],
 ["CRM.permissions","CRM permission is required","ต้องมีสิทธิ์ CRM","CRM の権限が必要です"],
 ["CRM.filesInherited","Related CRM activities and documents remain linked through the source opportunity.","กิจกรรมและเอกสาร CRM อ้างอิงผ่านโอกาสขายต้นทาง","関連する CRM 活動と文書は元の商談を通じて参照できます。"],
 ["CRM.editCustomer","Edit customer","แก้ไขข้อมูลลูกค้า","顧客情報を編集"],
 ["CRM.searchCustomer","Search by customer code or name…","ค้นหาด้วยรหัสหรือชื่อลูกค้า…","顧客コードまたは名称で検索…"], ["CRM.selectFromList","Select a customer from the list","กรุณาเลือกลูกค้าจากรายการ","リストから顧客を選択してください"], ["CRM.showOptions","Show customer list","แสดงรายชื่อลูกค้า","顧客リストを表示"],
 ["CRM.endUserCustomerId","End user (optional)","บริษัทผู้ใช้งานปลายทาง (ไม่บังคับ)","エンドユーザー（任意）"], ["CRM.endUserName","End user","ผู้ใช้งานปลายทาง","エンドユーザー"], ["CRM.searchEndUser","Search end user code or company name…","ค้นหารหัสหรือชื่อบริษัทผู้ใช้งานปลายทาง…","エンドユーザーのコードまたは会社名を検索…"],
 ["CRM.sameCustomer","Same as customer","บริษัทเดียวกับลูกค้า","顧客と同じ"], ["CRM.notSpecified","Not specified","ยังไม่ระบุ","未指定"], ["CRM.endUserHint","Uses the same company master as Estimate Cost and carries forward to Inquiry.","ใช้ข้อมูลบริษัทชุดเดียวกับ Estimate Cost และส่งต่อไปยัง Inquiry","Estimate Cost と同じ会社マスターを使用し、引合へ引き継ぎます。"],
 ["CRM.nameTh","Name (Thai)","ชื่อภาษาไทย","名前（タイ語）"], ["CRM.nameEn","Name (English)","ชื่อภาษาอังกฤษ","名前（英語）"], ["CRM.nameJa","Name (Japanese)","ชื่อภาษาญี่ปุ่น","名前（日本語）"],
 ["CRM.accountOwnerName","Account owner","ผู้ดูแลลูกค้า","顧客担当者"], ["CRM.customerName","Customer","ลูกค้า","顧客"], ["CRM.nextAction","Next action","สิ่งที่ต้องทำถัดไป","次のアクション"], ["CRM.nextDue","Next due","กำหนดครั้งถัดไป","次回期限"],
 ["CRM.salesOwnerName","Sales owner","ผู้รับผิดชอบงานขาย","営業担当者"],
 ["CRM.opportunityNo","Opportunity number","เลขที่โอกาสขาย","商談番号"], ["CRM.inquiryNo","Inquiry number","เลขที่ Inquiry","引合番号"], ["CRM.estimateNo","Estimate number","เลขที่ Estimate","見積番号"], ["CRM.projectNo","Project number","เลขที่โครงการ","案件番号"],
 ["CRM.projectName","Project name","ชื่อโครงการ","案件名"], ["CRM.revision","Revision","ฉบับแก้ไข","改訂"], ["CRM.total","Total (THB)","ยอดรวม (บาท)","合計 (THB)"], ["CRM.targetDelivery","Target delivery","กำหนดส่งมอบ","納入予定日"],
 ["CRM.uploadedByName","Uploaded by","ผู้อัปโหลด","アップロード者"], ["CRM.uploadedAt","Uploaded at","วันที่อัปโหลด","アップロード日時"], ["CRM.sizeBytes","Size (bytes)","ขนาด (ไบต์)","サイズ（バイト）"],
 ["CRM.inquiryId","Related inquiry","Inquiry ที่เกี่ยวข้อง","関連引合"], ["CRM.estimateId","Related estimate","Estimate ที่เกี่ยวข้อง","関連見積"], ["CRM.projectId","Related project","โครงการที่เกี่ยวข้อง","関連案件"],
].map(([key,en,th,jp])=>[key,{en,th,jp}]));
