"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { apiRequest, downloadCrmDocument, uploadCrmDocument, type BootstrapData } from "../api-client";
import { useLanguage, useT } from "../i18n";
import { Modal, Panel } from "../ui";
import { CustomerModal } from "./AdminAnalyticsScreens";
import "./crm.css";
import { CRM_COPY } from "./crm-copy";

export type CrmRecord = Record<string, unknown>;
type Page = {items:CrmRecord[];total:number;page:number;pageSize:number};
type Detail = {opportunity:CrmRecord;activities:CrmRecord[];followups:CrmRecord[];history:CrmRecord[];links:CrmRecord[]};
type CustomerDetail = {service:CrmRecord[];customer:CrmRecord;sites:CrmRecord[];contacts:CrmRecord[];inquiries:CrmRecord[];estimates:CrmRecord[];projects:CrmRecord[]};
export type CrmView = "crm-dashboard"|"crm-customers"|"crm-contacts"|"crm-opportunities"|"crm-activities"|"crm-pipeline";
type Props = {refreshBootstrap?:()=>Promise<void>;bootstrap:BootstrapData;view:CrmView;preferredOpportunityId?:number|null;openInquiry:(id:number)=>void;openEstimate:(id:number)=>void;openProject:(id:number)=>void};
const stages=["NEW","QUALIFICATION","REQUIREMENT","ESTIMATING","PROPOSAL","NEGOTIATION","WON","LOST","ON_HOLD"];
const activityTypes=["Meeting","Call","Email","SiteVisit","CustomerUpdate","InternalDiscussion","MessageLINE","Note","Other"];
const statuses=["Open","WaitingCustomer","WaitingInternal","WaitingSupplier","Done","Cancelled"];
const text=(v:unknown)=>v==null?"":String(v);
const date=(v:unknown)=>text(v).slice(0,10);
const money=(v:unknown)=>v==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"THB",maximumFractionDigits:0}).format(Number(v));
export const crmRequest=<T,>(path:string,method:string,body:unknown)=>apiRequest<T>(path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});

export function useCrmData<T>(url:string|null) {
  const [result,setResult]=useState<{url:string;value:T}|null>(null),[error,setError]=useState(false),[loading,setLoading]=useState(Boolean(url)),[revision,setRevision]=useState(0);
  const refresh=useCallback(()=>setRevision(v=>v+1),[]);
  useEffect(()=>{let cancelled=false;if(!url)return;const timer=setTimeout(()=>{setLoading(true);setError(false);void apiRequest<T>(url).then(v=>{if(!cancelled)setResult({url,value:v});}).catch(()=>{if(!cancelled)setError(true);}).finally(()=>{if(!cancelled)setLoading(false);});},0);return()=>{cancelled=true;clearTimeout(timer);};},[url,revision]);
  return {data:result?.url===url?result.value:null,error,loading,refresh};
}
function Notice({error,loading}:{error?:boolean;loading?:boolean}){const t=useT();return error?<div role="alert" className="alert danger">{t("CRM.error")}</div>:loading?<p role="status">{t("CRM.loading")}</p>:null;}
type Option={value:string;label:string};
type Field={key:string;label?:string;type?:string;options?:Option[];required?:boolean;wide?:boolean;disabled?:boolean};
function Fields({fields,value,set}:{fields:Field[];value:CrmRecord;set:(v:CrmRecord)=>void}) {
  const t=useT();return <div className="crm-form-grid">{fields.map(f=><label key={f.key} className={f.wide?"crm-full":""}><span>{t(f.label??`CRM.${f.key}`)}{f.required?" *":""}</span>{f.type==="checkbox"?<input type="checkbox" checked={value[f.key]!==false} onChange={e=>set({...value,[f.key]:e.target.checked})}/>:f.options?<select disabled={f.disabled} required={f.required} value={text(value[f.key])} onChange={e=>set({...value,[f.key]:f.key.endsWith("Id")&&e.target.value?Number(e.target.value):e.target.value})}><option value="">—</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==="textarea"?<textarea rows={4} value={text(value[f.key])} onChange={e=>set({...value,[f.key]:e.target.value})}/>:<input required={f.required} type={f.type??"text"} min={f.type==="number"?0:undefined} step={f.type==="number"?"any":undefined} value={f.type==="date"?date(value[f.key]):text(value[f.key])} onChange={e=>set({...value,[f.key]:f.type==="number"&&e.target.value!==""?Number(e.target.value):e.target.value})}/>}</label>)}</div>;
}
function Editor({title,initial,fields,onSave,onClose,children}:{title:string;initial:CrmRecord;fields:Field[];onSave:(v:CrmRecord)=>Promise<void>;onClose:()=>void;children?:(v:CrmRecord,set:(v:CrmRecord)=>void)=>ReactNode}) {
  const t=useT(),[value,set]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(false);
  return <Modal size="xl" title={t(title)} onClose={()=>{if(!busy)onClose();}}><form className="crm-editor" onSubmit={e=>{e.preventDefault();if(busy)return;setBusy(true);setError(false);void onSave(value).then(onClose).catch(()=>setError(true)).finally(()=>setBusy(false));}}><Notice error={error}/><Fields fields={fields} value={value} set={set}/>{children?.(value,set)}<div className="crm-toolbar"><button type="button" className="btn default" disabled={busy} onClick={onClose}>{t("Cancel")}</button><button className="btn primary" disabled={busy}>{t("Save")}</button></div></form></Modal>;
}
function Pager({page,onPage}:{page:Page|null;onPage:(v:number)=>void}){const t=useT();if(!page)return null;return <div className="crm-toolbar"><button className="btn default" disabled={page.page<=1} onClick={()=>onPage(page.page-1)}>{t("CRM.previous")}</button><span>{page.page} / {Math.max(1,Math.ceil(page.total/page.pageSize))} · {page.total}</span><button className="btn default" disabled={page.page*page.pageSize>=page.total} onClick={()=>onPage(page.page+1)}>{t("CRM.next")}</button></div>;}
function Records({rows,columns,onOpen}:{rows:CrmRecord[];columns:string[];onOpen?:(r:CrmRecord)=>void}) {
  const t=useT();if(!rows.length)return <p className="crm-empty">{t("CRM.empty")}</p>;return <div className="crm-table-wrap"><table className="crm-table"><thead><tr>{columns.map(c=><th key={c}>{t(c==="name"?"CRM.recordName":c==="title"?"CRM.reportTitle":`CRM.${c}`)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={text(r.id)||i}>{columns.map((c,n)=>{const value=text(r[c]);const tagged=["stage","status","contactRole"].includes(c);return <td key={c}>{n===0&&onOpen?<button className="crm-link" onClick={()=>onOpen(r)}>{value||"—"}</button>:c==="total"||c==="expectedValue"?money(r[c]):tagged&&value?<span className={`crm-tag crm-tag-${value.toLowerCase()}`}>{CRM_COPY[`CRM.${value}`]?t(`CRM.${value}`):value}</span>:CRM_COPY[`CRM.${value}`]?t(`CRM.${value}`):value||"—"}</td>;})}</tr>)}</tbody></table></div>;
}
function MetricStrip({items}:{items:{label:string;value:unknown;tone?:string;hint?:string}[]}){return <div className="crm-metrics">{items.map((item,index)=><article className={`crm-metric ${item.tone??["blue","green","amber","violet","red"][index%5]}`} key={item.label}><div><small>{item.label}</small><strong>{text(item.value)||"0"}</strong>{item.hint?<span>{item.hint}</span>:null}</div><b aria-hidden="true">{index+1}</b></article>)}</div>}
function useOptions(options:CrmRecord[]) {
  const {lang}=useLanguage();return (kind:string)=>options.filter(o=>o.kind===kind&&o.isActive!==false).map(o=>({value:text(o.code),label:text(o[lang==="TH"?"labelTh":lang==="JP"?"labelJa":"labelEn"])}));
}
const teamOptions=(bootstrap:BootstrapData):Option[]=>bootstrap.team.map(u=>({value:String(u.id),label:u.name}));

export function CrmScreen(props:Props) {
  const {bootstrap,view,preferredOpportunityId}=props,t=useT();
  const [opportunityId,setOpportunityId]=useState<number|null>(preferredOpportunityId??null),[customerId,setCustomerId]=useState<number|null>(null),[create,setCreate]=useState(false),[config,setConfig]=useState(false);
  const options=useCrmData<CrmRecord[]>("/api/v1/crm/options");
  useEffect(()=>{const timer=setTimeout(()=>{setOpportunityId(preferredOpportunityId??null);setCustomerId(null);},0);return()=>clearTimeout(timer);},[view,preferredOpportunityId]);
  const write=bootstrap.permissions.includes("crm.write");
  if(!bootstrap.permissions.includes("crm.read"))return <p>{t("CRM.permissions")}</p>;
  const title=opportunityId?"CRM Opportunities":customerId?"CRM Customers":({"crm-dashboard":"CRM Dashboard","crm-customers":"CRM Customers","crm-contacts":"CRM Contacts","crm-opportunities":"CRM Opportunities","crm-activities":"CRM Activities","crm-pipeline":"CRM Pipeline"})[view];
  const descriptions:Record<CrmView,string>={"crm-dashboard":"Overview of sales activities, opportunities and customer engagement.","crm-customers":"Manage customer information, account details and engagement.","crm-contacts":"Manage customer contacts and build stronger relationships.","crm-opportunities":"Manage sales opportunities, progress and next actions.","crm-activities":"Track meetings, calls, emails and follow-ups in one place.","crm-pipeline":"Track opportunities from inquiry through close."};
  const showNew=!opportunityId&&!customerId&&["crm-dashboard","crm-opportunities","crm-pipeline"].includes(view);
  return <div className="crm-workspace"><header className="crm-page-head"><div><small>{t("CRM & SALES")}</small><h2>{t(title)}</h2>{!opportunityId&&!customerId?<p>{descriptions[view]}</p>:null}</div><div className="crm-toolbar">{(opportunityId||customerId)?<button className="btn default" onClick={()=>{setOpportunityId(null);setCustomerId(null);}}>{t("CRM.back")}</button>:null}{write&&showNew?<button className="btn primary" onClick={()=>setCreate(true)}>＋ {t("CRM.new")}</button>:null}{bootstrap.permissions.includes("crm.configure")&&view==="crm-dashboard"?<button className="btn default" onClick={()=>setConfig(true)}>{t("CRM.configuration")}</button>:null}</div></header><Notice error={options.error}/>
    {opportunityId?<OpportunityWorkspace {...props} id={opportunityId} options={options.data??[]} openCustomer={setCustomerId} onCustomer={()=>setOpportunityId(null)}/>:customerId?<CustomerWorkspace {...props} id={customerId} options={options.data??[]} openOpportunity={setOpportunityId}/>:view==="crm-customers"?<CustomerList bootstrap={bootstrap} refreshBootstrap={props.refreshBootstrap} open={setCustomerId}/>:view==="crm-contacts"?<ContactList bootstrap={bootstrap} options={options.data??[]}/>:view==="crm-activities"?<ActivityList bootstrap={bootstrap} options={options.data??[]}/>:<OpportunityList bootstrap={bootstrap} mode={view} options={options.data??[]} open={setOpportunityId}/>}
    {create?<OpportunityEditor bootstrap={bootstrap} options={options.data??[]} onClose={()=>setCreate(false)} onSaved={r=>setOpportunityId(Number(r.id))}/>:null}
    {config?<Configuration options={options.data??[]} onClose={()=>setConfig(false)} refresh={options.refresh}/>:null}
  </div>;
}

function OpportunityList({bootstrap,mode,options,open}:{bootstrap:BootstrapData;mode:CrmView;options:CrmRecord[];open:(id:number)=>void}) {
  const t=useT(),choice=useOptions(options),[search,setSearch]=useState(""),[stage,setStage]=useState(""),[attention,setAttention]=useState(""),[page,setPage]=useState(1),[owner,setOwner]=useState(""),[sort,setSort]=useState("updated");
  const list=useCrmData<Page>(`/api/v1/crm/opportunities?${new URLSearchParams({search,stage,attention,open:mode==="crm-dashboard"?"true":"false",ownerId:owner,page:String(page),pageSize:mode==="crm-opportunities"?"30":"100",sort})}`);
  const dashboard=useCrmData<CrmRecord>("/api/v1/crm/dashboard");
  const rows=list.data?.items??[];
  const label=(s:string)=>choice("stage").find(o=>o.value===s)?.label??s;
  const card=(r:CrmRecord)=><button className="crm-opportunity-card" key={text(r.id)} onClick={()=>open(Number(r.id))}><strong>{text(r.name)}</strong><span className="crm-card-customer">{text(r.customerName)}</span><span>{money(r.expectedValue)}</span><span>{date(r.expectedClose)||"—"}</span><small>{text(r.nextAction)||t("CRM.NoNextAction")} {date(r.nextDue)}</small><div className="crm-flags">{(r.attention as string[]??[]).filter(a=>a!=="Scheduled").map(a=><em key={a}>{t(`CRM.${a}`)}</em>)}</div></button>;
  const metrics=mode==="crm-dashboard"?["open","NeedsFollowup","Overdue","WaitingCustomer","ESTIMATING","PROPOSAL"]:["open","ESTIMATING","PROPOSAL","NEGOTIATION","WON"];
  return <><Notice error={dashboard.error||list.error} loading={list.loading}/><MetricStrip items={metrics.map((k,i)=>({label:stages.includes(k)?label(k):t(`CRM.${k}`),value:dashboard.data?.[k]??0,tone:["blue","amber","red","violet","green","blue"][i]}))}/>
    <div className="crm-filterbar"><input className="crm-search" aria-label={t("CRM.search")} placeholder={t("CRM.search")} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select aria-label={t("CRM.stage")} value={stage} onChange={e=>{setStage(e.target.value);setPage(1);}}><option value="">{t("All")}</option>{choice("stage").map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><select aria-label={t("CRM.ownerId")} value={owner} onChange={e=>{setOwner(e.target.value);setPage(1);}}><option value="">{t("All")}</option>{teamOptions(bootstrap).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><select value={sort} aria-label={t("CRM.sort")} onChange={e=>setSort(e.target.value)}><option value="updated">{t("Last updated")}</option><option value="close">{t("CRM.expectedClose")}</option></select><button className="btn default" onClick={list.refresh}>{t("Refresh")}</button></div>
    {mode==="crm-dashboard"?<div className="crm-quick-filters">{["NoActivity","NoNextAction","EstimateDueSoon"].map(k=><button className="btn default" key={k} onClick={()=>{setAttention(k);setStage("");setPage(1);}}>{t(`CRM.${k}`)}</button>)}</div>:null}
    {attention?<button className="btn default" onClick={()=>setAttention("")}>{t(`CRM.${attention}`)} ×</button>:null}
    {mode==="crm-pipeline"?<div className="crm-pipeline">{stages.filter(s=>!["WON","LOST","ON_HOLD"].includes(s)).map(s=>{const stageRows=rows.filter(r=>r.stage===s);return <section key={s} data-stage={s}><header><h3>{label(s)}</h3><strong>{stageRows.length}</strong></header>{stageRows.map(card)}<button className="crm-pipeline-add">＋ {t("CRM.new")}</button></section>;})}</div>:<><div className="crm-section-head"><div><strong>{list.data?.total??0} {t("CRM Opportunities")}</strong><small>{t("CRM.attention")}</small></div></div><Records rows={rows} columns={["opportunityNo","name","customerName","stage","expectedValue","expectedClose","salesOwnerName","nextAction"]} onOpen={r=>open(Number(r.id))}/></>}
    {mode==="crm-pipeline"&&!rows.length&&!list.loading?<p className="crm-empty">{t("CRM.empty")}</p>:null}<Pager page={list.data} onPage={setPage}/></>;
}

function OpportunityEditor({bootstrap,options,initial,onClose,onSaved}:{bootstrap:BootstrapData;options:CrmRecord[];initial?:CrmRecord;onClose:()=>void;onSaved:(r:CrmRecord)=>void}) {
  const choice=useOptions(options),t=useT();
  const base=initial??{customerId:"",salesOwnerId:bootstrap.user.id,stage:"NEW",source:"DirectInquiry",priority:"Normal"};
  return <Editor title={initial?"Edit":"CRM.new"} initial={base} fields={[]} onClose={onClose} onSave={async v=>{const result=await crmRequest<CrmRecord>(`/api/v1/crm/opportunities${initial?`/${initial.id}`:""}`,initial?"PUT":"POST",v);onSaved(result);}}>{(v,set)=><><OpportunityFields bootstrap={bootstrap} options={options} value={v} set={set}/><details><summary>{t("CRM.optionalDetails")}</summary><Fields fields={[{key:"source",options:choice("source")},{key:"priority",options:["Low","Normal","High","Urgent"].map(s=>({value:s,label:t(s)}))},{key:"probability",type:"number"},{key:"competitor"},{key:"need",type:"textarea",wide:true},{key:"scope",type:"textarea",wide:true},{key:"internalNote",type:"textarea",wide:true}]} value={v} set={set}/></details>{v.stage==="LOST"?<Fields fields={[{key:"lostReason",required:true,options:choice("lostReason")},{key:"lostDetail",required:v.lostReason==="Other",type:"textarea"}]} value={v} set={set}/>:null}<p className="crm-muted">{t("CRM.waitingHint")}</p></>}</Editor>;
}
function OpportunityFields({bootstrap,options,value,set}:{bootstrap:BootstrapData;options:CrmRecord[];value:CrmRecord;set:(v:CrmRecord)=>void}) {
  const choice=useOptions(options),customer=useCrmData<CustomerDetail>(value.customerId?`/api/v1/crm/customers/${value.customerId}`:null);
  const fields:Field[]=[{key:"customerId",required:true,disabled:Boolean(value.id),options:bootstrap.customers.map(c=>({value:String(c.id),label:`${c.code} · ${c.name}`}))},{key:"name",required:true},{key:"siteId",options:(customer.data?.sites??[]).map(r=>({value:text(r.id),label:text(r.name)}))},{key:"contactId",options:(customer.data?.contacts??[]).filter(r=>!value.siteId||String(r.siteId)===String(value.siteId)).map(r=>({value:text(r.id),label:text(r.name)}))},{key:"salesOwnerId",required:true,options:teamOptions(bootstrap)},{key:"technicalOwnerId",options:teamOptions(bootstrap)},{key:"expectedClose",type:"date"},{key:"stage",options:choice("stage"),required:true}];
  if(bootstrap.permissions.includes("crm.commercial.read"))fields.push({key:"expectedValue",type:"number"});
  return <><Notice error={customer.error}/><Fields fields={fields} value={value} set={next=>{if(next.customerId!==value.customerId){next.siteId="";next.contactId="";}else if(next.siteId!==value.siteId)next.contactId="";set(next);}}/></>;
}

function OpportunityWorkspace({id,options,openCustomer,onCustomer,...props}:Props&{id:number;options:CrmRecord[];openCustomer:(id:number)=>void;onCustomer:()=>void}) {
  const t=useT(),choice=useOptions(options),[tab,setTab]=useState("overview"),[editor,setEditor]=useState<string|null>(null),[action,setAction]=useState<CrmRecord|null>(null);
  const state=useCrmData<Detail>(`/api/v1/crm/opportunities/${id}`),o=state.data?.opportunity,bootstrap=props.bootstrap,write=bootstrap.permissions.includes("crm.write");
  const customer=useCrmData<CustomerDetail>(o?.customerId?`/api/v1/crm/customers/${o.customerId}`:null);
  if(!o)return <Notice error={state.error} loading={state.loading}/>;
  const followupFields:Field[]=[{key:"action",required:true,wide:true},{key:"ownerId",required:true,options:teamOptions(bootstrap)},{key:"dueDate",required:true,type:"date"},{key:"priority",options:["Low","Normal","High","Urgent"].map(s=>({value:s,label:t(s)}))},{key:"status",options:statuses.map(s=>({value:s,label:t(`CRM.${s}`)}))}];
  return <><Notice error={state.error}/><Panel className="crm-hero" title={`${text(o.opportunityNo)} · ${text(o.name)}`} actions={<div className="crm-toolbar">{write?<button className="btn primary" onClick={()=>setEditor("opportunity")}>{t("Edit")}</button>:null}{bootstrap.permissions.includes("crm.convert")?<button className="btn default" onClick={()=>setEditor("convert")}>{t("CRM.convert")}</button>:null}<button className="btn default" onClick={()=>{openCustomer(Number(o.customerId));onCustomer();}}>{t("CRM Customers")}</button></div>}><MetricStrip items={[{label:t("CRM.customerId"),value:text(customer.data?.customer.name),tone:"blue"},{label:t("CRM.expectedValue"),value:money(o.expectedValue),tone:"amber"},{label:t("CRM.expectedClose"),value:date(o.expectedClose)||"—",tone:"green"},{label:t("CRM.stage"),value:choice("stage").find(s=>s.value===o.stage)?.label,tone:"violet"}]}/><div className="crm-stagebar">{stages.filter(s=>!["ON_HOLD"].includes(s)).map(s=><span className={s===o.stage?"active":""} key={s}>{choice("stage").find(x=>x.value===s)?.label??s}</span>)}</div></Panel>
    <nav className="crm-tabs">{["overview","contacts","activities","links","documents","history"].map(k=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t(`CRM.${k}`)}</button>)}</nav>
    {tab==="overview"?<><Panel title={t("CRM.overview")}><dl className="crm-details"><div><dt>{t("CRM.customerId")}</dt><dd>{text(customer.data?.customer.name)}</dd></div><div><dt>{t("CRM.salesOwnerId")} / {t("CRM.technicalOwnerId")}</dt><dd>{bootstrap.team.find(u=>u.id===Number(o.salesOwnerId))?.name} / {bootstrap.team.find(u=>u.id===Number(o.technicalOwnerId))?.name||"—"}</dd></div><div><dt>{t("CRM.lastActivity")}</dt><dd>{date(state.data?.activities[0]?.occurredAt)||"—"}</dd></div>{["need","scope","internalNote"].map(k=><div key={k}><dt>{t(`CRM.${k}`)}</dt><dd>{text(o[k])||"—"}</dd></div>)}</dl></Panel><Panel title={t("CRM.followups")} actions={write?<button className="btn primary" onClick={()=>{setAction(null);setEditor("action");}}>{t("CRM.addAction")}</button>:null}>{!(state.data?.followups??[]).some(f=>!["Done","Cancelled"].includes(text(f.status)))?<p className="crm-warning">{t("CRM.NoNextAction")}</p>:null}{state.data?.followups.map(f=><div key={text(f.id)} className="crm-action"><div><strong>{text(f.action)}</strong><p>{text(f.ownerName)} · {date(f.dueDate)} · {t(`CRM.${f.status}`)}</p></div>{write||Number(f.ownerId)===bootstrap.user.id?<button className="btn default" onClick={()=>{setAction(f);setEditor("action");}}>{t("Edit")}</button>:null}</div>)}</Panel></>:null}
    {tab==="contacts"?<ContactList bootstrap={bootstrap} customerId={Number(o.customerId)} options={options}/>:null}
    {tab==="activities"?<><div className="crm-toolbar">{bootstrap.permissions.includes("crm.activity.write")?<button className="btn primary" onClick={()=>setEditor("activity")}>{t("CRM.addActivity")}</button>:null}</div><Timeline bootstrap={bootstrap} rows={state.data?.activities??[]}/></>:null}
    {tab==="links"?<div className="crm-card-grid">{state.data?.links.map((r,i)=><article className="crm-opportunity-card" key={i}><button className="crm-link" onClick={()=>props.openInquiry(Number(r.inquiryId))}>{text(r.inquiryNo)} · {text(r.inquiryStatus)}</button>{r.estimateId&&bootstrap.permissions.includes("estimate.read")?<button className="crm-link" onClick={()=>props.openEstimate(Number(r.estimateId))}>{text(r.estimateNo)} · R{text(r.revision)} · {text(r.estimateStatus)} · {money(r.total)}</button>:null}{r.projectId&&bootstrap.permissions.includes("project.read")?<button className="crm-link" onClick={()=>props.openProject(Number(r.projectId))}>{text(r.projectNo)} · {text(r.projectStatus)}</button>:null}</article>)}</div>:null}
    {tab==="documents"?<CrmDocuments bootstrap={bootstrap} customerId={Number(o.customerId)} opportunityId={id}/>:null}
    {tab==="history"?<div className="crm-timeline">{state.data?.history.map(r=><article key={text(r.id)}><strong>{text(r.action).split(":").map(k=>CRM_COPY[`CRM.${k}`]?t(`CRM.${k}`):k).join(" · ")}</strong><p>{text(r.actorName)} · {text(r.occurredAt)}</p>{r.afterJson?<details><summary>{t("Details")}</summary><pre>{text(r.beforeJson)}{"\n"}{text(r.afterJson)}</pre></details>:null}</article>)}</div>:null}
    {editor==="opportunity"?<OpportunityEditor bootstrap={bootstrap} options={options} initial={o} onClose={()=>setEditor(null)} onSaved={state.refresh}/>:null}
    {editor==="action"?<Editor title="CRM.addAction" initial={action??{ownerId:bootstrap.user.id,priority:"Normal",status:"Open"}} fields={followupFields} onClose={()=>setEditor(null)} onSave={async v=>{await crmRequest(`/api/v1/crm/opportunities/${id}/followups${action?`/${action.id}`:""}`,action?"PUT":"POST",v);state.refresh();}}/>:null}
    {editor==="activity"?<ActivityEditor bootstrap={bootstrap} customerId={Number(o.customerId)} opportunityId={id} onClose={()=>setEditor(null)} onSaved={state.refresh}/>:null}
    {editor==="convert"?<Editor title="CRM.convert" initial={{estimateOwnerId:o.technicalOwnerId??"",projectType:"IoT"}} fields={[{key:"estimateOwnerId",required:true,options:teamOptions(bootstrap)},{key:"projectType",required:true},{key:"dueDate",required:true,type:"date"}]} onClose={()=>setEditor(null)} onSave={async v=>{const result=await crmRequest<{id:number}>("/api/v1/inquiries","POST",{...v,opportunityId:id,opportunityRowVersion:o.rowVersion});state.refresh();props.openInquiry(result.id);}}>{()=> <p>{t("CRM.filesInherited")}</p>}</Editor>:null}
  </>;
}

function Timeline({rows,bootstrap}:{rows:CrmRecord[];bootstrap:BootstrapData}){const {lang}=useLanguage(),t=useT(),[documentActivity,setDocumentActivity]=useState<CrmRecord|null>(null);return <><div className="crm-timeline">{!rows.length?<p>{t("CRM.empty")}</p>:rows.map(r=><article key={text(r.id)}><small>{new Intl.DateTimeFormat(lang==="TH"?"th-TH":lang==="JP"?"ja-JP":"en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(text(r.occurredAt)))} · {t(`CRM.${r.activityType}`)} · {text(r.ownerName)}</small><h3>{text(r.summary)}</h3><p>{text(r.decision)}</p><p>{text(r.actionItems)}</p><small>{text(r.participants)}</small>{r.nextAction?<p>{t("CRM.action")}: {text(r.nextAction)} · {text(r.nextOwnerName)} · {date(r.nextDue)}</p>:null}<button className="btn default" onClick={()=>setDocumentActivity(r)}>{t("CRM.documents")}</button></article>)}</div>{documentActivity?<Modal title={t("CRM.documents")} size="xl" onClose={()=>setDocumentActivity(null)}><div className="crm-editor"><CrmDocuments bootstrap={bootstrap} customerId={Number(documentActivity.customerId)} opportunityId={documentActivity.opportunityId?Number(documentActivity.opportunityId):undefined} activityId={Number(documentActivity.id)}/></div></Modal>:null}</>;}
function ActivityEditor({bootstrap,customerId,opportunityId,onClose,onSaved}:{bootstrap:BootstrapData;customerId?:number;opportunityId?:number;onClose:()=>void;onSaved:()=>void}) {
  const t=useT(),[occurredAt]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));return <Editor title="CRM.addActivity" initial={{customerId:customerId??"",opportunityId,activityType:"Meeting",nextOwnerId:bootstrap.user.id,ownerId:bootstrap.user.id,occurredAt}} fields={[...(!customerId?[{key:"customerId",required:true,options:bootstrap.customers.map(c=>({value:String(c.id),label:c.name}))}]:[]),{key:"activityType",required:true,options:activityTypes.map(s=>({value:s,label:t(`CRM.${s}`)}))},{key:"occurredAt",required:true,type:"datetime-local"},{key:"ownerId",required:true,options:teamOptions(bootstrap)},{key:"participants"},{key:"summary",required:true,wide:true},{key:"decision",type:"textarea"},{key:"actionItems",type:"textarea"}]} onClose={onClose} onSave={async v=>{const next=text(v.action).trim()?{action:v.action,ownerId:v.nextOwnerId,dueDate:v.dueDate}:undefined;await crmRequest("/api/v1/crm/activities","POST",{...v,occurredAt:new Date(text(v.occurredAt)).toISOString(),nextAction:next});onSaved();}}>{(v,set)=><><ActivityReferences value={v} set={set}/>{v.opportunityId?<details><summary>{t("CRM.addAction")}</summary><Fields fields={[{key:"action",wide:true},{key:"nextOwnerId",label:"CRM.ownerId",options:teamOptions(bootstrap)},{key:"dueDate",type:"date"}]} value={v} set={set}/></details>:null}</>}</Editor>;
}
function ActivityReferences({value,set}:{value:CrmRecord;set:(v:CrmRecord)=>void}) {
  const t=useT(),customer=useCrmData<CustomerDetail>(value.customerId?`/api/v1/crm/customers/${value.customerId}`:null),opportunities=useCrmData<Page>(value.customerId?`/api/v1/crm/opportunities?customerId=${value.customerId}&pageSize=100`:null);
  const choose=(rows:CrmRecord[],key:string)=>rows.map(r=>({value:text(r.id),label:text(r[key])}));
  return <details><summary>{t("CRM.links")}</summary><Fields value={value} set={set} fields={[
    {key:"opportunityId",label:"CRM.sourceOpportunity",options:choose(opportunities.data?.items??[],"name")},
    {key:"contactId",options:choose(customer.data?.contacts??[],"name")},
    {key:"inquiryId",options:choose((customer.data?.inquiries??[]).filter(r=>!value.opportunityId||Number(r.opportunityId)===Number(value.opportunityId)),"inquiryNo")},
    {key:"estimateId",options:choose(customer.data?.estimates??[],"estimateNo")},
    {key:"projectId",options:choose(customer.data?.projects??[],"projectNo")},
  ]}/></details>;
}
function ActivityList({bootstrap,customerId,year}:{bootstrap:BootstrapData;customerId?:number;options?:CrmRecord[];year?:string}) {
  const t=useT(),[page,setPage]=useState(1),state=useCrmData<Page>(`/api/v1/crm/activities?${new URLSearchParams({page:String(page),...(customerId?{customerId:String(customerId)}:{}),...(year?{year}:{})})}`),[add,setAdd]=useState(false);
  const rows=state.data?.items??[],count=(type:string)=>rows.filter(r=>r.activityType===type).length;
  return <><div className="crm-list-actions">{bootstrap.permissions.includes("crm.activity.write")?<button className="btn primary" onClick={()=>setAdd(true)}>＋ {t("CRM.addActivity")}</button>:null}</div><Notice error={state.error} loading={state.loading}/><MetricStrip items={[{label:"All activities",value:state.data?.total??0,tone:"blue"},{label:t("CRM.Meeting"),value:count("Meeting"),tone:"blue"},{label:t("CRM.Email"),value:count("Email"),tone:"green"},{label:t("CRM.Call"),value:count("Call"),tone:"violet"},{label:t("CRM.Note"),value:count("Note"),tone:"amber"},{label:t("CRM.SiteVisit"),value:count("SiteVisit"),tone:"red"}]}/><Timeline bootstrap={bootstrap} rows={rows}/><Pager page={state.data} onPage={setPage}/>{add?<ActivityEditor bootstrap={bootstrap} customerId={customerId} onClose={()=>setAdd(false)} onSaved={state.refresh}/>:null}</>;
}

function CustomerList({bootstrap,open,refreshBootstrap}:{bootstrap:BootstrapData;refreshBootstrap?:()=>Promise<void>;open:(id:number)=>void}) {
  const t=useT(),[search,setSearch]=useState(""),[page,setPage]=useState(1),[add,setAdd]=useState(false),state=useCrmData<Page>(`/api/v1/crm/customers?${new URLSearchParams({search,page:String(page)})}`);
  const rows=state.data?.items??[];
  return <><div className="crm-list-actions">{bootstrap.permissions.includes("crm.contact.write")?<button className="btn primary" onClick={()=>setAdd(true)}>＋ {t("CRM.newCustomer")}</button>:null}</div><Notice error={state.error} loading={state.loading}/><MetricStrip items={[{label:"Total customers",value:state.data?.total??0,tone:"blue"},{label:"Shown",value:rows.length,tone:"green"},{label:"With industry",value:rows.filter(r=>r.industry).length,tone:"blue"},{label:"Assigned owner",value:rows.filter(r=>r.accountOwnerName).length,tone:"violet"}]}/><div className="crm-filterbar"><input className="crm-search" aria-label={t("CRM.search")} placeholder={t("CRM.search")} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><button className="btn default" onClick={()=>setSearch("")}>Clear filters</button></div><div className="crm-section-head"><strong>{state.data?.total??0} customers</strong></div><Records rows={rows} columns={["code","name","industry","site","accountOwnerName"]} onOpen={r=>open(Number(r.id))}/><Pager page={state.data} onPage={setPage}/>{add?<CustomerModal customer={null} onClose={()=>setAdd(false)} onSaved={async()=>{setAdd(false);await refreshBootstrap?.();state.refresh();}}/>:null}</>;
}
function CustomerWorkspace({id,options,openOpportunity,...props}:Props&{id:number;options:CrmRecord[];openOpportunity:(id:number)=>void}) {
  const t=useT(),[tab,setTab]=useState("overview"),[year,setYear]=useState(""),[editor,setEditor]=useState<string|null>(null),[siteEdit,setSiteEdit]=useState<CrmRecord|null>(null),state=useCrmData<CustomerDetail>(`/api/v1/crm/customers/${id}${year?`?year=${year}`:""}`),opps=useCrmData<Page>(`/api/v1/crm/opportunities?customerId=${id}&pageSize=100${year?`&year=${year}`:""}`),activities=useCrmData<Page>(`/api/v1/crm/activities?customerId=${id}${year?`&year=${year}`:""}`),customer=state.data?.customer;
  if(!customer)return <Notice error={state.error} loading={state.loading}/>;
  const writable=props.bootstrap.permissions.includes("crm.contact.write");
  return <><Panel className="crm-customer-hero" title={text(customer.name)} actions={writable?<button className="btn primary" onClick={()=>setEditor("customer")}>{t("Edit")}</button>:null}><div className="crm-customer-identity"><span>{text(customer.name).slice(0,2).toUpperCase()}</span><div><strong>{text(customer.code)}</strong><p>{text(customer.accountOwnerName)} · {text(customer.site)}</p></div><label>{t("CRM.year")} <input type="number" min="2000" max="2200" value={year} onChange={e=>setYear(e.target.value)}/></label></div></Panel><Notice error={state.error||opps.error}/><nav className="crm-tabs">{["overview","contacts","activities","opportunities","inquiries","estimates","projects","service","documents"].map(k=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t(`CRM.${k}`)}</button>)}</nav>
    {tab==="overview"?<><div className="crm-summary">{["opportunities","inquiries","estimates","projects"].map(k=><button key={k} onClick={()=>setTab(k)}><span>{t(`CRM.${k}`)}</span><strong>{k==="opportunities"?opps.data?.total??0:state.data?.[k as "inquiries"|"estimates"|"projects"].length??0}</strong></button>)}</div><Panel title={t("CRM.lastActivity")}><p>{text(activities.data?.items?.[0]?.summary)||"—"} · {date(activities.data?.items?.[0]?.occurredAt)}</p></Panel><Panel title={t("CRM.followups")}><Records rows={(opps.data?.items??[]).filter(o=>o.nextAction&&!["WON","LOST","ON_HOLD"].includes(text(o.stage)))} columns={["name","nextAction","nextDue"]} onOpen={r=>openOpportunity(Number(r.id))}/></Panel><Panel title={t("CRM.sites")} actions={writable?<button className="btn default" onClick={()=>{setSiteEdit(null);setEditor("site");}}>{t("CRM.newSite")}</button>:null}><Records rows={state.data?.sites??[]} columns={["name","address","province","country"]} onOpen={writable?r=>{setSiteEdit(r);setEditor("site");}:undefined}/></Panel></>:null}
    {tab==="contacts"?<ContactList bootstrap={props.bootstrap} customerId={id} options={options}/>:null}
    {tab==="activities"?<ActivityList bootstrap={props.bootstrap} customerId={id} year={year}/>:null}
    {tab==="opportunities"?<Records rows={opps.data?.items??[]} columns={["name","opportunityNo","stage","nextAction"]} onOpen={r=>openOpportunity(Number(r.id))}/>:null}
    {tab==="inquiries"?<Records rows={state.data?.inquiries??[]} columns={["inquiryNo","projectName","status","dueDate"]} onOpen={r=>props.openInquiry(Number(r.id))}/>:null}
    {tab==="estimates"?<Records rows={state.data?.estimates??[]} columns={["estimateNo","revision","status","total"]} onOpen={r=>props.openEstimate(Number(r.id))}/>:null}
    {tab==="projects"?<Records rows={state.data?.projects??[]} columns={["projectNo","name","status","targetDelivery"]} onOpen={r=>props.openProject(Number(r.id))}/>:null}
    {tab==="service"?<><p>{t("CRM.serviceHistory")}</p><Records rows={state.data?.service??[]} columns={["reportNo","title","revision","status","reportDate"]} onOpen={r=>r.projectId?props.openProject(Number(r.projectId)):props.openInquiry(Number(r.inquiryId))}/></>:null}
    {tab==="documents"?<CrmDocuments bootstrap={props.bootstrap} customerId={id} year={year}/>:null}
    {editor==="customer"?<Editor title="Edit" initial={{...customer,nameEn:customer.nameEn||(!customer.nameTh&&!customer.nameJa?customer.name:"")}} fields={[{key:"nameTh"},{key:"nameEn"},{key:"nameJa"},{key:"shortName"},{key:"industry"},{key:"country"},{key:"website",type:"url"},{key:"accountOwnerId",options:teamOptions(props.bootstrap)},{key:"site",wide:true},{key:"isActive",type:"checkbox"}]} onClose={()=>setEditor(null)} onSave={async v=>{await crmRequest(`/api/v1/crm/customers/${id}`,"PUT",v);await props.refreshBootstrap?.();state.refresh();}}/>:null}
    {editor==="site"?<Editor title="CRM.newSite" initial={siteEdit??{country:customer.country}} fields={[{key:"code",required:true},{key:"name",label:"CRM.siteName",required:true},{key:"address",wide:true},{key:"province"},{key:"country"},{key:"accessNote",type:"textarea",wide:true}]} onClose={()=>setEditor(null)} onSave={async v=>{await crmRequest(`/api/v1/crm/customers/${id}/sites${siteEdit?`/${siteEdit.id}`:""}`,siteEdit?"PUT":"POST",v);state.refresh();}}/>:null}
  </>;
}

function ContactList({bootstrap,customerId,options}:{bootstrap:BootstrapData;customerId?:number;options:CrmRecord[]}) {
  const t=useT(),[search,setSearch]=useState(""),[page,setPage]=useState(1),[edit,setEdit]=useState<CrmRecord|null>(null);
  const state=useCrmData<Page>(`/api/v1/crm/contacts?${new URLSearchParams({search,page:String(page),...(customerId?{customerId:String(customerId)}:{})})}`),writable=bootstrap.permissions.includes("crm.contact.write");
  const rows=state.data?.items??[];
  return <><div className="crm-list-actions">{writable?<button className="btn primary" onClick={()=>setEdit({customerId:customerId??""})}>＋ {t("CRM.newContact")}</button>:null}</div><MetricStrip items={[{label:"Total contacts",value:state.data?.total??0,tone:"blue"},{label:"Shown",value:rows.length,tone:"blue"},{label:"With email",value:rows.filter(r=>r.email).length,tone:"green"},{label:"With role",value:rows.filter(r=>r.contactRole).length,tone:"violet"}]}/><div className="crm-filterbar"><input className="crm-search" aria-label={t("CRM.search")} placeholder={t("CRM.search")} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><button className="btn default" onClick={()=>setSearch("")}>Clear filters</button></div><Notice error={state.error} loading={state.loading}/><Records rows={rows} columns={["name","customerName","position","department","email","phone","contactRole"]} onOpen={writable?setEdit:undefined}/><Pager page={state.data} onPage={setPage}/>
    {edit?<Editor title={edit.id?"Edit":"CRM.newContact"} initial={{...edit,nameEn:edit.nameEn||(!edit.nameTh&&!edit.nameJa?edit.name:"")}} fields={[{key:"customerId",required:true,options:bootstrap.customers.map(c=>({value:String(c.id),label:c.name}))},{key:"nameTh"},{key:"nameEn"},{key:"nameJa"},{key:"email",type:"email"},{key:"phone"},{key:"department"},{key:"position"}]} onClose={()=>setEdit(null)} onSave={async v=>{await crmRequest(`/api/v1/sales/customers/${v.customerId}/contacts${edit.id?`/${edit.id}`:""}`,edit.id?"PUT":"POST",{...v,siteId:v.siteId||undefined});state.refresh();}}>{(v,set)=><ContactSite customerId={Number(v.customerId)} value={v} set={set}/>}</Editor>:null}
  </>;
}
function ContactSite({customerId,value,set}:{customerId:number;value:CrmRecord;set:(v:CrmRecord)=>void}){const data=useCrmData<CustomerDetail>(customerId?`/api/v1/crm/customers/${customerId}`:null);return value.id?null:<Fields fields={[{key:"siteId",options:(data.data?.sites??[]).map(r=>({value:text(r.id),label:text(r.name)}))}]} value={value} set={set}/>;}

function CrmDocuments({bootstrap,customerId,opportunityId,activityId,year}:{bootstrap:BootstrapData;customerId:number;opportunityId?:number;activityId?:number;year?:string}) {
  const t=useT(),state=useCrmData<CrmRecord[]>(`/api/v1/crm/documents?customerId=${customerId}${opportunityId?`&opportunityId=${opportunityId}`:""}${activityId?`&activityId=${activityId}`:""}${year?`&year=${year}`:""}`),[busy,setBusy]=useState(false),[error,setError]=useState(false);
  const download=async(r:CrmRecord)=>{setError(false);try{const blob=await downloadCrmDocument(Number(r.id)),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=text(r.name);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(true);}};
  return <Panel title={t("CRM.documents")}><Notice error={error||state.error} loading={busy}/>{bootstrap.permissions.includes("crm.activity.write")?<label className="crm-upload">{t("CRM.upload")}<input type="file" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError(false);void uploadCrmDocument(file,customerId,opportunityId,activityId).then(state.refresh).catch(()=>setError(true)).finally(()=>setBusy(false));e.target.value="";}}/></label>:null}<Records rows={state.data??[]} columns={["name","uploadedByName","uploadedAt","sizeBytes"]} onOpen={r=>void download(r)}/></Panel>;
}
function Configuration({options,onClose,refresh}:{options:CrmRecord[];onClose:()=>void;refresh:()=>void}) {
  const t=useT(),[edit,setEdit]=useState<CrmRecord|null>(null);return <Modal size="xl" title={t("CRM.configuration")} onClose={onClose}><div className="crm-editor"><button className="btn primary" onClick={()=>setEdit({kind:"source",isActive:true})}>{t("Add")}</button><Records rows={options} columns={["code","kind","labelEn","quietDays"]} onOpen={setEdit}/>{edit?<Editor title="CRM.configuration" initial={edit} fields={[...(!edit.rowVersion?[{key:"kind",required:true,options:["source","lostReason","contactRole"].map(k=>({value:k,label:t(`CRM.${k}`)}))},{key:"code",required:true}]:[]),{key:"labelTh",required:true},{key:"labelEn",required:true},{key:"labelJa",required:true},...(edit.kind==="stage"?[{key:"quietDays",type:"number"}]:[{key:"isActive",type:"checkbox"}])]} onClose={()=>setEdit(null)} onSave={async v=>{await crmRequest(`/api/v1/crm/options/${v.kind}/${encodeURIComponent(text(v.code))}`,"PUT",v);refresh();}}/>:null}</div></Modal>;
}

export function CrmMyWork({openOpportunity}:{openOpportunity?:(id:number)=>void}) {
  const t=useT(),state=useCrmData<{actions:CrmRecord[];attention:CrmRecord[]}>("/api/v1/crm/my-work"),[error,setError]=useState(false),[busy,setBusy]=useState(false);
  return <Panel title={t("CRM.followups")}><Notice error={state.error||error} loading={state.loading}/>{!state.data?.actions.length&&!state.data?.attention.length?<p>{t("CRM.empty")}</p>:null}{state.data?.actions.map(r=><div className="crm-action" key={text(r.id)}><div><button className="crm-link" onClick={()=>openOpportunity?.(Number(r.opportunityId))}>{text(r.action)}</button><p>{text(r.opportunityName)} · {date(r.dueDate)} · {t(`CRM.${r.status}`)}</p></div><button className="btn default" disabled={busy} onClick={()=>{setBusy(true);setError(false);void crmRequest(`/api/v1/crm/opportunities/${r.opportunityId}/followups/${r.id}`,"PUT",{rowVersion:r.rowVersion,status:"Done"}).then(state.refresh).catch(()=>setError(true)).finally(()=>setBusy(false));}}>{t("CRM.Done")}</button></div>)}{state.data?.attention.map(r=><div className="crm-action" key={`attention-${r.id}`}><button className="crm-link" onClick={()=>openOpportunity?.(Number(r.id))}>{text(r.name)}</button><span>{(r.attention as string[]).map(a=>t(`CRM.${a}`)).join(" · ")}</span></div>)}</Panel>;
}

export function CrmInquirySource({inquiryId,enabled}:{inquiryId:number;enabled:boolean}) {
  const t=useT(),state=useCrmData<CrmRecord>(enabled?`/api/v1/crm/inquiries/${inquiryId}/source`:null);
  return state.data?<div className="alert info"><a href={`#crm/${state.data.id}`}>{t("CRM.sourceOpportunity")}: {text(state.data.opportunityNo)} · {text(state.data.name)}</a><p>{text(state.data.salesOwnerName)} · {text(state.data.technicalOwnerName)}</p><small>{t("CRM.filesInherited")}</small></div>:null;
}
