"use client";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { apiRequest, type BootstrapData } from "../api-client";
import { useLanguage } from "../i18n";
import { Badge, EmptyState, Icon, Modal, Panel, type Tone } from "../ui";
import { projectHealth, overdueTask, shiftDay, type DashboardLink, type ExecutiveData, type ExecutiveAction } from "../../../backend-node/src/executive-dashboard-model";
import { periodRange, within, teamWorkload, projectManagerOptions } from "./executive-metrics";
import "./executive-dashboard.css";

type DetailRow={key:string;title:string;description:string;status?:string;value?:string;destination?:DashboardLink;entityId?:number};
type Props={bootstrap:BootstrapData;personal:ReactNode;onOpen:(destination:DashboardLink,id?:number)=>void};
const PERMISSIONS:Record<DashboardLink,string>={projects:"project.read",inquiries:"inquiry.read",estimates:"estimate.read",resources:"schedule.read",purchase:"procurement.read",pos:"procurement.read",receiving:"inventory.read",signing:"signing.read",reports:"report.read"};
const healthTone:Record<string,Tone>={healthy:"green",watch:"amber",critical:"red",unknown:"slate",closed:"blue"};
export function ExecutiveDashboard({bootstrap,personal,onOpen}:Props) {
  const {lang}=useLanguage();
  const tr=(en:string,th:string,jp:string)=>lang==="TH"?th:lang==="JP"?jp:en;
  const [view,setView]=useState("management");
  const [data,setData]=useState<ExecutiveData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
  const [period,setPeriod]=useState("month"),[department,setDepartment]=useState(""),[manager,setManager]=useState(""),[customer,setCustomer]=useState(""),[project,setProject]=useState("");
  const [health,setHealth]=useState("all"),[weeks,setWeeks]=useState(4);
  const [detail,setDetail]=useState<{title:string;rows:DetailRow[]}|null>(null);
  const [search,setSearch]=useState("");
  useEffect(()=>{const controller=new AbortController();
    void apiRequest<ExecutiveData>("/api/v1/dashboard/management",{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setData(result);setError("");}}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Unable to load dashboard");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();
  },[revision,bootstrap.user.id]);
  const reload=()=>{setLoading(true);setRevision(v=>v+1);};
  const selected=useMemo(()=>{
    if(!data)return null;
    const projects=data.projects.filter(p=>(!department||p.department===department)&&(!manager||p.managerId===Number(manager))&&(!customer||p.customerId===Number(customer))&&(!project||p.id===Number(project)));
    const linked=new Set(projects.map(p=>p.inquiryId));
    const inquiries=data.inquiries.filter(i=>(!customer||i.customerId===Number(customer))&&((manager||project)?linked.has(i.id):!department||i.department===department||linked.has(i.id)));
    const inquiryIds=new Set(inquiries.map(i=>i.id)),projectIds=new Set(projects.map(p=>p.id));
    const estimates=data.estimates.filter(e=>inquiryIds.has(e.inquiryId));
    const tasks=data.tasks.filter(t=>t.projectId?projectIds.has(t.projectId):inquiryIds.has(t.inquiryId!));
    return {projects,inquiries,estimates,tasks,procurement:data.procurement.filter(p=>projectIds.has(p.projectId)),projectIds,inquiryIds};
  },[data,department,manager,customer,project]);
  const format=new Intl.NumberFormat(lang==="TH"?"th-TH":lang==="JP"?"ja-JP":"en-GB",{maximumFractionDigits:1});
  const number=(n:number)=>format.format(n);
  const money=(n:number|null)=>n===null?"—":`${number(n)} THB`;
  const date=(s:string|null)=>s?new Intl.DateTimeFormat(lang==="TH"?"th-TH":lang==="JP"?"ja-JP":"en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(s.slice(0,10)+"T00:00:00Z")):"—";
  const healthName=(h:string)=>({healthy:tr("On track","ตามแผน","計画通り"),watch:tr("Watch","เฝ้าระวัง","要注意"),critical:tr("Critical","เร่งแก้ไข","重大"),unknown:tr("Incomplete plan","แผนไม่ครบ","計画不足"),closed:tr("Closed","ปิดแล้ว","完了")}[h]??h);
  const openDetail=(title:string,rows:DetailRow[])=>{setSearch("");setDetail({title,rows});};
  const canOpen=(destination:DashboardLink)=>bootstrap.permissions.includes(PERMISSIONS[destination])&&(!(data?.mode==="executive"&&bootstrap.user.role!=="Admin")||!["projects","resources","purchase","pos","reports"].includes(destination));
  const tabs=<div className="exec-view-tabs" role="group" aria-label={tr("Dashboard view","มุมมอง Dashboard","表示切替")}>
    <button type="button" className={view==="management"?"active":""} aria-pressed={view==="management"} onClick={()=>setView("management")}><Icon name="chart" />{tr("Management overview","ภาพรวมผู้บริหาร","経営概要")}</button>
    <button type="button" className={view==="personal"?"active":""} aria-pressed={view==="personal"} onClick={()=>setView("personal")}><Icon name="user" />{tr("My dashboard","Dashboard ของฉัน","個人ダッシュボード")}</button>
  </div>;
  if(view==="personal")return <>{tabs}{personal}</>;
  if(!data||!selected)return <div className="exec-dashboard">{tabs}{error?<div role="alert" className="exec-error">{error}<button type="button" className="btn default" onClick={reload}>{tr("Try again","ลองใหม่","再試行")}</button></div>:<div className="exec-loading" role="status"><span className="spinner" />{tr("Preparing management overview…","กำลังโหลดภาพรวมผู้บริหาร…","経営概要を読み込み中…")}</div>}</div>;
  const {projects,inquiries,estimates,tasks,procurement}=selected;
  const range=periodRange(data.today,period),activeProjects=projects.filter(p=>p.status!=="Closed");
  const cohort=inquiries.filter(i=>within(i.date,range.start,range.end)),previous=inquiries.filter(i=>within(i.date,range.previousStart,range.previousEnd));
  const estimatedIds=new Set(estimates.map(e=>e.inquiryId)),approvedIds=new Set(estimates.filter(e=>["Approved","Locked"].includes(e.status)).map(e=>e.inquiryId)),convertedIds=new Set(projects.map(p=>p.inquiryId));
  const converted=cohort.filter(i=>convertedIds.has(i.id));
  const done=tasks.filter(t=>t.status==="Done"&&within(t.completed,range.start,range.end)),oldDone=tasks.filter(t=>t.status==="Done"&&within(t.completed,range.previousStart,range.previousEnd));
  const late=tasks.filter(t=>overdueTask(t,data.today)&&(!t.projectId||activeProjects.some(p=>p.id===t.projectId)));
  const risky=activeProjects.filter(p=>["watch","critical"].includes(projectHealth(p,procurement,data.today))).sort((a,b)=>Number(projectHealth(b,procurement,data.today)==="critical")-Number(projectHealth(a,procurement,data.today)==="critical"));
  const prs=procurement.filter(p=>p.kind==="PR"&&["Draft","In Approval","Approved"].includes(p.status));
  const pos=procurement.filter(p=>p.kind==="PO"&&["Ordered","Partially Received","Received"].includes(p.status));
  const receipts=procurement.filter(p=>p.kind==="GRN"&&p.status==="Confirmed");
  const next30=shiftDay(data.today,30),monday=periodRange(data.today,"week").start;
  const workload=teamWorkload(data,tasks.filter(t=>!t.projectId||activeProjects.some(p=>p.id===t.projectId)),selected.inquiryIds,new Set(estimates.map(e=>e.id)),monday,weeks)
    .filter(p=>(!department||p.department===department)&&(!(project||manager||customer)||p.weeks.some(w=>w.assigned>0)||p.unknown>0))
    .sort((a,b)=>Number(b.weeks.some(w=>w.overloaded))-Number(a.weeks.some(w=>w.overloaded))||b.unknown-a.unknown||a.name.localeCompare(b.name));
  const actions:ExecutiveAction[]=[...data.actions.filter(a=>a.projectId?selected.projectIds.has(a.projectId):a.inquiryId?selected.inquiryIds.has(a.inquiryId):!department&&!manager&&!customer&&!project),
    ...prs.filter(p=>p.waitingMe).map(p=>({key:`PR-${p.id}`,number:p.number,name:projects.find(x=>x.id===p.projectId)?.name??"",owner:p.owner,kind:"PR approval",destination:"purchase" as const,projectId:p.projectId,inquiryId:null,due:p.due,since:p.date,amount:p.value})),
    ...(bootstrap.permissions.includes("estimate.approve")?estimates.filter(e=>e.status==="Engineering Review").map(e=>({key:`EST-${e.id}`,number:e.number,name:e.name,owner:e.owner,kind:"Estimate review",destination:"estimates" as const,projectId:null,inquiryId:e.inquiryId,due:e.due,since:null,amount:e.cost})):[])].sort((a,b)=>(a.due??"9999").localeCompare(b.due??"9999")||(a.since??"9999").localeCompare(b.since??"9999"));
  const projectRows=(items=projects):DetailRow[]=>items.map(p=>({key:`P-${p.id}`,title:p.number+" · "+p.name,description:`${p.customer} · ${p.manager} · ${date(p.due)}`,status:healthName(projectHealth(p,procurement,data.today)),value:money(p.budget),destination:"projects",entityId:p.id}));
  const inquiryRows=(items=inquiries):DetailRow[]=>items.map(i=>({key:`I-${i.id}`,title:i.number+" · "+i.name,description:`${i.customer} · ${i.owner} · ${date(i.due)}`,status:i.status,destination:"inquiries",entityId:i.id}));
  const estimateRows=(items=estimates):DetailRow[]=>items.map(e=>({key:`E-${e.id}`,title:e.number+" · "+e.name,description:`${e.owner} · ${date(e.due)}`,status:e.status,value:money(e.cost),destination:"estimates",entityId:e.id}));
  const taskRows=(items=tasks):DetailRow[]=>items.map(t=>({key:`T-${t.id}`,title:t.name,description:`${projects.find(p=>p.id===t.projectId)?.number??inquiries.find(i=>i.id===t.inquiryId)?.number??""} · ${date(t.completed??t.baselineDue??t.due)}`,status:t.status,value:`${number(t.progress)}%`,destination:t.projectId?"projects":"resources",...(t.projectId?{entityId:t.projectId}:{})}));
  const procurementRows=(items=procurement):DetailRow[]=>items.map(p=>({key:`${p.kind}-${p.id}`,title:p.number,description:`${projects.find(x=>x.id===p.projectId)?.number??""} · ${p.supplier||p.owner} · ${date(p.due??p.date)}${p.kind==="PO"?` · ${tr("Outstanding","ค้างรับ","未入荷")}: ${money(p.openValue)}`:""}`,status:p.status,value:money(p.value),destination:p.kind==="PR"?"purchase":p.kind==="PO"?"pos":"receiving"}));
  const capacityRows=(personId:number,start:string):DetailRow[]=>{
    const end=shiftDay(start,6);
    const overlaps=(from:string|null,to:string|null)=>!from||!to||(from<=end&&to>=start);
    const effortRows:DetailRow[]=data.efforts.filter(e=>e.ownerId===personId&&(e.kind==="Inquiry"?selected.inquiryIds.has(e.id):estimates.some(x=>x.id===e.id))&&overlaps(e.start,e.end)).map((e,i)=>({key:`EFF-${e.kind}-${e.id}-${i}`,title:e.kind==="Inquiry"?inquiries.find(x=>x.id===e.id)?.number??String(e.id):estimates.find(x=>x.id===e.id)?.number??String(e.id),description:`${date(e.start)} – ${date(e.end)}`,value:e.manDays===null?tr("Effort not set","ยังไม่ระบุแรงงาน","工数未設定"):`${number(e.manDays)} man-days`,destination:e.kind==="Inquiry"?"inquiries":"estimates",entityId:e.id}));
    return [...taskRows(tasks.filter(t=>t.status!=="Done"&&t.owners.includes(personId)&&overlaps(t.start,t.due))),...effortRows];
  };
  const actionRows:DetailRow[]=actions.map(a=>({key:a.key,title:`${a.number} · ${a.name}`,description:`${a.owner} · ${date(a.due)}${a.since?` · ${Math.max(0,Math.floor((Date.parse(data.today)-Date.parse(a.since))/86400000))} ${tr("days waiting","วันที่รอ","日待ち")}`:""}`,status:a.kind,value:a.amount===null?"":money(a.amount),destination:a.destination,...(a.destination==="estimates"?{entityId:Number(a.key.slice(4))}:{})}));
  const upcoming=tasks.filter(t=>t.milestone&&t.status!=="Done"&&within(t.forecast??t.due,data.today,next30)).sort((a,b)=>(a.forecast??a.due??"").localeCompare(b.forecast??b.due??""));
  const materialRisks=procurement.filter(p=>p.status!=="Cancelled"&&((p.kind==="PO"&&p.status!=="Draft"&&p.openValue>0&&p.due!==null&&p.due<data.today)||(p.kind==="GRN"&&(p.held>0||p.status==="Draft"))));
  const riskRows=[...projectRows(risky),...procurementRows(materialRisks),...taskRows(late)];
  const delta=(value:number,old:number)=>`${value-old>=0?"+":""}${number(value-old)} ${tr("vs previous equal period","เทียบช่วงก่อนหน้าเท่ากัน","前同期間比")}`;
  const snapshot=tr("Current snapshot","สถานะปัจจุบัน","現在の状態");
  const cards=[
    {label:tr("New inquiries","Inquiry ใหม่","新規引合"),value:cohort.length,note:delta(cohort.length,previous.length),rows:inquiryRows(cohort),tone:"blue"},
    {label:tr("Active projects","โครงการที่ดำเนินการ","進行中案件"),value:activeProjects.length,note:snapshot,rows:projectRows(activeProjects),tone:"blue"},
    {label:tr("Projects at risk","โครงการเสี่ยง","リスク案件"),value:risky.length,note:tr("Schedule & material signals","จากแผนงานและวัสดุ","工程・資材状況"),rows:projectRows(risky),tone:"red"},
    {label:tr("Overdue tasks","งานเลยกำหนด","期限超過タスク"),value:late.length,note:tr("Baseline, or current plan","เทียบ Baseline หรือแผนปัจจุบัน","基準計画または現行計画"),rows:taskRows(late),tone:"amber"},
    {label:tr("Completed work","งานที่ทำเสร็จ","完了作業"),value:done.length,note:delta(done.length,oldDone.length),rows:taskRows(done),tone:"green"},
    {label:tr("My decisions","รอการตัดสินใจของฉัน","自分の承認待ち"),value:actions.length,note:snapshot,rows:actionRows,tone:"violet"},
  ];
  const flow=[{name:"Inquiry",items:cohort},{name:tr("Has estimate","มี Estimate","見積あり"),items:cohort.filter(i=>estimatedIds.has(i.id))},{name:tr("Cost approved","อนุมัติต้นทุนแล้ว","原価承認済み"),items:cohort.filter(i=>approvedIds.has(i.id))},{name:"Project",items:converted}];
  return <div className="exec-dashboard">{tabs}
    <header className="exec-header"><div><span className="exec-eyebrow">{data.mode==="executive"?"EXECUTIVE OVERVIEW":"TEAM OPERATIONS"}</span><h1>{data.mode==="executive"?tr("Business at a glance","ภาพรวมธุรกิจ","経営ダッシュボード"):tr("Your team, in focus","ภาพรวมทีมของคุณ","チームダッシュボード")}</h1><p>{bootstrap.user.name} · {data.scope} · {tr("Updated","อัปเดต","更新")} {new Date(data.asOf).toLocaleString(lang==="TH"?"th-TH":lang==="JP"?"ja-JP":"en-GB")}</p></div><button type="button" className="btn default" disabled={loading} onClick={reload}><Icon name="refresh" />{loading?tr("Updating…","กำลังอัปเดต…","更新中…"):tr("Refresh","รีเฟรช","更新")}</button></header>
    {error?<div role="alert" className="exec-error">{tr("Refresh failed. Showing the last successful data.","อัปเดตไม่สำเร็จ กำลังแสดงข้อมูลที่โหลดสำเร็จครั้งล่าสุด","更新失敗。前回のデータを表示中。")}: {error}</div>:null}
    <div className="exec-filters">
      <label>{tr("Reporting period","ช่วงรายงาน","集計期間")}<select value={period} onChange={e=>setPeriod(e.target.value)}>{[["today",tr("Today","วันนี้","本日")],["week",tr("Week to date","สัปดาห์นี้ถึงวันนี้","今週累計")],["month",tr("Month to date","เดือนนี้ถึงวันนี้","今月累計")],["quarter",tr("Quarter to date","ไตรมาสนี้ถึงวันนี้","今四半期累計")]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
      <label>{tr("Department","แผนก","部署")}<select value={department} onChange={e=>{setDepartment(e.target.value);setProject("");setManager("");}}><option value="">{tr("All permitted","ทั้งหมดที่มีสิทธิ์","許可範囲すべて")}</option>{[...new Set([...data.projects.map(p=>p.department),...data.inquiries.map(i=>i.department),...data.team.map(p=>p.department),...(data.projectManagers??[]).map(p=>p.department)])].sort().map(v=><option key={v}>{v}</option>)}</select></label>
      <label>{tr("Project manager","ผู้จัดการโครงการ","案件管理者")}<select value={manager} onChange={e=>{setManager(e.target.value);setProject("");}}><option value="">{tr("All managers","ทุกคน","すべて")}</option>{projectManagerOptions(data,department).map(({id,name})=><option key={id} value={id}>{name}</option>)}</select></label>
      <label>{tr("Customer","ลูกค้า","顧客")}<select value={customer} onChange={e=>{setCustomer(e.target.value);setProject("");}}><option value="">{tr("All customers","ทุกลูกค้า","すべて")}</option>{[...new Map([...data.projects,...data.inquiries].map(p=>[p.customerId,p.customer])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
      <label>{tr("Project","โครงการ","案件")}<select value={project} onChange={e=>setProject(e.target.value)}><option value="">{tr("All projects","ทุกโครงการ","すべて")}</option>{data.projects.filter(p=>(!department||p.department===department)&&(!manager||p.managerId===Number(manager))&&(!customer||p.customerId===Number(customer))).map(p=><option key={p.id} value={p.id}>{p.number} · {p.name}</option>)}</select></label>
    </div>
    <p className="exec-context">{date(range.start)} – {date(range.end)} · {tr("Period applies to new inquiries, conversion and completed work. Open work shows current status.","ช่วงรายงานใช้กับ Inquiry ใหม่ Conversion และงานเสร็จ ส่วนงานเปิดแสดงสถานะปัจจุบัน","期間は新規引合・転換・完了作業に適用。未完了は現在の状態です。")}</p>
    <section className="exec-kpis" aria-label={tr("Key indicators","ตัวชี้วัดหลัก","主要指標")}>{cards.map(c=><button type="button" className={`exec-kpi ${c.tone}`} key={c.label} onClick={()=>openDetail(c.label,c.rows)}><span>{c.label}</span><strong>{number(c.value)}</strong><small>{c.note}</small><Icon name="arrowRight" /></button>)}</section>
    <Panel title={tr("Decisions that need you","รายการที่ต้องตัดสินใจ","対応が必要な承認")} subtitle={tr("Ordered by due date. Open the document to review and act.","เรียงตามกำหนด เปิดเอกสารเพื่อตรวจสอบและดำเนินการ","期限順。文書を開いて確認してください。")} actions={<button type="button" className="link-btn" onClick={()=>openDetail(tr("My decisions","รอการตัดสินใจของฉัน","自分の承認待ち"),actionRows)}>{tr("View all","ดูทั้งหมด","すべて表示")} ({actions.length})</button>}>
      <div className="exec-decisions">{actionRows.slice(0,4).map(a=><button key={a.key} type="button" onClick={()=>openDetail(a.title,[a])}><Badge tone="amber">{a.status}</Badge><strong>{a.title}</strong><span>{a.description}</span><b>{a.value}</b></button>)}{!actions.length?<p className="exec-empty">{tr("No decisions waiting for you in this scope.","ไม่มีรายการรอคุณตัดสินใจในขอบเขตนี้","この範囲に承認待ちはありません。")}</p>:null}</div>
    </Panel>
    <div className="exec-two-col">
      <Panel title={tr("Inquiry → Project","Inquiry → Project","引合 → 案件")} subtitle={tr("Same inquiry cohort • counts are distinct inquiries","ติดตาม Inquiry กลุ่มเดียวกัน • นับไม่ซ้ำ","同一期間の引合を重複せず集計")}>
        <div className="exec-funnel">{flow.map((f,i)=><button type="button" key={f.name} onClick={()=>openDetail(f.name,inquiryRows(f.items))}><span><small>0{i+1}</small>{f.name}</span><b>{number(f.items.length)}</b><span className="exec-track"><i style={{width:`${cohort.length?f.items.length/cohort.length*100:0}%`}} /></span></button>)}</div>
        <div className="exec-conversion"><strong>{cohort.length?number(converted.length/cohort.length*100)+"%":"—"}</strong><span>{tr("Converted to project","เปลี่ยนเป็น Project","案件化率")}<small>{tr("Current outcome of inquiries created in the selected period","ผลปัจจุบันของ Inquiry ที่สร้างในช่วงที่เลือก","選択期間に作成された引合の現在の結果")}</small></span></div>
        <button className="exec-foot-link" type="button" onClick={()=>openDetail(tr("Estimate pipeline · cost","Estimate pipeline · ต้นทุน","見積パイプライン・原価"),estimateRows(estimates.filter(e=>!["Closed","Cancelled","Approved","Locked"].includes(e.status))))}>{tr("Open estimates · estimated cost","Estimate ที่เปิด · ต้นทุนประเมิน","未完了見積・見積原価")}: {money(estimates.filter(e=>!["Closed","Cancelled","Approved","Locked"].includes(e.status)).reduce((sum,e)=>sum+e.cost,0))}<Icon name="arrowRight" /></button>
      </Panel>
      <Panel title={tr("Cost & procurement","ต้นทุนและการจัดซื้อ","原価・調達")} subtitle={tr("Current scoped totals • THB","ยอดปัจจุบันตามขอบเขต • THB","現在の対象範囲合計・THB")}>
        <div className="exec-finance">{[
          {label:tr("Active project estimate cost","ต้นทุนประเมินโครงการที่เปิด","進行案件の見積原価"),amount:activeProjects.some(p=>p.budget===null)?null:activeProjects.reduce((sum,p)=>sum+(p.budget??0),0),rows:projectRows(activeProjects)},
          {label:tr("Open PR requests","PR ที่ยังเปิด","未完了購買依頼"),amount:prs.reduce((sum,p)=>sum+p.value,0),rows:procurementRows(prs)},
          {label:tr("Total PO commitments","ยอดสั่งซื้อ PO","発注総額"),amount:pos.reduce((sum,p)=>sum+p.value,0),rows:procurementRows(pos)},
          {label:tr("Outstanding PO value","มูลค่า PO ที่ยังไม่รับ","未入荷発注額"),amount:pos.reduce((sum,p)=>sum+p.openValue,0),rows:procurementRows(pos.filter(p=>p.openValue>0))},
          {label:tr("Confirmed receipts at PO price","รับของยืนยันแล้วตามราคา PO","確定入荷額（発注単価）"),amount:receipts.reduce((sum,p)=>sum+p.value,0),rows:procurementRows(receipts)},
        ].map(item=><button key={item.label} type="button" onClick={()=>openDetail(item.label,item.rows)}><span>{item.label}</span><strong>{money(item.amount)}</strong><Icon name="chevronRight" /></button>)}</div>
        <p className="exec-note">{tr("These stages overlap: do not add PR, PO and receipts together. Receipt value is not expense or revenue.","ยอดแต่ละขั้นซ้อนกัน ห้ามบวก PR + PO + รับของเป็นยอดเดียว มูลค่ารับของยังไม่ใช่ค่าใช้จ่ายหรือรายได้","各段階には重複があります。購買依頼・発注・入荷を合算しないでください。入荷額は費用や売上ではありません。")}</p>
      </Panel>
    </div>
    <Panel title={tr("Project health","สถานะโครงการ","案件状況")} subtitle={tr("Risk signals from delivery dates, leaf tasks and materials","สัญญาณจากกำหนดส่ง งานย่อย และวัสดุ","納期・末端タスク・資材による状態")} flush actions={<select aria-label={tr("Health filter","กรองสถานะโครงการ","状況絞り込み")} value={health} onChange={e=>setHealth(e.target.value)}>{["all","critical","watch","healthy","unknown","closed"].map(h=><option key={h} value={h}>{h==="all"?tr("All statuses","ทุกสถานะ","すべて"):healthName(h)}</option>)}</select>}>
      <div className="table-wrap exec-table"><table><thead><tr>{[tr("Project / customer","โครงการ / ลูกค้า","案件・顧客"),tr("Manager","ผู้จัดการ","管理者"),tr("Health","สถานะ","状態"),tr("Actual / plan","จริง / แผน","実績・計画"),tr("Target / forecast","กำหนด / คาดการณ์","納期・予測"),tr("Late / blocked","ล่าช้า / ติดขัด","遅延・停止")].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{projects.filter(p=>health==="all"||projectHealth(p,procurement,data.today)===health).sort((a,b)=>({critical:0,watch:1,unknown:2,healthy:3,closed:4}[projectHealth(a,procurement,data.today)]-({critical:0,watch:1,unknown:2,healthy:3,closed:4}[projectHealth(b,procurement,data.today)]))).slice(0,12).map(p=><tr key={p.id}><td><button type="button" className="exec-record" onClick={()=>openDetail(p.number,[...projectRows([p]),...taskRows(tasks.filter(t=>t.projectId===p.id)),...procurementRows(procurement.filter(x=>x.projectId===p.id))])}><strong>{p.number} · {p.name}</strong><small>{p.customer}</small></button></td><td>{p.manager}</td><td><Badge tone={healthTone[projectHealth(p,procurement,data.today)]}>{healthName(projectHealth(p,procurement,data.today))}</Badge></td><td>{number(p.progress)}% / {p.plannedProgress===null?"—":number(p.plannedProgress)+"%"}<span className="exec-track"><i style={{width:`${Math.min(100,p.progress)}%`}} /></span></td><td>{date(p.due)}<small>{date(p.forecast)}</small></td><td>{p.overdue} / {p.blocked}</td></tr>)}</tbody></table></div>
      {!projects.length?<p className="exec-empty">{tr("No projects match these filters.","ไม่พบโครงการตามตัวกรอง","該当案件はありません。")}</p>:null}
      <div className="exec-table-footer"><small>{tr("Plan % is a time-based estimate weighted by planned effort; not earned value.","% แผนประมาณตามเวลาถ่วงน้ำหนักด้วยแรงงานตามแผน ไม่ใช่ Earned Value","計画％は計画工数で加重した時間基準の概算です。")}</small><button className="link-btn" type="button" onClick={()=>openDetail(tr("All projects","โครงการทั้งหมด","全案件"),projectRows(projects.filter(p=>health==="all"||projectHealth(p,procurement,data.today)===health)))}>{tr("View all","ดูทั้งหมด","すべて表示")} ({projects.length})</button></div>
    </Panel>
    <Panel title={tr("Team capacity outlook","กำลังคนล่วงหน้า","チーム稼働見通し")} subtitle={tr("Planned effort in this scope / configured capacity • man-days","แรงงานตามแผนในขอบเขตนี้ / กำลังคนที่ตั้งไว้ • man-days","対象範囲の計画工数 / 設定稼働能力・人日")} flush actions={<select aria-label={tr("Capacity horizon","ช่วงกำลังคน","予測期間")} value={weeks} onChange={e=>setWeeks(Number(e.target.value))}><option value={4}>4 {tr("weeks","สัปดาห์","週間")}</option><option value={8}>8 {tr("weeks","สัปดาห์","週間")}</option></select>}>
      <div className="table-wrap exec-table"><table><thead><tr><th>{tr("Team member","สมาชิกทีม","担当者")}</th>{Array.from({length:weeks},(_,i)=><th key={i}>{date(shiftDay(monday,i*7))}</th>)}</tr></thead><tbody>{workload.slice(0,15).map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.department}{p.unknown?` · ${p.unknown} ${tr("unplanned","งานข้อมูลไม่ครบ","計画不足")}`:""}</small></td>{p.weeks.map(w=><td key={w.start}><button type="button" className={`exec-capacity ${w.overloaded?"over":w.available===null?"unknown":""}`} onClick={()=>openDetail(`${p.name} · ${date(w.start)}`,capacityRows(p.id,w.start))}><strong>{number(w.assigned)} / {w.available===null?"—":number(w.available)}</strong><small>{w.percent===null?(w.available===null?tr("Capacity not set","ยังไม่ตั้ง Capacity","能力未設定"):tr("No capacity","ไม่มี Capacity","稼働枠なし")):`${number(w.percent)}%`}</small></button></td>)}</tr>)}</tbody></table></div>
      <div className="exec-table-footer"><small>{tr("Weekends and holidays excluded. Leave and work outside this scope are not deducted. Missing plans remain unknown.","ไม่นับเสาร์อาทิตย์และวันหยุด ยังไม่หักวันลาและงานนอกขอบเขต ข้อมูลแผนไม่ครบแสดงว่าไม่ทราบ","週末・祝日を除外。休暇と対象外作業は未反映。計画不足は不明として扱います。")}</small><button type="button" className="link-btn" onClick={()=>openDetail(tr("Team capacity","กำลังคนทีม","稼働能力"),workload.map(p=>({key:String(p.id),title:p.name,description:p.department,status:p.capacity===null?tr("Capacity not set","ยังไม่ตั้ง Capacity","能力未設定"):number(p.capacity)+" man-days/week",destination:"resources"})))}>{tr("All members","สมาชิกทั้งหมด","全メンバー")} ({workload.length})</button></div>
    </Panel>
    <div className="exec-two-col"><Panel title={tr("Risks to follow up","ความเสี่ยงที่ต้องติดตาม","追跡が必要なリスク")} subtitle={tr("Critical projects first, then materials and overdue tasks","เรียงโครงการวิกฤต วัสดุ และงานเลยกำหนด","重大案件・資材・期限超過の順")}>
      <div className="exec-list">{riskRows.slice(0,5).map(r=><button key={r.key} type="button" onClick={()=>openDetail(r.title,[r])}><Icon name="alertTriangle" /><span><strong>{r.title}</strong><small>{r.description}</small></span><Icon name="chevronRight" /></button>)}{!riskRows.length?<p className="exec-empty">{tr("No recorded risk signals in this scope.","ยังไม่พบสัญญาณความเสี่ยงที่บันทึกไว้ในขอบเขตนี้","この範囲に記録されたリスクはありません。")}</p>:null}</div><button type="button" className="exec-foot-link" onClick={()=>openDetail(tr("Risks","ความเสี่ยง","リスク"),riskRows)}>{tr("Review risk list","เปิดรายการความเสี่ยง","リスク一覧")}<Icon name="arrowRight" /></button>
    </Panel><Panel title={tr("Next 30 days","30 วันข้างหน้า","今後30日")} subtitle={tr("Upcoming milestones and project deliveries","Milestone และโครงการที่ใกล้ส่งมอบ","今後のマイルストーン・納品")}><div className="exec-list">{[...taskRows(upcoming),...projectRows(activeProjects.filter(p=>within(p.due,data.today,next30)))].slice(0,5).map(r=><button key={r.key} type="button" onClick={()=>openDetail(r.title,[r])}><Icon name="calendar" /><span><strong>{r.title}</strong><small>{r.description}</small></span></button>)}</div><button type="button" className="exec-foot-link" onClick={()=>openDetail(tr("Upcoming deliveries","กำหนดส่งมอบ","今後の納品"),[...taskRows(upcoming),...projectRows(activeProjects.filter(p=>within(p.due,data.today,next30)))])}>{tr("View delivery plan","ดูแผนส่งมอบ","納品予定を表示")}<Icon name="arrowRight" /></button></Panel></div>
    {data.warnings.length?<p className="exec-error">{tr("Schedule calculation unavailable for","คำนวณแผนไม่สำเร็จสำหรับ","工程計算不可")}: {data.warnings.join(", ")}</p>:null}
    <p className="exec-note">{tr("Reporting access does not grant approval authority. Open source records using your existing permissions. No revenue, profit or cash flow is inferred from estimate costs.","สิทธิ์ดูภาพรวมไม่เพิ่มอำนาจอนุมัติ การเปิดต้นทางใช้สิทธิ์เดิม และไม่ใช้ต้นทุนประเมินแทนรายได้ กำไร หรือกระแสเงินสด","閲覧権限は承認権限を付与しません。元データは既存権限で開きます。原価から売上・利益・資金繰りを推定しません。")}</p>
    {detail?<Modal title={detail.title} size="lg" onClose={()=>setDetail(null)}><label className="exec-detail-search">{tr("Search records","ค้นหารายการ","レコード検索")}<input value={search} onChange={e=>setSearch(e.target.value)} /></label><p className="exec-context">{detail.rows.length} {tr("records","รายการ","件")}</p><div className="exec-detail-list">{detail.rows.filter(r=>(r.title+" "+r.description).toLowerCase().includes(search.toLowerCase())).map(r=><article key={r.key}><div><strong>{r.title}</strong><p>{r.description}</p>{r.status?<Badge>{r.status}</Badge>:null}</div><div><b>{r.value}</b>{r.destination&&canOpen(r.destination)?<button type="button" className="btn default sm" onClick={()=>{setDetail(null);onOpen(r.destination!,r.entityId);}}>{tr("Open source","เปิดต้นทาง","元データ")}<Icon name="arrowRight" /></button>:<small>{tr("Read-only summary","ข้อมูลสรุปสำหรับอ่าน","閲覧用概要")}</small>}</div></article>)}</div>{!detail.rows.length?<EmptyState icon="inbox" title={tr("No records","ไม่มีรายการ","データなし")} message={tr("No matching records in the selected scope.","ไม่พบข้อมูลในขอบเขตที่เลือก","選択範囲に該当データはありません。")} />:null}</Modal>:null}
  </div>;
}
