"use client";
import { LocalizedText } from "../LocalizedText";
import { useLanguage, useT, type Translator } from '../i18n';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { apiRequest, type BootstrapData, type PagedResult } from '../api-client';
import { Badge, EmptyState, Field, Icon, Modal, Pagination, Panel, SearchInput, TablePageSize, Toolbar } from '../ui';
import './resource-tasks.css';

type Plan={assigneeId:number;start:string;workDays:number;manDays:number;note:string;scheduleVersion?:string|null};
type Source={id:number;kind:'Inquiry'|'Project';reference:string;title:string;assigneeIds:number[]};
export type ResourceTask={id:number;sourceKind:'Inquiry'|'Project';sourceId:number;reference:string;sourceTitle:string;scheduleTaskId:number|null;title:string;description:string;isIssue:boolean;reporter:string;priority:string;state:string;assigneeId:number;assigneeName:string;start:string|null;end:string|null;manDays:number|null;workDays:number;percentComplete:number;status:string;pendingPlan:Plan|null;acknowledgedAt:string|null;approvedAt:string|null;decisionNote:string;rowVersion:string;scheduleVersion:string|null;actualStart:string|null;actualFinish:string|null;canPlan:boolean;canPropose:boolean;canRespond:boolean;canClose:boolean};
type Impact={start:string;end:string;capacity:number|null;unknown:number;overloaded:boolean;needsReason:boolean;replacesInquiryAggregate:boolean;weeks:{start:string;before:number;removed:number;added:number;after:number;available:number|null;beforePercent:number|null;afterPercent:number|null;overloaded:boolean}[]};
type Props={bootstrap:BootstrapData;notify:(message:string)=>void;mine?:boolean;issues?:boolean;onChanged?:()=>void;openProjectSchedule?:(id:number)=>void};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const errorText=(e:unknown)=>e instanceof Error?e.message:String(e);
const number=(n:number)=>n.toLocaleString(undefined,{maximumFractionDigits:1});
const percent=(n:number|null)=>n===null?'—':`${number(n)}%`;
function TaskSelect({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}) {const t=useT();return <select className="select" aria-label={t(options[0]?.label??'')} value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{t(option.label)}</option>)}</select>;}
const taskLabel=(task:ResourceTask,t:Translator)=>t(task.state==='Closed'?'ปิดงานแล้ว':task.pendingPlan?task.state==='Approved'?'รออนุมัติแผนใหม่':'รออนุมัติงาน':task.state==='Rejected'?'ส่งกลับแก้ไข':task.status==='Done'?'เสร็จ · รอตรวจรับ':!task.acknowledgedAt?'รอตอบรับ':task.status==='In Progress'?'กำลังทำ':task.status==='Blocked'?'ติดปัญหา':'ตอบรับแล้ว');

export function ResourceTaskWorkspace({bootstrap,notify,mine=false,issues=false,onChanged,openProjectSchedule}:Props) {
  const t=useT();
  const {lang}=useLanguage();
  const [result,setResult]=useState<PagedResult<ResourceTask>>({items:[],page:1,pageSize:50,total:0});
  const [sources,setSources]=useState<Source[]>([]),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(50),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[project,setProject]=useState('');
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<ResourceTask|'new'|null>(null);
  const canRead=bootstrap.permissions.includes('schedule.read');
  const requestId=useRef(0);
  const invalidate=useCallback(()=>{requestId.current++;},[]);
  const canCreate=bootstrap.permissions.includes('schedule.plan')||bootstrap.permissions.includes('schedule.progress');
  const load=useCallback(async()=>{
    const current=++requestId.current;
    if(!canRead){setLoading(false);return;}
    setLoading(true);setError('');
    try { const query=new URLSearchParams({page:String(page),pageSize:String(pageSize),search,filter,mine:String(mine),issues:String(issues)});if(project)query.set('projectId',project);
      const [data,sourceData]=await Promise.all([apiRequest<PagedResult<ResourceTask>>(`/api/v1/resource-tasks?${query}`),apiRequest<Source[]>('/api/v1/resource-tasks/sources')]);if(current===requestId.current){setResult(data);setSources(sourceData);}
    }catch(e){if(current===requestId.current)setError(errorText(e));}finally{if(current===requestId.current)setLoading(false);}
  },[canRead,page,pageSize,search,filter,mine,issues,project]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>{clearTimeout(timer);invalidate();};},[load,invalidate]);
  useEffect(()=>{const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer);},[load]);
  if(!canRead)return <EmptyState icon="lock" title="ไม่มีสิทธิ์ดูแผนงาน" message="ต้องมีสิทธิ์ schedule.read เพื่อดูและตอบรับงาน" />;
  return <section className="resource-tasks">
    <div className="resource-task-heading"><div><h2>{t(issues?'Project Punchlist':mine?'งานที่ต้องตอบรับและติดตาม':'จัดการ Task ของทีม')}</h2><p>{issues?<LocalizedText text={"บันทึก Issue ลูกค้า → อนุมัติงาน → สมาชิกตอบรับ → ลงมือทำ → ตรวจรับและปิด Issue"} />:<LocalizedText text={"สร้างงานจาก Inquiry หรือ Project · ตรวจภาระงานก่อนอนุมัติ · ติดตามการตอบรับและความคืบหน้า"} />}</p></div>{canCreate&&!mine?<button className="btn primary" type="button" onClick={()=>setSelected('new')}><Icon name="plus" />{issues?<LocalizedText text={"เพิ่ม Issue ลูกค้า"} />:<LocalizedText text={"สร้าง Task"} />}</button>:null}</div>
    <Toolbar><SearchInput value={search} onChange={v=>{setSearch(v);setPage(1);}} placeholder="ค้นหาชื่องาน หรือเลข Inquiry / Project…" /><TaskSelect value={filter} onChange={v=>{setFilter(v);setPage(1);}} options={[{value:'All',label:'ทุกสถานะ'},{value:'Approval',label:'รออนุมัติ'},{value:'Acknowledgment',label:'รอตอบรับ'},{value:'Approved',label:'อนุมัติแล้ว'},{value:'Rejected',label:'ส่งกลับแก้ไข'},{value:'Closed',label:'ปิดงานแล้ว'}]} />{issues?<TaskSelect value={project} onChange={v=>{setProject(v);setPage(1);}} options={[{value:'',label:'ทุก Project'},...sources.filter(s=>s.kind==='Project').map(s=>({value:String(s.id),label:`${s.reference} · ${s.title}`}))]} />:null}<button className="btn ghost" type="button" disabled={loading} onClick={()=>void load()}><Icon name="refresh" /><LocalizedText text={"Refresh"} /></button></Toolbar>
    {error?<div className="callout danger" role="alert">{error}<button className="btn ghost" type="button" onClick={()=>void load()}><LocalizedText text={"ลองโหลดใหม่"} /></button></div>:null}
    <Panel title={`${result.total} ${t(issues?'issues':'tasks')}`} subtitle="เฉพาะงานในขอบเขตสิทธิ์ของคุณ · งานที่ยังไม่อนุมัติไม่รวมใน Workload" flush>
      <TablePageSize value={pageSize} onChange={v=>{setPageSize(v);setPage(1);}} />
      {loading?<div className="empty"><span className="spinner" /><LocalizedText text={"กำลังโหลดงาน…"} /></div>:result.items.length?<div className="table-wrap"><table><thead><tr><th><LocalizedText text={"งาน / ที่มา"} /></th><th><LocalizedText text={"Responsibility"} /></th><th><LocalizedText text={"แผนที่อนุมัติ"} /></th><th><LocalizedText text={"Progress"} /></th><th><LocalizedText text={"สถานะ / การตอบรับ"} /></th><th /></tr></thead><tbody>{result.items.map(task=><tr key={task.id}><td><button className="resource-task-link" type="button" onClick={()=>setSelected(task)}>{task.isIssue?'ISSUE':'TASK'}-{task.id} <LocalizedText text={"·"} /> {task.title}</button><small className="resource-task-meta">{task.reference} <LocalizedText text={"·"} /> {task.priority}{task.reporter?` · ${t('Reported by')} ${task.reporter}`:''}</small></td><td>{task.assigneeName}</td><td>{task.start?`${task.start} → ${task.end}`:<LocalizedText text={"ยังไม่ยืนยันแผน"} />}<small className="resource-task-meta">{task.manDays===null?'—':`${number(task.manDays)} MD`}</small></td><td>{task.percentComplete}%<small className="resource-task-meta">{t(task.status)}</small></td><td><Badge tone={task.pendingPlan?'amber':task.state==='Closed'||task.acknowledgedAt?'green':'blue'}>{taskLabel(task,t)}</Badge>{task.acknowledgedAt?<small className="resource-task-meta"><LocalizedText text={"ตอบรับ"} /> {new Date(task.acknowledgedAt).toLocaleString(lang==='TH'?'th-TH':lang==='JP'?'ja-JP':'en-GB')}</small>:null}</td><td><button type="button" className="btn default sm" onClick={()=>setSelected(task)}><LocalizedText text={"เปิดงาน"} /></button></td></tr>)}</tbody></table></div>:!error?<EmptyState icon="checkCircle" title="ไม่มีงานในรายการนี้" message={mine?'งานที่ได้รับมอบหมายจะปรากฏที่นี่เพื่อให้คุณตอบรับและเสนอแผน':'เปลี่ยนตัวกรอง หรือสร้างงานเพื่อส่งให้ผู้รับผิดชอบวางแผนและอนุมัติ'} />:null}
      <Pagination page={result.page} pageCount={Math.max(1,Math.ceil(result.total/result.pageSize))} from={result.total?(result.page-1)*result.pageSize+1:0} to={Math.min(result.page*result.pageSize,result.total)} total={result.total} onPage={setPage} />
    </Panel>
    {selected?<TaskDialog key={selected==='new'?'new':`${selected.id}-${selected.rowVersion}`} task={selected==='new'?null:selected} sources={sources} bootstrap={bootstrap} issue={issues} preferredProject={project} onClose={()=>setSelected(null)} onSaved={message=>{setSelected(null);notify(message);void load();onChanged?.();}} openProjectSchedule={openProjectSchedule} />:null}
  </section>;
}

function ImpactView({impact}:{impact:Impact}) {const t=useT();return <div className="resource-impact"><strong><LocalizedText text={"Workload ก่อน → หลังรับงาน"} /></strong><p><LocalizedText text={"plan"} /> {impact.start} <LocalizedText text={"to"} /> {impact.end}  <LocalizedText text={"· กำลังทำงาน"} /> {impact.capacity===null?<LocalizedText text={"ยังไม่กำหนด"} />:`${impact.capacity} ${t('วัน/สัปดาห์')}`}</p>{impact.unknown?<div className="callout warning"><LocalizedText text={"มี"} /> {impact.unknown}  <LocalizedText text={"งานที่แผนหรือ Effort ไม่ครบ ตัวเลขนี้ยังไม่ใช่ภาระงานทั้งหมด"} /></div>:null}{impact.capacity===null?<div className="callout warning"><LocalizedText text={"ยังไม่กำหนด Weekly capacity จึงคำนวณเปอร์เซ็นต์ไม่ได้"} /></div>:null}{impact.overloaded?<div className="callout danger"><LocalizedText text={"งานนี้ทำให้มีสัปดาห์เกินกำลัง กรุณาปรับคน/วัน หรือระบุเหตุผลก่อนอนุมัติ"} /></div>:null}<div className="table-wrap"><table><thead><tr><th><LocalizedText text={"สัปดาห์เริ่ม"} /></th><th><LocalizedText text={"เดิม"} /></th><th><LocalizedText text={"แทนแผนเดิม / เพิ่ม"} /></th><th><LocalizedText text={"Total"} /></th><th><LocalizedText text={"Workload"} /></th></tr></thead><tbody>{impact.weeks.map(week=><tr key={week.start} className={week.overloaded?'row-wait':undefined}><td>{week.start}</td><td>{number(week.before)} <LocalizedText text={"MD"} /></td><td>{week.removed ? `−${number(week.removed)} / ` : ""}+{number(week.added)} <LocalizedText text={"MD"} /></td><td>{number(week.after)} <LocalizedText text={"of"} /> {week.available===null?'—':number(week.available)} <LocalizedText text={"MD"} /></td><td><Badge tone={week.overloaded?'red':'blue'}>{percent(week.beforePercent)} → {percent(week.afterPercent)}</Badge></td></tr>)}</tbody></table></div>{impact.replacesInquiryAggregate?<small><LocalizedText text={"เมื่ออนุมัติงานย่อยแรก Inquiry นี้จะนับ Effort จาก Task แทนก้อนเดิม กรุณาแจกแจงงานของ Inquiry ให้ครบ"} /></small>:null}</div>;}

function TaskDialog({task,sources,bootstrap,issue,preferredProject,onClose,onSaved,openProjectSchedule}:{task:ResourceTask|null;sources:Source[];bootstrap:BootstrapData;issue:boolean;preferredProject:string;onClose:()=>void;onSaved:(message:string)=>void;openProjectSchedule?:((id:number)=>void)|undefined}) {
  const t=useT();
  const {lang}=useLanguage();
  const available=sources.filter(s=>!issue||s.kind==='Project');
  const defaultSource=task?`${task.sourceKind}:${task.sourceId}`:preferredProject?`Project:${preferredProject}`:available[0]?`${available[0].kind}:${available[0].id}`:'';
  const [source,setSource]=useState(defaultSource),[title,setTitle]=useState(task?.title??''),[description,setDescription]=useState(task?.description??''),[reporter,setReporter]=useState(task?.reporter??''),[priority,setPriority]=useState(task?.priority??'Normal');
  const [mode,setMode]=useState<'view'|'propose'>(task?'view':'propose');
  const [plan,setPlan]=useState<Plan>(task?.pendingPlan??{assigneeId:task?.assigneeId??available.find(s=>`${s.kind}:${s.id}`===defaultSource)?.assigneeIds[0]??bootstrap.user.id,start:task?.start??today(),workDays:task?.workDays??1,manDays:task?.manDays??1,note:'',scheduleVersion:task?.scheduleVersion??null});
  const [rawImpact,setImpact]=useState<Impact|null>(null),[verifiedKey,setVerifiedKey]=useState(''),[previewError,setPreviewError]=useState(''),[previewBusy,setPreviewBusy]=useState(false),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [progress,setProgress]=useState(task?.percentComplete??0),[status,setStatus]=useState(task?.status??'Not Started'),[actualStart,setActualStart]=useState(task?.actualStart??''),[actualEnd,setActualEnd]=useState(task?.actualFinish??'');
  const [kind,id]=source.split(':');const viewingProposal=!!task?.pendingPlan&&mode==='view';
  const previewPlan=viewingProposal?task.pendingPlan!:plan;
  const eligibleIds=sources.find(s=>`${s.kind}:${s.id}`===source)?.assigneeIds??[task?.assigneeId??bootstrap.user.id];
  const eligibleUsers=bootstrap.team.filter(user=>eligibleIds.includes(user.id));
  const previewKey=JSON.stringify({source,plan:previewPlan,mode});
  const impact=verifiedKey===previewKey?rawImpact:null;
  useEffect(()=>{
    let cancelled=false;
    if(!source||!previewPlan.assigneeId||!previewPlan.start||previewPlan.workDays<1||previewPlan.manDays<=0||task&&mode==='view'&&!task.pendingPlan){const reset=setTimeout(()=>{setPreviewBusy(false);setPreviewError('');},0);return()=>clearTimeout(reset);}
    const timer=setTimeout(()=>{
      setPreviewBusy(true);setImpact(null);setPreviewError('');
      void apiRequest<Impact>('/api/v1/resource-tasks/preview',{method:'POST',body:JSON.stringify({sourceKind:kind,sourceId:Number(id),taskId:task?.id,plan:previewPlan})}).then(result=>{if(!cancelled){setImpact(result);setVerifiedKey(previewKey);}}).catch(e=>{if(!cancelled)setPreviewError(errorText(e));}).finally(()=>{if(!cancelled)setPreviewBusy(false);});
    },350);return()=>{cancelled=true;clearTimeout(timer);};
  },[source,kind,id,previewPlan,task,mode,previewKey]);
  const changePlan=<K extends keyof Plan>(key:K,value:Plan[K])=>setPlan(current=>({...current,[key]:value}));
  const save=async(action:string)=>{
    if(busy)return;setBusy(true);setError('');
    try {
      const body=action==='create'?{sourceKind:kind,sourceId:Number(id),title,description,reporter,priority,isIssue:issue,plan}:{rowVersion:task?.rowVersion,scheduleVersion:task?.scheduleVersion,note,plan,percentComplete:progress,status,actualStart:actualStart||null,actualFinish:actualEnd||null,forecastFinish:null,remark:note||null};
      await apiRequest(action==='create'?'/api/v1/resource-tasks':`/api/v1/resource-tasks/${task!.id}/${action}`,{method:'POST',body:JSON.stringify(body)});onSaved(t(action==='acknowledge'?'ตอบรับงานแล้ว':action==='approve'?'อนุมัติแผนแล้ว สมาชิกต้องตอบรับแผนนี้':action==='create'?'ส่งงานเข้าคิวอนุมัติแล้ว':'บันทึกงานแล้ว'));
    }catch(e){setError(errorText(e));}finally{setBusy(false);}
  };
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void save(task?'propose':'create');};
  const editable=mode==='propose';
  return <Modal title={task?`${task.isIssue?'ISSUE':'TASK'}-${task.id} · ${task.title}`:t(issue?'บันทึก Issue และเสนองาน':'สร้าง Task และตรวจ Workload')} size="xl" onClose={()=>{if(!busy)onClose();}}>
    {error?<div className="callout danger" role="alert">{error}</div>:null}
    {task?<><div className="resource-task-details"><Badge tone="blue">{task.reference}</Badge><Badge tone="amber">{taskLabel(task,t)}</Badge><span>{task.assigneeName}</span></div><p>{task.description||'—'}</p>{task.reporter?<p><LocalizedText text={"ผู้แจ้ง:"} /> {task.reporter}</p>:null}<div className="info-strip"><LocalizedText text={"แผนอนุมัติ:"} /> {task.start??'—'} → {task.end??'—'} <LocalizedText text={"·"} /> {task.manDays??'—'} <LocalizedText text={"MD"} />{task.acknowledgedAt?` · ${t('ตอบรับแล้ว')} ${new Date(task.acknowledgedAt).toLocaleString(lang==='TH'?'th-TH':lang==='JP'?'ja-JP':'en-GB')}`:t('· ยังไม่มีการตอบรับ')}</div>{task.decisionNote?<p><LocalizedText text={"ผลการพิจารณา:"} /> {task.decisionNote}</p>:null}{task.scheduleTaskId&&openProjectSchedule?<button className="btn ghost" type="button" onClick={()=>{onClose();openProjectSchedule(task.sourceId);}}><LocalizedText text={"เปิดงานใน Project Schedule"} /> <Icon name="chevronRight" /></button>:null}</>:null}
    {editable?<form onSubmit={submit}><div className="form-grid two">
      {!task?<><Field label="Inquiry / Project"><select required value={source} onChange={e=>{const next=e.target.value;setSource(next);const ids=sources.find(s=>`${s.kind}:${s.id}`===next)?.assigneeIds??[];if(!ids.includes(plan.assigneeId))changePlan("assigneeId",ids[0]??0);}}><option value="">{t('เลือกที่มาของงาน')}</option>{available.map(s=><option key={`${s.kind}:${s.id}`} value={`${s.kind}:${s.id}`}>{s.reference} <LocalizedText text={"·"} /> {s.title}</option>)}</select></Field><Field label="ความสำคัญ"><select value={priority} onChange={e=>setPriority(e.target.value)}>{['Low','Normal','High','Urgent'].map(p=><option key={p} value={p}>{t(p)}</option>)}</select></Field><Field label="Task name"><input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={500} /></Field>{issue?<Field label="ผู้แจ้ง / ลูกค้า / เลขอ้างอิง"><input required maxLength={200} value={reporter} onChange={e=>setReporter(e.target.value)} /></Field>:null}<Field label="รายละเอียดและผลลัพธ์ที่ต้องการ"><textarea required={issue} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)} /></Field></>:null}
      <Field label="Responsibility"><select required value={plan.assigneeId} disabled={!!task&&!task.canPlan} onChange={e=>changePlan('assigneeId',Number(e.target.value))}>{eligibleUsers.map(u=><option key={u.id} value={u.id}>{u.name} <LocalizedText text={"·"} /> {u.department}</option>)}</select></Field>
      <Field label="เริ่มทำงาน"><input type="date" required value={plan.start} onChange={e=>changePlan('start',e.target.value)} /></Field><Field label="ระยะเวลา (วันทำงาน)"><input type="number" required min={1} max={730} value={plan.workDays} onChange={e=>changePlan('workDays',Number(e.target.value))} /><small><LocalizedText text={"ไม่นับเสาร์–อาทิตย์และวันหยุดบริษัท"} /></small></Field><Field label="Effort ที่ใช้ (Man-days)"><input type="number" required min={0.01} max={10000} step={0.01} value={plan.manDays} onChange={e=>changePlan('manDays',Number(e.target.value))} /><small><LocalizedText text={"เช่น ใช้ครึ่งวันต่อวันเป็นเวลา 4 วัน = 2 MD"} /></small></Field><Field label={task?'เหตุผลที่ขอปรับแผน':'หมายเหตุถึงผู้อนุมัติ'}><textarea required={!!task} maxLength={2000} value={plan.note} onChange={e=>changePlan('note',e.target.value)} /></Field>
    </div>{previewBusy?<p><LocalizedText text={"กำลังคำนวณ Workload…"} /></p>:null}{previewError?<div className="callout danger" role="alert">{previewError}</div>:null}{impact?<ImpactView impact={impact} />:null}<div className="resource-task-actions"><button className="btn default" type="button" disabled={busy} onClick={()=>task?setMode('view'):onClose()}><LocalizedText text={"Cancelled"} /></button><button className="btn primary" type="submit" disabled={busy||previewBusy||!impact||!!previewError}>{busy?<LocalizedText text={"Saving…"} />:<LocalizedText text={"ส่งขออนุมัติ"} />}</button></div></form>:null}
    {viewingProposal?<><h3><LocalizedText text={"แผนที่เสนอ"} /></h3><p><LocalizedText text={"เริ่ม"} /> {task.pendingPlan!.start} <LocalizedText text={"·"} /> {task.pendingPlan!.workDays}  <LocalizedText text={"วันทำงาน ·"} /> {task.pendingPlan!.manDays} MD · {bootstrap.team.find(u=>u.id===task.pendingPlan!.assigneeId)?.name??task.pendingPlan!.assigneeId}</p><p>{task.pendingPlan!.note}</p>{previewBusy?<p><LocalizedText text={"กำลังตรวจ Workload ล่าสุด…"} /></p>:null}{previewError?<div className="callout danger">{previewError}</div>:null}{impact?<ImpactView impact={impact} />:null}{task.canPlan?<><Field label={impact?.needsReason?'เหตุผลยืนยันแม้เกินกำลัง / ข้อมูลไม่ครบ (จำเป็น)':'หมายเหตุการอนุมัติ / เหตุผลส่งกลับ'}><textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} /></Field><div className="resource-task-actions"><button className="btn default" type="button" disabled={busy||!note.trim()} onClick={()=>void save('reject')}><LocalizedText text={"ส่งกลับแก้ไข"} /></button><button className="btn primary" type="button" disabled={busy||task.status==='Done'||!impact||previewBusy||!!previewError||impact.needsReason&&!note.trim()} onClick={()=>void save('approve')}><LocalizedText text={"อนุมัติและแจ้งให้สมาชิกตอบรับ"} /></button></div></>:<p className="muted"><LocalizedText text={"รอหัวหน้าหรือผู้จัดการพิจารณา แผนเดิมยังไม่เปลี่ยน"} /></p>}</>:null}
    {task&&mode==='view'?<><div className="resource-task-actions">{task.canRespond&&task.state==='Approved'&&!task.acknowledgedAt?<button className="btn primary" type="button" disabled={busy} onClick={()=>void save('acknowledge')}><Icon name="check" /><LocalizedText text={"รับทราบและยอมรับแผนงาน"} /></button>:null}{task.canPropose&&!task.pendingPlan?<button className="btn default" type="button" disabled={busy} onClick={()=>setMode('propose')}><LocalizedText text={"เสนอวัน / Effort ใหม่"} /></button>:null}</div>{task.canRespond&&task.acknowledgedAt&&task.state==='Approved'?<form onSubmit={event=>{event.preventDefault();void save('progress');}}><h3><LocalizedText text={"อัปเดตการทำงาน"} /></h3><div className="form-grid two"><Field label="State"><select value={status} onChange={e=>{setStatus(e.target.value);if(e.target.value==='Done')setProgress(100);if(e.target.value==='Not Started'){setProgress(0);setActualStart('');setActualEnd('');}}}>{['Not Started','In Progress','Blocked','Done'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></Field><Field label="ความคืบหน้า (%)"><input type="number" min={0} max={100} step={1} required value={progress} onChange={e=>setProgress(Number(e.target.value))} /></Field><Field label="วันเริ่มจริง"><input type="date" required={status==='Done'} value={actualStart} onChange={e=>setActualStart(e.target.value)} /></Field><Field label="วันเสร็จจริง"><input type="date" min={actualStart||undefined} required={status==='Done'} value={actualEnd} onChange={e=>setActualEnd(e.target.value)} /></Field><Field label="ผลการทำงาน / ปัญหาที่ติด"><textarea required={status==='Blocked'} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} /></Field></div><button className="btn primary" type="submit" disabled={busy}><LocalizedText text={"บันทึกความคืบหน้า"} /></button></form>:null}{task.canClose?<><Field label="ผลตรวจรับ / ยืนยันกับลูกค้า"><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} /></Field><button className="btn primary" type="button" disabled={busy||!note.trim()} onClick={()=>void save('close')}><LocalizedText text={"ตรวจรับและปิด"} />{task.isIssue?' Issue':<LocalizedText text={"Tasks"} />}</button></>:null}</>:null}
  </Modal>;
}
