/* Site Monitor (SiteMonitorScreen). Namespaced keys, merged last, so no shared label changes. */
type Copy = { th: string; en: string; jp: string };

export const SITE_MONITOR_COPY: Record<string, Copy> = {
  "Site Monitor": { th: "Site Monitor", en: "Site Monitor", jp: "サイトモニター" },
  "Monitor.subtitle": {
    th: "สถานะโปรแกรมและ Service ของทุก Site ที่ TMT Control Panel ส่งมา พร้อม Resource, Log และปัญหาที่ยังเปิดอยู่",
    en: "Every site's programs and services as TMT Control Panel reports them, with resources, logs and open problems.",
    jp: "TMT Control Panel が報告する各サイトのプログラムとサービスの状態、リソース、ログ、未解決の問題。",
  },
  "Monitor.addSite": { th: "เพิ่ม Site", en: "Add site", jp: "サイトを追加" },
  "Monitor.editSite": { th: "แก้ไข Site", en: "Edit site", jp: "サイトを編集" },
  "Monitor.filterByHealth": { th: "กรองตามสถานะ Site", en: "Filter by site status", jp: "サイトの状態で絞り込み" },
  "Monitor.searchSites": { th: "ค้นหาชื่อ Site หรือสถานที่", en: "Search site name or location", jp: "サイト名・場所で検索" },
  "Monitor.loading": { th: "กำลังโหลดสถานะ Site…", en: "Loading site status…", jp: "サイトの状態を読み込み中…" },
  "Monitor.emptyTitle": { th: "ยังไม่มี Site ที่เฝ้าระวัง", en: "No monitored sites yet", jp: "監視中のサイトはまだありません" },
  "Monitor.emptyManage": {
    th: "กด เพิ่ม Site แล้วสร้าง Agent key ให้เครื่องที่ติดตั้ง TMT Control Panel",
    en: "Add a site, then create an agent key for each machine that runs TMT Control Panel.",
    jp: "サイトを追加し、TMT Control Panel を実行する各マシンのエージェントキーを作成してください。",
  },
  "Monitor.emptyRead": {
    th: "ผู้ดูแลระบบยังไม่ได้เพิ่ม Site ให้เฝ้าระวัง",
    en: "An administrator has not added any site to monitor yet.",
    jp: "管理者はまだ監視するサイトを追加していません。",
  },
  "Monitor.staleData": {
    th: "โหลดข้อมูลล่าสุดไม่สำเร็จ กำลังแสดงข้อมูลครั้งก่อน",
    en: "The latest refresh failed; showing the previous data.",
    jp: "最新の更新に失敗しました。前回のデータを表示しています。",
  },
  "Monitor.autoRefresh": { th: "อัปเดตอัตโนมัติทุก 20 วินาที", en: "Updates automatically every 20 seconds.", jp: "20 秒ごとに自動更新します。" },
  "Monitor.noMatchTitle": { th: "ไม่พบ Site ที่ตรงเงื่อนไข", en: "No matching sites", jp: "該当するサイトはありません" },
  "Monitor.noMatchMessage": { th: "ลองล้างตัวกรองหรือใช้คำค้นอื่น", en: "Clear the filter or try a different search.", jp: "絞り込みを解除するか、別のキーワードをお試しください。" },
  "Monitor.allSites": { th: "Site ทั้งหมด", en: "All sites", jp: "すべてのサイト" },

  "Monitor.site": { th: "Site", en: "Site", jp: "サイト" },
  "Monitor.status": { th: "สถานะ", en: "Status", jp: "状態" },
  "Monitor.programsRunning": { th: "โปรแกรมที่ทำงาน", en: "Programs running", jp: "稼働中のプログラム" },
  "Monitor.machinesOnline": { th: "เครื่องออนไลน์", en: "Machines online", jp: "オンラインのマシン" },
  "Monitor.openProblems": { th: "ปัญหาที่ยังเปิดอยู่", en: "Open problems", jp: "未解決の問題" },
  "Monitor.lastReport": { th: "รายงานล่าสุด", en: "Last report", jp: "最終報告" },
  "Monitor.firstContact": { th: "ผู้ดูแลลำดับ 1", en: "Responsible #1", jp: "担当者 1" },
  "Monitor.noContact": { th: "ยังไม่ได้กำหนด", en: "Not assigned", jp: "未設定" },

  "Monitor.health.Healthy": { th: "ปกติ", en: "Healthy", jp: "正常" },
  "Monitor.health.Problem": { th: "มีปัญหา", en: "Problem", jp: "問題あり" },
  "Monitor.health.Offline": { th: "ขาดการติดต่อ", en: "Offline", jp: "オフライン" },
  "Monitor.health.NoMachine": { th: "ยังไม่มีเครื่อง", en: "No machine", jp: "マシン未登録" },
  "Monitor.health.Inactive": { th: "ปิดการเฝ้าระวัง", en: "Inactive", jp: "監視停止中" },


  "Monitor.incident.ProgramStopped": { th: "โปรแกรมหยุดทำงานโดยไม่ได้สั่ง", en: "Stopped unexpectedly", jp: "予期せず停止" },
  "Monitor.incident.AgentOffline": { th: "เครื่องหยุดส่งข้อมูล", en: "Machine stopped reporting", jp: "マシンからの報告が途絶" },
  "Monitor.notifiedUpTo": { th: "แจ้งอีเมลถึงผู้ดูแลลำดับที่", en: "Emailed up to responsible person", jp: "メール通知済みの担当者：" },
  "Monitor.notNotifiedYet": { th: "กำลังส่งอีเมลแจ้งผู้ดูแล", en: "Emailing the responsible people", jp: "担当者にメール送信中" },
  "Monitor.acknowledgedBy": { th: "รับทราบโดย", en: "acknowledged by", jp: "確認者：" },
  "Monitor.acknowledge": { th: "รับทราบ (หยุดส่งต่อ)", en: "Acknowledge (stop escalating)", jp: "確認（エスカレーション停止）" },
  "Monitor.acknowledged": { th: "รับทราบปัญหาแล้ว จะไม่ส่งอีเมลต่อไปยังลำดับถัดไป", en: "Acknowledged. No further escalation emails will be sent.", jp: "確認しました。以降のエスカレーションメールは送信されません。" },

  "Monitor.programs": { th: "โปรแกรม / Service", en: "Programs & services", jp: "プログラム / サービス" },
  "Monitor.programsHint": {
    th: "รายการตามที่ตั้งค่าไว้ใน TMT Control Panel ของแต่ละเครื่อง",
    en: "As configured in TMT Control Panel on each machine.",
    jp: "各マシンの TMT Control Panel で設定された一覧です。",
  },
  "Monitor.noProgramsTitle": { th: "ยังไม่มีโปรแกรม", en: "No programs yet", jp: "プログラムはまだありません" },
  "Monitor.noProgramsMessage": {
    th: "เครื่องยังไม่ได้ส่งรายการโปรแกรม ตรวจว่าเปิด Web monitor ใน TMT Control Panel แล้ว",
    en: "No machine has reported programs yet. Check that Web monitor is enabled in TMT Control Panel.",
    jp: "まだプログラムが報告されていません。TMT Control Panel で Web モニターが有効か確認してください。",
  },
  "Monitor.program": { th: "โปรแกรม", en: "Program", jp: "プログラム" },
  "Monitor.cpu": { th: "CPU", en: "CPU", jp: "CPU" },
  "Monitor.memory": { th: "หน่วยความจำ", en: "Memory", jp: "メモリ" },
  "Monitor.uptime": { th: "ทำงานมาแล้ว", en: "Uptime", jp: "稼働時間" },
  "Monitor.since": { th: "สถานะเปลี่ยนเมื่อ", en: "Status since", jp: "状態変化" },
  "Monitor.control": { th: "สั่งงาน", en: "Control", jp: "操作" },
  "Monitor.admin": { th: "Admin", en: "Admin", jp: "管理者" },
  "Monitor.state.running": { th: "ทำงาน", en: "Running", jp: "稼働中" },
  "Monitor.state.stopped": { th: "หยุด", en: "Stopped", jp: "停止" },
  "Monitor.state.unknown": { th: "ไม่ทราบ (เครื่องออฟไลน์)", en: "Unknown (machine offline)", jp: "不明（マシンがオフライン）" },
  "Monitor.pending.Start": { th: "กำลัง Start…", en: "Starting…", jp: "起動中…" },
  "Monitor.pending.Stop": { th: "กำลัง Stop…", en: "Stopping…", jp: "停止中…" },
  "Monitor.pending.Restart": { th: "กำลัง Restart…", en: "Restarting…", jp: "再起動中…" },
  "Monitor.blocked.inactive": { th: "Site นี้ปิดการเฝ้าระวังอยู่", en: "This site is inactive.", jp: "このサイトは監視停止中です。" },
  "Monitor.blocked.offline": { th: "เครื่องออฟไลน์ จึงรับคำสั่งไม่ได้", en: "The machine is offline, so it cannot receive commands.", jp: "マシンがオフラインのため操作できません。" },
  "Monitor.blocked.controlOff": {
    th: "เครื่องนี้ปิดการสั่งงานจากเว็บไว้ใน TMT Control Panel",
    en: "Remote control is turned off in TMT Control Panel on this machine.",
    jp: "このマシンの TMT Control Panel でリモート操作がオフになっています。",
  },
  "Monitor.blocked.inFlight": { th: "มีคำสั่งที่กำลังทำงานอยู่", en: "A command is already in progress.", jp: "実行中のコマンドがあります。" },
  "Monitor.verb.Start": { th: "Start", en: "Start", jp: "起動" },
  "Monitor.verb.Stop": { th: "Stop", en: "Stop", jp: "停止" },
  "Monitor.verb.Restart": { th: "Restart", en: "Restart", jp: "再起動" },

  "Monitor.machines": { th: "เครื่อง (Agent)", en: "Machines (agents)", jp: "マシン（エージェント）" },
  "Monitor.machinesHint": {
    th: "เครื่องที่ติดตั้ง TMT Control Panel และส่งข้อมูลด้วย Agent key ของ Site นี้",
    en: "Machines running TMT Control Panel that report with this site's agent keys.",
    jp: "このサイトのエージェントキーで報告する TMT Control Panel のマシン。",
  },
  "Monitor.noMachinesTitle": { th: "ยังไม่มีเครื่อง", en: "No machines yet", jp: "マシンはまだありません" },
  "Monitor.noMachinesManage": {
    th: "กด เพิ่มเครื่อง เพื่อสร้าง Agent key แล้วนำไปใส่ใน TMT Control Panel",
    en: "Use Add machine to create an agent key, then enter it in TMT Control Panel.",
    jp: "「マシンを追加」でエージェントキーを作成し、TMT Control Panel に入力してください。",
  },
  "Monitor.noMachinesMessage": {
    th: "ยังไม่มีเครื่องลงทะเบียนกับ Site นี้",
    en: "No machine is registered for this site yet.",
    jp: "このサイトに登録されたマシンはまだありません。",
  },
  "Monitor.machine": { th: "เครื่อง", en: "Machine", jp: "マシン" },
  "Monitor.disk": { th: "ดิสก์", en: "Disk", jp: "ディスク" },
  "Monitor.free": { th: "ว่าง", en: "free", jp: "空き" },
  "Monitor.keyActions": { th: "จัดการ Key", en: "Key actions", jp: "キー操作" },
  "Monitor.neverReported": { th: "ยังไม่เคยส่งข้อมูล", en: "Never reported", jp: "未報告" },
  "Monitor.key": { th: "Key", en: "key", jp: "キー" },
  "Monitor.controlAllowed": { th: "อนุญาตสั่งงานจากเว็บ", en: "Remote control allowed", jp: "リモート操作可" },
  "Monitor.controlOff": { th: "ปิดการสั่งงานจากเว็บ", en: "Remote control off", jp: "リモート操作オフ" },
  "Monitor.online": { th: "ออนไลน์", en: "Online", jp: "オンライン" },
  "Monitor.offline": { th: "ออฟไลน์", en: "Offline", jp: "オフライン" },
  "Monitor.newKey": { th: "ออก Key ใหม่", en: "New key", jp: "新しいキー" },
  "Monitor.removeMachine": { th: "ลบเครื่อง", en: "Remove", jp: "削除" },
  "Monitor.agentRemoved": { th: "ลบเครื่องแล้ว Key เดิมใช้ไม่ได้อีก", en: "Machine removed. Its key no longer works.", jp: "マシンを削除しました。キーは無効になりました。" },

  "Monitor.responsible": { th: "ผู้ดูแล (แจ้งอีเมลตามลำดับ)", en: "Responsible people (emailed in order)", jp: "担当者（順番にメール通知）" },
  "Monitor.escalation.stepwise": {
    th: "แจ้งลำดับ 1 ทันที ถ้ายังไม่มีใครรับทราบและยังไม่แก้ จะแจ้งลำดับ 2 และ 3 ต่อไป",
    en: "Person 1 is emailed at once; if nobody acknowledges and it is not fixed, persons 2 and 3 follow.",
    jp: "担当者 1 に即時通知し、確認も解決もされない場合は担当者 2、3 に通知します。",
  },
  "Monitor.escalation.allAtOnce": { th: "แจ้งผู้ดูแลทุกลำดับพร้อมกัน", en: "All responsible people are emailed at once.", jp: "全担当者に同時に通知します。" },
  "Monitor.escalation.every": { th: "ส่งต่อลำดับถัดไปทุก", en: "Escalates to the next person every", jp: "次の担当者へのエスカレーション間隔：" },

  "Monitor.recentCommands": { th: "คำสั่งล่าสุด", en: "Recent commands", jp: "最近のコマンド" },
  "Monitor.noCommandsTitle": { th: "ยังไม่มีคำสั่ง", en: "No commands yet", jp: "コマンドはまだありません" },
  "Monitor.noCommandsMessage": { th: "คำสั่ง Start / Stop / Restart จากเว็บจะแสดงที่นี่", en: "Start, stop and restart commands sent from the web appear here.", jp: "Web から送信した起動・停止・再起動がここに表示されます。" },
  "Monitor.commandStatus.Pending": { th: "รอเครื่องรับ", en: "Waiting", jp: "受信待ち" },
  "Monitor.commandStatus.Delivered": { th: "กำลังทำ", en: "Running", jp: "実行中" },
  "Monitor.commandStatus.Succeeded": { th: "สำเร็จ", en: "Succeeded", jp: "成功" },
  "Monitor.commandStatus.Failed": { th: "ไม่สำเร็จ", en: "Failed", jp: "失敗" },
  "Monitor.commandStatus.Expired": { th: "หมดเวลา", en: "Expired", jp: "期限切れ" },
  "Monitor.command.queued": { th: "ส่งคำสั่งแล้ว รอเครื่องดำเนินการ", en: "Command sent; waiting for the machine", jp: "コマンドを送信しました。マシンの実行待ちです" },
  "Monitor.command.succeeded": { th: "ทำคำสั่งสำเร็จ", en: "Command succeeded", jp: "コマンド成功" },
  "Monitor.command.failed": { th: "ทำคำสั่งไม่สำเร็จ", en: "Command failed", jp: "コマンド失敗" },
  "Monitor.command.stillRunning": { th: "เครื่องยังไม่ตอบกลับ ดูผลได้ที่ คำสั่งล่าสุด", en: "No reply yet; check Recent commands", jp: "まだ応答がありません。最近のコマンドを確認してください" },

  "Monitor.history": { th: "ปัญหาที่แก้แล้ว (14 วัน)", en: "Resolved problems (14 days)", jp: "解決済みの問題（14 日間）" },
  "Monitor.historyHint": { th: "ปัญหาที่กลับมาทำงานปกติแล้ว", en: "Problems that have recovered.", jp: "復旧した問題。" },
  "Monitor.noHistoryTitle": { th: "ไม่มีปัญหาในช่วงนี้", en: "No recent problems", jp: "最近の問題はありません" },
  "Monitor.noHistoryMessage": { th: "ไม่มีโปรแกรมหยุดหรือเครื่องขาดการติดต่อใน 14 วันที่ผ่านมา", en: "No program stopped and no machine went offline in the last 14 days.", jp: "過去 14 日間に停止やオフラインはありません。" },
  "Monitor.resolvedAfter": { th: "แก้ไขแล้วภายใน", en: "Resolved after", jp: "解決までの時間：" },

  "Monitor.confirm.Start": { th: "Start โปรแกรม", en: "Start program", jp: "プログラムを起動" },
  "Monitor.confirm.Stop": { th: "Stop โปรแกรม", en: "Stop program", jp: "プログラムを停止" },
  "Monitor.confirm.Restart": { th: "Restart โปรแกรม", en: "Restart program", jp: "プログラムを再起動" },
  "Monitor.confirm.commandMessage": {
    th: "คำสั่งจะถูกส่งไปยัง TMT Control Panel บนเครื่องนี้ และบันทึกไว้ว่าคุณเป็นผู้สั่ง",
    en: "The command goes to TMT Control Panel on this machine and is recorded under your name.",
    jp: "コマンドはこのマシンの TMT Control Panel に送信され、あなたの名前で記録されます。",
  },
  "Monitor.confirm.rotate": { th: "ออก Agent key ใหม่", en: "Issue a new agent key", jp: "新しいエージェントキーを発行" },
  "Monitor.confirm.rotateMessage": {
    th: "Key เดิมจะใช้ไม่ได้ทันที ต้องนำ Key ใหม่ไปใส่ใน TMT Control Panel ของเครื่องนี้",
    en: "The old key stops working at once. Enter the new key in TMT Control Panel on this machine.",
    jp: "旧キーはすぐに無効になります。新しいキーをこのマシンの TMT Control Panel に入力してください。",
  },
  "Monitor.confirm.revoke": { th: "ลบเครื่องออกจาก Site", en: "Remove machine from the site", jp: "サイトからマシンを削除" },
  "Monitor.confirm.revokeMessage": {
    th: "Key ของเครื่องนี้จะใช้ไม่ได้อีก และจะไม่แสดงโปรแกรมของเครื่องนี้ ประวัติยังเก็บไว้",
    en: "This machine's key stops working and its programs are no longer shown. History is kept.",
    jp: "このマシンのキーは無効になり、プログラムは表示されなくなります。履歴は保持されます。",
  },
  "Monitor.confirmButton": { th: "ยืนยัน", en: "Confirm", jp: "確定" },
  "Monitor.working": { th: "กำลังดำเนินการ…", en: "Working…", jp: "処理中…" },

  "Monitor.logs": { th: "Log จาก TMT Control Panel", en: "Logs from TMT Control Panel", jp: "TMT Control Panel のログ" },
  "Monitor.logsHint": { th: "เก็บย้อนหลัง 30 วัน อัปเดตพร้อมหน้าจอ", en: "Kept for 30 days; refreshes with the page.", jp: "30 日間保存。画面と一緒に更新されます。" },
  "Monitor.logLevel": { th: "ระดับ Log", en: "Log level", jp: "ログレベル" },
  "Monitor.logs.Problems": { th: "Error + Warning", en: "Errors & warnings", jp: "エラーと警告" },
  "Monitor.logs.Error": { th: "Error", en: "Errors", jp: "エラー" },
  "Monitor.logs.Warning": { th: "Warning", en: "Warnings", jp: "警告" },
  "Monitor.logs.Info": { th: "Info", en: "Info", jp: "情報" },
  "Monitor.logs.All": { th: "ทั้งหมด", en: "All", jp: "すべて" },
  "Monitor.allMachines": { th: "ทุกเครื่อง", en: "All machines", jp: "すべてのマシン" },
  "Monitor.searchLogs": { th: "ค้นหาข้อความใน Log", en: "Search log messages", jp: "ログメッセージを検索" },
  "Monitor.loadingLogs": { th: "กำลังโหลด Log…", en: "Loading logs…", jp: "ログを読み込み中…" },
  "Monitor.noLogsTitle": { th: "ไม่มี Log", en: "No log lines", jp: "ログはありません" },
  "Monitor.noLogsMessage": { th: "ไม่มี Log ที่ตรงกับตัวกรองนี้", en: "No log lines match this filter.", jp: "この条件に一致するログはありません。" },
  "Monitor.time": { th: "เวลา", en: "Time", jp: "時刻" },
  "Monitor.level": { th: "ระดับ", en: "Level", jp: "レベル" },
  "Monitor.message": { th: "ข้อความ", en: "Message", jp: "メッセージ" },
  "Monitor.level.Info": { th: "Info", en: "Info", jp: "情報" },
  "Monitor.level.Warning": { th: "Warning", en: "Warning", jp: "警告" },
  "Monitor.level.Error": { th: "Error", en: "Error", jp: "エラー" },
  "Monitor.olderLogs": { th: "โหลด Log เก่ากว่านี้", en: "Load older lines", jp: "さらに古いログを読み込む" },

  "Monitor.addMachine": { th: "เพิ่มเครื่อง", en: "Add machine", jp: "マシンを追加" },
  "Monitor.addMachineHint": {
    th: "สร้าง Agent key สำหรับเครื่องหนึ่งเครื่องที่ติดตั้ง TMT Control Panel",
    en: "Creates an agent key for one machine running TMT Control Panel.",
    jp: "TMT Control Panel を実行する 1 台のマシン用にエージェントキーを作成します。",
  },
  "Monitor.machineName": { th: "ชื่อเครื่อง", en: "Machine name", jp: "マシン名" },
  "Monitor.machineNameHint": { th: "ชื่อที่ทีมเรียก เช่น Server หลัก หรือ PC ห้องควบคุม", en: "What the team calls it, e.g. Main server or Control room PC.", jp: "チームでの呼び名（例：メインサーバー、制御室 PC）。" },
  "Monitor.machineNamePlaceholder": { th: "เช่น Server หลัก", en: "e.g. Main server", jp: "例：メインサーバー" },
  "Monitor.createKey": { th: "สร้าง Key", en: "Create key", jp: "キーを作成" },
  "Monitor.keyTitle": { th: "Agent key ของเครื่อง", en: "Machine agent key", jp: "マシンのエージェントキー" },
  "Monitor.keyOnce": {
    th: "แสดงครั้งเดียวเท่านั้น ระบบเก็บเฉพาะค่าแฮช คัดลอกไปใส่ใน TMT Control Panel ตอนนี้",
    en: "Shown only once; only its hash is stored. Copy it into TMT Control Panel now.",
    jp: "表示はこの一度だけです（ハッシュのみ保存）。今すぐ TMT Control Panel にコピーしてください。",
  },
  "Monitor.keySaved": { th: "คัดลอกแล้ว ปิด", en: "I have copied it", jp: "コピーしました" },
  "Monitor.serverUrl": { th: "Server URL", en: "Server URL", jp: "サーバー URL" },
  "Monitor.agentKey": { th: "Agent key", en: "Agent key", jp: "エージェントキー" },
  "Monitor.copy": { th: "คัดลอก", en: "Copy", jp: "コピー" },
  "Monitor.setup.step1": {
    th: "ที่เครื่องนั้น เปิด TMT Control Panel → Admin… → Web monitor…",
    en: "On that machine open TMT Control Panel → Admin… → Web monitor…",
    jp: "そのマシンで TMT Control Panel →「Admin…」→「Web monitor…」を開きます。",
  },
  "Monitor.setup.step2": {
    th: "ใส่ Server URL และ Agent key ด้านบน แล้วกด Test connection",
    en: "Enter the Server URL and agent key above, then press Test connection.",
    jp: "上記のサーバー URL とエージェントキーを入力し、「Test connection」を押します。",
  },
  "Monitor.setup.step3": {
    th: "ติ๊ก Enable และเลือกว่าจะอนุญาตให้สั่ง Start / Stop / Restart จากเว็บหรือไม่ แล้วกด Save",
    en: "Tick Enable, choose whether the web may start, stop and restart programs, then Save.",
    jp: "「Enable」をオンにし、Web からの起動・停止・再起動を許可するか選んで保存します。",
  },

  "Monitor.siteName": { th: "ชื่อ Site", en: "Site name", jp: "サイト名" },
  "Monitor.siteNamePlaceholder": { th: "เช่น โรงงาน A - ระยอง", en: "e.g. Plant A - Rayong", jp: "例：工場 A - ラヨーン" },
  "Monitor.location": { th: "สถานที่", en: "Location", jp: "場所" },
  "Monitor.description": { th: "หมายเหตุ", en: "Notes", jp: "メモ" },
  "Monitor.contact.1": { th: "ผู้ดูแลลำดับ 1 (แจ้งทันที)", en: "Responsible #1 (emailed at once)", jp: "担当者 1（即時通知）" },
  "Monitor.contact.2": { th: "ผู้ดูแลลำดับ 2", en: "Responsible #2", jp: "担当者 2" },
  "Monitor.contact.3": { th: "ผู้ดูแลลำดับ 3", en: "Responsible #3", jp: "担当者 3" },
  "Monitor.contactNone": { th: "— ไม่ระบุ —", en: "— none —", jp: "— なし —" },
  "Monitor.escalationMinutes": { th: "ส่งต่อลำดับถัดไปทุก (นาที)", en: "Escalate every (minutes)", jp: "エスカレーション間隔（分）" },
  "Monitor.escalationHint": { th: "0 = แจ้งทุกลำดับพร้อมกัน", en: "0 = email everyone at once", jp: "0 = 全員に同時通知" },
  "Monitor.offlineMinutes": { th: "ถือว่าเครื่องขาดการติดต่อหลัง (นาที)", en: "Machine offline after (minutes)", jp: "オフライン判定（分）" },
  "Monitor.offlineHint": { th: "เครื่องส่งข้อมูลทุก 15 วินาที", en: "Machines report every 15 seconds.", jp: "マシンは 15 秒ごとに報告します。" },
  "Monitor.siteActive": { th: "การเฝ้าระวัง", en: "Monitoring", jp: "監視" },
  "Monitor.siteActiveHint": { th: "เปิดใช้งาน (ปิดแล้วจะไม่ส่งอีเมลและสั่งงานไม่ได้)", en: "Active (when off, no emails are sent and programs cannot be controlled)", jp: "有効（オフの場合はメール通知も操作もしません）" },
  "Monitor.siteSaved": { th: "บันทึก Site แล้ว", en: "Site saved", jp: "サイトを保存しました" },
  "Monitor.validation.name": { th: "กรุณาใส่ชื่อ Site", en: "Enter a site name.", jp: "サイト名を入力してください。" },
  "Monitor.validation.escalation": { th: "ระยะส่งต่อต้องเป็น 0–1440 นาที", en: "Escalation must be 0–1440 minutes.", jp: "エスカレーション間隔は 0〜1440 分です。" },
  "Monitor.validation.offline": { th: "เวลาถือว่าขาดการติดต่อต้องเป็น 1–120 นาที", en: "Offline time must be 1–120 minutes.", jp: "オフライン判定は 1〜120 分です。" },
  "Monitor.validation.duplicateContact": { th: "เลือกคนเดียวกันซ้ำหลายลำดับไม่ได้", en: "Choose a different person for each step.", jp: "各順番に別の担当者を選んでください。" },
  "Monitor.validation.noContact": { th: "ยังไม่มีผู้ดูแล จะไม่มีใครได้รับอีเมลแจ้งปัญหา", en: "No responsible person: nobody will be emailed about problems.", jp: "担当者がいないため、問題のメールは誰にも届きません。" },
};
