"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { apiRequest, downloadSupportAttachment, uploadSupportAttachment } from '../api-client';
import { localeFor, useLanguage } from '../i18n';
import { Icon } from '../ui';
import { supportLabel } from '../support-copy';
import { supportError, supportMeta, supportRead, supportRequestKey, type ContributionPage, type SupportMeta, type SupportPage, type SupportTicket } from '../support-client';
import './support-center.css';

const statuses=['New','Acknowledged','InProgress','WaitingForReporter','Resolved','Closed','Cancelled'];
const categories=['Application','Equipment','Documents','Coordination','Other'];
const useCopy=()=>{const {lang}=useLanguage();return {s:(key:string)=>supportLabel(key,lang),lang,date:(value:string)=>new Date(value).toLocaleString(localeFor(lang))};};
function SelectField({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){return <label className="support-field">{label}<select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
function PageButtons({page,total,size,onPage}:{page:number;total:number;size:number;onPage:(page:number)=>void}){const {s}=useCopy();return <div className="support-pagination"><span>{total?Math.min((page-1)*size+1,total):0}–{Math.min(page*size,total)} / {total}</span><button className="btn default sm" type="button" disabled={page<=1} onClick={()=>onPage(page-1)}>{s('Previous')}</button><span>{page} / {Math.max(1,Math.ceil(total/size))}</span><button className="btn default sm" type="button" disabled={page*size>=total} onClick={()=>onPage(page+1)}>{s('Next')}</button></div>;}
function SupportDialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);const {s}=useCopy();
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement;dialog?.showModal();return()=>{dialog?.close();if(previous instanceof HTMLElement)previous.focus();};},[]);
 return <dialog ref={ref} className="support-dialog support-center" onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}><header><h2>{title}</h2><button className="icon-btn" type="button" aria-label={s('Close')} onClick={onClose}><Icon name="x" /></button></header>{children}</dialog>;
}

export function SupportCreateDialog({context,onClose,onCreated,onOpen}:{context:Record<string,string>;onClose:()=>void;onCreated:(id:number)=>void;onOpen:(id:number)=>void}) {
 const {s,lang}=useCopy();const [category,setCategory]=useState('Application'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[impact,setImpact]=useState('CanWork'),[includeContext,setIncludeContext]=useState(true),[steps,setSteps]=useState(''),[expected,setExpected]=useState(''),[location,setLocation]=useState('');
 const [files,setFiles]=useState<{file:File;key:string;done:boolean}[]>([]),[created,setCreated]=useState<SupportTicket|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uploadName,setUploadName]=useState('');
 const request=useRef<{body:string;key:string}|null>(null),saving=useRef(false);
 const dirty=!created&&Boolean(subject||description||files.length||steps||expected||location);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||busy)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,busy]);
 const close=()=>{if(!busy&&(!dirty||window.confirm(s('Discard changes?'))))onClose();};
 const submit=async()=>{
  if(saving.current)return;saving.current=true;setBusy(true);setError('');
  try {
   let ticket=created;
   if(!ticket){const body={category,subject,description,impact,context:{...(category==='Application'&&includeContext?context:{}),...(category==='Application'?{steps,expected}:{location})}},signature=JSON.stringify(body);if(request.current?.body!==signature)request.current={body:signature,key:supportRequestKey()};ticket=await apiRequest<SupportTicket>('/api/v1/support/tickets',{method:'POST',body:JSON.stringify({...body,requestKey:request.current.key})});setCreated(ticket);onCreated(ticket.id);}
   for(const item of files.filter(f=>!f.done)){setUploadName(item.file.name);await uploadSupportAttachment(ticket.id,item.file,item.key);setFiles(old=>old.map(f=>f.key===item.key?{...f,done:true}:f));}
  }catch(e){setError(supportError(e,lang));}finally{setBusy(false);saving.current=false;setUploadName('');}
 };
 return <SupportDialog title={s('Report a problem')} onClose={close}><form onSubmit={e=>{e.preventDefault();void submit();}}>
  {created?<div className="support-thanks" role="status"><h3>{s('Thank you for reporting')}</h3><p>{created.ticketNo}</p><p>{s('Thank-you points')}: {s('Pending review')}</p><button className="btn default" type="button" disabled={busy} onClick={()=>onOpen(created.id)}>{s('View ticket')}</button></div>:<fieldset disabled={busy}><div className="support-grid"><SelectField label={s('Category')} value={category} onChange={setCategory} options={categories.map(v=>({value:v,label:s(v)}))}/><SelectField label={s('Impact')} value={impact} onChange={setImpact} options={['CanWork','PartlyBlocked','Blocked'].map(v=>({value:v,label:s(v)}))}/></div>
  <label className="support-field">{s('Subject')} *<input required minLength={5} maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)}/></label>
  <label className="support-field">{s('Description')} *<textarea required minLength={10} maxLength={5000} rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label>
  {category==='Application'?<>{includeContext&&context.module?<div className="support-context"><span>{s('Page context')}: {context.module} {context.reference??''}</span><button type="button" className="btn ghost sm" onClick={()=>setIncludeContext(false)}>{s('Remove')}</button></div>:null}<details><summary>{s('Steps')}</summary><label className="support-field">{s('Steps')}<textarea maxLength={600} rows={2} value={steps} onChange={e=>setSteps(e.target.value)}/></label><label className="support-field">{s('Expected')}<textarea maxLength={600} rows={2} value={expected} onChange={e=>setExpected(e.target.value)}/></label></details></>:<label className="support-field">{s('Location')}<input maxLength={160} value={location} onChange={e=>setLocation(e.target.value)}/></label>}
  <label className="support-field">{s('Attachments')}<input type="file" accept=".png,.jpg,.jpeg,.pdf" multiple onChange={e=>{const selected=[...e.target.files??[]];if(selected.length>5||selected.some(f=>f.size>10*1024*1024)){setError(s('File limits'));e.target.value='';return;}setError('');setFiles(selected.map(file=>({file,key:supportRequestKey(),done:false})));}}/><small>{s('File limits')}</small></label></fieldset>}
  {created&&files.some(f=>!f.done)?<div className="support-upload-status"><p>{s(error?'Upload failed':'Uploading')}</p><ul>{files.filter(f=>!f.done).map(f=><li key={f.key}>{f.file.name}</li>)}</ul></div>:null}
  {busy&&uploadName?<p role="status">{s('Uploading')} {uploadName}</p>:null}{error?<div className="callout error" role="alert">{error}</div>:null}
  <div className="support-actions"><button className="btn default" type="button" disabled={busy} onClick={close}>{s('Close')}</button>{!created||files.some(f=>!f.done)?<button className="btn primary" disabled={busy} type="submit">{busy?s('Loading'):s(created?'Retry uploads':'Submit ticket')}</button>:null}</div>
 </form></SupportDialog>;
}

export function SupportCenter({ticketId,onSelect,onCreate,notify,onDirtyChange,externalRevision=0}:{ticketId:number|null;onSelect:(id:number|null)=>void;onCreate:()=>void;notify:(message:string)=>void;onDirtyChange:(dirty:boolean)=>void;externalRevision?:number}) {
 const {s,lang,date}=useCopy();const [meta,setMeta]=useState<SupportMeta|null>(null),[mode,setMode]=useState('mine'),[page,setPage]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[filter,setFilter]=useState(''),[list,setList]=useState<SupportPage>({items:[],page:1,pageSize:50,total:0}),[contributions,setContributions]=useState<ContributionPage|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const requestId=useRef(0);
 useEffect(()=>{let cancelled=false;supportMeta().then(m=>{if(!cancelled)setMeta(m);}).catch(e=>{if(!cancelled)setError(supportError(e,lang));});return()=>{cancelled=true;};},[lang,revision]);
 useEffect(()=>{
  const id=++requestId.current;const timer=setTimeout(()=>{setLoading(true);setError('');const query=new URLSearchParams({scope:mode,page:String(page),search,status,category,filter});
   const load=mode==='contributions'?apiRequest<ContributionPage>(`/api/v1/me/support-contributions?page=${page}`).then(r=>{if(id===requestId.current)setContributions(r);}):mode==='members'?Promise.resolve():apiRequest<SupportPage>(`/api/v1/support/tickets?${query}`).then(r=>{if(id===requestId.current)setList(r);});
   void load.catch(e=>{if(id===requestId.current)setError(supportError(e,lang));}).finally(()=>{if(id===requestId.current)setLoading(false);});
  },200);return()=>{clearTimeout(timer);requestId.current=id+1;};
 },[mode,page,search,status,category,filter,revision,lang,ticketId,externalRevision]);
 const refresh=()=>setRevision(v=>v+1);
 if(ticketId!==null)return <SupportTicketView key={ticketId} id={ticketId} meta={meta} onBack={()=>onSelect(null)} notify={notify} onDirtyChange={onDirtyChange}/>;
 return <section className="support-center"><div className="support-heading"><div><h2>{s('Support Center')}</h2><p>{s('Thank you for reporting')}</p></div><button className="btn primary" type="button" onClick={onCreate}><Icon name="plus"/>{s('Report a problem')}</button></div>
 <div className="support-toolbar"><div className="support-tabs">{['mine',...(meta?.queue?['queue']:[]),'contributions',...(meta?.manage?['members']:[])].map(m=><button key={m} type="button" className={mode===m?'active':''} aria-pressed={mode===m} onClick={()=>{setMode(m);setPage(1);}}>{s(m==='mine'?'My tickets':m==='queue'?'Support queue':m==='contributions'?'Contribution history':'Support members')}</button>)}</div><button className="support-refresh" type="button" onClick={refresh}><Icon name="refresh"/>{s('Refresh')}</button></div>
 {error?<div className="callout error" role="alert">{error}</div>:null}
 {mode==='members'&&meta?.manage?<SupportMembers meta={meta} onSaved={refresh}/>:mode==='contributions'?<><div className="support-thanks"><h3>{s('Total points')}: {contributions?.points??'—'} {s('points')}</h3></div>{loading?<p role="status">{s('Loading')}</p>:contributions?.items.map(item=><article className="support-contribution" key={item.ticketId}><div><button className="support-link" type="button" onClick={()=>onSelect(item.ticketId)}>{item.ticketNo}</button><p>{item.message}</p><small>{item.evaluatorName} · {date(item.updatedAt)}</small></div><strong>{item.points?`+${item.points} ${s('points')}`:s('Thanked')}</strong></article>)}{contributions?<PageButtons page={page} total={contributions.total} size={50} onPage={setPage}/>:null}</>:<>
 <div className="support-filters"><label className="support-field">{s('Search')}<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><SelectField label={s('Status')} value={status} onChange={v=>{setStatus(v);setPage(1);}} options={[{value:'',label:s('All')},...statuses.map(v=>({value:v,label:s(v)}))]}/><SelectField label={s('Category')} value={category} onChange={v=>{setCategory(v);setPage(1);}} options={[{value:'',label:s('All')},...categories.map(v=>({value:v,label:s(v)}))]}/>{mode==='queue'?<SelectField label={s('Assignee')} value={filter} onChange={v=>{setFilter(v);setPage(1);}} options={[{value:'',label:s('All')},{value:'unassigned',label:s('Unassigned')},{value:'assigned',label:s('Assigned to me')}]}/>:null}</div>
 {loading?<p role="status">{s('Loading')}</p>:list.items.length?<div className="table-wrap"><table><thead><tr>{['Subject','Status','Assignee','Thank-you points','Updated'].map(k=><th key={k}>{s(k)}</th>)}</tr></thead><tbody>{list.items.map(item=><tr key={item.id}><td><button className="support-link" type="button" onClick={()=>onSelect(item.id)}>{item.ticketNo} · {item.subject}</button><small className="support-meta">{s(item.category)} · {s(item.impact)}</small></td><td><span className={`support-badge ${item.status}`}>{s(item.status)}</span><small className="support-meta">{s(item.priority)}</small></td><td>{item.assigneeName??s('Unassigned')}</td><td>{item.recognitionPoints==null?s('Pending review'):item.recognitionPoints?`+${item.recognitionPoints}`:s('Thanked')}</td><td>{date(item.updatedAt)}</td></tr>)}</tbody></table></div>:!error?<div className="empty">{s('Empty')}</div>:null}<PageButtons page={page} total={list.total} size={50} onPage={setPage}/></>}
 </section>;
}

function SupportTicketView({id,meta,onBack,notify,onDirtyChange}:{id:number;meta:SupportMeta|null;onBack:()=>void;notify:(message:string)=>void;onDirtyChange:(dirty:boolean)=>void}) {
 const {s,lang,date}=useCopy();const [ticket,setTicket]=useState<SupportTicket|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState(''),[message,setMessage]=useState(''),[internal,setInternal]=useState(false),[reason,setReason]=useState(''),[target,setTarget]=useState('InProgress'),[assignee,setAssignee]=useState(''),[category,setCategory]=useState(''),[priority,setPriority]=useState('Normal'),[duplicate,setDuplicate]=useState(''),[file,setFile]=useState<{file:File;key:string}|null>(null),[fileInternal,setFileInternal]=useState(false),[useful,setUseful]=useState(false),[detailed,setDetailed]=useState(false),[actionable,setActionable]=useState(false),[thanks,setThanks]=useState('');
 const pending=useRef<{signature:string;key:string}|null>(null),locked=useRef(false);
 const dirty=Boolean(message||reason||thanks||file||action);
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||busy)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,busy]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setTicket(await supportRead(id));}catch(e){setTicket(null);setError(supportError(e,lang));}finally{setLoading(false);}},[id,lang]);
 useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>{setLoading(true);supportRead(id).then(r=>{if(!cancelled)setTicket(r);}).catch(e=>{if(!cancelled)setError(supportError(e,lang));}).finally(()=>{if(!cancelled)setLoading(false);});},0);return()=>{cancelled=true;clearTimeout(timer);};},[id,lang]);
 const reset=()=>{setAction('');setReason('');setThanks('');setMessage('');setDuplicate('');setInternal(false);setFileInternal(false);};
 const mutate=async(kind:string,body:Record<string,unknown>)=>{
  if(!ticket||locked.current)return;locked.current=true;setBusy(true);setError('');
  try {const signature=JSON.stringify({kind,...body});if(pending.current?.signature!==signature)pending.current={signature,key:supportRequestKey()};const result=await apiRequest<SupportTicket>(`/api/v1/support/tickets/${id}/${kind}`,{method:'POST',body:JSON.stringify({...body,rowVersion:ticket.rowVersion,requestKey:pending.current.key})});setTicket(result);pending.current=null;reset();notify(s('Saved'));}catch(e){setError(supportError(e,lang));}finally{setBusy(false);locked.current=false;}
 };
 const upload=async()=>{if(!file||locked.current)return;locked.current=true;setBusy(true);setError('');try{await uploadSupportAttachment(id,file.file,file.key,fileInternal);setFile(null);setTicket(await supportRead(id));notify(s('Saved'));}catch(e){setError(supportError(e,lang));}finally{setBusy(false);locked.current=false;}};
 const download=async(fileId:number,name:string)=>{setError('');try{const blob=await downloadSupportAttachment(id,fileId),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(supportError(e,lang));}};
 const showAction=(value:string)=>{if(dirty&&!window.confirm(s('Discard changes?')))return;reset();setAction(value);if(ticket){setAssignee(ticket.assigneeId===null?'':String(ticket.assigneeId));setCategory(ticket.category);setPriority(ticket.priority);setUseful(ticket.recognition?.useful??false);setDetailed(ticket.recognition?.detailed??false);setActionable(ticket.recognition?.actionable??false);setThanks(ticket.recognition?.message??'');setTarget(ticket.status==='New'?'Acknowledged':'InProgress');}};
 const goBack=()=>{if(!busy&&(!dirty||window.confirm(s('Discard changes?')))){onDirtyChange(false);onBack();}};
 const actionTargets=ticket?Array.from(new Set([...(ticket.permissions.operate?({New:['Cancelled'],Acknowledged:['InProgress','WaitingForReporter','Resolved','Cancelled'],InProgress:['WaitingForReporter','Resolved','Cancelled'],WaitingForReporter:['InProgress','Resolved','Cancelled'],Resolved:['InProgress',...(ticket.permissions.assign?['Closed']:[])],Closed:['InProgress'],Cancelled:[]} as Record<string,string[]>)[ticket.status]??[]:[]),...(ticket.permissions.own?ticket.status==='Resolved'?['Closed','InProgress','Cancelled']:ticket.status==='Closed'?['InProgress']:ticket.status!=='Cancelled'?['Cancelled']:[]:[])])):[];
 return <section className="support-center"><div className="support-heading"><button type="button" className="btn default" disabled={busy} onClick={goBack}>← {s('Back')}</button><div className="support-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>void load()}>{s('Refresh')}</button><button className="btn ghost" type="button" onClick={()=>{const link=`${window.location.origin}${window.location.pathname}#support/${id}`;if(navigator.clipboard)void navigator.clipboard.writeText(link).then(()=>notify(s('Copied'))).catch(()=>setError(s('Failed')));else window.prompt(s('Shareable link'),link);}}>{s('Shareable link')}</button></div></div>
 {error?<div className="callout error" role="alert">{error}</div>:null}{loading?<p role="status">{s('Loading')}</p>:null}
 {ticket?<><div className="support-heading"><div><small>{ticket.ticketNo}</small><h2>{ticket.subject}</h2></div><span className={`support-badge ${ticket.status}`}>{s(ticket.status)}</span></div><div className="support-detail-grid"><div><article className="support-panel"><h3>{s('Description')}</h3><p className="support-pre">{ticket.description}</p>{Object.entries(ticket.context).filter(([,v])=>v).map(([k,v])=><div key={k} className="support-context"><strong>{s(({module:'Page context',reference:'Page context',steps:'Steps',expected:'Expected',location:'Location'} as Record<string,string>)[k]??k)}</strong><span className="support-pre">{k==='module'?s(v):v}</span></div>)}</article>
 <article className="support-panel"><h3>{s('Attachments')}</h3>{ticket.attachments.map(f=><div key={f.id} className="support-file"><button type="button" className="support-link" onClick={()=>void download(f.id,f.name)}>{f.name}</button><small>{Math.ceil(f.sizeBytes/1024)} KB {f.internal?`· ${s('Internal attachment')}`:''}</small></div>)}{ticket.permissions.comment?<><label className="support-field">{s('Upload')}<input key={file?.key??'empty'} type="file" disabled={busy} accept=".png,.jpg,.jpeg,.pdf" onChange={e=>{const selected=e.target.files?.[0];if(selected){if(selected.size>(meta?.maxFileBytes??10485760)){setError(s('File limits'));return;}setFile({file:selected,key:supportRequestKey()});}}}/><small>{s('File limits')}</small></label>{ticket.permissions.internal?<label className="support-check"><input type="checkbox" checked={fileInternal} onChange={e=>setFileInternal(e.target.checked)}/>{s('Internal attachment')}</label>:null}<button className="btn default" disabled={!file||busy} type="button" onClick={()=>void upload()}>{s('Upload')}</button></>:null}</article>
 <article className="support-panel"><h3>{s('Conversation')}</h3>{ticket.events.map(event=><div key={event.id} className={`support-event ${event.internal?'internal':''}`}><small>{event.actorName} · {date(event.createdAt)} · {s(event.kind)}{event.internal?` · ${s('Internal note')}`:''}</small>{event.details.to?<p>{s(String(event.details.from))} → {s(String(event.details.to))}</p>:null}{event.body?<p className="support-pre">{event.body}</p>:null}{typeof event.details.points==='number'?<p>{s('Thank-you points')}: {event.details.points}{typeof event.details.delta==='number'?` (${event.details.delta>=0?'+':''}${event.details.delta})`:''}</p>:null}{typeof event.details.reason==='string'?<p className="support-pre">{s('Reason')}: {event.details.reason}</p>:null}</div>)}{ticket.permissions.comment?<form onSubmit={e=>{e.preventDefault();void mutate('comments',{message,internal});}}><label className="support-field">{s('Reply')}<textarea required maxLength={5000} rows={3} value={message} disabled={busy} onChange={e=>setMessage(e.target.value)}/></label>{ticket.permissions.internal?<label className="support-check"><input type="checkbox" checked={internal} disabled={busy} onChange={e=>setInternal(e.target.checked)}/>{s('Internal note')}</label>:null}<button type="submit" className="btn primary" disabled={busy||!message.trim()}>{s('Send')}</button></form>:null}</article>
 </div><aside><article className="support-panel"><dl>{[['Reporter',ticket.reporterName],['Assignee',ticket.assigneeName??s('Unassigned')],['Category',s(ticket.category)],['Impact',s(ticket.impact)],['Priority',s(ticket.priority)]].map(([k,v])=><div key={k}><dt>{s(k)}</dt><dd>{v}</dd></div>)}</dl><div className="support-stack">{ticket.permissions.claim?<button className="btn default" type="button" disabled={busy} onClick={()=>showAction('claim')}>{s('Take ticket')}</button>:null}{ticket.permissions.assign?<button className="btn default" type="button" disabled={busy} onClick={()=>showAction('assign')}>{s('Assign ticket')}</button>:null}{actionTargets.length?<button className="btn default" type="button" disabled={busy} onClick={()=>{showAction('transition');setTarget(actionTargets[0]!);}}>{s('Change status')}</button>:null}</div></article>
 <article className="support-panel support-thanks"><h3>{s('Thank-you points')}</h3>{ticket.recognition?<><strong>{ticket.recognition.points?`+${ticket.recognition.points} ${s('points')}`:s('Thanked')}</strong><p className="support-pre">{ticket.recognition.message}</p><ul>{ticket.recognition.useful?<li>{s('Useful')}</li>:null}{ticket.recognition.detailed?<li>{s('Detailed')}</li>:null}{ticket.recognition.actionable?<li>{s('Actionable')}</li>:null}</ul><small>{s('Awarded by')} {ticket.recognition.evaluatorName} · {date(ticket.recognition.updatedAt)}</small></>:<p>{s('Pending review')}</p>}{ticket.permissions.award&&!ticket.recognition?<button type="button" className="btn primary" disabled={busy} onClick={()=>showAction('recognition')}>{s('Thank reporter')}</button>:ticket.permissions.adjust&&ticket.recognition?<button type="button" className="btn default" disabled={busy} onClick={()=>showAction('recognition/adjust')}>{s('Adjust recognition')}</button>:null}</article>
 </aside></div>
 {action?<SupportActionForm action={action} ticket={ticket} meta={meta} busy={busy} reason={reason} setReason={setReason} assignee={assignee} setAssignee={setAssignee} category={category} setCategory={setCategory} priority={priority} setPriority={setPriority} target={target} setTarget={setTarget} targets={actionTargets} duplicate={duplicate} setDuplicate={setDuplicate} criteria={{useful,detailed,actionable}} setCriteria={(key,value)=>{if(key==='useful'){setUseful(value);if(!value){setDetailed(false);setActionable(false);}}else if(key==='detailed')setDetailed(value);else setActionable(value);}} thanks={thanks} setThanks={setThanks} onClose={()=>{if(!busy&&window.confirm(s('Discard changes?')))reset();}} onSave={body=>void mutate(action==='claim'?'assign':action,body)} error={error}/>:null}
 </>:null}</section>;
}

type ActionProps={action:string;ticket:SupportTicket;meta:SupportMeta|null;busy:boolean;reason:string;setReason:(v:string)=>void;assignee:string;setAssignee:(v:string)=>void;category:string;setCategory:(v:string)=>void;priority:string;setPriority:(v:string)=>void;target:string;setTarget:(v:string)=>void;targets:string[];duplicate:string;setDuplicate:(v:string)=>void;criteria:{useful:boolean;detailed:boolean;actionable:boolean};setCriteria:(key:'useful'|'detailed'|'actionable',value:boolean)=>void;thanks:string;setThanks:(v:string)=>void;onClose:()=>void;onSave:(body:Record<string,unknown>)=>void;error:string};
function SupportActionForm(p:ActionProps){const {s}=useCopy();const recognition=p.action.startsWith('recognition');const self=p.meta?.userId??null;
 const submit=()=>p.onSave(recognition?{...p.criteria,message:p.thanks,reason:p.reason,recognitionVersion:p.ticket.recognition?.rowVersion}:p.action==='transition'?{status:p.target,reason:p.reason,...(p.duplicate?{duplicateOf:Number(p.duplicate)}:{})}:{assigneeId:p.action==='claim'?self:p.assignee?Number(p.assignee):null,category:p.action==='claim'?p.ticket.category:p.category,priority:p.action==='claim'?p.ticket.priority:p.priority,reason:p.reason});
 const available=p.meta?[...p.meta.users.filter(u=>u.canManage),...p.meta.members.filter(m=>m.category_code===p.category)].filter((u,index,list)=>list.findIndex(x=>x.id===u.id)===index):[];
 return <SupportDialog title={s(recognition?'Thank reporter':p.action==='transition'?'Change status':p.action==='claim'?'Take ticket':'Assign ticket')} onClose={p.onClose}><form onSubmit={e=>{e.preventDefault();submit();}}><fieldset disabled={p.busy}>
 {recognition?<><p>{p.ticket.reporterName} · {p.ticket.ticketNo}</p>{(['useful','detailed','actionable'] as const).map(key=><label key={key} className="support-score-check"><input type="checkbox" checked={p.criteria[key]} disabled={key!=='useful'&&!p.criteria.useful} onChange={e=>p.setCriteria(key,e.target.checked)}/>{s(key==='useful'?'Useful':key==='detailed'?'Detailed':'Actionable')}</label>)}<div className="support-thanks">{p.criteria.useful?`+${5+(p.criteria.detailed?3:0)+(p.criteria.actionable?2:0)} / 10 ${s('points')}`:s('Thank without points')}</div><label className="support-field">{s('Thank-you message')} *<textarea required minLength={10} maxLength={1000} rows={4} value={p.thanks} onChange={e=>p.setThanks(e.target.value)}/></label><p className="support-meta">{s('Policy note')}</p></>:p.action==='transition'?<><SelectField label={s('Status')} value={p.target} onChange={p.setTarget} options={p.targets.map(v=>({value:v,label:s(v)}))}/>{p.ticket.permissions.assign&&p.target==='Cancelled'?<label className="support-field">{s('Duplicate ticket ID')}<input type="number" min={1} value={p.duplicate} onChange={e=>p.setDuplicate(e.target.value)}/></label>:null}</>:p.action==='assign'?<><SelectField label={s('Category')} value={p.category} onChange={v=>{p.setCategory(v);p.setAssignee('');}} options={categories.map(v=>({value:v,label:s(v)}))}/><SelectField label={s('Assignee')} value={p.assignee} onChange={p.setAssignee} options={[{value:'',label:s('Unassigned')},...available.map(u=>({value:String(u.id),label:u.name}))]}/><SelectField label={s('Priority')} value={p.priority} onChange={p.setPriority} options={['Low','Normal','High','Urgent'].map(v=>({value:v,label:s(v)}))}/></>:<p>{s('Take ticket')} · {p.ticket.ticketNo}</p>}
 {!recognition||p.action==='recognition/adjust'?<label className="support-field">{s(p.action==='recognition/adjust'?'Adjustment reason':'Reason')} *<textarea required minLength={p.action==='recognition/adjust'?10:1} maxLength={1000} rows={3} value={p.reason} onChange={e=>p.setReason(e.target.value)}/></label>:null}
 </fieldset>{p.error?<div className="callout error" role="alert">{p.error}</div>:null}<div className="support-actions"><button className="btn default" type="button" disabled={p.busy} onClick={p.onClose}>{s('Cancel')}</button><button className="btn primary" type="submit" disabled={p.busy||p.action==='claim'&&self===null}>{s(p.action==='recognition/adjust'?'Adjust recognition':recognition?p.criteria.useful?'Award points':'Thank without points':'Save')}</button></div></form></SupportDialog>;
}

function SupportMembers({meta,onSaved}:{meta:SupportMeta;onSaved:()=>void}){const {s,lang}=useCopy();const [category,setCategory]=useState('Application'),[user,setUser]=useState(''),[award,setAward]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async(userId:number,enabled:boolean,canAward:boolean,categoryCode=category)=>{if(busy)return;setBusy(true);setError('');try{await apiRequest('/api/v1/support/members',{method:'POST',body:JSON.stringify({category:categoryCode,userId,enabled,canAward})});onSaved();}catch(e){setError(supportError(e,lang));}finally{setBusy(false);}};
 return <article className="support-panel"><h3>{s('Support members')}</h3><form onSubmit={e=>{e.preventDefault();void save(Number(user),true,award);}}><div className="support-grid"><SelectField label={s('Category')} value={category} onChange={setCategory} options={categories.map(v=>({value:v,label:s(v)}))}/><SelectField label={s('Member')} value={user} onChange={setUser} options={[{value:'',label:'—'},...meta.users.map(u=>({value:String(u.id),label:u.name}))]}/></div><label className="support-check"><input type="checkbox" checked={award} onChange={e=>setAward(e.target.checked)}/>{s('Can award')}</label><button type="submit" className="btn primary" disabled={busy||!user}>{s('Enable member')}</button></form>{error?<div className="callout error" role="alert">{error}</div>:null}<div className="table-wrap"><table><thead><tr>{['Category','Member','Can award','Remove member'].map(k=><th key={k}>{s(k)}</th>)}</tr></thead><tbody>{meta.members.map(m=><tr key={`${m.category_code}-${m.id}`}><td>{s(m.category_code)}</td><td>{m.name}</td><td>{m.can_award?'✓':'—'}</td><td><button className="btn ghost" type="button" disabled={busy} onClick={()=>void save(m.id,false,false,m.category_code)}>{s('Remove member')}</button></td></tr>)}</tbody></table></div></article>;
}
