"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {useLanguage,localeFor,useT} from '../i18n';
import {Icon} from '../ui';
import {apiRequest} from '../api-client';
import {activityRead,activityWrite,activityRequestKey,bangkokDay,activityModuleLabels,type ActivityMeta,type ActivityOverview,type ActivityDetail,type ActivityRule,type ActivityScore} from '../activity-client';
import './team-activity.css';

const useCopy=()=>{const {lang}=useLanguage();return {s:(th:string,en:string,jp:string)=>lang==='TH'?th:lang==='JP'?jp:en,date:(v:string|null)=>v?new Date(v).toLocaleString(localeFor(lang),{timeZone:'Asia/Bangkok',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—'};};
const number=(v:number|null|undefined)=>v==null?'—':v.toFixed(1);
function ZeroEvidenceNote(){const {s}=useCopy();return <p className="activity-note">{s('หากไม่มีการอัปเดตเลยตลอดรอบ ให้ 0 ทั้งสามด้านพร้อมระบุเหตุผลได้โดยไม่เลือกหลักฐาน ระบบจะตรวจสอบก่อนบันทึก','If there are no updates in the entire cycle, enter zero in all three areas and explain why. The system verifies this before saving without evidence.','期間全体に更新がない場合は、3項目をすべて0にして理由を記入してください。根拠なしでの保存前にシステムが確認します。')}</p>;}
function Status({value}:{value:string}){const {s}=useCopy();const labels:Record<string,string>={NO_DATA:s('ไม่มีข้อมูล','No data','データなし'),EXEMPT:s('ยกเว้น / วันหยุด','Exempt / holiday','対象外・休日'),NOT_REQUIRED:s('ไม่มีงานถึงรอบรายงาน','No report due','報告予定なし'),PENDING:s('รออัปเดต','Awaiting update','更新待ち'),ON_TIME:s('อัปเดตตรงเวลา','Updated on time','期限内に更新'),LATE:s('อัปเดตช้า','Updated late','遅れて更新'),MISSING:s('เลยกำหนดอัปเดต','Update overdue','更新期限超過')};return <span className={`activity-status ${value}`}>{labels[value]??value}</span>;}
function ScoreCard({score}:{score:ActivityScore}){const {s}=useCopy();return <section className="activity-box"><div className="activity-actions"><h3>{s('คะแนนวินัยการอัปเดตงาน','Work Update Score','業務更新スコア')}</h3><span className="activity-status">{score.frozen?s('รับรองแล้ว','Finalized','確定済み'):score.mode==='TRIAL'?s('รอบทดลอง','Trial cycle','試行期間'):s('มีผลต่อ KPI 10%','10% of KPI','KPIの10%')}</span></div><div className="activity-score"><strong>{number(score.total)}</strong><span>/ 100</span></div><div className="activity-breakdown"><div>{s('ตรงเวลา','Timeliness','期限遵守')}<strong>{number(score.timeliness)} / 60</strong></div><div>{s('ครบทุกงาน','Coverage','報告網羅率')}<strong>{number(score.coverage)} / 25</strong></div><div>{s('คุณภาพ','Quality','品質')}<strong>{number(score.quality)} / 15</strong></div></div><p className="activity-note">{score.eligibleDays} {s('วันที่ประเมินได้ · ขั้นต่ำ 10 วัน','assessed days · minimum 10 days','評価対象日・最低10日')}<br/>{score.quality===null?s('รอหัวหน้าประเมินคุณภาพ คะแนนอัตโนมัติ','Quality review pending. Automatic score','品質評価待ち。自動スコア')+` ${number(score.automatic)} / 85`:s('ระดับคะแนน','Rating','評価')+` ${number(score.rating)} / 5`}</p>{!score.eligible&&<div className="activity-banner">{s('ข้อมูลยังไม่ถึง 10 วัน ใช้ KPI เดิม 100% สำหรับรอบที่มีข้อมูลไม่พอ','Fewer than 10 assessed days. Existing KPI retains 100% weight when data is insufficient.','評価対象日が10日未満の場合、従来KPIを100%使用します。')}</div>}<p className="activity-note">{s('สูตร v1: ตรงเวลา 1 · ช้าภายในวัน 0.5 · ขาด/ย้อนหลัง 0 | วันที่ยังไม่หมดเวลายังไม่รวมคะแนน','Formula v1: on time 1 · same-day late 0.5 · missing/backdated 0. Today is excluded until its deadlines pass.','計算式v1：期限内1・当日遅延0.5・未報告/過去分0。当日は締切後に算入。')}</p></section>;}

export function TeamActivityScreen({initialSelf=false,openSource}:{initialSelf?:boolean;openSource?:(type:string,id:number,projectId:number|null)=>void}){
 const {s,date}=useCopy();const [meta,setMeta]=useState<ActivityMeta|null>(null),[overview,setOverview]=useState<ActivityOverview|null>(null),[day,setDay]=useState(bangkokDay()),[project,setProject]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[selected,setSelected]=useState<number|null>(null),[cycle,setCycle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[policyOpen,setPolicyOpen]=useState(false);
 const request=useRef(0);
 const cycleScoreLabel=s('คะแนนรอบนี้','Cycle score','期間スコア');
 useEffect(()=>{let live=true;void activityRead<ActivityMeta>('meta').then(m=>{if(live){setMeta(m);setCycle(old=>old||String(m.cycles.find(c=>c.periodStart<=bangkokDay()&&c.periodEnd>=bangkokDay())?.id??m.cycles[0]?.id??''));if(initialSelf)setSelected(m.selfId);}}).catch(e=>{if(live)setError(String(e.message));});return()=>{live=false;};},[initialSelf,revision]);
 useEffect(()=>{const id=++request.current;let live=true;void Promise.resolve().then(()=>{if(live){setBusy(true);setOverview(null);setError('');}});void activityRead<ActivityOverview>(`overview?day=${day}${cycle?`&cycleId=${cycle}`:''}${project?`&projectId=${project}`:''}`).then(r=>{if(live&&request.current===id)setOverview(r);}).catch(e=>{if(request.current===id)setError(String(e.message));}).finally(()=>{if(request.current===id)setBusy(false);});return()=>{live=false;};},[day,project,cycle,revision]);
 const items=overview?.items??[],required=(r:typeof items[number])=>r.day.expected>0;
 const groups=[{id:'entered',label:s('เข้าใช้แล้ว','Active today','利用済み'),test:(r:typeof items[number])=>r.entered},{id:'updated',label:s('อัปเดตงานแล้ว','Updated work','業務更新済み'),test:(r:typeof items[number])=>r.updatedTasks>0},{id:'waiting',label:s('เข้าแล้ว ยังไม่อัปเดต','Visited, no update','利用済み・未更新'),test:(r:typeof items[number])=>r.entered&&r.updatedTasks===0&&required(r)},{id:'absent',label:s('ยังไม่เข้าใช้งาน','No activity yet','利用記録なし'),test:(r:typeof items[number])=>!r.entered&&required(r)},{id:'overdue',label:s('เลยกำหนดอัปเดต','Updates overdue','更新期限超過'),test:(r:typeof items[number])=>r.day.status==='MISSING'}];
 const scoped=items.filter(r=>(!department||r.department===department)&&(!search||`${r.name} ${r.department}`.toLowerCase().includes(search.toLowerCase())));
 const shown=scoped.filter(r=>filter==='all'||groups.find(g=>g.id===filter)!.test(r));
 return <div className="team-activity"><header className="activity-heading"><div><h1>{s('ติดตามการใช้งานทีม','Team Activity','チーム利用状況')}</h1><p>{s('การเข้าใช้งาน · รายงานประจำวัน · คะแนนวินัย','App activity · Daily reporting · Reporting discipline','利用履歴・日次報告・更新スコア')}</p></div><div className="activity-actions"><button className="btn default" onClick={()=>setSelected(meta?.selfId??null)} disabled={!meta}>{s('คะแนนของฉัน','My activity','自分のスコア')}</button><button className="btn default" onClick={()=>setRevision(r=>r+1)} disabled={busy}><Icon name="refresh"/>{s('รีเฟรช','Refresh','更新')}</button></div></header>
 {meta&&<div className="activity-banner">{s('เริ่มเก็บข้อมูล','Tracking started','記録開始')} {date(meta.startedAt)} · {s('นับเฉพาะกิจกรรมในระบบ จำนวน Login ไม่มีผลต่อคะแนน','Only app activity is measured. Login counts do not earn points.','アプリ内の操作を記録します。ログイン回数は加点されません。')}</div>}
 <div className="activity-toolbar"><label className="activity-field">{s('วันที่','Date','日付')}<input type="date" value={day} max={bangkokDay()} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><label className="activity-field">{s('โครงการ','Project','プロジェクト')}<select value={project} onChange={e=>setProject(e.target.value)}><option value="">{s('ทุกโครงการในสิทธิ์','All authorized projects','権限内の全プロジェクト')}</option>{meta?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="activity-field">{s('แผนก','Department','部署')}<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{s('ทุกแผนกในสิทธิ์','All authorized departments','権限内の全部署')}</option>{[...new Set(meta?.members.map(m=>m.department))].filter(Boolean).map(d=><option key={d}>{d}</option>)}</select></label><label className="activity-field">{s('ค้นหาสมาชิก','Find a member','メンバー検索')}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={s('ชื่อสมาชิก','Member name','氏名')}/></label></div>
 {error&&<div className="activity-error" role="alert">{error}</div>}
 <div className="activity-stats">{groups.map(g=><button className="activity-stat" key={g.id} aria-pressed={filter===g.id} onClick={()=>setFilter(filter===g.id?'all':g.id)}><span>{g.label}</span><strong>{busy?'—':scoped.filter(g.test).length}</strong><small>{s('คน','people','人')}</small></button>)}</div>
 <div className="activity-actions"><span>{s('สมาชิก','Members','メンバー')} · {shown.length} {filter!=='all'&&<button className="btn ghost sm" onClick={()=>setFilter('all')}>{s('ล้างตัวกรอง','Clear filter','絞込解除')}</button>}</span><span className="activity-note">{s('ข้อมูลล่าสุด','Updated','最終更新')} {date(overview?.updatedAt??null)}</span></div>
 <div className="table-wrap" aria-busy={busy}><table className="activity-table"><thead><tr>{[s('สมาชิก','Member','メンバー'),s('ครั้งแรกวันนี้','First activity','本日初回'),s('ใช้งานล่าสุด','Last activity','最終利用'),s('รอบเข้าใช้','Sessions','利用回数'),s('งานที่อัปเดต','Updated tasks','更新業務'),s('ครบตามรอบ','Reporting coverage','報告網羅率'),s('สถานะ','Status','状態')].map(h=><th key={h}>{h}</th>)}<th>{cycleScoreLabel}</th></tr></thead><tbody>{!busy&&shown.map(m=><tr key={m.id}><td><button className="activity-name" onClick={()=>setSelected(m.id)}>{m.name}<small>{m.department} · {m.role}</small></button></td><td>{m.accessVisible?date(m.firstAt):s('เฉพาะโครงการ','Project scope','プロジェクト内')}</td><td>{m.accessVisible?date(m.lastAt):'—'}</td><td>{m.sessions??'—'}</td><td>{m.updatedTasks}</td><td>{m.day.expected?`${m.day.updated} / ${m.day.expected}`:'—'}</td><td><Status value={m.day.status}/></td><td>{m.score?(m.score.total===null?`${number(m.score.automatic)} / 85`:`${number(m.score.total)} / 100`): '\u2014'}</td></tr>)}</tbody></table>{(busy||!shown.length)&&<div className="activity-empty">{busy?s('กำลังโหลด…','Loading…','読み込み中…'):s('ไม่พบสมาชิกตามตัวกรอง','No members match these filters','該当メンバーがいません')}</div>}</div>
 <div className="activity-toolbar"><label className="activity-field">{s('รอบ KPI สำหรับดูคะแนน','KPI score cycle','KPI評価期間')}<select value={cycle} onChange={e=>setCycle(e.target.value)}>{meta?.cycles.map(c=><option key={c.id} value={c.id}>{c.code} · {c.mode==='TRIAL'?s('ทดลอง','Trial','試行'):s('มีผล 10%','Active 10%','有効10%')}</option>)}</select></label>{meta?.canConfigure&&<button className="btn default" onClick={()=>setPolicyOpen(!policyOpen)}>{s('ตั้งค่ารอบ KPI','Configure KPI cycle','KPI期間設定')}</button>}<p className="activity-note">{s('กดชื่อสมาชิกเพื่อดูปฏิทิน หลักฐาน และคะแนนในรอบที่เลือก','Select a member for their calendar, evidence and selected-cycle score.','メンバーを選択すると、カレンダー・根拠・期間スコアを表示します。')}</p></div>
 {policyOpen&&meta&&<PolicyForm meta={meta} cycleId={cycle} onSaved={()=>{setPolicyOpen(false);setRevision(r=>r+1);}}/>}
 {selected&&meta&&<MemberDialog key={`${selected}:${cycle}`} userId={selected} meta={meta} cycleId={cycle} initialDay={day} onClose={()=>setSelected(null)} onChanged={()=>setRevision(r=>r+1)} openSource={openSource}/>}
 </div>;
}

function MemberDialog({userId,meta,cycleId,initialDay,onClose,onChanged,openSource}:{userId:number;meta:ActivityMeta;cycleId:string;initialDay:string;onClose:()=>void;onChanged:()=>void;openSource?:(type:string,id:number,projectId:number|null)=>void}){
 const t=useT();
 const {s,date}=useCopy(),dialog=useRef<HTMLDialogElement>(null),sequence=useRef(0);const [month,setMonth]=useState(initialDay.slice(0,7)),[selectedDay,setSelectedDay]=useState(initialDay),[data,setData]=useState<ActivityDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[form,setForm]=useState(''),[reportRule,setReportRule]=useState<ActivityRule|null>(null);
 useEffect(()=>{const d=dialog.current,previous=document.activeElement;d?.showModal();return()=>{d?.close();if(previous instanceof HTMLElement)previous.focus();};},[]);
 const reload=useCallback(()=>{setRevision(r=>r+1);onChanged();},[onChanged]);
 useEffect(()=>{const id=++sequence.current;let live=true;void Promise.resolve().then(()=>{if(live){setBusy(true);setData(null);setError('');}});const end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0)).toISOString().slice(0,10);void activityRead<ActivityDetail>(`members/${userId}?start=${month}-01&end=${end}${cycleId?`&cycleId=${cycleId}`:''}`).then(r=>{if(live&&id===sequence.current)setData(r);}).catch(e=>{if(id===sequence.current)setError(e.message);}).finally(()=>{if(id===sequence.current)setBusy(false);});return()=>{live=false;};},[userId,month,cycleId,revision]);
 const own=userId===meta.selfId,events=data?.events.filter(e=>bangkokDay(new Date(e.occurredAt))===selectedDay&&e.kind!=='ACTIVE')??[],reviewable=meta.canReview&&!own&&data?.full&&!data.score?.frozen;
 const discardDraft=()=>!form&&!reportRule||window.confirm(s('ปิดแบบฟอร์มที่ยังไม่ได้บันทึก?','Discard the open form?','未保存のフォームを閉じますか？'));
 const changeForm=(next:string)=>{if(discardDraft()){setReportRule(null);setForm(next===form?'':next);}};
 const changeReport=(rule:ActivityRule,stop=false)=>{if(reportRule?.id===rule.id&&form===(stop?'stop':''))return;if(discardDraft()){setForm(stop?'stop':'');setReportRule(rule);}};
 const close=()=>{if(discardDraft())onClose();};
 return <dialog ref={dialog} className="activity-dialog team-activity" onCancel={e=>{e.preventDefault();close();}} aria-label={s('ประวัติและคะแนนสมาชิก','Member activity and score','メンバー履歴とスコア')}><header><div><h2>{data?.member.name??s('กำลังโหลด…','Loading…','読み込み中…')}</h2><p className="activity-note">{data?.member.department} · {data?.member.role}</p></div><button className="icon-btn" aria-label={s('ปิด','Close','閉じる')} onClick={close}><Icon name="x"/></button></header>
 {error&&<div className="activity-error" role="alert">{error}</div>}{busy&&<p role="status">{s('กำลังโหลด…','Loading…','読み込み中…')}</p>}
 {data&&<><div className="activity-detail-grid"><section className="activity-box"><div className="activity-actions"><h3>{s('ปฏิทินการรายงาน','Reporting calendar','報告カレンダー')}</h3><input aria-label={s('เดือน','Month','月')} type="month" value={month} onChange={e=>{if(e.target.value&&discardDraft()){setForm('');setReportRule(null);setMonth(e.target.value);setSelectedDay(`${e.target.value}-01`);}}}/></div><div className="activity-calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><span className="activity-calendar-label" key={d}>{s(['อา','จ','อ','พ','พฤ','ศ','ส'][i],d,['日','月','火','水','木','金','土'][i])}</span>)}{Array.from({length:new Date(`${month}-01T00:00:00Z`).getUTCDay()},(_,i)=><span key={`blank${i}`}/>)}{data.days.map(d=><button key={d.day} className={`activity-status ${d.status}`} aria-label={`${d.day} ${d.status} ${d.updated}/${d.expected}`} aria-pressed={selectedDay===d.day} onClick={()=>{if(form!=='exception'||discardDraft()){if(form==='exception')setForm('');setSelectedDay(d.day);}}}><span>{Number(d.day.slice(-2))}</span><small>{d.expected?`${d.updated}/${d.expected}`:'—'}</small></button>)}</div><div className="activity-checks">{['ON_TIME','LATE','MISSING','PENDING','EXEMPT','NO_DATA'].map(status=><Status key={status} value={status}/>)}</div><p className="activity-note">{s('ช่วงก่อนเริ่มเก็บข้อมูลไม่มีคะแนน การเปิดหลายแท็บนับเป็นรอบเดียวกัน','Dates before tracking have no score. Multiple tabs share one activity session.','記録開始前は採点対象外。複数タブは同じ利用セッションです。')}</p></section>
 <section className="activity-box"><h3>{s('กิจกรรม','Activity','操作履歴')} · {selectedDay}</h3>{data.exceptions.filter(e=>e.day===selectedDay).map(e=><div className="activity-banner" key={e.day}>{s('ยกเว้น','Exemption','対象外')} · {e.reason}</div>)}<ol className="activity-timeline">{events.map(e=><li key={e.id}><time>{date(e.occurredAt)} · #{e.id}</time><strong>{e.kind==='SESSION'?s('เริ่มเข้าใช้งาน','Session started','利用開始'):e.kind==='PAGE'?s('เปิดหน้า','Opened page','画面表示')+` · ${t(activityModuleLabels[e.module]??"Workspace")}`:e.summary}</strong>{e.details&&['progress','nextStep','evidence','remark'].map(k=>typeof e.details?.[k]==='string'&&<p key={k}>{String(e.details[k])}</p>)}{e.sourceId&&['Schedule Task','Resource Task','Inquiry'].includes(e.sourceType??'')&&openSource&&<button className="btn ghost sm" onClick={()=>{if(!form&&!reportRule){onClose();openSource(e.sourceType!,e.sourceId!,e.projectId);}}}>{s('เปิดงานต้นทาง','Open source work','元の業務を開く')}</button>}</li>)}</ol>{!events.length&&<p className="activity-note">{s('ไม่พบกิจกรรมที่แสดงได้ในวันนี้','No visible activity on this day','この日の表示可能な履歴はありません')}</p>}</section></div>
 {data.score?<ScoreCard score={data.score}/>:<div className="activity-banner">{s('สิทธิ์โครงการแสดงเฉพาะกิจกรรมในโครงการ คะแนน KPI รวมดูได้เฉพาะเจ้าตัวและผู้จัดการหน่วยงาน','Project access shows project activity. Overall KPI scores are available to the employee and department review managers.','プロジェクト権限では該当業務のみ表示。総合KPIは本人と部署評価者が閲覧できます。')}</div>}
 <section className="activity-box"><div className="activity-actions"><h3>{s('งานและรอบรายงาน','Reporting commitments','報告対象業務')}</h3>{meta.canManage&&<button className="btn default" onClick={()=>changeForm('rule')}>{s('เพิ่มงานที่ต้องรายงาน','Add reporting commitment','報告対象を追加')}</button>}</div>{!data.rules.length&&<div className="activity-banner">{s('ยังไม่ได้กำหนดงานที่ต้องรายงาน หัวหน้าเลือกงานและรอบรายงานก่อนเริ่มคิดคะแนน','No reporting commitments yet. A leader must select assigned work and its reporting schedule before scoring begins.','報告対象が未設定です。リーダーが業務と報告日程を設定すると採点を開始します。')}</div>}{data.rules.map(r=><div className="activity-rule" key={r.id}><strong>{r.title}</strong><small>{r.startsOn} → {r.stoppedOn??r.endsOn} · {s('ก่อน','by','締切')} {String(Math.floor(r.cutoffMinute/60)).padStart(2,'0')}:{String(r.cutoffMinute%60).padStart(2,'0')}</small><div className="activity-actions">{own&&r.startsOn<=bangkokDay()&&r.endsOn>=bangkokDay()&&(!r.stoppedOn||r.stoppedOn>bangkokDay())&&<button className="btn primary sm" onClick={()=>changeReport(r)}>{s('รายงานความคืบหน้า','Report progress','進捗を報告')}</button>}{meta.canManage&&!r.stoppedOn&&<button className="btn default sm" onClick={()=>changeReport(r,true)}>{s('หยุดรอบรายงาน','Stop future reports','今後の報告を終了')}</button>}</div></div>)}</section>
 <div className="activity-actions">{reviewable&&<><button className="btn default" onClick={()=>changeForm('exception')}>{s('ยกเว้นวันที่เลือก','Exempt selected day','選択日を対象外に')}</button>{cycleId&&<button className="btn primary" onClick={()=>changeForm('quality')}>{s('ประเมินคุณภาพ 15 คะแนน','Review quality / 15','品質評価 / 15')}</button>}</>}{own&&cycleId&&!data.score?.frozen&&<button className="btn default" onClick={()=>changeForm('clarify')}>{s('ชี้แจงคะแนน','Add clarification','スコアに補足')}</button>}</div>
 {form==='rule'&&<RuleForm data={data} onSaved={()=>{setForm('');reload();}}/>}
 {reportRule&&form!=='stop'&&<ReportForm key={reportRule.id} rule={reportRule} onSaved={()=>{setReportRule(null);reload();}} onCancel={()=>setReportRule(null)}/>}
 {form==='stop'&&reportRule&&<NoteForm key={reportRule.id} title={s('หยุดตั้งแต่วันพรุ่งนี้หรือวันที่งานเริ่ม หากยังไม่เริ่ม','Stop tomorrow, or on the start date if later','翌日以降、または開始日から終了')} onSubmit={async note=>{const tomorrow=bangkokDay(new Date(Date.now()+86400_000));await activityWrite(`rules/${reportRule.id}/stop`,{stoppedOn:reportRule.startsOn>tomorrow?reportRule.startsOn:tomorrow,reason:note,rowVersion:reportRule.rowVersion});setReportRule(null);setForm('');reload();}}/>}
 {form==='exception'&&<NoteForm title={`${s('เหตุผลยกเว้น','Exemption reason','対象外の理由')} · ${selectedDay}`} onSubmit={async note=>{await activityWrite('exceptions',{userId,day:selectedDay,reason:note});setForm('');reload();}}/>}
 {form==='clarify'&&<NoteForm title={s('คำชี้แจงจะเก็บไว้กับรอบประเมิน','Your clarification is retained with this review cycle','補足は評価期間に保存されます')} onSubmit={async note=>{await activityWrite('clarifications',{cycleId:Number(cycleId),note});setForm('');reload();}}/>}
 {form==='quality'&&data.score&&<QualityForm data={data} onSaved={()=>{setForm('');reload();}}/>}
 {data.score?.clarifications.map(c=><div className="activity-banner" key={c.id}>{date(c.createdAt)} · {c.note}</div>)}
 </>}
 </dialog>;
}

function NoteForm({title,onSubmit}:{title:string;onSubmit:(note:string)=>Promise<void>}){const {s}=useCopy();const [note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="activity-box activity-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onSubmit(note);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="activity-field">{title}<textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<div className="activity-error" role="alert">{error}</div>}<button className="btn primary" disabled={busy}>{s('บันทึก','Save','保存')}</button></form>;}
function RuleForm({data,onSaved}:{data:ActivityDetail;onSaved:()=>void}){const {s}=useCopy();const [tomorrow]=useState(()=>bangkokDay(new Date(Date.now()+86400_000))),[source,setSource]=useState(''),[start,setStart]=useState(tomorrow),[end,setEnd]=useState(`${Number(tomorrow.slice(0,4))+1}-${tomorrow.slice(5)}`),[mask,setMask]=useState(62),[cutoff,setCutoff]=useState('17:00'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const chosen=data.sources.find(r=>`${r.sourceType}:${r.sourceId}`===source);if(!chosen)return;await activityWrite('rules',{userId:data.member.id,...chosen,startsOn:start,endsOn:end,weekdayMask:mask,cutoffMinute:Number(cutoff.slice(0,2))*60+Number(cutoff.slice(3))});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <form className="activity-box activity-form" onSubmit={submit}><h3>{s('กำหนดงานและวันรายงานล่วงหน้า','Schedule reporting in advance','報告日程を事前設定')}</h3><label className="activity-field">{s('งานที่ได้รับมอบหมาย','Assigned work','担当業務')}<select required value={source} onChange={e=>setSource(e.target.value)}><option value="">{s('เลือกงาน','Select work','業務を選択')}</option>{data.sources.map(r=><option key={`${r.sourceType}:${r.sourceId}`} value={`${r.sourceType}:${r.sourceId}`}>{r.title}</option>)}</select></label>{!data.sources.length&&<p className="activity-note">{s('ไม่พบงานที่มอบหมายและยังเปิดอยู่ในขอบเขตสิทธิ์','No open assigned work is available within your scope.','権限内に進行中の担当業務がありません。')}</p>}<div className="activity-form-grid"><label className="activity-field">{s('เริ่มวันที่','Start date','開始日')}<input required type="date" min={tomorrow} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="activity-field">{s('สิ้นสุดวันที่','End date','終了日')}<input required type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="activity-checks">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><label key={d}><input type="checkbox" checked={Boolean(mask&(1<<i))} onChange={()=>setMask(m=>m^(1<<i))}/>{s(['อา','จ','อ','พ','พฤ','ศ','ส'][i],d,['日','月','火','水','木','金','土'][i])}</label>)}</div><label className="activity-field">{s('เวลารายงาน (ไทย)','Deadline (Bangkok)','締切（バンコク時間）')}<input required type="time" value={cutoff} onChange={e=>setCutoff(e.target.value)}/></label>{error&&<div className="activity-error" role="alert">{error}</div>}<button className="btn primary" disabled={busy||!source||!mask}>{s('บันทึกรอบรายงาน','Save commitment','報告日程を保存')}</button></form>;
}
function ReportForm({rule,onSaved,onCancel}:{rule:ActivityRule;onSaved:()=>void;onCancel:()=>void}){const {s}=useCopy();const [progress,setProgress]=useState(''),[nextStep,setNextStep]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef({signature:'',key:''});return <form className="activity-box activity-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={ruleId:rule.id,progress,nextStep,evidence},signature=JSON.stringify(body);if(signature!==request.current.signature)request.current={signature,key:activityRequestKey()};await activityWrite('reports',{...body,requestKey:request.current.key});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h3>{rule.title}</h3><label className="activity-field">{s('ทำอะไรแล้ว ผลเป็นอย่างไร','Progress and results','進捗と結果')}<textarea required maxLength={700} value={progress} onChange={e=>setProgress(e.target.value)}/></label><label className="activity-field">{s('ขั้นตอนถัดไปและกำหนดเวลา','Next step and expected date','次の対応と予定日')}<textarea required maxLength={700} value={nextStep} onChange={e=>setNextStep(e.target.value)}/></label><label className="activity-field">{s('หลักฐาน หรืออุปสรรคและแผนติดตาม','Evidence, or blocker and follow-up plan','根拠、または障害と対応計画')}<textarea required maxLength={500} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><p className="activity-note">{s('รายงานนี้เก็บเป็นหลักฐานประจำวัน หากต้องเปลี่ยน % Progress ให้เปิดงานต้นทาง','This saves daily reporting evidence. Open the source work to change its progress percentage.','日次報告の根拠として保存します。進捗率は元の業務で変更してください。')}</p>{error&&<div className="activity-error" role="alert">{error}</div>}<div className="activity-actions"><button className="btn default" type="button" disabled={busy} onClick={onCancel}>{s('ยกเลิก','Cancel','キャンセル')}</button><button className="btn primary" disabled={busy}>{s('บันทึกรายงานวันนี้','Save today’s report','本日の報告を保存')}</button></div></form>;}
function QualityForm({data,onSaved}:{data:ActivityDetail;onSaved:()=>void}){const {s}=useCopy(),score=data.score!;const [values,setValues]=useState([score.qualityReview?.clarity??3,score.qualityReview?.nextStep??3,score.qualityReview?.evidence??3]),[note,setNote]=useState(score.qualityReview?.note??''),[ids,setIds]=useState<number[]>(score.qualityReview?.evidenceIds??[]),[busy,setBusy]=useState(false),[error,setError]=useState('');const evidence=data.events.filter(e=>e.kind==='UPDATE'&&bangkokDay(new Date(e.occurredAt))>=score.periodStart&&bangkokDay(new Date(e.occurredAt))<=score.periodEnd);return <form className="activity-box activity-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await activityWrite('quality',{userId:data.member.id,cycleId:score.cycleId,clarity:values[0],nextStep:values[1],evidence:values[2],note,evidenceIds:ids,rowVersion:score.qualityReview?.rowVersion});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h3>{s('ประเมินจากรายงานจริง','Review actual reporting evidence','実際の報告を評価')}</h3><ZeroEvidenceNote/><p className="activity-note">{s('0 ไม่มีข้อมูล · 3 มีข้อมูลแต่ต้องถามต่อ · 5 ชัดเจนและใช้ติดตามต่อได้','0 absent · 3 needs follow-up questions · 5 clear and actionable','0 情報なし・3 追加確認が必要・5 明確で対応可能')}</p><div className="activity-form-grid">{[s('ความคืบหน้าชัดเจน','Clear progress','進捗の明確さ'),s('ขั้นตอนถัดไป','Next steps','次の対応'),s('หลักฐานและอุปสรรค','Evidence and blockers','根拠と障害')].map((label,i)=><label className="activity-field" key={label}>{label}<select value={values[i]} onChange={e=>setValues(old=>old.map((v,j)=>i===j?Number(e.target.value):v))}>{[0,1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}</div><label className="activity-field">{s('เหตุผลการให้คะแนน','Rating explanation','評価理由')}<textarea required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><strong>{s('เลือกรายงานประกอบ (เดือนที่เปิดดู)','Supporting reports (displayed month)','評価根拠（表示月）')}</strong><div className="activity-evidence">{evidence.map(e=><label key={e.id}><input type="checkbox" checked={ids.includes(e.id)} onChange={()=>setIds(old=>old.includes(e.id)?old.filter(id=>id!==e.id):[...old,e.id])}/><span>#{e.id} · {e.summary}</span></label>)}</div>{!evidence.length&&<p>{s('ยังไม่มีรายงานในเดือนนี้ เลือกเดือนที่มีหลักฐานก่อนประเมิน','No reports this month. Select a month with evidence to review.','この月に報告がありません。根拠のある月を選んでください。')}</p>}{error&&<div className="activity-error" role="alert">{error}</div>}<button className="btn primary" disabled={busy||(!ids.length&&values.some(value=>value!==0))}>{s('บันทึกคะแนนคุณภาพ','Save quality review','品質評価を保存')}</button></form>;}
function PolicyForm({meta,cycleId,onSaved}:{meta:ActivityMeta;cycleId:string;onSaved:()=>void}){const {s}=useCopy();const cycle=meta.cycles.find(c=>String(c.id)===cycleId),[mode,setMode]=useState('TRIAL'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[due,setDue]=useState('');return <section className="activity-box"><h3>{s('ประกาศกติการอบใหม่','Publish next-cycle policy','次期ルールを確定')}</h3><p className="activity-note">{s('กำหนดได้ก่อนเริ่มรอบเท่านั้น ประกาศแล้วแก้ย้อนหลังไม่ได้ · น้ำหนัก 10% · ขั้นต่ำ 10 วัน','Publish before the cycle starts. Published rules cannot be changed retroactively. Weight 10%, minimum 10 assessed days.','期間開始前に確定してください。確定後の遡及変更は不可。比重10%、最低10日。')}</p><div className="activity-toolbar"><strong>{cycle?.code}</strong><select aria-label={s('โหมดคะแนน','Scoring mode','採点モード')} value={mode} onChange={e=>setMode(e.target.value)}><option value="TRIAL">{s('ทดลอง ไม่กระทบ KPI','Trial · no KPI impact','試行・KPIへの影響なし')}</option><option value="ACTIVE">{s('มีผล KPI 10%','Active · 10% of KPI','有効・KPIの10%')}</option></select><button className="btn primary" disabled={busy||!cycle||cycle.configured||cycle.periodStart<=bangkokDay()} onClick={async()=>{setBusy(true);setError('');try{await activityWrite('cycle-policy',{cycleId:Number(cycleId),mode});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{s('ประกาศกติการอบที่เลือก','Publish selected-cycle policy','選択期間のルールを確定')}</button></div><details><summary>{s('สร้างรอบ KPI ใหม่','Create a KPI cycle','KPI期間を新規作成')}</summary><form className="activity-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await apiRequest('/api/v1/performance/cycles',{method:'POST',body:JSON.stringify({code,name:code,periodStart:start,periodEnd:end,reviewDueDate:due})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="activity-field">{s('ชื่อรอบ','Cycle name','期間名')}<input required maxLength={30} value={code} onChange={e=>setCode(e.target.value)}/></label><div className="activity-form-grid">{[{label:s('เริ่ม','Start','開始'),value:start,set:setStart},{label:s('สิ้นสุด','End','終了'),value:end,set:setEnd},{label:s('กำหนดประเมิน','Review due','評価期限'),value:due,set:setDue}].map(f=><label className="activity-field" key={f.label}>{f.label}<input type="date" required value={f.value} onChange={e=>f.set(e.target.value)}/></label>)}</div><button className="btn default" disabled={busy}>{s('สร้างรอบ','Create cycle','期間を作成')}</button></form></details>{error&&<div className="activity-error" role="alert">{error}</div>}</section>;}
